-- ds_3105_pult.lua
-- Pergament für das Druidensystem
-- Falk
-- require("base.books") <-- does not exist anymore
require("base.common")

module("druid.item.id_3105_bookrest", package.seeall)

-- UPDATE common SET com_script='druid.item.id_3105_bookrest' WHERE com_itemid = 3105;
 
function UseItem(User, SourceItem, TargetItem, Counter, Param, ltstate)
--      if base.books.InitBook() then
--         base.books.AddLanguage("common language",0);
--         
--        base.books.AddGermanBookText("Das ist das Buch des Druidentums.",0,0,0);
--        base.books.AddGermanBookText("Glassblöcke werden für die Herstellung von Spiegeln benötigt.",0,0,0);
--        base.books.AddGermanBookText("Das Buch über Glassherstellung schreibt: 'Man braucht Quartzsand, Pottasche, ein Glassblasrohr, eine Holzkelle und einen Glassschmelzofen, um Glass herzustellen.",0,0,0);
--        base.books.AddGermanBookText("Druiden sind Heiler, Beschützer der Natur und Freunde allen Lebens.",0,0,0);
--        base.books.AddGermanBookText("Gefahr! Bier - vor allem das von Zwergen gebraut wurde - verträgt nicht jeder.",0,0,0);
--        base.books.AddGermanBookText("Einige glauben, dass der legendäre Seher und Heiler Nifrindarai der Begründer des Druidentums war.",0,0,0);
--        base.books.AddGermanBookText("Einige Lehren berichten von geheimer Zauberkunst, die Druiden Macht über die Natur gibt.",0,0,0);
--        base.books.AddGermanBookText("Einige Pilze wachsen am besten im Kompost.",0,0,0);
--        base.books.AddGermanBookText("Jede lebende und unbelebte Kreatur existiert nur durch die Vermischung der fünf Ursprünge.",0,0,0);
--        base.books.AddGermanBookText("Druiden machen nur Profit im friedlichen und harmonischen Miteinander mit ihren Nachbarn.",0,0,0);
--        base.books.AddGermanBookText("Ein Druide ist immer freundlich, was sich in seiner liebenswürdigen Art ausdrückt.",0,0,0);
--        base.books.AddGermanBookText("Einen Druiden zu bedrohen, kann große Gefahr auslösen. Gewöhnlich friedfertig, wissen Druiden nicht nur zu heilen, sondern kennen auch die Kunst der Zerstörung.",0,0,0);
--        base.books.AddGermanBookText("Sich in einem immerwährenden Fluss befindend, versammelt, verschmilzt und zerfliesst die Welt ständig.",0,0,0);
--        base.books.AddGermanBookText("In der Anfangszeit des Druidenzirkels der Wälder musste er die Ignoranten zügeln, die sich weigerten an ein friedfertiges Leben zu glauben.",0,0,0);
--        base.books.AddGermanBookText("Druiden sind oft auch Alchemisten!",0,0,0);
--        base.books.AddGermanBookText("Um Tinte zu machen, braucht man eine mineralische Komponente, eine verdünnende und eine botanische Komponente.",0,0,0);
--        base.books.AddGermanBookText("Tinte ist eine Mischung die in einem Mörser hergestellt wird.",0,0,0);
--        base.books.AddGermanBookText("Um Tinte zu bekommen, müssen alle Komponeten in einem großen Zuber vermischt werden.",0,0,0);
--        base.books.AddGermanBookText("Tinte wird in Flaschen abgefüllt.",0,0,0);
--        
--        base.books.AddGermanBookText("Lernt etwas über die Pflanzen, die Ihr für Tränke braucht.",0,0,0); 
--        base.books.AddGermanBookText("Kein Analphabet folgte jemals dem Pfad des Druidentums.",0,0,0); 
--        base.books.AddGermanBookText("Lesen und Schreiben ist das Geheimnis des Lernens.",0,0,0); 
--        base.books.AddGermanBookText("Tragt all das Wissen zusammen und Ihr werdet Erfolg haben.",0,0,0); 
--        base.books.AddGermanBookText("Die Tage der einfältigen Druiden sind gezählt.",0,0,0); 
--        base.books.AddGermanBookText("Nicht jede Pflanze ist magisch.",0,0,0); 
--        base.books.AddGermanBookText("Tränke brauen ist nicht das einzige, das ein Druide lernen kann.",0,0,0); 
--        base.books.AddGermanBookText("Man findet die Wüstenhimmelkapsel im Wüstensand. Sie wird genutzt, um das Element des Windes freizusetzen.",0,0,0); 
--        base.books.AddGermanBookText("Das Donfblatt ist eine Pflanze, die im Wald zu finden ist. Es wird genutzt, um etwas an etwas anderes zu leimen.",0,0,0); 
--        base.books.AddGermanBookText("Die Sandbeere verstärkt den Effekt eines Trankes. Man soll sie in der Wüste finden.",0,0,0); 
--        base.books.AddGermanBookText("Das Rotköpfchen ist ein wohlschmeckender Pilz, der im Wald vorzufinden ist.",0,0,0); 
--        base.books.AddGermanBookText("Den Fliegenpilz kann man in der Nähe von Tannenbäumen finden.",0,0,0); 
--        base.books.AddGermanBookText("Firnisblüten kommen sehr häufig auf Wiesen in der Nähe eines Bächleins vor.",0,0,0); 
--        base.books.AddGermanBookText("Manche nehmen sie nur für Kuchen: Die Erdbeere verbirgt einige ihrer Geheimnisse.",0,0,0); 
--        base.books.AddGermanBookText("Knollenschwammpilze sind nicht so nutzlos, wie viele Leute glauben.",0,0,0); 
--        base.books.AddGermanBookText("Es gibt mehr Geheimnise als dieses Buch preisgeben kann.",0,0,0); 
--        base.books.AddGermanBookText("Nicht jede Blume verbirgt ein Geheimnis.",0,0,0); 
--        base.books.AddGermanBookText("Esst keine Fliegenpilze, sie schaden Eurer Gesundheit.",0,0,0); 
--        base.books.AddGermanBookText("Wenn Ihr keine Tränke herstellen könnt, backt einen Erdbeerkuchen.",0,0,0);
--        
--        base.books.AddGermanBookText("\nEine Einführung in die Alchemie",0,0,0);
--        base.books.AddGermanBookText("Für den angehenden Druiden bildet das Alchemiesystem den notwendigen Einstieg, ohne Alchemie kein Leben als Druide, könnte man sagen.",0,0,0);
--        base.books.AddGermanBookText("Um sich in der Alchemie zu bewähren, benötigt man zunächst einmal ein fundiertes Wissen zu den einzelneen Kräutern und Substanzen, die für die Verarbeitung zu Tränken, Pulvern und Essenzen benötigt werden.",0,0,0);
--        base.books.AddGermanBookText("Das wichtigste Requisit des Alchemisten ist ein guter Kupferkessel, jeder Druide besitzt seinen eigenen Kochtopf, von dem er sich nie, nie im Leben trennen würde.",0,0,0);
--        base.books.AddGermanBookText("Dann braucht man natürlich etwas, um die Essenzen aus den Pflanzen aufzufangen - also jede Menge leerer Flaschen.",0,0,0);
--        base.books.AddGermanBookText("Und schlussendlich braucht man, wen wundert's, einen reichen Vorrat an Pflanzen.",0,0,0);
--        base.books.AddGermanBookText("Wer nicht selbst hinausgeht und sich die Hände schmutzig macht, der sollte beim Kauf auf Qualität achten. Aus schlechten Pflanzen wird selten ein guter Trank.",0,0,0);
--        base.books.AddGermanBookText("Hat man seine sieben Sachen beieinander, kanns endlich losgehen. Jetzt heißt es, Geduld bewahren.",0,0,0);
--        base.books.AddGermanBookText("Mit der leeren Flasche in der einen und einem benötigten Kräutlein in der anderen Hand, sollte einem bei Benutzung des Kupferkessels bald ein erster Erfolg beschieden sein.",0,0,0);
--        base.books.AddGermanBookText("Auch wenn man vielleicht anfangs nicht viel sieht, die erste Flasche mit Essenzen sollte auch noch eine Zeitlang mit Pflanzensäften gefüllt werden, bald schon wird sich das erwartete Ereignis einstellen.",0,0,0);
--        base.books.AddGermanBookText("Wer Geduld hat und fleißig sein Fläschlein füllt, den wird der Geist der Druiden bald umgeben, schau in dein Runenverzeichnis, jetzt bist du ein Mitglied im druidischen Zirkel.",0,0,0);
--        base.books.AddGermanBookText("Wer dort jedoch sieht, dass ihm die Götter bereits Runen des Magiers, des Barden oder gar des Priesters geschenkt haben, dem bleiben die Pforten der Druiden verschlossen, vielleicht auf ewig.",0,0,0);
--        base.books.AddGermanBookText("\nDie erste Rune",0,0,0);
--        base.books.AddGermanBookText("Was kann man nun aber mit der ersten druidischen Rune anstellen? Nun, mit ihr lassen sich Pflanzen nach ihren Inhaltsstoffen bestimmen. Nichts Spektakuläres, wie etwa ein Unsichtbarkeitstrank, aber für die weitere Laufbahn als Druide sehr sehr nützlich.",0,0,0);
--        base.books.AddGermanBookText("Und so geht es nun weiter, nach einer Weile kann man die zweite Rune erlangen, mit ihr lässt sich immerhin schon eine Essenz bestimmen. Oder jedenfalls fast.",0,0,0);
--        base.books.AddGermanBookText("Spätestens mit der dritten Rune sollte man sich bei der Herstellung von Pflanzenextrakten einigermaßen sicher fühlen und in der Lage sein, einen Trank herzustellen, der genau die gewünschten Inhaltsstoffe aufweist.",0,0,0);
--        base.books.AddGermanBookText("Damit endet dann auch diese kleine Einführung in die Alchemie.",0,0,0);
--         
--        -----------
--        
--        base.books.AddEnglishBookText("This is a book about druidism",0,0,0);
--        base.books.AddEnglishBookText("Glass blocks are needed for the fabrication of mirrors",0,0,0);
--        base.books.AddEnglishBookText("The book about glassworks reads: 'You need quartz sand, pott ash, a glass blow pipe, a wooden shovel and a glass oven to create glass items.",0,0,0);
--        base.books.AddEnglishBookText("Druids are healers, protectors of nature and friend to all mankind.",0,0,0);
--        base.books.AddEnglishBookText("Danger! Beer - particularly those brewed by dwarves - is not digestible to everyone.",0,0,0);
--        base.books.AddEnglishBookText("Some believe, the legendary seer and healer Nifrindarai was the founder of druidism.",0,0,0);
--        base.books.AddEnglishBookText("Some lore tells of secret witchery that gives druids power within nature.",0,0,0);
--        base.books.AddEnglishBookText("Some mushrooms grow best in compost.",0,0,0);
--        base.books.AddEnglishBookText("Every living and unliving creature only exists by the blending of the five roots.",0,0,0);
--        base.books.AddEnglishBookText("The profits of druids are always made in peace and harmony with their neighbourhood.",0,0,0);
--        base.books.AddEnglishBookText("A druid is always friendly, expressed in his amiable attitude.",0,0,0);
--        base.books.AddEnglishBookText("Menacing a druid can cause great danger. Usually peaceful, the druid knows not only how to cure, but also the art of destruction.",0,0,0);
--        base.books.AddEnglishBookText("In a constant state of flux, the world is always gathering, disintergrating and amalgamating.",0,0,0);
--        base.books.AddEnglishBookText("In the beginning the circle of the druids of the woods has to bridle against those infidels who refused to believe in a peaceful living.",0,0,0);
--        base.books.AddEnglishBookText("Druids are often alchemists too!",0,0,0);
--        base.books.AddEnglishBookText("To make ink you need a mineral component, a thinner and a botanical component.",0,0,0);
--        base.books.AddEnglishBookText("Ink is a mixture you produce in a mortar.",0,0,0);
--        base.books.AddEnglishBookText("To get ink all components need to me intermixed in a big tub.",0,0,0);
--        base.books.AddEnglishBookText("Ink has to be bottled.",0,0,0);
--        
--        base.books.AddEnglishBookText("Learn about the plants you need for potions.",0,0,0); 
--        base.books.AddEnglishBookText("No analphabeth ever followed the path of druidism.",0,0,0); 
--        base.books.AddEnglishBookText("To read and to write is the secret of learning.",0,0,0); 
--        base.books.AddEnglishBookText("Bring together all the knowledge and you will succeed.",0,0,0); 
--        base.books.AddEnglishBookText("The days of brainless druids have come to an end.",0,0,0); 
--        base.books.AddEnglishBookText("Not every plant is a magical one.",0,0,0); 
--        base.books.AddEnglishBookText("Making potions is not the only thing a druid can learn.",0,0,0); 
--        base.books.AddEnglishBookText("The desert sky capsule can be found in the desert sand. It is used to release the element of wind.",0,0,0); 
--        base.books.AddEnglishBookText("The donf blade is a plant that can be found in the forest. It is used to glue something on something else.",0,0,0); 
--        base.books.AddEnglishBookText("The sandberry strengthens the effect of a potion. It is said to be found in the desert.",0,0,0); 
--        base.books.AddEnglishBookText("The red head is a delicious mushroom that can be found in the forest.",0,0,0); 
--        base.books.AddEnglishBookText("The toadstool is to be found close to fir trees.",0,0,0); 
--        base.books.AddEnglishBookText("Firnis blossoms are very recurrent at meadows close to a creek.",0,0,0); 
--        base.books.AddEnglishBookText("Some take it for cakes only: the strawberry hides some of its secrets.",0,0,0); 
--        base.books.AddEnglishBookText("Bulbsponge mushrooms are not as useless as many people believe.",0,0,0); 
--        base.books.AddEnglishBookText("There are more secrets as this little book can tell.",0,0,0); 
--        base.books.AddEnglishBookText("Not every flower hides a secret.",0,0,0); 
--        base.books.AddEnglishBookText("Do not eat toadstools, they will harm your health.",0,0,0); 
--        base.books.AddEnglishBookText("If you can't make a potion, make a strawberry cake.",0,0,0);
--        
--        base.books.AddEnglishBookText("\nFirst Steps To Alchemy",0,0,0);
--        base.books.AddEnglishBookText("For future druids the alchemy-system is the indispensable entrance, no druidism without alchemy, one even could say.",0,0,0);
--        base.books.AddEnglishBookText("To prove on alchemy, one first need a deep knowledge about the several herbs and substances, needed for the processing of potions, powders and essences.",0,0,0);
--        base.books.AddEnglishBookText("The most important utensil of alchemists is a fine copper vat, every druid owns one an noone never ever would part with his vat.",0,0,0);
--        base.books.AddEnglishBookText("Then, of course, you need something to catch the essences of the plants in - so are aplenty of empty bottles.",0,0,0);
--        base.books.AddEnglishBookText("And finally you need, who wonders, a rich store of plants.",0,0,0);
--        base.books.AddEnglishBookText("Who does not go outside himself to get his hands in the ditch, better should care for good quality when buying herbs. Seldom a good potion was made out of bad ingrediants.",0,0,0);
--        base.books.AddEnglishBookText("If you have all your's kit together, we can finitely start. Now it's obtained to keep patience.",0,0,0);
--        base.books.AddEnglishBookText("With an empty bottle in the one and a single needed herb in your other hand, you should succeed after some short time while using the copper vat.",0,0,0);
--        base.books.AddEnglishBookText("Also if you can't see that much spectacular in the beginning, the first bottle with essences should carried on to be filled with sap for some time. Soon after the craved result will arise.",0,0,0);
--        base.books.AddEnglishBookText("Who has patience and fills his cruse up to the brim diligently, will soon be lavished in the spirit of druidism, just have a look into your rune-schedule, now you are a member of the circle of druid.",0,0,0);
--        base.books.AddEnglishBookText("Who faces there that the gods already have endowed him with the grace of being a mage, a bard or even a priest, keeps debarred from druidism, maybe forever.",0,0,0);
--        base.books.AddEnglishBookText("\nThe First Rune",0,0,0);
--        base.books.AddEnglishBookText("But what the heck you can do with your first rune now? Well, with the first rune one can discern the ingrediants of plants. Not very spectacular, like a potion of invisibility, but very very beneficial for you further career as a druid.",0,0,0);
--        base.books.AddEnglishBookText("And that's the way the story goes, after a while you'll receive your second rune, to determine the ingrediants of a potion with. Or part of it -so far.",0,0,0);
--        base.books.AddEnglishBookText("At the latest with the third rune, you should get familiar to the production of plant-essences and be ready to make a potion of just those the wherewithal ingrediants and desired effects.",0,0,0);
--        base.books.AddEnglishBookText("Therewith our little introduction of alchemy comes to its end.",0,0,0);
--      
------------------------------- Dragon Quest ~ Kadiya---------------------------------------------------------
--		-- Book I --
--		base.books.AddLanguage("ancient language",666);
--
--		base.books.AddGermanBookText("\n~Die erste Weisheit~",0,20,666);
--		base.books.AddGermanBookText("In deine Händen, Suchender, hältst du die erste Weisheit.",0,20,666);
--		base.books.AddGermanBookText("Damit endet dann auch diese kleine Einführung in die Alchemie.",0,20,666);
--
--		base.books.AddEnglishBookText("Therewith our little introduction of alchemy comes to its end.",0,20,666);		
--     
--		-- Book II --
--
--		-- Book III --
--
-------------------------------- Dragon Quest End ------------------------------------------------------------
--   end
--	base.books.SendBookPage(User,Sourceitem.id_data,Counter);
end
-- 
function LookAtItem(User,Item)
--   if base.books.InitTitle() then
--    base.books.AddGermanBookTitle("Buch mit dem Titel \"Grundlagen der Alchemie\"",0);
--    base.books.AddEnglishBookTitle("Book with the title \"Alchemist's Basics\"",0);
--	base.books.AddGermanBookTitle("Buch mit dem Titel \"Die erste Weisheit\"",666);
--    base.books.AddEnglishBookTitle("Book with the title \"The first wisdom\"",666);
--   end
--   base.books.GetBookItemInform(User,Item);
end