-- INSERT INTO npc VALUES (nextval('npc_seq'),3,898,775,2,2,false,'Archmage Elvaine Morgan','npc_archmage_elvaine_morgan.lua',0);

require("npcs.base.autonpcfunctions")

function useNPC(user,counter,param)
    thisNPC:increaseSkill(1,"common language",100);
    thisNPC:talkLanguage(CCharacter.say, CPlayer.german, "Finger weg!");
    thisNPC:talkLanguage(CCharacter.say, CPlayer.english, "Don't you touch me!");
end

function initializeNpc()
    if TraderFirst then
        return true;
    end

    InitTalkLists();

    -- ********* START DYNAMIC PART ********

    QuestID = 0;
    -- NPC by Estralis Seborian
    -- Help
    AddTraderTrigger("Help","");
    AddConsequence("inform","[Game Help] This NPC is Archmage Elvaine Morgan of Runewick. Keyphrases: TRIGGERS.");
    AddTraderTrigger("Hilfe","");
    AddConsequence("inform","[Spielhilfe] Dieser NPC ist Erzmagier Elvaine Morgan von Runewick. Schlüsselwörter: TRIGGERS.");
    -- General speech
    AddTraderTrigger("Hello","ENGLISH1.");
    AddAdditionalTrigger("Greetings");
    AddAdditionalTrigger("Be greeted");
    AddAdditionalTrigger("Hail");
    AddAdditionalTrigger("Good day");
    AddAdditionalTrigger("Good morning");
    AddAdditionalTrigger("Good evening");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Grüße","GERMAN1.");
    AddAdditionalTrigger("Gruß");
    AddAdditionalTrigger("Seid gegrüßt");
    AddAdditionalTrigger("Guten Tag");
    AddAdditionalTrigger("Guten Abend");
    AddAdditionalTrigger("Mahlzeit");
    AddAdditionalTrigger("Tach");
    AddAdditionalTrigger("Moin");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("Hiho","ENGLISH1.");
    AddAdditionalTrigger("Hallo");
    AddAdditionalTrigger("Hey");
    AddAdditionalTrigger("Greebas");
    AddAdditionalTrigger("Greebs");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Hiho","GERMAN1.");
    AddAdditionalTrigger("Hallo");
    AddAdditionalTrigger("Hey");
    AddAdditionalTrigger("Greebas");
    AddAdditionalTrigger("Greebs");
    AddCondition("lang","german");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("Farewell","ENGLISH1.");
    AddAdditionalTrigger("Good bye");
    AddAdditionalTrigger("Bye");
    AddAdditionalTrigger("Fare thy well");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Tschüß","GERMAN1.");
    AddAdditionalTrigger("Tschüss");
    AddAdditionalTrigger("Wiedersehen");
    AddAdditionalTrigger("Gehabt euch wohl");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("Ciao","ENGLISH1.");
    AddAdditionalTrigger("Adieu");
    AddAdditionalTrigger("Au revoir");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Ciao","GERMAN1.");
    AddAdditionalTrigger("Adieu");
    AddAdditionalTrigger("Au revoir");
    AddCondition("lang","german");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("How are you","ENGLISH1.");
    AddAdditionalTrigger("How feel");
    AddAdditionalTrigger("How do you do");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Wie geht","GERMAN1.");
    AddAdditionalTrigger("Wie fühlst");
    AddAdditionalTrigger("Wie ist es ergangen");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("your name","ENGLISH1.");
    AddAdditionalTrigger("who are you");
    AddAdditionalTrigger("who art thou");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("dein name","GERMAN1.");
    AddAdditionalTrigger("wer bist du");
    AddAdditionalTrigger("wer seid ihr");
    AddAdditionalTrigger("wie heißt");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    -- Catching typical NPC phrases
    AddTraderTrigger("what sell","ENGLISH1.");
    AddAdditionalTrigger("what buy");
    AddAdditionalTrigger("list wares");
    AddAdditionalTrigger("price of");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("was verkauf","GERMAN1.");
    AddAdditionalTrigger("was kauf");
    AddAdditionalTrigger("warenliste");
    AddAdditionalTrigger("preis von");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("tell something","ENGLISH1.");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("erzähl was","GERMAN1.");
    AddAdditionalTrigger("erzähl etwas");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    -- Small talk: The talk here should focus on possible questions. Feel free to add more!
    AddTraderTrigger("profession","ENGLISH1.");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("beruf","GERMAN1.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("job","GERMAN1.");
    AddCondition("lang","german");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("job","ENGLISH1.");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Gobaith","ENGLISH1.");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Gobaith","GERMAN1.");
    AddCondition("lang","german");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    -- More small talk; add at least five triggers
    AddTraderTrigger("ENGLISH1.","ENGLISH1.");
    AddAdditionalTrigger("ENGLISH2.");
    AddAdditionalTrigger("ENGLISH3.");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("ENGLISH1.","ENGLISH1.");
    AddAdditionalTrigger("ENGLISH2.");
    AddAdditionalTrigger("ENGLISH3.");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("ENGLISH1.","ENGLISH1.");
    AddAdditionalTrigger("ENGLISH2.");
    AddAdditionalTrigger("ENGLISH3.");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("ENGLISH1.","ENGLISH1.");
    AddAdditionalTrigger("ENGLISH2.");
    AddAdditionalTrigger("ENGLISH3.");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("ENGLISH1.","ENGLISH1.");
    AddAdditionalTrigger("ENGLISH2.");
    AddAdditionalTrigger("ENGLISH3.");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("GERMAN1.","GERMAN1.");
    AddAdditionalTrigger("GERMAN2.");
    AddAdditionalTrigger("GERMAN3.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("GERMAN1.","GERMAN1.");
    AddAdditionalTrigger("GERMAN2.");
    AddAdditionalTrigger("GERMAN3.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("GERMAN1.","GERMAN1.");
    AddAdditionalTrigger("GERMAN2.");
    AddAdditionalTrigger("GERMAN3.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("GERMAN1.","GERMAN1.");
    AddAdditionalTrigger("GERMAN2.");
    AddAdditionalTrigger("GERMAN3.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("GERMAN1.","GERMAN1.");
    AddAdditionalTrigger("GERMAN2.");
    AddAdditionalTrigger("GERMAN3.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    -- Faction stuff
    AddTraderTrigger("Elvaine","ENGLISH1.");
    AddAdditionalTrigger("Morgan");
    AddAdditionalTrigger("archmage");
    AddAdditionalTrigger("Erzmagier");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Elvaine","GERMAN1.");
    AddAdditionalTrigger("Morgan");
    AddAdditionalTrigger("archmage");
    AddAdditionalTrigger("Erzmagier");
    AddCondition("lang","german");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("Runewick","ENGLISH1.");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Runewick","GERMAN1.");
    AddCondition("lang","german");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("Valerio","ENGLISH1.");
    AddAdditionalTrigger("Guilianni");
    AddAdditionalTrigger("Don");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Valerio","GERMAN1.");
    AddAdditionalTrigger("Guilianni");
    AddAdditionalTrigger("Don");
    AddCondition("lang","german");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("Galmair","ENGLISH1.");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Galmair","GERMAN1.");
    AddCondition("lang","german");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("rosaline","ENGLISH1.");
    AddAdditionalTrigger("königin");
    AddAdditionalTrigger("queen");
    AddAdditionalTrigger("edwards");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("rosaline","GERMAN1.");
    AddAdditionalTrigger("königin");
    AddAdditionalTrigger("queen");
    AddAdditionalTrigger("edwards");
    AddCondition("lang","german");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("Cadomyr","ENGLISH1.");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Cadomyr","GERMAN1.");
    AddCondition("lang","german");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    -- Main land factions
    AddTraderTrigger("albar","ENGLISH1.");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("albar","GERMAN1.");
    AddCondition("lang","german");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("gynk","ENGLISH1.");
    AddAdditionalTrigger("gync");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("gync","GERMAN1.");
    AddAdditionalTrigger("gynk");
    AddCondition("lang","german");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("salkama","ENGLISH1.");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("salkama","GERMAN1.");
    AddCondition("lang","german");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    -- Gods; gods are relevant, so the faction leader has to have an opinion on ALL gods
    AddTraderTrigger("Adron","ENGLISH1.");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Adron","GERMAN1.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("Bragon","ENGLISH1.");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Bragon","GERMAN1.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("Cherga","ENGLISH1.");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Cherga","GERMAN1.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("Elara","ENGLISH1.");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Elara","GERMAN1.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("Eldan","ENGLISH1.");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Eldan","GERMAN1.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("Findari","ENGLISH1.");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Findari","GERMAN1.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("Irmorom","ENGLISH1.");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Irmorom","GERMAN1.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("Malachin","ENGLISH1.");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Malachin","GERMAN1.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("Moshran","ENGLISH1.");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Moshran","GERMAN1.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("Nargun","ENGLISH1.");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Nargun","GERMAN1.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("Oldra","ENGLISH1.");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Oldra","GERMAN1.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("Ronagan","ENGLISH1.");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Ronagan","GERMAN1.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("Sirani","ENGLISH1.");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Sirani","GERMAN1.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("Tanora","ENGLISH1.");
    AddAdditionalTrigger("Zelphia");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Tanora","GERMAN1.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("Ushara","ENGLISH1.");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Ushara","GERMAN1.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("Zhambra","ENGLISH1.");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Zhambra","GERMAN1.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    -- Catching quest triggers
    AddTraderTrigger("quest","ENGLISH1.");
    AddCondition("lang","english");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("quest","GERMAN1.");
    AddCondition("lang","german");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("task","ENGLISH1.");
    AddAdditionalTrigger("adventure");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Auftrag","GERMAN1.");
    AddAdditionalTrigger("Aufgabe");
    AddAdditionalTrigger("Abenteuer");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    -- Last catch: Think about keyphrases the player might say and that are not caught until here
    AddTraderTrigger("Yes","ENGLISH1.");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Ja","GERMAN1.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    AddTraderTrigger("No","ENGLISH1.");
    AddAdditionalText("ENGLISH2.");
    AddAdditionalText("ENGLISH3.");
    AddTraderTrigger("Nein","GERMAN1.");
    AddAdditionalText("GERMAN2.");
    AddAdditionalText("GERMAN3.");
    -- Cycletext: Please add at least(!) ten cycletext messages. The more, the better. You can use emotes (#me is green), too.
    AddCycleText("GERMAN.","ENGLISH.");
    AddCycleText("GERMAN.","ENGLISH.");
    AddCycleText("GERMAN.","ENGLISH.");
    AddCycleText("GERMAN.","ENGLISH.");
    AddCycleText("GERMAN.","ENGLISH.");
    AddCycleText("GERMAN.","ENGLISH.");
    AddCycleText("GERMAN.","ENGLISH.");
    AddCycleText("GERMAN.","ENGLISH.");
    AddCycleText("GERMAN.","ENGLISH.");
    AddCycleText("GERMAN.","ENGLISH.");
    -- ********* END DYNAMIC PART ********
    TradSpeakLang={0,1};
    TradStdLang=0;

    increaseLangSkill(TradSpeakLang);
    thisNPC.activeLanguage=TradStdLang;

end

function nextCycle()  -- ~10 times per second
    initializeNpc();
    SpeakerCycle();
end

function receiveText(texttype, message, originator)
    if BasicNPCChecks(originator,2) then
        if LangOK(originator,TradSpeakLang) then
            TellSmallTalk(message,originator);
        else
            Confused(
               "#me sieht dich leicht verwirrt an",
               "#me looks at you a little confused"
            );
        end
    end
end