-- INSERT INTO npc VALUES (nextval('npc_seq'),1,-100,-400,0,4,false,'Bruno Blackhole','npc_bruno_blackhole.lua',0);

require("npcs.base.autonpcfunctions")

function useNPC(user,counter,param)
    thisNPC:increaseSkill(1,"common language",100);
    thisNPC:talkLanguage(CCharacter.say, CPlayer.german, "Finger weg!");
    thisNPC:talkLanguage(CCharacter.say, CPlayer.english, "Don't you touch me!");
end

function initializeNpc()
    if TraderFirst then
        return true;
    end

    InitTalkLists();

    -- ********* START DYNAMIC PART ********

    QuestID = 65;
    -- NPC by Alsaya, revised by Estralis Seborian
    -- Queststatus Overview
    -- 0: No Quest taken
    -- 1: Quest 1 taken - gather 10 raw materials for 50cp
    -- 2: Quest 1 solved
    -- 3: Quest 2 taken - gather 20 raw materials for 100cp
    -- 4: Quest 2 solved
    -- 5: Quest 3 taken - gather 5 rare raw materials for 100cp
    -- 6: Quest 3 solved
    -- 7: Quest 4 taken - gather 10 distant raw materials for 200cp
    -- 8: Quest 4 solved
    -- Debugging
    AddTraderTrigger("set 0","Quest status set to 0");
    AddConsequence("qpg","=",0);
    AddTraderTrigger("set 1","Quest status set to 1");
    AddConsequence("qpg","=",1);
    AddTraderTrigger("set 2","Quest status set to 2");
    AddConsequence("qpg","=",2);
    AddTraderTrigger("set 3","Quest status set to 3");
    AddConsequence("qpg","=",3);
    AddTraderTrigger("set 4","Quest status set to 4");
    AddConsequence("qpg","=",4);
    AddTraderTrigger("set 5","Quest status set to 5");
    AddConsequence("qpg","=",5);
    AddTraderTrigger("set 6","Quest status set to 6");
    AddConsequence("qpg","=",6);
    AddTraderTrigger("set 7","Quest status set to 7");
    AddConsequence("qpg","=",7);
    AddTraderTrigger("set 8","Quest status set to 8");
    AddConsequence("qpg","=",8);
    -- Help
    AddTraderTrigger("Help","");
    AddConsequence("inform","[Game Help] This NPC is the miner Bruno Blackhole. Keyphrases: Hello, quest, pick-axe, miner.");
    AddTraderTrigger("Hilfe","");
    AddConsequence("inform","[Spielhilfe] Dieser NPC ist der Bergarbeiter Bruno Blackhole. Schlüsselwörter: Hallo, Quest, Spitzhacke, Bergarbeiter.");
    -- General speech
    AddTraderTrigger("Hello","Be greeted ma friend!");
    AddAdditionalTrigger("Greetings");
    AddAdditionalTrigger("Be greeted");
    AddAdditionalTrigger("Hail");
    AddAdditionalTrigger("Good day");
    AddAdditionalTrigger("Good morning");
    AddAdditionalTrigger("Good evening");
    AddAdditionalText("Welcome in da Malachite mine.");
    AddAdditionalText("Greetings I hope ya don't try to steal meh ma gold!");
    AddTraderTrigger("Grüße","Tach mein Freund!");
    AddAdditionalTrigger("Gruß");
    AddAdditionalTrigger("Seid gegrüßt");
    AddAdditionalTrigger("Guten Tag");
    AddAdditionalTrigger("Guten Abend");
    AddAdditionalTrigger("Mahlzeit");
    AddAdditionalTrigger("Tach");
    AddAdditionalTrigger("Moin");
    AddAdditionalText("Willkommen inner Malachitmine!");
    AddAdditionalText("Grüße, ich hoff' du versuchst nicht mein Gold zu stehlen!");
    AddTraderTrigger("Hiho","Be greeted ma friend!");
    AddAdditionalTrigger("Hallo");
    AddAdditionalTrigger("Hey");
    AddAdditionalTrigger("Greebas");
    AddAdditionalTrigger("Greebs");
    AddCondition("lang","english");
    AddAdditionalText("Welcome in da Malachite mine.");
    AddAdditionalText("Greetings I hope ya don't try to steal meh ma gold!");
    AddTraderTrigger("Hiho","Tach mein Freund!");
    AddAdditionalTrigger("Hallo");
    AddAdditionalTrigger("Hey");
    AddAdditionalTrigger("Greebas");
    AddAdditionalTrigger("Greebs");
    AddCondition("lang","german");
    AddAdditionalText("Willkommen inner Malachitmine!");
    AddAdditionalText("Grüße, ich hoff' du versuchst nicht mein Gold zu stehlen!");
    AddTraderTrigger("Farewell","May Irmorom guide ya on yar ways!");
    AddAdditionalTrigger("Good bye");
    AddAdditionalTrigger("Bye");
    AddAdditionalTrigger("Fare thy well");
    AddAdditionalText("Come back whenever ya miss the coolness of da mine.");
    AddAdditionalText("Farewell.");
    AddTraderTrigger("Tschüß","Möge Irmorom dich auf deinen Wegen beschützen!");
    AddAdditionalTrigger("Tschüss");
    AddAdditionalTrigger("Wiedersehen");
    AddAdditionalTrigger("Gehabt euch wohl");
    AddAdditionalText("Komm' ruhig zurück wenn du die Kühle der Mine vermisst.");
    AddAdditionalText("Auf bald.");
    AddTraderTrigger("Ciao","Farewell is what we say around here.");
    AddAdditionalTrigger("Adieu");
    AddAdditionalTrigger("Au revoir");
    AddCondition("lang","english");
    AddAdditionalText("Fancy words don't bring you further around here. Farewell.");
    AddAdditionalText("Irmorom with ya!");
    AddTraderTrigger("Ciao","Auf bald sagen wa hier.");
    AddAdditionalTrigger("Adieu");
    AddAdditionalTrigger("Au revoir");
    AddCondition("lang","german");
    AddAdditionalText("Schicke Worte helfen dir auch nicht weiter. Auf bald.");
    AddAdditionalText("Irmorom mit dir!");
    AddTraderTrigger("How are you","None of ya business.");
    AddAdditionalTrigger("How feel");
    AddAdditionalTrigger("How do you do");
    AddAdditionalText("I'm fine and ya?");
    AddAdditionalText("I could use some beer.");
    AddTraderTrigger("Wie geht","Geht dich nichts an.");
    AddAdditionalTrigger("Wie fühlst");
    AddAdditionalTrigger("Wie ist es ergangen");
    AddAdditionalText("Gut und dir?");
    AddAdditionalText("Ich könnte 'n Bier vertragen.");
    AddTraderTrigger("your name","I'm Bruno Blackhole.");
    AddAdditionalTrigger("who are you");
    AddAdditionalTrigger("who art thou");
    AddAdditionalText("I'm a dwarven miner named Bruno.");
    AddAdditionalText("Just call meh Bruno for now.");
    AddTraderTrigger("dein name","Ich bin Bruno Blackhole.");
    AddAdditionalTrigger("wer bist du");
    AddAdditionalTrigger("wer seid ihr");
    AddAdditionalTrigger("wie heißt");
    AddAdditionalText("Ich bin 'n zwergischer Bergarbeiter namens Bruno.");
    AddAdditionalText("Nenn' mich einfach Bruno.");
    -- Catching typical NPC phrases
    AddTraderTrigger("what sell","I do not sell or buy anything, but I could need ya help.");
    AddAdditionalTrigger("what buy");
    AddAdditionalTrigger("list wares");
    AddAdditionalTrigger("price of");
    AddAdditionalText("Do I really look like a trader?");
    AddAdditionalText("I'm no trader, I'm a miner!");
    AddTraderTrigger("was verkauf","Ich kaufe und verkaufe nichts, aber ich könnte Hilfe gebrauchen.");
    AddAdditionalTrigger("was kauf");
    AddAdditionalTrigger("warenliste");
    AddAdditionalTrigger("preis von");
    AddAdditionalText("Seh' ich wirklich wie 'n Händler aus?");
    AddAdditionalText("Ich bin kein Händler, sondern 'n Bergarbeiter.");
    AddTraderTrigger("tell something","If you want to hear a story, ya in da wrong place.");
    AddAdditionalText("I'm here to work, not to tell stories.");
    AddAdditionalText("My gold nugget is my most precious posession.");
    AddTraderTrigger("erzähl was","Wenn du 'ne Geschichte hören wollt, biste am falschen Ort.");
    AddAdditionalTrigger("erzähl etwas");
    AddAdditionalText("Ich bin nicht zum Geschichtenerzählen hier, sondern zum Arbeiten.");
    AddAdditionalText("Mein Goldnugget ist mein wertvollster Besitz.");
    -- Small talk: The talk here should focus on possible questions. Feel free to add more!
    AddTraderTrigger("miner","Aye, that's what I am. Da very best miner of Galmair.");
    AddAdditionalText("A miner mines in da mines of Galmair for ore and coal.");
    AddAdditionalText("Miners are important to smiths, because they sell ore and coal to them.");
    AddTraderTrigger("Bergarbeiter","Aye, das bin ich. Der beste Bergarbeiter von Galmair.");
    AddAdditionalText("Ein Bergarbeiter sucht in den Minen Galmairs nach Erz und Kohle.");
    AddAdditionalText("Bergarbeiter sind wichtig für Schmiede, weil sie Erz und Kohle an sie verkaufen.");
    AddTraderTrigger("Malachit","The Malachite mine belongs to Galmair and one can mine for copper and iron here.");
    AddCondition("lang","english");
    AddAdditionalText("Copper and iron are the most common ores here, but when ya get lucky ya might find goldnuggets as well.");
    AddAdditionalText("The Malachite mine is mah favorite spot. Isn't it nice here?");
    AddTraderTrigger("Malachit","Die Malachitmine gehört zu Galmair und man findet Kupfer- und Eisenerz hier.");
    AddCondition("lang","german");
    AddAdditionalText("Kupfer- und Eisenerz kommt hier am meisten vor, aber wenn du Glück hast, findest du auch Goldnuggets.");
    AddAdditionalText("Die Malachitmine ist mein liebster Platz, ist es nicht toll hier?");
    -- Factions
    AddTraderTrigger("Runewick","Ein faules Pack wohnt dort in Runewick. Nett sind sie zwar, aber sowas von faul!");
    AddCondition("lang","german");
    AddTraderTrigger("Runewick","Lazy scum is living in Runewick. Gentle they are, but lazy!");
    AddCondition("lang","english");
    AddTraderTrigger("Galmair","Der Ort schlechthin: Galmair. Gemütlich, frei und Geld zählt man in großen Beträgen.");
    AddCondition("lang","german");
    AddTraderTrigger("Galmair","The place to be: Galmair. Cozy, free and money counts in large amounts.");
    AddCondition("lang","english");
    AddTraderTrigger("Cadomyr","Edel, pff, die Leute aus Cadomyr verhalten sich nur edel, wenn sie ihr Königin anstarren können.");
    AddCondition("lang","german");
    AddTraderTrigger("Cadomyr","Noble man, pah, the people of Cadomyr behave only noble as long as they stare at the queen.");
    AddCondition("lang","english");
    -- Tool hints
    AddTraderTrigger("pick","You'll need a pickaxe in order to mine for ore. Just hit the rocks with it. If you want to try it I could give you a little quest.");
    AddCondition("qpg","=",0);
    AddTraderTrigger("Hacke","Du wirst 'ne Spitzhacke brauchen um nach Erzen zu suchen, einfach auf die Steine hauen damit. Wenn du es probieren willst, könnte ich dir 'nen kleinen Auftrag geben.");
    AddCondition("qpg","=",0);
    AddTraderTrigger("pick","If ya need another pickaxe, ask a smith or another miner. The best miners can be found in Galmair.");
    AddTraderTrigger("Hacke","Wenn du 'ne weitere Spitzhacke brauchst, frag' 'nen Schmied oder 'nen anderen Bergarbeiter. Die besten Bergarbeiter kann man in Galmair finden.");
    -- 1st quest: Take a tool and gather 10 raw materials for 50cp.
    AddTraderTrigger("quest","Aye, I hope ya like hard work. Bring meh ten raw stones and I will give you a little something.");
    AddAdditionalTrigger("mission");
    AddCondition("qpg","=",0);
    AddCondition("lang","english");
    AddConsequence("item",2763,1,399,0);
    AddConsequence("qpg","=",1);
    AddConsequence("inform","[New quest] Malachite Mine I");
    AddTraderTrigger("quest","Aye, ich hoffe du magst harte Arbeit. Bring mir zehn rohe Steine, dann gebe ich dir 'ne Kleinigkeit.");
    AddAdditionalTrigger("mission");
    AddCondition("qpg","=",0);
    AddCondition("lang","german");
    AddConsequence("item",2763,1,399,0);
    AddConsequence("qpg","=",1);
    AddConsequence("inform","[Neues Quest] Malachitmine I");
    AddTraderTrigger("task","Aye, I hope ya like hard work. Bring meh ten raw stones and I will give ya a little something.");
    AddAdditionalTrigger("adventure");
    AddCondition("qpg","=",0);
    AddConsequence("item",2763,1,399,0);
    AddConsequence("qpg","=",1);
    AddConsequence("inform","[New quest] Malachite Mine I");
    AddTraderTrigger("Auftrag","Aye, ich hoffe du magst harte Arbeit. Bring mir zehn rohe Steine, dann gebe ich dir 'ne Kleinigkeit.");
    AddAdditionalTrigger("Aufgabe");
    AddAdditionalTrigger("Abenteuer");
    AddCondition("qpg","=",0);
    AddConsequence("item",2763,1,399,0);
    AddConsequence("qpg","=",1);
    AddConsequence("inform","[Neues Quest] Malachitmine I");
    AddTraderTrigger("quest","Do ya have da ten raw stones yet? Just hit on da rocks over there with your pick-axe.");
    AddAdditionalTrigger("mission");
    AddCondition("qpg","=",1);
    AddCondition("lang","english");
    AddTraderTrigger("quest","Hast du die zehn rohen Steine schon? Haue einfach mit der Spitzhacke auf die Steine dort drüben.");
    AddAdditionalTrigger("mission");
    AddCondition("qpg","=",1);
    AddCondition("lang","german");
    AddTraderTrigger("task","Do ya have da ten raw stones yet? Just hit on da rocks over there with your pick-axe.");
    AddAdditionalTrigger("adventure");
    AddCondition("qpg","=",1);
    AddTraderTrigger("Auftrag","Hast du die zehn rohen Steine schon? Haue einfach mit der Spitzhacke auf die Steine dort drüben.");
    AddAdditionalTrigger("Aufgabe");
    AddAdditionalTrigger("Abenteuer");
    AddCondition("qpg","=",1);
    AddTraderTrigger(".+","Gute Arbeit, dies zeigt das du kein Schwächling bist.");
    AddCondition("qpg","=",1);
    AddCondition("item",735,"all",">",9);
    AddCondition("town","=","galmair");
    AddCondition("lang","german");
    AddConsequence("deleteitem",735,10);
    AddConsequence("inform","[Quest gelöst] Du erhältst 50 Kupferstücke und deine Bergbaufertigkeit steigt. Dein Ansehen bei Don Valerio Guilianni steigt.");
    AddConsequence("rankpoints","galmair","+",5);
    AddConsequence("money","+",50);
    AddConsequence("skill","crafting","mining","+",1);
    AddConsequence("qpg","=",2);
    AddTraderTrigger(".+","Good work, that shows meh that you're not a whimp.");
    AddCondition("qpg","=",1);
    AddCondition("item",735,"all",">",9);
    AddCondition("town","=","galmair");
    AddCondition("lang","english");
    AddConsequence("deleteitem",735,10);
    AddConsequence("inform","[Quest solved] You are awarded 50 copper coins and your mining skill increases. You advance in Don Valerio Guilianni's favour.");
    AddConsequence("rankpoints","galmair","+",5);
    AddConsequence("money","+",50);
    AddConsequence("skill","crafting","mining","+",1);
    AddConsequence("qpg","=",2);
    AddTraderTrigger(".+","Gute Arbeit, dies zeigt das du kein Schwächling bist.");
    AddCondition("qpg","=",1);
    AddCondition("item",735,"all",">",9);
    AddCondition("lang","german");
    AddConsequence("deleteitem",735,10);
    AddConsequence("inform","[Quest gelöst] Du erhältst 50 Kupferstücke und deine Bergbaufertigkeit steigt.");
    AddConsequence("money","+",50);
    AddConsequence("skill","crafting","mining","+",1);
    AddConsequence("qpg","=",2);
    AddTraderTrigger(".+","Good work, that shows meh that you're not a whimp.");
    AddCondition("qpg","=",1);
    AddCondition("item",735,"all",">",9);
    AddCondition("lang","english");
    AddConsequence("deleteitem",735,10);
    AddConsequence("inform","[Quest solved] You are awarded 50 copper coins and your mining skill increases.");
    AddConsequence("money","+",50);
    AddConsequence("skill","crafting","mining","+",1);
    AddConsequence("qpg","=",2);
    AddTraderTrigger(".+","Du solltest mir zehn rohe Steine bringen und nicht weniger. Versuch es bei den Steinen dort drüben.");
    AddCondition("qpg","=",1);
    AddCondition("item",735,"all","<",10);
    AddCondition("lang","german");
    AddTraderTrigger(".+","I asked you to bring meh ten raw stones and not less. Try it at the rocks over there.");
    AddCondition("qpg","=",1);
    AddCondition("item",735,"all","<",10);
    AddCondition("lang","english");
    -- 2nd quest: Gather 20 different raw materials for 100cp.
    AddTraderTrigger("quest","Ya'll become a good miner someday lad! Bring meh twenty pieces of copper ore and I'll pay for it.");
    AddAdditionalTrigger("mission");
    AddCondition("sex","male");
    AddCondition("qpg","=",2);
    AddCondition("lang","english");
    AddConsequence("qpg","=",3);
    AddConsequence("inform","[New quest] Malachite Mine II");
    AddTraderTrigger("quest","Ya'll become a good miner someday lass! Bring meh twenty pieces of copper ore and I'll pay for it.");
    AddAdditionalTrigger("mission");
    AddCondition("sex","female");
    AddCondition("qpg","=",2);
    AddCondition("lang","english");
    AddConsequence("qpg","=",3);
    AddConsequence("inform","[New quest] Malachite Mine II");
    AddTraderTrigger("quest","Du wirst mal 'n guter Bergarbeiter Bursche! Bring mir zwanzig Brocken Kupfererz und ich bezahle dich dafür.");
    AddAdditionalTrigger("mission");
    AddCondition("sex","male");
    AddCondition("qpg","=",2);
    AddCondition("lang","german");
    AddConsequence("qpg","=",3);
    AddConsequence("inform","[Neues Quest] Malachitmine II");
    AddTraderTrigger("quest","Du wirst mal 'n guter Bergarbeiter Mädel! Bring mir zwanzig Brocken Kupfererz und ich bezahle dich dafür.");
    AddAdditionalTrigger("mission");
    AddCondition("sex","female");
    AddCondition("qpg","=",2);
    AddCondition("lang","german");
    AddConsequence("qpg","=",3);
    AddConsequence("inform","[Neues Quest] Malachitmine II");
    AddTraderTrigger("task","Ya'll become a good miner someday lad! Bring meh twenty pieces of copper ore and I'll pay for it.");
    AddAdditionalTrigger("adventure");
    AddCondition("sex","male");
    AddCondition("qpg","=",2);
    AddConsequence("qpg","=",3);
    AddConsequence("inform","[New quest] Malachite Mine II");
    AddTraderTrigger("task","Ya'll become a good miner someday lass! Bring meh twenty pieces of copper ore and I'll pay for it.");
    AddAdditionalTrigger("adventure");
    AddCondition("sex","female");
    AddCondition("qpg","=",2);
    AddConsequence("qpg","=",3);
    AddConsequence("inform","[New quest] Malachite Mine II");
    AddTraderTrigger("Auftrag","Du wirst mal 'n guter Bergarbeiter Bursche! Bring mir zwanzig Brocken Kupfererz und ich bezahle dich dafür.");
    AddAdditionalTrigger("Aufgabe");
    AddAdditionalTrigger("Abenteuer");
    AddCondition("sex","male");
    AddCondition("qpg","=",2);
    AddConsequence("qpg","=",3);
    AddConsequence("inform","[Neues Quest] Malachitmine II");
    AddTraderTrigger("Auftrag","Du wirst mal 'n guter Bergarbeiter Mädel! Bring mir zwanzig Brocken Kupfererz und ich bezahle dich dafür.");
    AddAdditionalTrigger("Aufgabe");
    AddAdditionalTrigger("Abenteuer");
    AddCondition("sex","female");
    AddCondition("qpg","=",2);
    AddConsequence("qpg","=",3);
    AddConsequence("inform","[Neues Quest] Malachitmine II");
    AddTraderTrigger("quest","I need twenty pieces copper ore, do ya have it yet?");
    AddAdditionalTrigger("mission");
    AddCondition("qpg","=",3);
    AddCondition("lang","english");
    AddTraderTrigger("quest","Ich brauche zwanzig Brocken Kupfererz, hast du die schon?");
    AddAdditionalTrigger("mission");
    AddCondition("qpg","=",3);
    AddCondition("lang","german");
    AddTraderTrigger("task","I need twenty pieces of copper ore, do ya have it yet?");
    AddAdditionalTrigger("adventure");
    AddCondition("qpg","=",3);
    AddTraderTrigger("Auftrag","Ich brauche zwanzig Brocken Kupfererz, hast du die schon?");
    AddAdditionalTrigger("Aufgabe");
    AddAdditionalTrigger("Abenteuer");
    AddCondition("qpg","=",3);
    AddTraderTrigger(".+","Thank ya pal! Here is ya money, don't spend it all at once.");
    AddCondition("qpg","=",3);
    AddCondition("item",2536,"all",">",19);
    AddCondition("town","=","galmair");
    AddCondition("lang","english");
    AddConsequence("deleteitem",2536,20);
    AddConsequence("inform","[Quest solved] You are awarded 100 copper coins and your mining skill increases. You advance in Don Valerio Guilianni's favour.");
    AddConsequence("rankpoints","galmair","+",10);
    AddConsequence("money","+",100);
    AddConsequence("skill","crafting","mining","+",1);
    AddConsequence("qpg","=",4);
    AddTraderTrigger(".+","Danke Kumpel! Hier is dein Geld, gib' nicht alles auf einmal aus.");
    AddCondition("qpg","=",3);
    AddCondition("item",2536,"all",">",19);
    AddCondition("town","=","galmair");
    AddCondition("lang","german");
    AddConsequence("deleteitem",2536,20);
    AddConsequence("inform","[Quest gelöst] Du erhältst 100 Kupferstücke und deine Bergbaufertigkeit steigt. Dein Ansehen bei Don Valerio Guilianni steigt.");
    AddConsequence("rankpoints","galmair","+",10);
    AddConsequence("money","+",100);
    AddConsequence("skill","crafting","mining","+",1);
    AddConsequence("qpg","=",4);
    AddTraderTrigger(".+","Thank ya pal! Here is ya money, don't spend it all at once.");
    AddCondition("qpg","=",3);
    AddCondition("item",2536,"all",">",19);
    AddCondition("lang","english");
    AddConsequence("deleteitem",2536,20);
    AddConsequence("inform","[Quest solved] You are awarded 100 copper coins and your mining skill increases.");
    AddConsequence("money","+",100);
    AddConsequence("skill","crafting","mining","+",1);
    AddConsequence("qpg","=",4);
    AddTraderTrigger(".+","Danke Kumpel! Hier is dein Geld, gib' nicht alles auf einmal aus.");
    AddCondition("qpg","=",3);
    AddCondition("item",2536,"all",">",19);
    AddCondition("lang","german");
    AddConsequence("deleteitem",2536,20);
    AddConsequence("inform","[Quest gelöst] Du erhältst 100 Kupferstücke und deine Bergbaufertigkeit steigt.");
    AddConsequence("money","+",100);
    AddConsequence("skill","crafting","mining","+",1);
    AddConsequence("qpg","=",4);
    AddTraderTrigger(".+","Ne Kumpel, zwanzig Brocken brauch ich. Soviel hast du noch nicht, also geh wieder an die Arbeit.");
    AddCondition("qpg","=",3);
    AddCondition("item",2536,"all","<",20);
    AddCondition("lang","german");
    AddTraderTrigger(".+","Nah pal, I need twenty pieces and ya don't have that much yet, so go back to work.");
    AddCondition("qpg","=",3);
    AddCondition("item",2536,"all","<",20);
    AddCondition("lang","english");
    -- 3rd quest: Gather 5 rare raw materials for 100cp.
    AddTraderTrigger("quest","Another quest? Alright pal, I need five gold nuggets, ya think ya can find them?");
    AddAdditionalTrigger("mission");
    AddCondition("qpg","=",4);
    AddCondition("lang","english");
    AddConsequence("qpg","=",5);
    AddConsequence("inform","[New quest] Malachite Mine III");
    AddTraderTrigger("quest","Noch 'n Auftrag? Na gut Kumpel. Ich brauche fünf Goldnuggets, denkst du, du kannst die finden?");
    AddAdditionalTrigger("mission");
    AddCondition("qpg","=",4);
    AddCondition("lang","german");
    AddConsequence("qpg","=",5);
    AddConsequence("inform","[Neues Quest] Malachitmine III");
    AddTraderTrigger("task","Another task? Alright pal, I need five gold nuggets, ya think ya can find them?");
    AddAdditionalTrigger("adventure");
    AddCondition("qpg","=",4);
    AddConsequence("qpg","=",5);
    AddConsequence("inform","[New quest] Malachite Mine III");
    AddTraderTrigger("Auftrag","Noch 'n Auftrag? Na gut Kumpel. Ich brauche fünf Goldnuggets, denkst du, du findest welche?");
    AddAdditionalTrigger("Aufgabe");
    AddAdditionalTrigger("Abenteuer");
    AddCondition("qpg","=",4);
    AddConsequence("qpg","=",5);
    AddConsequence("inform","[Neues Quest] Malachitmine III");
    AddTraderTrigger("quest","Five gold nuggets is what I need. Ya can find them in the rocks.");
    AddAdditionalTrigger("mission");
    AddCondition("qpg","=",5);
    AddCondition("lang","english");
    AddTraderTrigger("quest","Ich brauche fünf Goldnuggets. Du kannst sie in den Steinen finden.");
    AddAdditionalTrigger("mission");
    AddCondition("qpg","=",5);
    AddCondition("lang","german");
    AddTraderTrigger("task","Five gold nuggets is what I need. Ya can find them in the rocks.");
    AddAdditionalTrigger("adventure");
    AddCondition("qpg","=",5);
    AddTraderTrigger("Auftrag","Ich brauche fünf Goldnuggets. Du kannst sie in den Steinen finden.");
    AddAdditionalTrigger("Aufgabe");
    AddAdditionalTrigger("Abenteuer");
    AddCondition("qpg","=",5);
    AddTraderTrigger(".+","Jetzt bist du 'n richtiger Bergarbeiter. Hier hast du 'n Silberstück.");
    AddCondition("qpg","=",5);
    AddCondition("item",234,"all",">",4);
    AddCondition("town","=","galmair");
    AddCondition("lang","german");
    AddConsequence("deleteitem",234,5);
    AddConsequence("inform","[Quest gelöst] Du erhältst 100 Kupferstücke und deine Bergbaufertigkeit steigt. Dein Ansehen bei Don Valerio Guilianni steigt.");
    AddConsequence("rankpoints","galmair","+",15);
    AddConsequence("money","+",100);
    AddConsequence("skill","crafting","mining","+",1);
    AddConsequence("qpg","=",6);
    AddTraderTrigger(".+","Now ya are a real miner. Here is a silver coin for ya.");
    AddCondition("qpg","=",5);
    AddCondition("item",234,"all",">",4);
    AddCondition("town","=","galmair");
    AddCondition("lang","english");
    AddConsequence("deleteitem",234,5);
    AddConsequence("inform","[Quest solved] You are awarded 100 copper coins and your mining skill increases. You advance in Don Valerio Guilianni's favour.");
    AddConsequence("rankpoints","galmair","+",15);
    AddConsequence("money","+",100);
    AddConsequence("skill","crafting","mining","+",1);
    AddConsequence("qpg","=",6);
    AddTraderTrigger(".+","Jetzt bist du 'n richtiger Bergarbeiter. Hier hast du 'n Silberstück.");
    AddCondition("qpg","=",5);
    AddCondition("item",234,"all",">",4);
    AddCondition("lang","german");
    AddConsequence("deleteitem",234,5);
    AddConsequence("inform","[Quest gelöst] Du erhältst 100 Kupferstücke und deine Bergbaufertigkeit steigt.");
    AddConsequence("money","+",100);
    AddConsequence("skill","crafting","mining","+",1);
    AddConsequence("qpg","=",6);
    AddTraderTrigger(".+","Now ya are a real miner. Here is a silver coin for ya.");
    AddCondition("qpg","=",5);
    AddCondition("item",234,"all",">",4);
    AddCondition("lang","english");
    AddConsequence("deleteitem",234,5);
    AddConsequence("inform","[Quest solved] You are awarded 100 copper coins and your mining skill increases.");
    AddConsequence("money","+",100);
    AddConsequence("skill","crafting","mining","+",1);
    AddConsequence("qpg","=",6);
    AddTraderTrigger(".+","Schade das du die fünf Goldnuggets noch nicht gefunden hast.");
    AddCondition("qpg","=",5);
    AddCondition("item",234,"all","<",5);
    AddCondition("lang","german");
    AddTraderTrigger(".+","A pity that ya haven't found those five gold nuggets yet.");
    AddCondition("qpg","=",5);
    AddCondition("item",234,"all","<",5);
    AddCondition("lang","english");
    -- 4th quest: Gather 10 raw materials from a totally different location for 200cp. Link to other quest. Hint how to get there.
    AddTraderTrigger("quest","Ya know pal, it's mah sweet gold nuggets birthday soon. She likes virgins weed but I have too much work to get them mahself. Could ya bring meh ten virgins weed? Ya should ask Raban at his grove, he can help ya.");
    AddAdditionalTrigger("mission");
    AddCondition("qpg","=",6);
    AddCondition("lang","english");
    AddConsequence("qpg","=",7);
    AddConsequence("inform","[New quest] Malachite Mine IV");
    AddTraderTrigger("quest","Weißt du Kumpel, mein süßes Goldnugget hat bald Geburtstag. Sie mag Jungfernkraut, aber ich habe zu viel zu tun um sie selbst zu suchen. Könntest du mir zehn Jungfernkraut bringen? Du solltest Raban in seinem Hain fragen, er kann dir helfen.");
    AddAdditionalTrigger("mission");
    AddCondition("qpg","=",6);
    AddCondition("lang","german");
    AddConsequence("qpg","=",7);
    AddConsequence("inform","[Neues Quest] Malachitmine IV");
    AddTraderTrigger("task","Ya know pal, it's mah sweet gold nuggets birthday soon. She likes virgins weed but I have too much work to get them mahself. Could ya bring meh ten virgins weed? Ya should ask Raban at his grove, he can help ya.");
    AddAdditionalTrigger("adventure");
    AddCondition("qpg","=",6);
    AddConsequence("qpg","=",7);
    AddConsequence("inform","[New quest] Malachite Mine IV");
    AddTraderTrigger("Auftrag","Weißt du Kumpel, mein süßes Goldnugget hat bald Geburtstag. Sie mag Jungfernkraut, aber ich habe zu viel zu tun um sie selbst zu suchen. Könntest du mir zehn Jungfernkraut bringen? Du solltest Raban in seinem Hain fragen, er kann dir helfen.");
    AddAdditionalTrigger("Aufgabe");
    AddAdditionalTrigger("Abenteuer");
    AddCondition("qpg","=",6);
    AddConsequence("qpg","=",7);
    AddConsequence("inform","[Neues Quest] Malachitmine IV");
    AddTraderTrigger("quest","Do ya have the ten virgins weed for mah wife yet? Ya should go to Raban's grove and ask Raban himself for help.");
    AddAdditionalTrigger("mission");
    AddCondition("qpg","=",7);
    AddCondition("lang","english");
    AddTraderTrigger("quest","Hast du die zehn Jungerfernkraut für meine Frau schon? Du solltest zu Rabans Hain gehen und Raban um Hilfe bitten.");
    AddAdditionalTrigger("mission");
    AddCondition("qpg","=",7);
    AddCondition("lang","german");
    AddTraderTrigger("task","Do ya have the ten virgins weed for mah wife yet? Ya should go to Raban's grove and ask Raban himself for help.");
    AddAdditionalTrigger("adventure");
    AddCondition("qpg","=",7);
    AddTraderTrigger("Auftrag","Hast du die zehn Jungfernkraut für meine Frau schon? Du solltest zu Rabans Hain gehen und Raban um Hilfe bitten.");
    AddAdditionalTrigger("Aufgabe");
    AddAdditionalTrigger("Abenteuer");
    AddCondition("qpg","=",7);
    AddTraderTrigger(".+","Danke, meine Frau wird begeistert sein. Hier hast du 'ne kleine Entschädigung.");
    AddCondition("qpg","=",7);
    AddCondition("item",144,"all",">",9);
    AddCondition("town","=","galmair");
    AddCondition("lang","german");
    AddConsequence("deleteitem",144,10);
    AddConsequence("inform","[Quest gelöst] Du erhältst 200 Kupferstücke und deine Bergbaufertigkeit steigt. Dein Ansehen bei Don Valerio Guilianni steigt.");
    AddConsequence("rankpoints","galmair","+",20);
    AddConsequence("money","+",200);
    AddConsequence("skill","crafting","mining","+",1);
    AddConsequence("qpg","=",8);
    AddTraderTrigger(".+","Thank you, mah wife will be very pleased. Here ya have some compensation money.");
    AddCondition("qpg","=",7);
    AddCondition("item",144,"all",">",9);
    AddCondition("town","=","galmair");
    AddCondition("lang","english");
    AddConsequence("deleteitem",144,10);
    AddConsequence("inform","[Quest solved] You are awarded 200 copper coins and your mining skill increases. You advance in Don Valerio Guilianni's favour.");
    AddConsequence("rankpoints","galmair","+",20);
    AddConsequence("money","+",200);
    AddConsequence("skill","crafting","mining","+",1);
    AddConsequence("qpg","=",8);
    AddTraderTrigger(".+","Danke, meine Frau wird begeistert sein. Hier hast du 'ne kleine Entschädigung.");
    AddCondition("qpg","=",7);
    AddCondition("item",144,"all",">",9);
    AddCondition("lang","german");
    AddConsequence("deleteitem",144,10);
    AddConsequence("inform","[Quest gelöst] Du erhältst 200 Kupferstücke und deine Bergbaufertigkeit steigt.");
    AddConsequence("money","+",200);
    AddConsequence("skill","crafting","mining","+",1);
    AddConsequence("qpg","=",8);
    AddTraderTrigger(".+","Thank you, mah wife will be very pleased. Here ya have some compensation money.");
    AddCondition("qpg","=",7);
    AddCondition("item",144,"all",">",9);
    AddCondition("lang","english");
    AddConsequence("deleteitem",144,10);
    AddConsequence("inform","[Quest solved] You are awarded 200 copper coins and your mining skill increases.");
    AddConsequence("money","+",200);
    AddConsequence("skill","crafting","mining","+",1);
    AddConsequence("qpg","=",8);
    AddTraderTrigger(".+","Come back when ya have ten virgins weed for mah wife, than I will give you your money.");
    AddCondition("qpg","=",7);
    AddCondition("item",144,"all","<",10);
    AddCondition("lang","english");
    AddTraderTrigger(".+","Komm wieder wenn du zehn Jungfernkraut hast, dann werde ich dir dein Geld geben.");
    AddCondition("qpg","=",7);
    AddCondition("item",144,"all","<",10);
    AddCondition("lang","german");
    -- Final dialogue: No more quests, just nice hints
    AddTraderTrigger("quest","There is nothing ya can do for meh now. Why don't you help someone else, maybe even Raban?");
    AddAdditionalTrigger("mission");
    AddCondition("qpg","=",8);
    AddCondition("lang","english");
    AddTraderTrigger("quest","Ich habe nun nichts mehr für dich zu tun. Wieso hilfst du nicht jemand anderes, vielleicht sogar Raban?");
    AddAdditionalTrigger("mission");
    AddCondition("qpg","=",8);
    AddCondition("lang","german");
    AddTraderTrigger("task","There is nothing ya can do for meh now. Why don't you help someone else, maybe even Raban?");
    AddAdditionalTrigger("adventure");
    AddCondition("qpg","=",8);
    AddTraderTrigger("Auftrag","Ich habe nun nichts mehr für dich zu tun. Wieso hilfst du nicht jemand anderes, vielleicht sogar Raban?");
    AddAdditionalTrigger("Aufgabe");
    AddAdditionalTrigger("Abenteuer");
    AddCondition("qpg","=",8);
    -- Last catch: Think about keyphrases the player might say and that are not caught until here
    AddTraderTrigger("Yes","Good for you.");
    AddAdditionalText("Aye, I see.");
    AddAdditionalText("Are you sure?");
    AddAdditionalText("If you say so.");
    AddTraderTrigger("Ja","Gut für dich.");
    AddAdditionalText("Aye, in Ordnung.");
    AddAdditionalText("Bist du dir sicher?");
    AddAdditionalText("Wenn du das sagst.");
    AddTraderTrigger("No","What a shame.");
    AddAdditionalText("Maybe you'll change your mind.");
    AddAdditionalText("Well...");
    AddTraderTrigger("Nein","Schade.");
    AddAdditionalText("Vielleicht änderst du deine Meinung noch.");
    AddAdditionalText("Nun...");
    AddTraderTrigger("nugget","You might find some down here. But you know my wife is my most precious gold nugget for meh. Are you married?");
    AddCondition("lang","english");
    AddTraderTrigger("nugget","Vielleicht findest du welche hier unten. Doch für mich ist meine Frau mein wertwollstes Goldnugget. Bist du verheiratet?");
    AddCondition("lang","german");
    AddTraderTrigger("Raban","Raban is most likely at his grove in the south. He never leaves the places and talks to his plants all day long.");
    AddCondition("lang","english");
    AddTraderTrigger("Raban","Raban ist wahrscheinlich in seinem Hain im Süden. Er verlässt den Platz nie und spricht den ganzen Tag zu seinen Pflanzen.");
    AddCondition("lang","german");
    AddTraderTrigger("grove","Raban's grove is in the forest in the south, I use to get lost between all those trees.");
    AddTraderTrigger("Hain","Rabans Hain ist im Wald im Süden. Ich verlauf mich immer zwischen all diesen Bäumen.");
    AddTraderTrigger("Mine","There are several mines close to Galmair. Just aks a fellow miner or a smith.");
    AddCondition("lang","english");
    AddTraderTrigger("Mine","Es gibt mehrere Minen hier bei Galmair. Frag' einfach einen anderen Bergarbeiter oder einen Schmied.");
    AddCondition("lang","german");
    AddTraderTrigger("ore","A smith can make several things out of ore. Tools, swords, shields and more. Just ask one and maybe he'll even give ya work.");
    AddTraderTrigger("erz","Ein Schmied kann viele Dinge aus Erz machen. Werkzeuge, Schwerter, Schilder und noch mehr. Frag' doch einfach einen Schmied und vielleicht gibt er dir ja sogar Arbeit.");
    AddTraderTrigger("Stone","From raw stone ya can do stoneblocks which are needed to build houses. All ya need is a chisel and a place to work.");
    AddTraderTrigger("Stein","Von rohen Steinen kann man Steinquader machen, welche man braucht um Häuser zu bauen. Alles was du brauchst ist ein Meißel und ein Platz zum Arbeiten.");
    AddTraderTrigger("Irmorom","Hail Irmorom!");
    AddCondition("lang","english");
    AddTraderTrigger("Irmorom","Lobet Irmorom!");
    AddCondition("lang","german");
    -- Cycletext: Please add at least(!) five cycletext messages. The more, the better. You can use emotes (#me is green), too.
    AddCycleText("#me poliert gedankenverloren ein Goldnugget.","#me seems to be lost in thought while polishing a gold nugget.");
    AddCycleText("#me tritt nach einem Stein der klimpernd wegspringt.","#me kicks at a small stone which bounces away with a strumming noise.");
    AddCycleText("#me nuschelt vor sich hin: 'Ich hätte mehr Bier mitnehmen sollen.'","#me mumbles: 'I should have brought more beer.'");
    AddCycleText("Irmorom is der Gott des Handwerks und Handels und zudem der Weltenschmied. Er hat die Zwerge nach seinem Ebenbild geschaffen damit sie der Welt und den anderen Rassen eine Stütze sind.","Irmorom is the god of trade and craftmanship and also the worldsmith. He created us dwarves in his own likeness so that we can be a support for the world and the other races.");
    AddCycleText("Wenn ich einmal sterbe, werde ich all die großen Zwerge in dem großen Berg wiedersehen und werde Irmorom zeigen können was ich gelernt habe.","When I die I'll see all those great dwarves again in the big mountain and can show Irmorom what I learned.");
    AddCycleText("Hey-ho!","Hey-ho!");
    AddCycleText("Glück auf!","Good luck!");
    -- ********* END DYNAMIC PART ********
    TradSpeakLang={0,1};
    TradStdLang=0;

    increaseLangSkill(TradSpeakLang);
    thisNPC.activeLanguage=TradStdLang;

end

function nextCycle()  -- ~10 times per second
    initializeNpc();
    SpeakerCycle();
end

function receiveText(texttype, message, originator)
    if BasicNPCChecks(originator,2) then
        if LangOK(originator,TradSpeakLang) then
            TellSmallTalk(message,originator);
        else
            Confused(
               "#me sieht dich leicht verwirrt an",
               "#me looks at you a little confused"
            );
        end
    end
end