-- INSERT INTO npc VALUES (nextval('npc_seq'),0,-115,-400,0,4,false,'Henry Darter','npc_henry_darter.lua',0);

require("npcs.base.autonpcfunctions")

function useNPC(user,counter,param)
    thisNPC:increaseSkill(1,"common language",100);
    thisNPC:talkLanguage(CCharacter.say, CPlayer.german, "Finger weg!");
    thisNPC:talkLanguage(CCharacter.say, CPlayer.english, "Don't you touch me!");
end

function initializeNpc()
    if TraderFirst then
        return true;
    end

    npcs.base.autonpcfunctions.InitTalkLists();

    -- ********* START DYNAMIC PART ********

    QuestID = 64;
    -- NPC by Jupiter, revised by Estralis Seborian
    -- Queststatus Overview
    -- 0: No Quest taken
    -- 1: Quest 1 taken - gather 10 raw materials for 50cp
    -- 2: Quest 1 solved
    -- 3: Quest 2 taken - gather 20 raw materials for 100cp
    -- 4: Quest 2 solved
    -- 5: Quest 3 taken - gather 5 rare raw materials for 100cp
    -- 6: Quest 3 solved
    -- 7: Quest 4 taken - gather 10 distant raw materials for 200cp
    -- 8: Quest 4 solved
    -- Debugging
    npcs.base.autonpcfunctions.AddTraderTrigger("set 0","Quest status set to 0");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",0);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 1","Quest status set to 1");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 2","Quest status set to 2");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 3","Quest status set to 3");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 4","Quest status set to 4");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 5","Quest status set to 5");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 6","Quest status set to 6");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 7","Quest status set to 7");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 8","Quest status set to 8");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",8);
    -- Help
    npcs.base.autonpcfunctions.AddTraderTrigger("Help","");
    npcs.base.autonpcfunctions.AddConsequence("inform","[Game Help] This NPC is the butcher Henry Darter. Keyphrases: Hello, quest, butcher.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Hilfe","");
    npcs.base.autonpcfunctions.AddConsequence("inform","[Spielhilfe] Dieser NPC ist der Schlachter Henry Darter. Schlüsselwörter: Hallo, Quest, Schlachter.");
    -- General speech
    npcs.base.autonpcfunctions.AddTraderTrigger("Hello","Greetings, my friend.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Greetings");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Be greeted");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Hail");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Good day");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Good morning");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Good evening");
    npcs.base.autonpcfunctions.AddAdditionalText("Hello. A great day to butcher some pigs, isn't it?");
    npcs.base.autonpcfunctions.AddAdditionalText("Hello, hello.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Grüße","Grüße, mein Freund.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Gruß");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Seid gegrüßt");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Guten Tag");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Guten Abend");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Mahlzeit");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Tach");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Moin");
    npcs.base.autonpcfunctions.AddAdditionalText("Hallo. Ein herrlicher Tag zum Schweineschlachten, nicht?");
    npcs.base.autonpcfunctions.AddAdditionalText("Hallo, hallo.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Hiho","Greetings. Do not waste your time with small talk!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Hallo");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Hey");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Greebas");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Greebs");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddAdditionalText("Be greeted.");
    npcs.base.autonpcfunctions.AddAdditionalText("Greetings, my friend.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Hiho","Grüße. Verschwende deine Zeit nicht mit Plausch!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Hallo");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Hey");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Greebas");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Greebs");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddAdditionalText("Seid gegrüßt.");
    npcs.base.autonpcfunctions.AddAdditionalText("Grüße, mein Freund.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Farewell","Have a nice day!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Good bye");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Bye");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Fare thy well");
    npcs.base.autonpcfunctions.AddAdditionalText("Farewell.");
    npcs.base.autonpcfunctions.AddAdditionalText("Goodbye, my friend.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Tschüß","Schönen Tag noch!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Tschüss");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Wiedersehen");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Gehabt euch wohl");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Auf bald");
    npcs.base.autonpcfunctions.AddAdditionalText("Lebt wohl!");
    npcs.base.autonpcfunctions.AddAdditionalText("Auf bald, mein Freund.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Ciao","See you later!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Adieu");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Au revoir");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddAdditionalText("Aye, goodbye.");
    npcs.base.autonpcfunctions.AddAdditionalText("Farewell.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Ciao","Auf bald!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Adieu");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Au revoir");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddAdditionalText("Ja, ja, gehabt euch wohl!");
    npcs.base.autonpcfunctions.AddAdditionalText("Frohes Schaffen.");
    npcs.base.autonpcfunctions.AddTraderTrigger("How are you","Good, as long as I have enough to butcher.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("How feel");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("How do you do");
    npcs.base.autonpcfunctions.AddAdditionalText("Good as always.");
    npcs.base.autonpcfunctions.AddAdditionalText("I'm fine and you?");
    npcs.base.autonpcfunctions.AddTraderTrigger("Wie geht","Gut, so lange ich genug zum Schlachten habe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Wie fühlst");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Wie ist es ergangen");
    npcs.base.autonpcfunctions.AddAdditionalText("Gut wie immer.");
    npcs.base.autonpcfunctions.AddAdditionalText("Mir geht's gut und euch?");
    npcs.base.autonpcfunctions.AddTraderTrigger("your name","I am Henry the butcher.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("who are you");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("who art thou");
    npcs.base.autonpcfunctions.AddAdditionalText("Just the good, old Henry");
    npcs.base.autonpcfunctions.AddAdditionalText("Henry Darter.");
    npcs.base.autonpcfunctions.AddTraderTrigger("dein name","Ich bin Henry der Schlachter");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("wer bist du");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("wer seid ihr");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("wie heißt");
    npcs.base.autonpcfunctions.AddAdditionalText("Der gute alte Henry.");
    npcs.base.autonpcfunctions.AddAdditionalText("Henry Darter.");
    -- Catching typical NPC phrases
    npcs.base.autonpcfunctions.AddTraderTrigger("what sell","I don't buy anything.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("what buy");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("list wares");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("price of");
    npcs.base.autonpcfunctions.AddAdditionalText("I'm a butcher, not a trader.");
    npcs.base.autonpcfunctions.AddTraderTrigger("was verkauf","Ich kaufe nichts.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("was kauf");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("warenliste");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("preis von");
    npcs.base.autonpcfunctions.AddAdditionalText("Bin Schlachter, aber kein Händler.");
    npcs.base.autonpcfunctions.AddTraderTrigger("tell something","If you want to butcher, make sure that you're using a sharp knife.");
    npcs.base.autonpcfunctions.AddAdditionalText("You better smoke meat rather than cook it.");
    npcs.base.autonpcfunctions.AddAdditionalText("Work carefully with deer meat! It is expensive.");
    npcs.base.autonpcfunctions.AddTraderTrigger("erzähl was","Wenn du Schlachten willst, stelle sicher, dass du ein scharfes Messer verwendest.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("erzähl etwas");
    npcs.base.autonpcfunctions.AddAdditionalText("Fleisch kann besser geräuchert werden als gekocht.");
    npcs.base.autonpcfunctions.AddAdditionalText("Arbeite vorsichtig mit Wildfleich. Es ist kostbar.");
    -- Small talk: The talk here should focus on possible questions. Feel free to add more!
    npcs.base.autonpcfunctions.AddTraderTrigger("butcher","I am a butcher and proud of it!");
    npcs.base.autonpcfunctions.AddAdditionalText("Yes, I am a butcher.");
    npcs.base.autonpcfunctions.AddAdditionalText("Butchering is a hard but good work.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Schlachter","Ich bin Schlachter und stolz darauf!");
    npcs.base.autonpcfunctions.AddAdditionalText("Ja, ich bin ein Schlachter.");
    npcs.base.autonpcfunctions.AddAdditionalText("Schlachten ist eine harte, aber ehrliche Arbeit.");
    npcs.base.autonpcfunctions.AddTraderTrigger("swamp","It's beautiful here, isn't it? So wet and full of life.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("dew");
    npcs.base.autonpcfunctions.AddTraderTrigger("sumpf","Schön hier, nicht? So feucht und lebendig.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("morgentau");
    npcs.base.autonpcfunctions.AddTraderTrigger("Messer","Schlachten tut man am besten mit einem Messer. Ein Beil ist so... brutal.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Dolch");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Beil");
    npcs.base.autonpcfunctions.AddTraderTrigger("knife","Butchering is done best with a knife. A hatchet is so... brute.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("dagger");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("hatchet");
    -- Factions
    npcs.base.autonpcfunctions.AddTraderTrigger("Runewick","Friedlich ist es hier in der Nähe von Runewick. Nur manchmal stören mich die Tierliebhaber, was essen denn die? Blumen?");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("Runewick","It is peaceful in the vicinity of Runewick. But sometimes, those animal lovers enerve me, what do they eat? Flowers?");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("Galmair","Nett ist es in Galmair, aber ich zahl doch kein Schutzgeld von dem wenigen, was ich mit meinem Fleisch verdiene.");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("Galmair","It is quite nice in Galmair, but I don't want to pay for my safety; I earn not much with my meat.");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("Cadomyr","Cadomyr hat diverse Nachteile: Es ist weit weg, die Leute reden komisch und es ist trocken dort.");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("Cadomyr","Cadomyr has serveral drawbacks: It is far away, the people speak strangely and it is dry there.");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    -- 1st quest: Take a tool and gather 10 raw materials for 50cp.
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","You can help me butchering the pigs. Take this knife and bring me ten pieces of pork. You will earn some money.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",0);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("item",189,1,399,0);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Dewy Swamps I");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Du kannst mir helfen die Schweine zu schlachten. Nehme dieses Messer und bring mir zehn Stücke Schweinefleisch. Du bekommst auch ein paar Münzen.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",0);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("item",189,1,399,0);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Morgentausumpf I");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","You can help me butchering the pigs. Take this knife and bring me ten pieces of pork. You will earn some money.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",0);
    npcs.base.autonpcfunctions.AddConsequence("item",189,1,399,0);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Dewy Swamps I");
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Du kannst mir helfen die Schweine zu schlachten. Nehme dieses Messer und bring mir zehn Stücke Schweinefleich. Du bekommst auch ein paar Münzen.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",0);
    npcs.base.autonpcfunctions.AddConsequence("item",189,1,399,0);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Morgentausumpf I");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","You can help me butchering the pigs. Bring me ten pieces of pork. You will earn some money.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Du kannst mir helfen die Schweine zu schlachten. Bring mir zehn Stücke Schweinefleisch. Du bekommst auch ein paar Münzen.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","You can help me butchering the pigs. Bring me ten pieces of pork. You will earn some money.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Du kannst mir helfen die Schweine zu schlachten. Bring mir zehn Stücke Schweinefleisch. Du bekommst auch ein paar Münzen.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Ah, wunderbar. Ich nehme das Fleisch und du bekommst deinen Lohn. Sag bescheid, wenn du noch einen Auftrag willst.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("item",307,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("town","=","runewick");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",307,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 50 Kupferstücke und deine Kochfertigkeit steigt. Dein Ansehen bei Erzmagier Elvaine Morgan steigt.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","runewick","+",5);
    npcs.base.autonpcfunctions.AddConsequence("money","+",50);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","cooking and baking","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Ah, great. I'll take the pork and you get your money. Tell me if you want another task.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("item",307,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("town","=","runewick");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",307,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 40 copper coins and your cooking skill increases. You advance in Archmage Elvaine Morgan's favour.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","runewick","+",5);
    npcs.base.autonpcfunctions.AddConsequence("money","+",50);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","cooking and baking","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Ah, wunderbar. Ich nehme das Fleisch und du bekommst deinen Lohn. Sag bescheid, wenn du noch einen Auftrag willst.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("item",307,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",307,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 50 Kupferstücke und deine Kochfertigkeit steigt.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",50);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","cooking and baking","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Ah, great. I'll take the pork and you get your money. Tell me if you want another task.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("item",307,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",307,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 50 copper coins and your cooking skill increases.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",50);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","cooking and baking","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Zehn Stücke Schweinefleisch und nicht weniger!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("item",307,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Not less than ten pieces of pork!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("item",307,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    -- 2nd quest: Gather 20 different raw materials for 100cp.
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","You did it very well with the pork. Now you can try to bring twenty slabs of raw leather to me. Your reward will be a hundred copper coins.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",2);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Dewy Swamps II");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Das Schweinefleisch hast du gut besorgt. Nun kannst du mir mal zwanzig Häute Rohleder auftreiben. Dein Lohn sollen hundert Kupferstücke sein.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",2);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Morgentausumpf II");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","You did it very well with the pork. Now you can try to bring twenty slabs of raw leather to me to me. Your reward will be a hundred copper coins.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",2);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Dewy Swamps II");
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag"," Das Schweinefleisch hast du gut besorgt. Du kannst mir nun mal zwanzig Häute Rohleder auftreiben. Dein Lohn sollen hundert Kupferstücke sein.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",2);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Morgentausumpf II");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","You did it very well with the pork. Now you can try to bring twenty slabs of raw leather to me. Your reward will be a hundred copper coins.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Das Schweinefleisch hast du gut besorgt. Nun kannst du mir mal zwanzig Häute Rohleder auftreiben. Dein Lohn sollen hundert Kupferstücke sein.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","You did it very well with the pork. Now you can try to bring twenty slabs of raw leather to me. Your reward will be a hundred copper coins.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Das Schweinefleisch hast du gut besorgt. Nun kannst du mir mal zwanzig Häute Rohleder auftreiben. Dein Lohn sollen hundert Kupferstücke sein.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Das sind doch mal ein paar ordentlichen Häute! Hier dein Geld und sag bescheid, wenn du wieder eine Aufgabe brauchst.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("item",69,"all",">",19);
    npcs.base.autonpcfunctions.AddCondition("town","=","runewick");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",69,20);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 100 Kupferstücke und deine Kochfertigkeit steigt. Dein Ansehen bei Erzmagier Elvaine Morgan steigt.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","runewick","+",10);
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","cooking and baking","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Very good pieces of leather. Here is your money and tell me, if you want an other task.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("item",69,"all",">",19);
    npcs.base.autonpcfunctions.AddCondition("town","=","runewick");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",69,20);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 100 copper coins and your cooking skill increases. You advance in Archmage Elvaine Morgan's favour.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","runewick","+",10);
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","cooking and baking","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Das sind doch mal ein paar ordentlichen Häute! Hier dein Geld und sag bescheid, wenn du wieder eine Aufgabe brauchst.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("item",69,"all",">",19);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",69,20);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 100 Kupferstücke und deine Kochfertigkeit steigt.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","cooking and baking","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Very good pieces of leather. Here is your money and tell me, if you want an other task.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("item",69,"all",">",19);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",69,20);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 100 copper coins and your cooking skill increases.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","cooking and baking","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Na, wo bleiben meine zwanzig Häute Rohleder?");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("item",69,"all","<",20);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","And? Where are my twenty slabs of raw leather?");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("item",69,"all","<",20);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    -- 3rd quest: Gather 5 rare raw materials for 100cp.
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","You want another task? Well, bring me five pieces of deer meat and you will earn a hundred copper coins.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",4);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Dewy Swamps III");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Du willst noch eine Aufgabe? Dann bring mir mal fünf Rehrücken und du erhältst hundert Kupfermünzen.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",4);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Morgentausumpf III");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","You want another task? Well, bring me five pieces of deer meat and you will earn a hundred copper coins.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",4);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Dewy Swamps III");
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Du willst noch eine Aufgabe? Dann bring mir mal fünf Rehrücken und du erhältst hundert Kupfermünzen.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",4);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Morgentausumpf III");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","You want another task? Well, bring me five pieces of deer meat and you will earn a hundred copper coins.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Du willst noch eine Aufgabe? Dann bring mir mal fünf Rehrücken und du erhälst hundert Kupfermünzen.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","You want another task? Well, bring me five pieces of deer meat and you will earn a hundred copper coins.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Du willst noch eine Aufgabe? Dann bring mir mal fünf Rehrücken und du erhälst hundert Kupfermünzen.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Was für ein hervorragendes Fleisch. Dafür bekommst du deine hundert Kupfermünzen.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("item",552,"all",">",4);
    npcs.base.autonpcfunctions.AddCondition("town","=","runewick");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",552,5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 100 Kupferstücke und deine Kochfertigkeit steigt. Dein Ansehen bei Erzmagier Elvaine Morgan steigt.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","runewick","+",15);
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","cooking and baking","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","That's meat with a great quality. Here are your coins for this work.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("item",552,"all",">",4);
    npcs.base.autonpcfunctions.AddCondition("town","=","runewick");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",552,5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 100 copper coins and your cooking skill increases. You advance in Archmage Elvaine Morgan's favour.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","runewick","+",15);
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","cooking and baking","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Was für ein hervorragendes Fleisch. Dafür bekommst du deine hundert Kupfermünzen.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("item",552,"all",">",4);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",552,5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 100 Kupferstücke und deine Kochfertigkeit steigt.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","cooking and baking","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","That's meat with a great quality. Here are your coins for this work.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("item",552,"all",">",4);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",552,5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 100 copper coins and your cooking skill increases.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","cooking and baking","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Fünf feine Rehrücken. Los, los.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("item",552,"all","<",5);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Five fine pieces of deer meat, hurry up.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("item",552,"all","<",5);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    -- 4th quest: Gather 10 raw materials from a totally different location for 200cp. Link to other quest. Hint how to get there.
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Of course I have an other task for you. For a barbecue, I need ten lumps of coal. Head for the Malachite mine, my buddy Bruno will help you. And believe it or not, your reward will be two hundred copper coins!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",6);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Dewy Swamps IV");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Natürlich habe ich noch was für dich zutun. Für ein richtiges Grillfest brauche ich zehn Klumpen Kohle. Lauf mal zur Malachitmine, mein Kumpel Bruno wird dir helfen. Und glaub es oder nicht, dein Lohn werden zweihundert Kupfermünzen sein.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",6);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Morgentausumpf IV");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","Of course I have an other task for you. For a barbecue, I need ten lumps of coal. Head for the Malachite mine, my buddy Bruno will help you. And believe it or not, your reward will be two hundred copper coins!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",6);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Dewy Swamps IV");
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag"," Natürlich habe ich noch was für dich zutun. Für ein richtiges Grillfest brauche ich zehn Klumpen Kohle. Lauf mal zur Malachitmine, mein Kumpel Bruno wird dir helfen. Und glaub es oder nicht, dein Lohn werden zweihundert Kupfermünzen sein.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",6);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Morgentausumpf IV");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Of course I have an other task for you. For a barbecue, I need ten lumps of coal. Head for the Malachite mine, my buddy Bruno will help you. And believe it or not, your reward will be two hundred copper coins!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Natürlich habe ich noch was für dich zutun. Für ein richtiges Grillfest brauche ich zehn Klumpen Kohle. Lauf mal zur Malachitmine, mein Kumpel Bruno wird dir helfen. Und glaub es oder nicht, dein Lohn werden zweihundert Kupfermünzen sein.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","Of course I have an other task for you. For a barbecue, I need ten lumps of coal. Head for the Malachite mine, my buddy Bruno will help you. And believe it or not, your reward will be two hundred copper coins!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Natürlich habe ich noch was für dich zutun. Für ein richtiges Grillfest brauche ich zehn Klumpen Kohle. Lauf mal zur Malachitmine, mein Kumpel Bruno wird dir helfen. Und glaub es oder nicht, dein Lohn werden zweihundert Kupfermünzen sein.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Das ist wirklich gute Kohle. Da hast du dir diese Münzen wirklich verdient.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",21,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("town","=","runewick");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",21,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 200 Kupferstücke und deine Kochfertigkeit steigt. Dein Ansehen bei Erzmagier Elvaine Morgan steigt.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","runewick","+",20);
    npcs.base.autonpcfunctions.AddConsequence("money","+",200);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","cooking and baking","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",8);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Hmmm, good coal. You really deserve the coins.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",21,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("town","=","runewick");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",21,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 200 copper coins and your cooking skill increases. You advance in Archmage Elvaine Morgan's favour.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","runewick","+",20);
    npcs.base.autonpcfunctions.AddConsequence("money","+",200);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","cooking and baking","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",8);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Das ist wirklich gute Kohle. Da hast du dir diese Münzen wirklich verdient.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",21,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",21,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 200 Kupferstücke und deine Kochfertigkeit steigt.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",200);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","cooking and baking","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",8);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Hmmm, good coal. You really deserve the coins.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",21,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",21,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 200 copper coins and your cooking skill increases.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",200);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","cooking and baking","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",8);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Wo ist denn meine Kohle, bitte schön?");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",21,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Where is my coal, eh?");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",21,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    -- Final dialogue: No more quests, just nice hints
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","I'm sorry, but you really did enough for me. You were a great help. But maybe you go to the Malachite mine close to Galmair. There is someone who can need your help, too.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",8);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Tut mir leid, du hast wirklich genug gemacht. Du warst eine tolle Hilfe. Aber gehe doch mal zur Malachitmine bei Galmair. Da ist jemand, der deine Hilfe gebrauchen kann.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",8);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","I'm sorry, but you really did enough for me. You were a great help. But maybe you go to the Malachite mine close to Galmair. There is someone who can need your help, too.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",8);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Tut mir leid, du hast wirklich genug gemacht. Du warst eine tolle Hilfe. Aber gehe doch mal zur Malachitmine bei Galmair. Da ist jemand, der deine Hilfe gebrauchen kann.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",8);
    -- Last catch: Think about keyphrases the player might say and that are not caught until here
    npcs.base.autonpcfunctions.AddTraderTrigger("Rind","Rinder findet ihr in der Steppe. Die Steaks von den Rindern sind wirklich gut. Aber irgendwie mögen die Elfen nicht, wenn ich sie besuchen komme...");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Kuh");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Kühe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Kalb");
    npcs.base.autonpcfunctions.AddTraderTrigger("Schwein","Schinken vom Schwein ist der Klassiker. Damit verdient so mancher sein erstes Geld hier.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Schaf","Schafe findet ihr auf den Weiden.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Reh","Rehe findet ihr in den meißten Waldgebieten.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Wild");
    npcs.base.autonpcfunctions.AddTraderTrigger("cow","You can find cattle on the plains. The steaks from the cattle there are really good. But somehow, the elves don't like me visiting them...");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("cattle");
    npcs.base.autonpcfunctions.AddTraderTrigger("pig","Ham from the pigs is delicate. A lot of people earn their first money with it.");
    npcs.base.autonpcfunctions.AddTraderTrigger("sheep","You can find sheep on the stockyards.");
    npcs.base.autonpcfunctions.AddTraderTrigger("deer","You can find deers in most of the forest areas.");
    -- Cycletext: Please add at least(!) five cycletext messages. The more, the better. You can use emotes (#me is green), too.
    npcs.base.autonpcfunctions.AddCycleText("#me wischt etwas Blut von seinem Schlachtermesser.","#me wipes off some blood from his knife.");
    npcs.base.autonpcfunctions.AddCycleText("Frisches Fleisch! Beste Qualität!","Fresh meat! Best quality!");
    npcs.base.autonpcfunctions.AddCycleText("#me spricht leise zu sich selbst: 'Ich brauche neues Fleisch.'","#me speaks quietly to himself: 'I need more meat.'");
    npcs.base.autonpcfunctions.AddCycleText("#me singt: 'Ich hack das Schwein, ich hack es klein'","#me sings: 'I butcher the pig, I butcher until it's dead.'");
    npcs.base.autonpcfunctions.AddCycleText("Will man es richtig geschlachtet haben, muss man es selbst schlachten.","If you want to have it butchered the right way, you need to butcher it by your own.");
    npcs.base.autonpcfunctions.AddCycleText("Brust oder Keule? Was räuchere ich zuerst?","Chest or ham? What shall I smoke first?");
    -- ********* END DYNAMIC PART ********
    TradSpeakLang={0,1};
    TradStdLang=0;

    npcs.base.autonpcfunctions.increaseLangSkill(TradSpeakLang);
    thisNPC.activeLanguage=TradStdLang;

end

function nextCycle()  -- ~10 times per second
    initializeNpc();
    npcs.base.autonpcfunctions.SpeakerCycle();
end

function receiveText(texttype, message, originator)
    if npcs.base.autonpcfunctions.BasicNPCChecks(originator,2) then
        if npcs.base.autonpcfunctions.LangOK(originator,TradSpeakLang) then
            npcs.base.autonpcfunctions.TellSmallTalk(message,originator);
        else
            npcs.base.autonpcfunctions.Confused(
               "#me sieht dich leicht verwirrt an",
               "#me looks at you a little confused"
            );
        end
    end
end