-- INSERT INTO npc VALUES (nextval('npc_seq'),2,-120,-400,0,4,false,'Nana Winterbutter','npc_nana_winterbutter.lua',1);

require("npcs.base.autonpcfunctions")
module("npcs.nana_winterbutter")

function useNPC(user,counter,param)
    thisNPC:increaseSkill(1,"common language",100);
    thisNPC:talkLanguage(CCharacter.say, CPlayer.german, "Finger weg!");
    thisNPC:talkLanguage(CCharacter.say, CPlayer.english, "Don't you touch me!");
end

function initializeNpc()
    if TraderFirst then
        return true;
    end

    npcs.base.autonpcfunctions.InitTalkLists();

    -- ********* START DYNAMIC PART ********

    QuestID = 70;
    -- NPC by Magdha Tiefenerz, heavily revised by Estralis Seborian
    -- Queststatus Overview
    -- 0: No Quest taken
    -- 1: Quest 1 taken - gather 10 bundle of grain for 50cp
    -- 2: Quest 1 solved
    -- 3: Quest 2 taken - gather 20 tomatoes for 100cp
    -- 4: Quest 2 solved
    -- 5: Quest 3 taken - gather 5 onions for 100cp
    -- 6: Quest 3 solved
    -- 7: Quest 4 taken - gather 10 salmon fish for 200cp
    -- 8: Quest 4 solved
    -- Debugging
    npcs.base.autonpcfunctions.AddTraderTrigger("set 0","Quest status set to 0");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",0);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 1","Quest status set to 1");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 2","Quest status set to 2");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 3","Quest status set to 3");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 4","Quest status set to 4");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 5","Quest status set to 5");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 6","Quest status set to 6");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 7","Quest status set to 7");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 8","Quest status set to 8");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",8);
    -- Help
    npcs.base.autonpcfunctions.AddTraderTrigger("Help","");
    npcs.base.autonpcfunctions.AddConsequence("inform","[Game Help] This NPC is the cook Nana Winterbutter. Keyphrases: Hello, quest, bowl, cook, cooking.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Hilfe","");
    npcs.base.autonpcfunctions.AddConsequence("inform","[Spielhilfe] Dieser NPC ist die Köchin Nana Winterbutter. Schlüsselwörter: Hallo, Quest, Schüssel, Koch, Kochen.");
    -- General speech
    npcs.base.autonpcfunctions.AddTraderTrigger("Hello","Greetings! Maybe you could help me with a recipe.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Greetings");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Be greeted");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Hail");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Good day");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Good morning");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Good evening");
    npcs.base.autonpcfunctions.AddTraderTrigger("Grüße","Seid gegrüßt! Vielleicht könntet Ihr mir bei einem Rezept helfen.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Gruß");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Seid gegrüßt");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Guten Tag");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Guten Abend");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Mahlzeit");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Tach");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Moin");
    npcs.base.autonpcfunctions.AddTraderTrigger("Hiho","Greetings! Maybe you could help me with a recipe.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Hallo");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Hey");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Greebas");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Greebs");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("Hiho","Seid gegrüßt! Vielleicht könntet Ihr mir bei einem Rezept helfen.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Hallo");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Hey");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Greebas");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Greebs");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("Farewell","Farewell!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Good bye");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Bye");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Fare thy well");
    npcs.base.autonpcfunctions.AddAdditionalText("Oldra's blessing!");
    npcs.base.autonpcfunctions.AddAdditionalText("Come back soon!");
    npcs.base.autonpcfunctions.AddTraderTrigger("Tschüß","Auf Wiedersehen!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Tschüss");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Wiedersehen");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Gehabt euch wohl");
    npcs.base.autonpcfunctions.AddAdditionalText("Oldras Segen!");
    npcs.base.autonpcfunctions.AddAdditionalText("Kommt bald wieder!");
    npcs.base.autonpcfunctions.AddTraderTrigger("Ciao","Farewell!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Adieu");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Au revoir");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddAdditionalText("Oldra's blessing!");
    npcs.base.autonpcfunctions.AddAdditionalText("Come back soon!");
    npcs.base.autonpcfunctions.AddTraderTrigger("Ciao","Auf Wiedersehen!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Adieu");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Au revoir");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddAdditionalText("Oldras Segen!");
    npcs.base.autonpcfunctions.AddAdditionalText("Kommt bald wieder!");
    npcs.base.autonpcfunctions.AddTraderTrigger("How are you","I'm fine.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("How feel");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("How do you do");
    npcs.base.autonpcfunctions.AddAdditionalText("Thank you very much!");
    npcs.base.autonpcfunctions.AddAdditionalText("Well, I have this recipe in mind, which I would like to try.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Wie geht","Mir geht es gut.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Wie fühlst");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Wie ist es ergangen");
    npcs.base.autonpcfunctions.AddAdditionalText("Vielen Dank!");
    npcs.base.autonpcfunctions.AddAdditionalText("Nun, ich habe dieses Rezept im Kopf, welches ich gerne ausprobieren würde.");
    npcs.base.autonpcfunctions.AddTraderTrigger("your name","I am Nana Winterbutter.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("who are you");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("who art thou");
    npcs.base.autonpcfunctions.AddAdditionalText("I'm a cook as you might have noticed. And a good one I might add");
    npcs.base.autonpcfunctions.AddTraderTrigger("dein name","Ich bin Nana Winterbutter.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("wer bist du");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("wer seid ihr");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("wie heißt");
    npcs.base.autonpcfunctions.AddAdditionalText("Ich bin eine Köchin, wie Ihr vielleicht bereits bemerkt habt. Und eine gute, wenn ich das hinzufügen darf.");
    -- Catching typical NPC phrases
    npcs.base.autonpcfunctions.AddTraderTrigger("what sell","Sorry, I don't sell anything. But there are other people in Runewick. Some may even sell things to you.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("what buy");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("list wares");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("price of");
    npcs.base.autonpcfunctions.AddTraderTrigger("was verkauf","Tut mir leid, ich verkaufe nichts. Aber es gibt andere Leute in Runewick. Einige verkaufen Euch vielleicht auch etwas.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("was kauf");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("warenliste");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("preis von");
    npcs.base.autonpcfunctions.AddTraderTrigger("tell something","I'm not much of a storyteller.");
    npcs.base.autonpcfunctions.AddAdditionalText("I'm just a cook. I would rather try out my new recipe instead of telling stories.");
    npcs.base.autonpcfunctions.AddTraderTrigger("erzähl was","Ich bin nicht gerade eine gute Geschichtenerzählerin.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("erzähl etwas");
    npcs.base.autonpcfunctions.AddAdditionalText("Ich bin nur eine Köchin. Ich würde viel lieber mein Rezept ausprobieren, als Geschichten zu erzählen.");
    -- Small talk: The talk here should focus on possible questions. Feel free to add more!
    npcs.base.autonpcfunctions.AddTraderTrigger("cook","Yes, I'm a good cook. I just use the best materials for cooking. Right now I would like to try out this new recipe.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Koch","Ich bin eine gute Köchin. Ich verwende nur die besten Zutaten zum Kochen. Im Moment würde ich gerne dieses neue Rezept ausprobieren.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Köchin");
    npcs.base.autonpcfunctions.AddTraderTrigger("Yewdale","Yewdale is a peaceful place.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Eibenthal","Eibenthal ist ein friedlicher Ort.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Eibental");
    -- Factions
    npcs.base.autonpcfunctions.AddTraderTrigger("Runewick","Runewick ist wundervoll. Und ich bin eine der besten Köchinnen hier.");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("Runewick","Runewick is wonderful. And I'm one of the best cooks around here.");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("Galmair","Ohje! Galmair ist so stinkig und dreckig!");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("Galmair","Oh! Galmair is so smelly and dirty!");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("Cadomyr","Ich war noch nie in Cadomyr. Aber ich hab gehört, es liegt im Süden.");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("Cadomyr","I have never visited Cadomyr myself so far. But I have heard that it is to the south.");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    -- Tool hints
    npcs.base.autonpcfunctions.AddTraderTrigger("recipe","I have this special recipe in mind. I don't want to reveal too much about it but I would be grateful if you could help me with a quest.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",0);
    npcs.base.autonpcfunctions.AddTraderTrigger("Rezept","Ich habe dieses besondere Rezept im Kopf. Ich möchte nicht zu viel darüber verraten, aber ich wäre dankbar, wenn Ihr mir bei einer Aufgabe helfen würdet.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",0);
    npcs.base.autonpcfunctions.AddTraderTrigger("bowl","I'm preparing some dough but it won't last. Maybe you can help me with this quest.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",0);
    npcs.base.autonpcfunctions.AddTraderTrigger("Schüssel","Ich rühre etwas Teig an aber der wird nicht reichen. Vielleicht könnt Ihr mir ja bei dieser Aufgabe helfen.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",0);
    npcs.base.autonpcfunctions.AddTraderTrigger("scythe","You can use the scythe to reap wheat once it has this nice golden colour.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Sense","Ihr könnt eine Sense dafür verwenden, um Getreide zu mähen sobald es diese goldene Farbe hat.");
    npcs.base.autonpcfunctions.AddTraderTrigger("sickle","You can use a sickle to collect vegetables once they are ripe. Or you can use it to collect herbs and mushrooms");
    npcs.base.autonpcfunctions.AddTraderTrigger("Sichel","Ihr könnt eine Sichel verwenden um Gemüse einzusammeln sobald es reif ist. Oder Ihr verwendet sie um Kräuter und Pilze zu sammeln.");
    -- 1st quest: Take a tool and gather 10 bundles of grain for 50cp 
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","For my recipe, I need wheat. Please take this this scythe and get me ten bundles of grain. I will then handpick the grain from the spikes myself.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",0);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("item",271,1,399,0);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Yewdale I");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Für mein Rezept brauche ich Weizen. Bitte nehmt diese Sense und bringt mir zehn Getreidebündel. Ich werde dann selbst die Samen von Hand aus den Ähren lesen.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",0);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("item",271,1,399,0);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Eibenthal I");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","For my recipe, I need wheat. Please take this this scythe and get me ten bundles of grain. I will then handpick the grain from the spikes myself.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",0);
    npcs.base.autonpcfunctions.AddConsequence("item",271,1,399,0);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Yewdale I");
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Für mein Rezept brauche ich Weizen. Bitte nehmt diese Sense und bringt mir zehn Getreidebündel. Ich werde dann selbst die Samen von Hand aus den Ähren lesen.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",0);
    npcs.base.autonpcfunctions.AddConsequence("item",271,1,399,0);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Eibenthal I");
    npcs.base.autonpcfunctions.AddTraderTrigger("recipe","It is very kind of you to get me ten bundles of grain. Please return to me and tell me when you are finished.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("bowl");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddTraderTrigger("Rezept","Es ist sehr nett von Euch mir zehn Getreidebündel zu besorgen. Kehrt bitte zu mir zurück und sagt mir, wenn Ihr fertig seid.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Schüssel");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","It is very kind of you to get me ten bundles of grain. Please return to me and tell me when you are finished.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Es ist sehr nett von Euch mir zehn Getreidebündel zu besorgen. Kehrt bitte zu mir zurück und sagt mir, wenn Ihr fertig seid.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","It is very kind of you to get me ten bundles of grain. Please return to me and tell me when you are finished.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Es ist sehr nett von Euch mir zehn Getreidebündel zu besorgen. Kehrt bitte zu mir zurück und sagt mir, wenn Ihr fertig seid.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Ja, das sollte ausreichend feines Getreide sein. Vielen herzlichen Dank! Bitte nehmt diese Kupfermünzen als Zeichen meiner Dankbarkeit.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("item",249,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("town","=","runewick");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",249,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 50 Kupferstücke und deine Landwirtschaftsfertigkeit steigt. Dein Ansehen bei Erzmagier Elvaine Morgan steigt.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","runewick","+",5);
    npcs.base.autonpcfunctions.AddConsequence("money","+",50);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","peasantry","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Yes, this should give plenty of fine grain. Thank you very much! Please take these copper coins as a sign of my gratitude.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("item",249,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("town","=","runewick");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",249,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 50 copper coins and your peasantry skill increases. You advance in Archmage Elvaine Morgan's favour.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","runewick","+",5);
    npcs.base.autonpcfunctions.AddConsequence("money","+",50);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","peasantry","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Ja, das sollte ausreichend feines Getreide sein. Vielen herzlichen Dank! Bitte nehmt diese Kupfermünzen als Zeichen meiner Dankbarkeit.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("item",249,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",249,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 50 Kupferstücke und deine Landwirtschaftsfertigkeit steigt.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",50);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","peasantry","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Yes, this should give plenty of fine grain. Thank you very much! Please take these copper coins as a sign of my gratitude.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("item",249,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",249,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 50 copper coins and your peasantry skill increases.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",50);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","peasantry","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Es ist sehr nett von Euch mir zehn Getreidebündel zu besorgen. Kehrt bitte zu mir zurück und sagt mir, wenn Ihr fertig seid.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("item",249,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","It is very kind of you to get me ten bundles of grain. Please return to me and tell me when you are finished.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("item",249,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    -- 2nd quest: Gather 20 tomatoes for 100cp 
    npcs.base.autonpcfunctions.AddTraderTrigger("recipe","Well, since you helped me before I might even tell you about the recipe. I think about fish in a crust with tomato sauce. But I don't have enough tomatoes and might need your help with this task again.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("bowl");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",2);
    npcs.base.autonpcfunctions.AddTraderTrigger("Rezept","Nun, da Ihr mir schon zuvor geholfen habt, kann ich Euch auch etwas über das Rezept sagen. Ich denke da an Fisch im Teigmantel mit Tomatensoße. Aber ich habe nicht genug Tomaten und könnte erneut Eure Hilfe bei dieser Aufgabe gebrauchen.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Schüssel");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",2);
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","I'd like to cook fish in a crust with tomato sauce. I need twenty tomatoes for the sauce to the fish. Care to help me?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",2);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Yewdale II");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","I möchte Fisch im Teigmantel mit Tomatensoße kochen. Ich brauchen zwanzig Tomaten für die Soße. Könnt ihr mir helfen?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",2);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Eibenthal II");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","I'd like to cook fish in a crust with tomato sauce. I need twenty tomatoes for the sauce to the fish. Care to help me?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",2);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Yewdale II");
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","I möchte Fisch im Teigmantel mit Tomatensoße kochen. Ich brauchen zwanzig Tomaten für die Soße. Könnt ihr mir helfen?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",2);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Eibenthal II");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Please bring me twenty tomatoes for my sauce.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Bitte bringt mir zwanzig Tomaten für meine Soße.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","Please bring me twenty tomatoes for my sauce.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Bitte bringt mir zwanzig Tomaten für meine Soße.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Großartig! Zwanzig reife Tomaten. Das wird in der Tat eine feine Soße ergeben. Bitte nehmt diese Kupfermünzen. Aber mein Gericht ist noch nicht fertig.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("item",200,"all",">",19);
    npcs.base.autonpcfunctions.AddCondition("town","=","runewick");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",200,20);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 100 Kupferstücke und deine Landwirtschaftsfertigkeit steigt. Dein Ansehen bei Erzmagier Elvaine Morgan steigt.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","runewick","+",10);
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","peasantry","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Great! Twenty ripe tomatoes. That will give a very fine sauce indeed. Please take these copper coins. But my recipe is still not finished.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("item",200,"all",">",19);
    npcs.base.autonpcfunctions.AddCondition("town","=","runewick");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",200,20);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 100 copper coins and your peasantry skill increases. You advance in Archmage Elvaine Morgan's favour.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","runewick","+",10);
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","peasantry","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Großartig! Zwanzig reife Tomaten. Das wird in der Tat eine feine Soße ergeben. Bitte nehmt diese Kupfermünzen. Aber mein Gericht ist noch nicht fertig.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("item",200,"all",">",19);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",200,20);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 100 Kupferstücke und deine Landwirtschaftsfertigkeit steigt.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","peasantry","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Great! Twenty ripe tomatoes. That will give a very fine sauce indeed. Please take these copper coins. But my recipe is still not finished.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("item",200,"all",">",19);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",200,20);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 100 copper coins and your peasantry skill increases.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","peasantry","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Würdet Ihr mir bitte zwanzig Tomaten bringen? Ich danke Euch vielmals!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("item",200,"all","<",20);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Would you please bring me twenty tomatoes? I thank you very much!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("item",200,"all","<",20);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    -- 3rd quest: Gather onions for 100cp 
    npcs.base.autonpcfunctions.AddTraderTrigger("recipe","You've helped with my recipe quite a lot so far. Please, don't think that I'm ungrateful, but I might have another task for you.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("bowl");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",4);
    npcs.base.autonpcfunctions.AddTraderTrigger("Rezept","Ihr habt mir schon sehr bei meinem Rezept geholfen. Bitte, denkt nicht, dass ich undankbar bin, aber ich hätte da noch eine Aufgabe für Euch.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Schüssel");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",4);
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","I think some onions would spice up the sauce. See if you can find at least five onions, please.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",4);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Yewdale III");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Ich denke, ein paar Zwiebeln würden die Soße etwas aufpeppen. Versucht bitte, mindestens fünf Zwiebeln zu finden.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",4);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Eibenthal III");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","I think some onions would spice up the sauce. See if you can find at least five onions, please.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",4);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Yewdale III");
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Ich denke, ein paar Zwiebeln würden die Soße etwas aufpeppen. Versucht bitte, mindestens fünf Zwiebeln zu finden.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",4);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Eibenthal III");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","I hope you are able to find at least five onions so that I can spice up my sauce.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Ich hoffe Ihr könnt mindestens fünf Zwiebeln finden, so dass ich meine Soße etwas aufpeppen kann.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","I hope you are able to find at least five onions so that I can spice up my sauce.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Ich hoffe Ihr könnt mindestens fünf Zwiebeln finden, so dass ich meine Soße etwas aufpeppen kann.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Fantastisch! Ihr habt wirklich fünf Zwiebeln auftreiben können. Hier, nehmt ein paar Kupferstücke im Austausch. Aber wie peinlich, ich habe nun ein Problem mit dem Rezept.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("item",201,"all",">",4);
    npcs.base.autonpcfunctions.AddCondition("town","=","runewick");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",201,5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 100 Kupferstücke und deine Landwirtschaftsfertigkeit steigt. Dein Ansehen bei Erzmagier Elvaine Morgan steigt.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","runewick","+",15);
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","peasantry","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Fantastic! You've really managed to come up with five onions. Here, have some copper coins. But how embarrassing, I have a probem with the recipe now.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("item",201,"all",">",4);
    npcs.base.autonpcfunctions.AddCondition("town","=","runewick");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",201,5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 100 copper coins and your peasantry skill increases. You advance in Archmage Elvaine Morgan's favour.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","runewick","+",15);
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","peasantry","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Fantastisch! Ihr habt wirklich fünf Zwiebeln auftreiben können. Hier, nehmt ein paar Kupferstücke im Austausch. Aber wie peinlich, ich habe nun ein Problem mit dem Rezept.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("item",201,"all",">",4);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",201,5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 100 Kupferstücke und deine Landwirtschaftsfertigkeit steigt.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","peasantry","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Fantastic! You've really managed to come up with five onions. Here, have some copper coins. But how embarrassing, I have a probem with the recipe now.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("item",201,"all",">",4);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",201,5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 100 copper coins and your peasantry skill increases.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","peasantry","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Ich weiß, dass sie schwer zu finden sind, aber ich bräuchte mindestens fünf Zwiebeln.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("item",201,"all","<",5);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","I know that they are hard to find but I would need at least five onions.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("item",201,"all","<",5);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    -- 4th quest: Gather 10 salmon fish for 200cp. Link to Fishing quest in Zzyathis. Hint how to get there.
    npcs.base.autonpcfunctions.AddTraderTrigger("problem","How embarrassing! I was not careful enough with storing the fish for my recipe and now it is rotten. I hope that you can help me one last time with the task to get new fish.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",6);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("Problem","Wie peinlich! Ich war bei der Lagerung des Fisch, den ich verwenden will, nicht sorgfältig genug und nun ist er verdorben. Ich hoffe, Ihr helft mir ein letztes Mal bei der Besorgung von neuem Fisch.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",6);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("recipe","How embarrassing! I was not careful enough with storing the fish for my recipe and now it is rotten. I hope that you can help me one last time with the task to get new fish.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("bowl");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",6);
    npcs.base.autonpcfunctions.AddTraderTrigger("Rezept","Wie peinlich! Ich war bei der Lagerung des Fisch, den ich verwenden will, nicht sorgfältig genug und nun ist er verdorben. Ich hoffe, Ihr helft mir ein letztes Mal bei der Besorgung von neuem Fisch.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Schüssel");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",6);
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","I usually buy fish from Zerarisa. I am really sorry, but I always forget what this fish is called. But I need ten of these fish again.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",6);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Yewdale IV");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Normalerweise kaufe ich Fisch von Zerarisa. Tut mir wirklich leid, aber ich vergesse immer, wie dieser Fisch heißt. Aber ich bräuchte wieder zehn von diesen Fischen.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",6);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Eibenthal IV");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","I usually buy fish from Zerarisa. I am really sorry, but I always forget what this fish is called. But I need ten of these fish again.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",6);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Yewdale IV");
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Normalerweise kaufe ich Fisch von Zerarisa. Tut mir wirklich leid, aber ich vergesse immer, wie dieser Fisch heißt. Aber ich bräuchte wieder zehn von diesen Fischen.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",6);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Eibenthal IV");
    npcs.base.autonpcfunctions.AddTraderTrigger("Zerarisa","Oh, Zerarisa, she is one of the lizard people who live in Cadomyr at Cape Farewell. She comes to Runewick once a month to sell fish.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("Zerarisa","Oh, Zerarisa, sie ist eine von den Echsenleuten, die in Cadomyr am Kap des Abschiedes leben. Sie kommt einmal im Monat nach Runewick um Fisch zu verkaufen.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Habt Ihr schon mit Zerarisa über die Fische gesprochen, die ich normalerweise bei ihr kaufe? Ich brauche wirklich zehn von diesen Fischen, um mein Rezept auszuprobieren.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Did you already speak to Zerarisa about the fish I usually buy from her? I really need ten of these fish to try out my recipe.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","Did you already speak to Zerarisa about the fish I usually buy from her? I really need ten of these fish to try out my recipe.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Habt Ihr schon mit Zerarisa über die Fische gesprochen, die ich normalerwiese bei ihr kaufe? Ich brauche wirklich zehn von diesen Fischen, um mein Rezept auszuprobieren.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddTraderTrigger("salmon","Salmon? Yes, that could be the name of the fish. Now that you mention it. I think Zerarisa mentioned that name. But I need ten salmons for my recipe.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",355,"all","<",10);
    npcs.base.autonpcfunctions.AddTraderTrigger("Lachs","Lachs? Ja, das könnte der Name des Fisches sein. Jetzt wo Ihr es erwähnt. Ich denke Zerarisa hat mal diesen Namen erwähnt. Aber ich brauche zehn Lachse für mein Rezept.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",355,"all","<",10);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Wunderbar! Ja, dies ist genau der Fisch, den ich brauche. Hier, sie sind jedes Kupferstück wert. Ich bin so glücklich, dass ich jetzt alles für meine Rezpet habe. Möge Oldra Euch segnen!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",355,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("town","=","runewick");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",355,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 200 Kupferstücke und deine Landwirtschaftsfertigkeit steigt. Dein Ansehen bei Erzmagier Elvaine Morgan steigt.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","runewick","+",20);
    npcs.base.autonpcfunctions.AddConsequence("money","+",200);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","peasantry","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",8);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Wonderful! Yes, this is exactly the fish I need. Here, this is more than worth the copper. I'm so happy that I have everything for my recipe now. May Oldra bless you!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",355,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("town","=","runewick");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",355,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 200 copper coins and your peasantry skill increases. You advance in Archmage Elvaine Morgan's favour.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","runewick","+",20);
    npcs.base.autonpcfunctions.AddConsequence("money","+",200);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","peasantry","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",8);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Wunderbar! Ja, dies ist genau der Fisch, den ich brauche. Hier, sie sind jedes Kupferstück wert. Ich bin so glücklich, dass ich jetzt alles für meine Rezpet habe. Möge Oldra Euch segnen!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",355,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",355,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 200 Kupferstücke und deine Landwirtschaftsfertigkeit steigt.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",200);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","peasantry","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",8);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Wonderful! Yes, this is exactly the fish I need. Here, this is more than worth the copper. I'm so happy that I have everything for my recipe now. May Oldra bless you!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",355,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",355,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 200 copper coins and your peasantry skill increases.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",200);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","peasantry","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",8);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Ich brauche wirklich zehn von diesen Fischen, die mir Zerarisa normalerweise verkauft. Könntet Ihr die bitte für mich besorgen?");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",355,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","I really need ten of the fish that Zerarisa usually sells me. Would you please get them for me?");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",355,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    -- Final dialogue: No more quests, just nice hints
    npcs.base.autonpcfunctions.AddTraderTrigger("recipe","Thanks to you I finally have all the ingredients I need to try out my new recipe. I thank you with all my heart!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("bowl");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",8);
    npcs.base.autonpcfunctions.AddTraderTrigger("Rezept","Dank Euch habe ich endlich alle Zutaten zusammen, um mein neues Rezept auszuprobieren. Ich danke Euch von ganzem Herzen!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Schüssel");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",8);
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","You have already done way too much for me. I will always keep you in good memory. You are truly a hero to me! May Oldra bless you!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",8);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Ihr habt bereits viel zu viel für mich getan. Ich werde Euch immer in guter Erinnerung behalten. Ihr seid wahrlich ein Held für mich! Möge Oldra Euch segnen!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",8);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","You have already done way too much for me. I will always keep you in good memory. You are truly a hero to me! May Oldra bless you!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",8);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Ihr habt bereits viel zu viel für mich getan. Ich werde Euch immer in guter Erinnerung behalten. Ihr seid wahrlich ein Held für mich! Möge Oldra Euch segnen!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",8);
    -- Last catch: Think about keyphrases the player might say and that are not caught until here
    npcs.base.autonpcfunctions.AddTraderTrigger("Yes","Pardon, I don't understand what you are referring to.");
    npcs.base.autonpcfunctions.AddAdditionalText("What do you mean with 'Yes'?");
    npcs.base.autonpcfunctions.AddTraderTrigger("Ja","Verzeiht, aber ich verstehe nicht, worauf Ihr Euch bezieht.");
    npcs.base.autonpcfunctions.AddAdditionalText("Was meint Ihr mit 'Ja'?");
    npcs.base.autonpcfunctions.AddTraderTrigger("No","Pardon, I don't understand what you are referring to.");
    npcs.base.autonpcfunctions.AddAdditionalText("What do you mean with 'No'?");
    npcs.base.autonpcfunctions.AddTraderTrigger("Nein","Verzeiht, aber ich verstehe nicht, worauf Ihr Euch bezieht.");
    npcs.base.autonpcfunctions.AddAdditionalText("Was meint Ihr mit 'Nein'?");
    npcs.base.autonpcfunctions.AddTraderTrigger("grain","Grain can be used as seed or you can grind it to flour. Put the grain on fertile land and the crop will grow.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Getreide","Getreidekörner können als Saatgut verwendet werden oder man zermahlt sie zu Mehl. Gib die Saat auf fruchtbares Land und das Getreide wird wachsen.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Korn");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Körner");
    npcs.base.autonpcfunctions.AddTraderTrigger("tomato","You can put tomato seeds into fertile soil. Be sure to fasten the growing plants to poles so that it grows straight up.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Tomate","Ihr könnt Tomatensamen in fruchtbaren Boden geben. Geht sicher die heranwachsenden Pflanzen an Stangen zu befestigen, damit sie senkrecht nach oben wachsen.");
    npcs.base.autonpcfunctions.AddTraderTrigger("mushroom","Mushrooms love shadowy places and can be found in forests. You will need a sharp sickle to gather them.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Pilze","Pilze lieben schattige Plätze und können in Wäldern gefunden werden. Ihr werdet eine scharfe Sichel brauchen, um sie zu sammeln.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Champignon");
    npcs.base.autonpcfunctions.AddTraderTrigger("fish","I know how to prepare fish but it seems that I always forget how the fish are called. You better ask someone else if you want to know more about fish.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Fisch","Ich weiß wie man Fisch zubereitet, aber es scheint, als würde ich immer vergessen, wie die Fischen heißen.");
    npcs.base.autonpcfunctions.AddTraderTrigger("onion","Onions are tasty, aren't they? But your breath turns... bah!");
    npcs.base.autonpcfunctions.AddTraderTrigger("zwiebeln","Zwiebeln sind lecker, nicht wahr? Aber dein Atem... igitt!");
    -- Cycletext: Please add at least(!) five cycletext messages. The more, the better. You can use emotes (#me is green), too.
    npcs.base.autonpcfunctions.AddCycleText("#me rührt etwas Teig in einer Schüssel in ihrem linken Arm um.","#me stirs some dough in a bowl in her left arm.");
    npcs.base.autonpcfunctions.AddCycleText("#me starrt besorgt in die Schüssel in ihrem linken Arm.","#me stares worryingly into the bowl in her left arm.");
    npcs.base.autonpcfunctions.AddCycleText("Das wird nie und nimmer reichen.","This won't never ever last.");
    npcs.base.autonpcfunctions.AddCycleText("#me gießt vorsichtig etwas Wasser in Schüssel in ihrem linken Arm.","#me pours carefully some water into the bowl in her left arm.");
    npcs.base.autonpcfunctions.AddCycleText("Vielleicht sollte ich doch etwas anderes kochen.","Maybe I should cook something else.");
    -- ********* END DYNAMIC PART ********
    TradSpeakLang={0,1};
    TradStdLang=0;

    npcs.base.autonpcfunctions.increaseLangSkill(TradSpeakLang);
    thisNPC.activeLanguage=TradStdLang;

end

function nextCycle()  -- ~10 times per second
    initializeNpc();
    npcs.base.autonpcfunctions.SpeakerCycle();
end

function receiveText(texttype, message, originator)
    if npcs.base.autonpcfunctions.BasicNPCChecks(originator,2) then
        if npcs.base.autonpcfunctions.LangOK(originator,TradSpeakLang) then
            npcs.base.autonpcfunctions.TellSmallTalk(message,originator);
        else
            npcs.base.autonpcfunctions.Confused(
               "#me sieht dich leicht verwirrt an",
               "#me looks at you a little confused"
            );
        end
    end
end