-- INSERT INTO npc VALUES (nextval('npc_seq'),0,-110,-400,0,4,false,'Rutrus','npc_rutrus.lua',0);

require("npcs.base.autonpcfunctions")
module("npcs.rutrus")

function useNPC(user,counter,param)
    thisNPC:increaseSkill(1,"common language",100);
    thisNPC:talkLanguage(CCharacter.say, CPlayer.german, "Finger weg!");
    thisNPC:talkLanguage(CCharacter.say, CPlayer.english, "Don't you touch me!");
end

function initializeNpc()
    if TraderFirst then
        return true;
    end

    npcs.base.autonpcfunctions.InitTalkLists();

    -- ********* START DYNAMIC PART ********

    QuestID = 67;
    -- NPC by Jupiter, revised by Estralis Seborian
    -- Queststatus Overview
    -- 0: No Quest taken
    -- 1: Quest 1 taken - gather 10 raw materials for 50cp
    -- 2: Quest 1 solved
    -- 3: Quest 2 taken - gather 20 raw materials for 100cp
    -- 4: Quest 2 solved
    -- 5: Quest 3 taken - gather 5 rare raw materials for 100cp
    -- 6: Quest 3 solved
    -- 7: Quest 4 taken - gather 10 distant raw materials for 200cp
    -- 8: Quest 4 solved
    -- Debugging
    npcs.base.autonpcfunctions.AddTraderTrigger("set 0","Quest status set to 0");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",0);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 1","Quest status set to 1");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 2","Quest status set to 2");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 3","Quest status set to 3");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 4","Quest status set to 4");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 5","Quest status set to 5");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 6","Quest status set to 6");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 7","Quest status set to 7");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npcs.base.autonpcfunctions.AddTraderTrigger("set 8","Quest status set to 8");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",8);
    -- Help
    npcs.base.autonpcfunctions.AddTraderTrigger("Help","");
    npcs.base.autonpcfunctions.AddConsequence("inform","[Game Help] This NPC is the digger Rutrus. Keyphrases: Hello, quest, shovel, profession.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Hilfe","");
    npcs.base.autonpcfunctions.AddConsequence("inform","[Spielhilfe] Dieser NPC ist der Gräber Rutrus. Schlüsselwörter: Hallo, Quest, Schaufel, Beruf.");
    -- General speech
    npcs.base.autonpcfunctions.AddTraderTrigger("Hello","Hello, Hello.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Greetings");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Be greeted");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Hail");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Good day");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Good morning");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Good evening");
    npcs.base.autonpcfunctions.AddAdditionalText("You greet me and I greet back: Greetings!");
    npcs.base.autonpcfunctions.AddAdditionalText("Good day.");
    npcs.base.autonpcfunctions.AddAdditionalText("Welcome to this sandy area.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Grüße","Hallo, Hallo.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Gruß");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Seid gegrüßt");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Guten Tag");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Guten Abend");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Mahlzeit");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Tach");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Moin");
    npcs.base.autonpcfunctions.AddAdditionalText("Du grüßt mich und ich grüße zurück: Grüße!");
    npcs.base.autonpcfunctions.AddAdditionalText("Guten Tag.");
    npcs.base.autonpcfunctions.AddAdditionalText("Willkommen in dieser sandigen Gegend.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Hiho","Hello, Hello.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Hallo");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Hey");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Greebas");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Greebs");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddAdditionalText("You greet me and I greet back: Greetings!");
    npcs.base.autonpcfunctions.AddAdditionalText("Good day.");
    npcs.base.autonpcfunctions.AddAdditionalText("Welcome to this sandy area.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Hiho","Hallo, Hallo.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Hallo");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Hey");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Greebas");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Greebs");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddAdditionalText("Du grüßt mich und ich grüße zurück: Grüße!");
    npcs.base.autonpcfunctions.AddAdditionalText("Guten Tag.");
    npcs.base.autonpcfunctions.AddAdditionalText("Willkommen in dieser sandigen Gegend.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Farewell","Have a nice day!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Good bye");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Bye");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Fare thy well");
    npcs.base.autonpcfunctions.AddAdditionalText("Goodbye, goodbye, come back soon!");
    npcs.base.autonpcfunctions.AddAdditionalText("Farewell, you friendly being!");
    npcs.base.autonpcfunctions.AddTraderTrigger("Tschüß","Einen schönen Tag auch.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Tschüss");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Wiedersehen");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Gehabt euch wohl");
    npcs.base.autonpcfunctions.AddAdditionalText("Leb wohl, leb wohl, komm bald wieder!");
    npcs.base.autonpcfunctions.AddAdditionalText("Auf bald, du freundliches Wesen!");
    npcs.base.autonpcfunctions.AddTraderTrigger("Ciao","Have a nice day!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Adieu");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Au revoir");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddAdditionalText("Goodbye, goodbye, come back soon!");
    npcs.base.autonpcfunctions.AddAdditionalText("Farewell, you friendly being!");
    npcs.base.autonpcfunctions.AddTraderTrigger("Ciao","Einen schönen Tag auch.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Adieu");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Au revoir");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddAdditionalText("Leb wohl, leb wohl, komm bald wieder!");
    npcs.base.autonpcfunctions.AddAdditionalText("Auf bald, du freundliches Wesen!");
    npcs.base.autonpcfunctions.AddTraderTrigger("How are you","I have a grain of sand in my eye - how would you feel?!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("How feel");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("How do you do");
    npcs.base.autonpcfunctions.AddAdditionalText("Fine, fine.");
    npcs.base.autonpcfunctions.AddAdditionalText("I just can say: I hope you are feeling as good as I do!");
    npcs.base.autonpcfunctions.AddTraderTrigger("Wie geht","Ich habe Sand ins Auge bekommen - wie würdest du dich fühlen?!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Wie fühlst");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Wie ist es ergangen");
    npcs.base.autonpcfunctions.AddAdditionalText("Gut, gut.");
    npcs.base.autonpcfunctions.AddAdditionalText("Ich kann nur sagen, ich hoffe es geht dir so gut wie mir!");
    npcs.base.autonpcfunctions.AddTraderTrigger("your name","I am Rutrus and who are you?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("who are you");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("who art thou");
    npcs.base.autonpcfunctions.AddAdditionalText("Be greeted, I am the digger Rutus.");
    npcs.base.autonpcfunctions.AddAdditionalText("I am Rutrus and this here is my shovel.");
    npcs.base.autonpcfunctions.AddTraderTrigger("dein name","Ich bin Rutrus und wer bist du?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("wer bist du");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("wer seid ihr");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("wie heißt");
    npcs.base.autonpcfunctions.AddAdditionalText("Grüße dich, ich bin der Gräber Rutrus.");
    npcs.base.autonpcfunctions.AddAdditionalText("Ich bin Rutrus und das in meinen Händen ist meine Schaufel.");
    -- Catching typical NPC phrases
    npcs.base.autonpcfunctions.AddTraderTrigger("what sell","I'm not a trader but a digger!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("what buy");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("list wares");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("price of");
    npcs.base.autonpcfunctions.AddAdditionalText("I do not sell or buy anything, but I may have a quest for you.");
    npcs.base.autonpcfunctions.AddAdditionalText("No trading! However, You could get some coins, if you do a task for me.");
    npcs.base.autonpcfunctions.AddTraderTrigger("was verkauf","Ich bin kein Händler sondern ein Gräber!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("was kauf");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("warenliste");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("preis von");
    npcs.base.autonpcfunctions.AddAdditionalText("Ich kaufe und verkaufe nichts, aber ich habe vielleicht eine Aufgabe für dich.");
    npcs.base.autonpcfunctions.AddAdditionalText("Kein Handel! Wie auch immer, du kannst ein paar Münzen bekommen, wenn du einen Auftrag erledigst.");
    npcs.base.autonpcfunctions.AddTraderTrigger("tell something","We have to be very thankful that the shovel allows us to work with it.");
    npcs.base.autonpcfunctions.AddAdditionalText("Without shovel no clay, without clay no bricks, without bricks no house! The shovel if the beginnig of everything.");
    npcs.base.autonpcfunctions.AddAdditionalText("Dig next to rocks for sand. There you can find the best sand to make glass.");
    npcs.base.autonpcfunctions.AddTraderTrigger("erzähl was","Wir müssen dankbar sein, dass die Schaufel uns das Arbeiten mit ihr erlaubt.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("erzähl etwas");
    npcs.base.autonpcfunctions.AddAdditionalText("Ohne Schaufel kein Lehm, ohne Lehm keine Ziegel, ohne Ziegel kein Haus! Die Schaufel ist der Anfang von Allem.");
    npcs.base.autonpcfunctions.AddAdditionalText("Grabe neben Steinen nach Sand. Da findet du den besten Sand zum Glasmachen.");
    -- Small talk: The talk here should focus on possible questions. Feel free to add more!
    npcs.base.autonpcfunctions.AddTraderTrigger("Profession","I'm a digger. I dig. I dig in the sand and where else you can dig.");
    npcs.base.autonpcfunctions.AddAdditionalText("My job? I bring sand to glassblowers.");
    npcs.base.autonpcfunctions.AddAdditionalText("I steal the sand from the desert.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Beruf","Ich bin Gräber. Ich grabe. Ich grabe im Sand und wo man sonst noch graben kann.");
    npcs.base.autonpcfunctions.AddAdditionalText("Mein Beruf? Ich bringe Glasbläsern Sand.");
    npcs.base.autonpcfunctions.AddAdditionalText("Ich stehle der Wüste den Sand.");
    npcs.base.autonpcfunctions.AddTraderTrigger("oasis","This is the Oasis of Stars - a paradise for diggers.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("desert");
    npcs.base.autonpcfunctions.AddAdditionalText("The desert is a nice place, yes. But you need to watch out for scorpions.");
    npcs.base.autonpcfunctions.AddAdditionalText("Welcome to the desert! If your throat gets try, you can visit the tavern.");
    npcs.base.autonpcfunctions.AddTraderTrigger("oase","Dies ist die Sternenoase - ein Paradies für Sandgräber!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("wüste");
    npcs.base.autonpcfunctions.AddAdditionalText("Obgleich unsere Wüste ein schöner Ort ist, sollte man sich vor den Skorpionen hüten.");
    npcs.base.autonpcfunctions.AddAdditionalText("Willkommen in der Wüste! Sollte deine Kehle mal zu trocken werden, schau doch in der Taverne vorbei.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Raban","Raban... I remember this name. It has been a while.");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("Raban","Raban... Ich erinnere mich an diesen Namen. Lange ist's her.");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    -- Factions
    npcs.base.autonpcfunctions.AddTraderTrigger("Runewick","Ein verwunschener Ort. Traue keinem Elfen, sage ich.");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("Runewick","A wicked place! Never trust an elf, I say.");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("Galmair","What's that for a location?");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("Galmair","Was soll das für ein Ort sein?");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("Cadomyr","Die lassen mich meist alleine.");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddAdditionalText("Manchmal gehe ich nach Cadomyr um meine Schaufel reparieren zu lassen.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Cadomyr","They leave me alone, usually.");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddAdditionalText("From time to time, I go to Cadomyr to get my shovel fixed.");
    -- Tool hints
    npcs.base.autonpcfunctions.AddTraderTrigger("Tool","The shovel is my tool. It seems to be a normal thing, but it is powerful in the right hands. I will give you one if you do a little task for me.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",0);
    npcs.base.autonpcfunctions.AddTraderTrigger("Werkzeug","Mein Werkzeug ist die Schaufel. Sie scheint gewöhnlich, aber in richtigen Händen ist sie mächtig. Ich gebe dir eine, wenn du Aufgaben für mich erledigst.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",0);
    npcs.base.autonpcfunctions.AddTraderTrigger("Schaufel","Werkzeug");
    npcs.base.autonpcfunctions.AddTraderTrigger("shovel","The shovel is my tool. It seems to be a normal thing, but it is powerful in the right hands. I will give you one if you do a little task for me.");
    -- 1st quest: Take a tool and gather 10 raw materials for 50cp.
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Oh! You want to help me? Take this shovel and get ten piles of coarse sand. Dig for it next to the rocks in the desert. Your reward will be fifty copper coins.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",0);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("item",24,1,399,0);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Oasis of Stars I");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Oh! Du willst mir helfen? Nehme diese Schaufel hier und beschaffe mir zehn Haufen groben Sand. Grabe neben Steinen in der Wüste. Dein Lohn sollen fünfzig Kupferlinge sein.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",0);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("item",24,1,399,0);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Sternenoase I");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","Oh! You want to help me? Take this shovel and get ten piles of coarse sand. Dig for it next to the rocks in the desert. Your reward will be fifty copper coins. Oh");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",0);
    npcs.base.autonpcfunctions.AddConsequence("item",24,1,399,0);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Oasis of Stars I");
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","! Du willst mir helfen? Nehme diese Schaufel hier und beschaffe mir zehn Haufen groben Sand. Grabe neben Steinen in der Wüste. Dein Lohn sollen fünfzig Kupferlinge sein.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",0);
    npcs.base.autonpcfunctions.AddConsequence("item",24,1,399,0);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Sternenoase I");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","You want to help me? Just bring me ten piles of coarse sand and you'll get fourty copper coins.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Oh! Du willst mir helfen? Bringe mir zehn Haufen groben Sand und dein Lohn sollen vierzig Kupferlinge sein.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","You want to help me? Just bring me ten piles of coarse sand and you'll get fourty copper coins.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Oh! Du willst mir helfen? Bringe mir zehn Haufen groben Sand und dein Lohn sollen vierzig Kupferlinge sein.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Oh, hoho! Das hast du toll gemacht. Hier deine versprochene Belohung. Solltest du noch eine Aufgabe wollen, sag es.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("item",726,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("town","=","cadomyr");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",726,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 50 Kupferstücke und deine Bergbaufertigkeit steigt. Dein Ansehen bei Königin Rosaline Edwards steigt.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","cadomyr","+",5);
    npcs.base.autonpcfunctions.AddConsequence("money","+",50);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Oh, hoho! Great job, my friend. Here is the reward I promised you. Just tell me, if you want an other task.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("item",726,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("town","=","cadomyr");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",726,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 50 copper coins and your mining skill increases. You advance in Queen Rosaline Edwards's favour.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","cadomyr","+",5);
    npcs.base.autonpcfunctions.AddConsequence("money","+",50);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Oh, hoho! Das hast du toll gemacht. Hier deine versprochene Belohung. Solltest du noch eine Aufgabe wollen, sag es.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("item",726,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",726,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 50 Kupferstücke und deine Bergbaufertigkeit steigt.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",50);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Oh, hoho! Great job, my friend. Here is the reward I promised you. Just tell me, if you want an other task.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("item",726,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",726,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 50 copper coins and your mining skill increases.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",50);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Ich sagte, du sollest zehn Haufen groben Sand bringen! Zurück in die Wüste, husch!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("item",726,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","I told you to bring me ten piles of coarse sand! Back into the desert!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("item",726,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    -- 2nd quest: Gather 20 different raw materials for 100cp.
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Another task? Alright, listen: I need twenty piles of quartz sand. First of all you need to get the coarse sand and then you need to filter it with a sieve. You will earn a hundred coppercoins.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",2);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Oasis of Stars II");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Du willst eine weitere Aufgabe? Hör zu: I brauche zwanzig Haufen Quartzsand. Zuerst musst du groben Sand sammeln und diesen dann mit einem Sieb filtern. Du wirst hundert Kupferlinge zum Lohn erhalten.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",2);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Sternenoase II");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","Another task? Alright, listen: I need twenty piles of quartz sand. First of all you need to get the coarse sand and then you need to filter it with a sieve. You will earn a hundred coppercoins.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",2);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Oasis of Stars II");
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Du willst eine weitere Aufgabe? Hör zu: I brauche zwanzig Haufen Quartzsand. Zuerst musst du groben Sand sammeln und diesen dann mit einem Sieb filtern. Du wirst hundert Kupferlinge zum Lohn erhalten.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",2);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Sternenoase II");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Another task? I need twenty piles of quartz sand. First of all you need to get the coarse sand and then you need to filter it with a sieve. You will earn eighty coppercoins.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Du willst eine weitere Aufgabe? I brauche zwanzig Haufen Quartzsand. Zuerst musst du groben Sand sammeln und diesen dann mit einem Sieb filtern. Du wirst achtzig Kupferlinge zum Lohn erhalten.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","Another task? I need twenty piles of quartz sand. First of all you need to get the coarse sand and then you need to filter it with a sieve. You will earn eighty coppercoins.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Du willst eine weitere Aufgabe? Ich brauche zwanzig Haufen Quartzsand. Zuerst musst du groben Sand sammeln und diesen dann mit einem Sieb filtern. Du wirst achtzig Kupferlinge zum Lohn erhalten.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Das ist doch mal feiner Sand. Und hier hast du dein Geld.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("item",316,"all",">",19);
    npcs.base.autonpcfunctions.AddCondition("town","=","cadomyr");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",316,20);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 100 Kupferstücke und deine Bergbaufertigkeit steigt. Dein Ansehen bei Königin Rosaline Edwards steigt.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","cadomyr","+",10);
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","This is what I call fine sand. And here is your money.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("item",316,"all",">",19);
    npcs.base.autonpcfunctions.AddCondition("town","=","cadomyr");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",316,20);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 100 copper coins and your mining skill increases. You advance in Queen Rosaline Edwards's favour.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","cadomyr","+",10);
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Das ist doch mal feiner Sand. Und hier hast du dein Geld.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("item",316,"all",">",19);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",316,20);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 100 Kupferstücke und deine Bergbaufertigkeit steigt.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","This is what I call fine sand. And here is your money.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("item",316,"all",">",19);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",316,20);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 100 copper coins and your mining skill increases.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Ich will meine zwanzig Haufen Quartzsand!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("item",316,"all","<",20);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","I want my twenty piles of quartz sand!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("item",316,"all","<",20);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    -- 3rd quest: Gather 5 rare raw materials for 100cp.
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","I need your help again. But this time it is a bit more complicated. I want you to collect five raw topaz and your reward will be a hundred coppercoins!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",4);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Oasis of Stars III");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Ich brauche wieder deine Hilfe. Dieses ist es etwas schwerer. Du sollst fünf ungeschliffene Topaze sammeln und dein Lohn sollen hundert Kupferlinge sein!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",4);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Sternenoase III");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","I need your help again. But this time it is a bit more complicated. I want you to collect five raw topaz and your reward will be a hundred coppercoins!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",4);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Oasis of Stars III");
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Ich brauche wieder deine Hilfe. Dieses ist es etwas schwerer. Du sollst fünf ungeschliffene Topaze sammeln und dein Lohn sollen hundert Kupferlinge sein!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",4);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Sternenoase III");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","I need you to collect five raw topaz. Could you... dig on?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Ich brauche dich, um fünf ungeschliffene Topaze zu sammeln. Buddel weiter!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","I need you to collect five raw topaz. Could you... dig on?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Ich brauche dich, um fünf ungeschliffene Topaze zu sammeln. Buddel weiter!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Du hast tatsächlich ungeschliffene Topaze gefunden? Großartig! Hier, dein Lohn.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("item",257,"all",">",4);
    npcs.base.autonpcfunctions.AddCondition("town","=","cadomyr");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",257,5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 100 Kupferstücke und deine Bergbaufertigkeit steigt. Dein Ansehen bei Königin Rosaline Edwards steigt.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","cadomyr","+",15);
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","You really found raw topaz? Great! Here you go.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("item",257,"all",">",4);
    npcs.base.autonpcfunctions.AddCondition("town","=","cadomyr");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",257,5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 100 copper coins and your mining skill increases. You advance in Queen Rosaline Edwards's favour.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","cadomyr","+",15);
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Du hast tatsächlich ungeschliffene Topaze gefunden? Großartig! Hier, dein Lohn.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("item",257,"all",">",4);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",257,5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 100 Kupferstücke und deine Bergbaufertigkeit steigt.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","You really found raw topaz? Great! Here you go.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("item",257,"all",">",4);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",257,5);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 100 copper coins and your mining skill increases.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",100);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Das sind aber nicht genug Topaze. Da musst du wohl noch ein bisschen graben.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("item",257,"all","<",5);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","You don't have enough topaz yet. It seems that you need to dig some more.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("item",257,"all","<",5);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    -- 4th quest: Gather 10 raw materials from a totally different location for 200cp. Link to other quest. Hint how to get there.
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","You are a hardworking one. I'd like to have a barbeque, all alone with my shovel. Can you bring me ten lumps of coal from the Dark Hole mine for two hundred copper coins?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",6);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Oasis of Stars IV");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Dich nenne ich fleißig! Ich würde gerne für meine Schaufel eine kleine Grillfeier schmeißen. Kannst du mir zehn Kohleklumpen für zweihundert Kupferstücke aus der Dunkellochmine bringen?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",6);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Sternenoase IV");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","You are a hardworking one. I'd like to have a barbeque, all alone with my shovel. Can you bring me ten lumps of coal from the Dark Hole mine for two hundred copper coins?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",6);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npcs.base.autonpcfunctions.AddConsequence("inform","[New quest] Oasis of Stars IV");
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Dich nenne ich fleißig! Ich würde gerne für meine Schaufel eine kleine Grillfeier schmeißen. Kannst du mir zehn Kohleklumpen für zweihundert Kupferstücke aus der Dunkellochmine bringen?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",6);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Sternenoase IV");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","You are a hardworking one. I'd like to have a barbeque, all alone with my shovel. Can you bring me ten lumps of coal from the Dark Hole mine for two hundred copper coins?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Dich nenne ich fleißig! Ich würde gerne für meine Schaufel eine kleine Grillfeier schmeißen. Kannst du mir zehn Kohleklumpen für zweihundert Kupferstücke aus der Silberbrandmine bringen?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","You are a hardworking one. I'd like to have a barbeque, all alone with my shovel. Can you bring me ten lumps of coal from the Dark Hole mine for two hundred copper coins?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Dich nenne ich fleißig! Ich würde gerne für meine Schaufel eine kleine Grillfeier schmeißen. Kannst du mir zehn Kohleklumpen für zweihundert Kupferstücke aus der Dunkellochmine bringen?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Ha! You did it great - just like all the other tasks. You were a big help and here are your coins. I'll place a sausage over the fire later on for you, my friend.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",21,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("town","=","cadomyr");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",21,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 200 copper coins and your mining skill increases. You advance in Queen Rosaline Edwards's favour.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","cadomyr","+",20);
    npcs.base.autonpcfunctions.AddConsequence("money","+",200);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",8);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Ha! Das hast du großartig gemacht - wie auch alle anderen Aufgaben. Du warst eine große Hilfe und hier ist dein Lohn. Ich werde nachher eine Extrawurst für dich auf den Grill packen, mein Freund.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",21,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("town","=","cadomyr");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",21,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 200 Kupferstücke und deine Bergbaufertigkeit steigt. Dein Ansehen bei Königin Rosaline Edwards steigt.");
    npcs.base.autonpcfunctions.AddConsequence("rankpoints","cadomyr","+",20);
    npcs.base.autonpcfunctions.AddConsequence("money","+",200);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",8);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Ha! You did it great - just like all the other tasks. You were a big help and here are your coins. I'll place a sausage over the fire later on for you, my friend.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",21,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",21,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 200 copper coins and your mining skill increases.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",200);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",8);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Ha! Das hast du großartig gemacht - wie auch alle anderen Aufgaben. Du warst eine große Hilfe und hier ist dein Lohn. Ich werde nachher eine Extrawurst für dich auf den Grill packen, mein Freund.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",21,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",21,10);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 200 Kupferstücke und deine Bergbaufertigkeit steigt.");
    npcs.base.autonpcfunctions.AddConsequence("money","+",200);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",8);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Zehn Klumpen Kohle - Das kann doch nicht so schwer sein!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",21,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Ten lumps of coal - shouldn't be too difficult, eh?");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",21,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    -- Final dialogue: No more quests, just nice hints
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","You helped me enough, really. I have no other jobs for you. But maybe you can find someone in the Dark Hole mine who will give you something to do. And remember: The shovel is your friend.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",8);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Du hast mir genug geholfen, wirklich. Ich habe keine Aufgaben mehr für dich. Aber vielleicht findest du in der Dunkellochmine jemanden, der etwas für dich zu tun hat. Und denk daran: Die Schaufel ist dein Freund.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",8);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","You helped me enough, really. I have no other jobs for you. But maybe you can find someone in the Dark Hole mine who will give you something to do. And remember: The shovel is your friend.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",8);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Du hast mir genug geholfen, wirklich. Ich habe keine Aufgaben mehr für dich. Aber vielleicht findest du in der Dunkellochmine jemanden, der etwas für dich zu tun hat. Und denk daran: Die Schaufel ist dein Freund.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",8);
    -- Cycletext: Please add at least(!) five cycletext messages. The more, the better. You can use emotes (#me is green), too.
    npcs.base.autonpcfunctions.AddCycleText("#me streicht sich durch das Haar und lässt so einige Sandkörner herumfliegen.","#me strokes through his hair and a few grains of sand fly around.");
    npcs.base.autonpcfunctions.AddCycleText("#me säubert seine Schaufel.","#me cleans his shovel. ");
    npcs.base.autonpcfunctions.AddCycleText("Na warte, Wüste. Ich grabe so lange, bis du erledigt bist!","Just wait, desert. I continue digging until you are gone!");
    npcs.base.autonpcfunctions.AddCycleText("#me lässt seinen Blick durch die Gegend wandern, während er sich auf seiner Schaufel abstützt.","#me leans on his shovel and looks around.");
    npcs.base.autonpcfunctions.AddCycleText("Ein Mann ohne Schaufel ist nur ein halber Mann.","A man without a shovel is just half a man.");
    npcs.base.autonpcfunctions.AddCycleText("#me murmelt etwas zu seiner Schaufel.","#me murmurs to his shovel.");
    npcs.base.autonpcfunctions.AddCycleText("#me beginnt, ein Loch im Sand auszuheben.","#me starts to dig a hole.");
    -- ********* END DYNAMIC PART ********
    TradSpeakLang={0,1};
    TradStdLang=0;

    npcs.base.autonpcfunctions.increaseLangSkill(TradSpeakLang);
    thisNPC.activeLanguage=TradStdLang;

end

function nextCycle()  -- ~10 times per second
    initializeNpc();
    npcs.base.autonpcfunctions.SpeakerCycle();
end

function receiveText(texttype, message, originator)
    if npcs.base.autonpcfunctions.BasicNPCChecks(originator,2) then
        if npcs.base.autonpcfunctions.LangOK(originator,TradSpeakLang) then
            npcs.base.autonpcfunctions.TellSmallTalk(message,originator);
        else
            npcs.base.autonpcfunctions.Confused(
               "#me sieht dich leicht verwirrt an",
               "#me looks at you a little confused"
            );
        end
    end
end