-- INSERT INTO npc VALUES (nextval('npc_seq'),1,-5,-137,0,4,false,'Saren Eisenfaust','npc_saren_eisenfaust.lua',0);

require("npcs.base.autonpcfunctions")

function useNPC(user,counter,param)
    thisNPC:increaseSkill(1,"common language",100);
    thisNPC:talkLanguage(CCharacter.say, CPlayer.german, "Finger weg!");
    thisNPC:talkLanguage(CCharacter.say, CPlayer.english, "Don't you touch me!");
end

function initializeNpc()
    if TraderFirst then
        return true;
    end

    npcs.base.autonpcfunctions.InitTalkLists();

    -- ********* START DYNAMIC PART ********

    npcs.base.autonpcfunctions.SetRadius(0);
    QuestID = 0;
    -- Queststatus Overview 
    -- 0: No Quest taken 
    -- 1: Quest 1 taken - gather 10 raw materials of two different kinds and 1 needed tools for +5 skill while skill<=20 
    -- 2: Quest 1 solved 
    -- 3: Quest 2 taken - gather 15 raw materials, 2 differnt tools and 5 semi finished products for +5 skill while 20<=40 
    -- 4: Quest 2 solved 
    -- 5: Quest 3 taken - gather 4 needed tools, 10 semi finished products of 2 kinds and 5 easy finished products for +5 skill while 40<=60 
    -- 6: Quest 3 solved 
    -- 7: Quest 4 taken - gather 15 semi finished products, 10 easy finished products of 2 kinds and 5 advanced finished products for skill+5 while 60<=80 
    -- 8: Quest 4 solved 
    -- Cycletext:
    npcs.base.autonpcfunctions.AddCycleText("#me streicht sich über seinen langen Bart.","#me uncurls his long beard.");
    npcs.base.autonpcfunctions.AddCycleText("#me blickt sich mistrauisch in der Höhle um und kratzt sich anschließend breit grinsend am Hintern.","#me looks around suspeciously through the cave and afterwards scratchs his buttocks grinning broadly.");
    npcs.base.autonpcfunctions.AddCycleText("#me nimmt eine Bierflasche aus seiner Tasche und trinkt einen Schluck","#me takes a beer bottle out of his bag and takes a mouthful.");
    npcs.base.autonpcfunctions.AddCycleText("#me wischt sich den Schweiß von der Stirn, als er die Arbeit unterbricht","#me wipes the sweat off his forehead, when he intterupts his work.");
    npcs.base.autonpcfunctions.AddCycleText("#me brummt leise etwas in seinen Bart als er beim Schmieden auf seinen Finger schlägt","#me grumbles something into his beard when he hits his finger with his hammer.");
    -- Help 
    npcs.base.autonpcfunctions.AddTraderTrigger("Help","[Game Help] This NPC is the smith Saren Eisenfaust. Keyphrases: Hello, quest, pickaxe, adventure");
    npcs.base.autonpcfunctions.AddTraderTrigger("Hilfe","[Spielhilfe] Dieser NPC ist der Schmied Saren Eisenfaust. Schlüsselwörter: Hallo, Quest, Aufgaben, Spitzhacke");
    -- General speech 
    npcs.base.autonpcfunctions.AddTraderTrigger("greetings","Good day, what do ya want?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("hello");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("huhu");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("good evening");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("good day");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("good morning");
    npcs.base.autonpcfunctions.AddAdditionalText("Irmorom with ya, do ya need anything?");
    npcs.base.autonpcfunctions.AddTraderTrigger("grüße","Tach auch, wat gibts?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("huhu");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Tach");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Guten Abend");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Guten Morgen");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Guten Tag");
    npcs.base.autonpcfunctions.AddAdditionalText("Irmorom zum Gruße, brauchst du wat?");
    npcs.base.autonpcfunctions.AddTraderTrigger("Hiho","What do ya want, eh? We say greetings around here.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Hallo");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Hey");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Greebas");
    npcs.base.autonpcfunctions.AddAdditionalTrigger(",english");
    npcs.base.autonpcfunctions.AddAdditionalText("Aye, whatever.");
    npcs.base.autonpcfunctions.AddAdditionalText("You won't come far with that, that's greetings around here.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Hiho","Wat willste, eh? Dat heißt Tach!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Hallo");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Hey");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Greebas");
    npcs.base.autonpcfunctions.AddAdditionalTrigger(",german");
    npcs.base.autonpcfunctions.AddAdditionalText("Aye, wat auch immer.");
    npcs.base.autonpcfunctions.AddAdditionalText("Damit kommste hier nich weit, es heißt Tach!");
    npcs.base.autonpcfunctions.AddTraderTrigger("Ciao","Eh..what did you just say about my mother?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Adieu");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Au revoir");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddAdditionalText("What are you jabbering about?");
    npcs.base.autonpcfunctions.AddAdditionalText("Nah, I don't wanna buy that!");
    npcs.base.autonpcfunctions.AddTraderTrigger("Ciao","Eh..wat hast du grad über meine Mutter gesagt?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Adieu");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Au revoir");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddAdditionalText("Wat quasselst du da?");
    npcs.base.autonpcfunctions.AddAdditionalText("Nay, ich will dat nich kaufen!");
    npcs.base.autonpcfunctions.AddTraderTrigger("who are you","I'm Saran and who are you?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("whats your name");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("your name");
    npcs.base.autonpcfunctions.AddAdditionalText("I'm called Saran, Saran Eisenfaust and what's your name?");
    npcs.base.autonpcfunctions.AddTraderTrigger("wer bist du","Ich bin der Saren und wer bist du?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("wer seid ihr");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("wie heißt du");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("dein name");
    npcs.base.autonpcfunctions.AddAdditionalText("Man nennt mich Saren, Saren Eisenfaust und wie nennt man dich?");
    npcs.base.autonpcfunctions.AddTraderTrigger("Farewell","Aye, take care.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("good bye");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("bye");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("see you");
    npcs.base.autonpcfunctions.AddAdditionalText("Irmorom with ya!");
    npcs.base.autonpcfunctions.AddAdditionalText("Until next time!");
    npcs.base.autonpcfunctions.AddTraderTrigger("Auf bald","Aye, machs gut.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Tschüß");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Wiedersehen");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Machs gut");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Bis dann");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Bis später");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Schönen Tag noch");
    npcs.base.autonpcfunctions.AddAdditionalText("Irmorom mit dir!");
    npcs.base.autonpcfunctions.AddAdditionalText("Man sieht sich.");
    npcs.base.autonpcfunctions.AddTraderTrigger("how are you","Can't say that something's bothering me and ya?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("how feel");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("how do you do");
    npcs.base.autonpcfunctions.AddAdditionalText("So-so, but I'm fine right now.");
    npcs.base.autonpcfunctions.AddTraderTrigger("wie gehts","Ich kann nich klagen und du?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("wie fühlst");
    npcs.base.autonpcfunctions.AddAdditionalText("Ganz gut und selbst?");
    npcs.base.autonpcfunctions.AddAdditionalText("Mal so, mal so, aber gerade geht es mir ganz gut.");
    -- Catching typical NPC phrases 
    npcs.base.autonpcfunctions.AddTraderTrigger("what sell","Do I looks like a merchant? I don't think so!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("what buy");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("list wares");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("price of");
    npcs.base.autonpcfunctions.AddAdditionalText("Nah, I don't buy anything and I won't ever sell something to you!");
    npcs.base.autonpcfunctions.AddAdditionalText("Maybe some other time, not today.");
    npcs.base.autonpcfunctions.AddTraderTrigger("was verkauf","Sehe ich aus wie ein Händler, ich denke nicht!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("was kauf");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("warenliste");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("preis von");
    npcs.base.autonpcfunctions.AddAdditionalText("Nay, ich kauf nix und verkaufen tu ich erst recht nix an dich!");
    npcs.base.autonpcfunctions.AddAdditionalText("Ein ander mal vielleicht, heute nich.");
    -- Small talk
    npcs.base.autonpcfunctions.AddTraderTrigger("profession","You ask what my profession is? I'm a smith, the best even.");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddAdditionalText("I'm a smith and you?");
    npcs.base.autonpcfunctions.AddTraderTrigger("Beruf","Du fragst nach meinem Beruf? Ich bin Schmied, einer der besten sogar.");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddAdditionalText("Von Beruf bin ich Schmied und du?");
    npcs.base.autonpcfunctions.AddTraderTrigger("location","You're in the mountains, where else?");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("Ort","In den Bergen bist du hier, wo sonst?");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("runewick","Runewick is the city full of that mage-folk right? Don't like them much.");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("runewick","Runewick ist die Stadt mit diesem Magierpack, stimmts? Mag die nicht besonders.");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("cadomyr","Well, a little hot there but the queen is supposed to be good looking, wouldn't mind if she came here.");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("cadomyr","Nun, ein bisschen warm dort, aber die Königin soll gutaussehen. Würde nichts dagegen haben, wenn sie mal herkommt.");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("galmair","Fine town, really fine town you know. But only if ya have enough silvercoins in your pocket you know what I mean?");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("galmair","Tolle Stadt, wirklich tolle Stadt weißt du. Aber nur wenn du genug Silbermünzen in der Tasche hast, weißt du was ich meine?");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("queen","Don't know her personally but wouldn't mind if she really is as good looking as they say. Told to be a harsh leader though.");
    npcs.base.autonpcfunctions.AddTraderTrigger("königin","Kenn die nicht persönlich aber würde mich nicht weigern wenn sie wirklich so gut aussieht wie man sagt. Man sagt auch das sie eine taffe herrscherin is.");
    npcs.base.autonpcfunctions.AddTraderTrigger("erzmagier","Kenn ich nicht, wer soll denn das sein?");
    npcs.base.autonpcfunctions.AddTraderTrigger("archmage","Don't know him, who's that supposed to be?");
    npcs.base.autonpcfunctions.AddTraderTrigger("don","Well, not much to say here. He's the leader of Galmair and does his job really good.");
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("don","Nun, gibt nicht viel zu sagen. Er ist der Anführer von Galmair und macht seine Arbeit sehr gut.");
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    -- Tool hints 
    npcs.base.autonpcfunctions.AddTraderTrigger("pickaxe","You can mine for ore with it, a merchant can surely sell ya one if you lose yours.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",0);
    npcs.base.autonpcfunctions.AddTraderTrigger("Spitzhacke","Damit kannst du das Erz abbauen, ein Händler kann dir sicher eine verkaufen wenn du deine verlierst");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",0);
    -- 1st quest
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","I can help ya if ya wanna become a smith, but first bring me 10 lumps of coal aswell as 10 chunks of iron ore, and don't forget to bring a hammer. Here is a pickaxe for you to get the ore.");
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",20);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("item",2763,1,399,0);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Ich kann dir helfen falls du Schmied werden willst,  hol mir aber erstma 10 Brocken Kohle sowie 10 Klumpen Eisenerz und nen Hammer nich zu vergessen. Hier noch die Spitzhacke zum abbauen des Erzes.");
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",20);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("item",2763,1,399,0);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npcs.base.autonpcfunctions.AddTraderTrigger("task","I can help ya if ya wanna become a smith, but first bring me 10 lumps of coal aswell as 10 chunks of iron ore, and don't forget to bring a hammer. Here is a pickaxe for you to get the ore.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",20);
    npcs.base.autonpcfunctions.AddConsequence("item",2763,1,399,0);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Ich kann dir helfen, falls du Schmied werden willst, dafür solltest du mir aber erstma 10 Brocken Kohle sowie 10 Klumpen Eisenerz bringen. Und hier eine Hacke um das Erz abzubauen.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",20);
    npcs.base.autonpcfunctions.AddConsequence("item",2763,1,399,0);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","I want ya to get 10 lumps of coal and 10 cunks of iron ore, and don't forget the hammer!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","10 Brocken Kohle und 10 Klumpen Eisenerz will ich das du holst, vergiss aber auch nicht den Hammer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","Aye, 10 lumps of coal and 10 chunks of iron ore and a hammer, that's what I want.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Aye, 10 Brocken Eisenerz, 10 Klumpen Kohle und nen Hammer is es wat ich haben will!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Arr, gut gemacht. Jetzt schau mir gut zu, damit du auch wat lernst!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("item",21,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("item",22,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("item",23,"all",">",0);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",21,10);
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",22,10);
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",23,1);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","smithing","+",5);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest erfüllt!] Du hast das Gefühl als hättest du was dazu gelernt.");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Arr, good job. Now watch me, so that you actually learn something!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("item",21,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("item",22,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("item",23,"all",">",0);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",21,10);
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",22,10);
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",23,1);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","smithing","+",5);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest finished!] You have the feeling as if you really learnt something.");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Arr, wenn du dir mit mir einen Spaß erlauben willst, werd ich dir nich helfen, ich sehe genau das du nich alles da hast wat ich haben wollte!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("item",21,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("item",22,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("item",23,"all","<",1);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Arr, if you try to trick me, I won't help you. I see that this is not everything that I wanted.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",1);
    npcs.base.autonpcfunctions.AddCondition("item",21,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("item",22,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("item",23,"all","<",1);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    -- 2nd quest 
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Aye, I have another task for ya. I need 15 copper ore, a new crucible, a fine smith hammer and 5 iron ingots!");
    npcs.base.autonpcfunctions.AddCondition("skill","smithing",">",20);
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",40);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Aye, hab wieder wat für dich zu tun. 15 Kupfererz, einen neuen Schmelztiegel, einen Feinschmiedehammer und 5 Eisenbarren brauch ich!");
    npcs.base.autonpcfunctions.AddCondition("skill","smithing",">",20);
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",40);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npcs.base.autonpcfunctions.AddTraderTrigger("task","Aye, I have another task for ya. I need 15 copper ore, a new crucible, a fine smith hammer and 5 iron ingots!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("skill","smithing",">",20);
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",40);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Aye, hab wieder wat für dich zu tun. 15 Kupfererz, einen neuen Schmelztiegel, einen Feinschmiedehammer und 5 Eisenbarren brauch ich!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("skill","smithing",">",20);
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",40);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Leave me be for now, I wanna smith something for me for a change. Come back later, alright?");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",2);
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",20);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Lass mich mal in Ruhe, will auch selber mal wat schmieden. Kannst ja später wieder kommen, nich?");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",2);
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",20);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","Leave me be for now, I wanna smith something for me for a change. Come back later, alright?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",20);
    npcs.base.autonpcfunctions.AddCondition("qpg","=",2);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Lass mich mal in Ruhe, will auch selber mal wat schmieden. Kannst ja später wieder kommen, nich?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",20);
    npcs.base.autonpcfunctions.AddCondition("qpg","=",2);
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Ya're supposed to bring me 15 copper ore, a crucible, a fine smith hammer and 5 iron ingots. Not that hard to memorize, is it?");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Du sollst mir 15 Kupfererz, einen neuen Schmelztiegel, einen Feinschmiedehammer und 5 Eisenbarren bringen, is das so schwer zu merken,eh?");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","Ya're supposed to bring me 15 copper ore, a crucible, a fine smith hammer and 5 iron ingots. Not that hard to memorize, is it?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Du sollst mir 15 Kupfererz, einen neuen Schmelztiegel, einen Feinschmiedehammer und 5 Eisenbarren bringen, is das so schwer zu merken,eh?");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Sieht gut aus, alles da wat ich von dir verlangt hab, scheint als könnt aus dir doch nen richtiger Schmied werden.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("item",2536,"all",">",14);
    npcs.base.autonpcfunctions.AddCondition("item",2535,"all",">",4);
    npcs.base.autonpcfunctions.AddCondition("item",2699,"all",">",1);
    npcs.base.autonpcfunctions.AddCondition("item",122,"all",">",1);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",2536,15);
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",25351,5);
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",2699,1);
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",122,1);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","smithing","+",5);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest erfüllt!] Du hast das Gefühl als hättest du was dazu gelernt.");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Looks good and even everything that I wanted ya to bring. Looks as if you could become a real smith after all.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("item",2536,"all",">",14);
    npcs.base.autonpcfunctions.AddCondition("item",2535,"all",">",4);
    npcs.base.autonpcfunctions.AddCondition("item",2699,"all",">",1);
    npcs.base.autonpcfunctions.AddCondition("item",122,"all",">",1);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",2536,15);
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",2535,5);
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",2699,1);
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",122,1);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","smithing","+",5);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest finished!] You have the feeling as if you really learnt something.");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Wie mir scheint, kann man sich nich auf dich verlassen. Oder du bist dümmer als du aussiehst, denn es is nich besonders schwer 15 Kupfererz, 5 Eisenbarren, einen Schmelztiegel und einen Feinschmiedehammer zu besorgen!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("item",2356,"all","<",15);
    npcs.base.autonpcfunctions.AddCondition("item",2535,"all","<",5);
    npcs.base.autonpcfunctions.AddCondition("item",2699,"all","=",0);
    npcs.base.autonpcfunctions.AddCondition("item",122,"all","=",0);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","It seems ya're not trustworthy after all, or maybe ya're just dumber that ya look, because you didn't bring me the 15 copper ore, 5 iron ingots, a crucible and a fine smith hammer.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",3);
    npcs.base.autonpcfunctions.AddCondition("item",2356,"all","<",15);
    npcs.base.autonpcfunctions.AddCondition("item",2535,"all","<",5);
    npcs.base.autonpcfunctions.AddCondition("item",2699,"all","=",0);
    npcs.base.autonpcfunctions.AddCondition("item",122,"all","=",0);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    -- 3rd quest
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Ya're quiet good now. It's time to teach ya something real. Bring me 10 iron ingots, 10 copper ingots, 5 steel greaves and 4 pickaxes, than I'll show ya what a smith can do.");
    npcs.base.autonpcfunctions.AddCondition("skill","smithing",">",40);
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",60);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Du machst dich ganz gut. Nun wird es aber an der Zeit dir wat richtiges beizubringen. Bring mir zehn Eisenbarren, zehn Kupferbarren, fünf Stahlbeinschienen und vier Spitzhacken, dann siehst du selbst was ein Schmied so alles kann.");
    npcs.base.autonpcfunctions.AddCondition("skill","smithing",">",40);
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",60);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npcs.base.autonpcfunctions.AddTraderTrigger("task","Ya're quiet good now. It's time to teach ya something real. Bring me 10 iron ingots, 10 copper ingots, 5 steel greaves and 4 pickaxes, than I'll show ya what a smith can do.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("skill","smithing",">",40);
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",60);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Du machst dich ganz gut. Nun wird es aber an der Zeit dir wat richtiges beizubringen. Bring mir zehn Eisenbarren, zehn Goldbarren, fünf Kupferbarren und vier große Schwertgriffe, dann siehst du selbst was ein Schmied so alles kann.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("skill","smithing",">",40);
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",60);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Be gone, I have no time for ya right now and as it seems you didn't make any progress! Practice some more, than I'll show you how to smith some nice weapons.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",4);
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",40);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Verschwinde, ich hab grad keine Zeit und so wie du aussiehst, hast du eh keine Fortschritte gemacht! Übe mehr, dann zeig ich dir auch wie man ne nette Waffe schmiedet.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",4);
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",40);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","Be gone, I have no time for ya right now and as it seems you didn't make any progress! Practice some more, than I'll show you how to smith some nice weapons.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",40);
    npcs.base.autonpcfunctions.AddCondition("qpg","=",4);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Verschwinde, ich hab grad keine Zeit und so wie du aussiehst, hast du eh keine Fortschritte gemacht! Übe mehr, dann zeig ich dir auch wie man ne nette Waffe schmiedet.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",40);
    npcs.base.autonpcfunctions.AddCondition("qpg","=",4);
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","It's 10 iron ingots, 10 copper ingots, 5 steel greaves and 4 pickaxes I wanted from you.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Es waren zehn Eisenbarren, zehn Kupferbarren, fünf Stahlbeinschienen und vier Spitzhacken die ich haben wollt, aye!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","It's 10 iron ingots, 10 copper ingots, 5 steel greaves and 4 pickaxes I wanted from you.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Es waren zehn Eisenbarren, zehn Kupferbarren, fünf Stahlbeinschienen und vier Spitzhacken die ich haben wollt, aye!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Endlich biste wieder zurück, ich hatte mir schon Sorgen gemacht. Nun pass aber auf wie ich die Erze kombiniere.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("item",2763,"all",">",3);
    npcs.base.autonpcfunctions.AddCondition("item",2535,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("item",2550,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("item",2176,"all",">",4);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",2763,4);
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",2535,10);
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",2550,10);
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",2176,5);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","smithing","+",5);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest erfüllt!] Du hast das Gefühl als hättest du was dazu gelernt.");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Finally, you're back, I started to worry about ya. Now watch me, how I combine those ore.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("item",2763,"all",">",3);
    npcs.base.autonpcfunctions.AddCondition("item",2535,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("item",2550,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("item",2176,"all",">",4);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",2763,4);
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",2535,10);
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",2550,10);
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",2176,5);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","smithing","+",5);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest finished!] You have the feeling as if you really learnt something.");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Wenn du nix lernen willst, dann mach das du verschwindest! Wenn du nichtmal die kleinsten Aufträge erfüllen willst, wie willste da nen guter Schmied werden?!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("item",2763,"all","<",4);
    npcs.base.autonpcfunctions.AddCondition("item",2535,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("item",2550,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("item",2176,"all","<",5);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","If ya don't wanna learn anything, just go. Ya don't even want to fulfill the simplest task, how do ya want to become a good smith than?!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",5);
    npcs.base.autonpcfunctions.AddCondition("item",2763,"all","<",4);
    npcs.base.autonpcfunctions.AddCondition("item",2535,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("item",2550,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("item",2176,"all","<",5);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    -- 4th quest
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Never thought I would see your face again. But good that you ask, I need 15 copper ingots, 10 war hammer, 10 rapier and 2 steel plate.");
    npcs.base.autonpcfunctions.AddCondition("skill","smithing",">",60);
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",80);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Das ich dich mal wieder zu Gesicht bekomme hätte ich nich gedacht. Aber jut das du fragst. 15 Kupferbarren, 10 Kriegshämmer, 10 Degen und 2 Stahlharnische bräuchte ich von dir.");
    npcs.base.autonpcfunctions.AddCondition("skill","smithing",">","60s");
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",80);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npcs.base.autonpcfunctions.AddTraderTrigger("task","Never thought I would see your face again. But good that you ask, I need 15 copper ingots, 10 war hammer, 10 rapier and 2 steel plate.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("skill","smithing",">",60);
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",80);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Das ich dich mal wieder zu Gesicht bekomme hätte ich nich gedacht. Aber jut das du fragst. 15 Kupferbarren, 10 Kriegshämmer, 10 Degen und 2 Stahlharnische bräuchte ich von dir.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddCondition("skill","smithing",">",60);
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",80);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Come back later, I've no time for ya at the moment.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",6);
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",60);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Komm später wieder, ich hab im Moment keine Zeit für dich.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",6);
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",60);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","Come back later, I've no time for ya at the moment.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",60);
    npcs.base.autonpcfunctions.AddCondition("qpg","=",6);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Komm später wieder, ich hab im Moment keine Zeit für dich.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("skill","smithing","=<",60);
    npcs.base.autonpcfunctions.AddCondition("qpg","=",6);
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","You were supposed to bring me 15 copper ingots, 10 war hammer, 10 rapier and 2 steel plate.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Die Sachen die du mir bringen solltest waren 15 Kupferbarren, 10 Kriegshämmer, 10 Degen und 2 Stahlharnische.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","You were supposed to bring me 15 copper ingots, 10 war hammer, 10 rapier and 2 steel plate.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Die Sachen die du mir bringen solltest waren 15 Kupferbarren, 10 Kriegshämmer, 10 Degen und 2 Stahlharnische.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Sehr gut gemacht, ich wusste man kann sich auf dich verlassen. Nun sperr die Augen weit auf und beobachte wie ich dat Schwert schmiede!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",2550,"all",">",14);
    npcs.base.autonpcfunctions.AddCondition("item",2675,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("item",226,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("item",2364,"all",">",1);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",2550,15);
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",2675,10);
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",226,10);
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",2364,2);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","smithing","+",5);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",8);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest erfüllt!] Du hast das Gefühl als hättest du was dazu gelernt.");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",2550,"all",">",14);
    npcs.base.autonpcfunctions.AddCondition("item",2675,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("item",226,"all",">",9);
    npcs.base.autonpcfunctions.AddCondition("item",2364,"all",">",1);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",2550,15);
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",2675,10);
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",226,10);
    npcs.base.autonpcfunctions.AddConsequence("deleteitem",2364,2);
    npcs.base.autonpcfunctions.AddConsequence("skill","crafting","smithing","+",5);
    npcs.base.autonpcfunctions.AddConsequence("qpg","=",8);
    npcs.base.autonpcfunctions.AddConsequence("inform","[Quest finished!] You have the feeling as if you really learnt something.");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Nay, ick red mit dir kein Wort mehr bist du mir nicht das bringst, was ich von dir haben wollte!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",2550,"all","<",15);
    npcs.base.autonpcfunctions.AddCondition("item",2675,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("item",226,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("item",2364,"all","<",2);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger(".+","Nah, I won't talk to ya until ya bring me the things I asked you for.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",7);
    npcs.base.autonpcfunctions.AddCondition("item",2550,"all","<",15);
    npcs.base.autonpcfunctions.AddCondition("item",2675,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("item",226,"all","<",10);
    npcs.base.autonpcfunctions.AddCondition("item",2364,"all","<",2);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    -- Final dialogue: No more quests, just nice hints 
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Nah, you learnt enough from me. You have to find out everything else there is. That's what a good smith is all about.");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",8);
    npcs.base.autonpcfunctions.AddCondition("lang","english");
    npcs.base.autonpcfunctions.AddTraderTrigger("quest","Nay, ich glaub du hast genug von mir gelernt. Alles weitere musst du jetzt selber herausfinden, das macht einen guten Schmied aus!");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",8);
    npcs.base.autonpcfunctions.AddCondition("lang","german");
    npcs.base.autonpcfunctions.AddTraderTrigger("task","Nah, you learnt enough from me. You have to find out everything else there is. That's what a good smith is all about.");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",8);
    npcs.base.autonpcfunctions.AddTraderTrigger("Auftrag","Nay, ich glaub du hast genug von mir gelernt. Alles weitere musst du jetzt selber herausfinden, das macht einen guten Schmied aus!");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npcs.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npcs.base.autonpcfunctions.AddCondition("qpg","=",8);
    -- Last catch: Think about keyphrases the player might say and that are not caught until here 
    npcs.base.autonpcfunctions.AddTraderTrigger("Yes","Aye, than go and collect those things I asked you for.");
    npcs.base.autonpcfunctions.AddAdditionalText("If ya say so.");
    npcs.base.autonpcfunctions.AddAdditionalText("Alright, have fun!");
    npcs.base.autonpcfunctions.AddTraderTrigger("Ja","Aye, dann mach dich auf dem Weg und sammel was ich von dir wollte!");
    npcs.base.autonpcfunctions.AddAdditionalText("Na wenn du meinst");
    npcs.base.autonpcfunctions.AddAdditionalText("Is gut, viel Vergnügen!");
    npcs.base.autonpcfunctions.AddTraderTrigger("No","What did ya say, I hope I didn't hear ya correctly?!");
    npcs.base.autonpcfunctions.AddAdditionalText("You say no... no to me, what do ya think your speaking to?");
    npcs.base.autonpcfunctions.AddAdditionalText("With that attitude, ya won't become a good smith.");
    npcs.base.autonpcfunctions.AddTraderTrigger("Nein","Wat sachste, ich hoffe ich habe mich verhört?!");
    npcs.base.autonpcfunctions.AddAdditionalText("Du sagst Nein...nein zu mir, wat denkst du mit wem du sprichst!");
    npcs.base.autonpcfunctions.AddAdditionalText("Dann nich, so wird nie was aus dir!");
    -- ********* END DYNAMIC PART ********
    TradSpeakLang={0,1};
    TradStdLang=0;

    npcs.base.autonpcfunctions.increaseLangSkill(TradSpeakLang);
    thisNPC.activeLanguage=TradStdLang;

end

function nextCycle()  -- ~10 times per second
    initializeNpc();
    npcs.base.autonpcfunctions.SpeakerCycle();
end

function receiveText(texttype, message, originator)
    if npcs.base.autonpcfunctions.BasicNPCChecks(originator,2) then
        if npcs.base.autonpcfunctions.LangOK(originator,TradSpeakLang) then
            npcs.base.autonpcfunctions.TellSmallTalk(message,originator);
        else
            npcs.base.autonpcfunctions.Confused(
               "#me sieht dich leicht verwirrt an",
               "#me looks at you a little confused"
            );
        end
    end
end
