-- I_2608_book_chronicle_3.lua
-- by Falk
require("base.books")
 
function UseItem(User, SourceItem, TargetItem, Counter, Param)
   if ( TargetItem.id == 266 ) or ( TargetItem.id == 267 ) then
      world:erase(SourceItem,1);
   else
      if base.books.InitBook() then
         base.books.AddLanguage("common language",0);
         
base.books.AddGermanBookText("Am 3. Januar fragt Crosis an, ob Interesse an einer Halblinggilde besteht. Die Gilde Hobbiteers entsteht.",0,0,0)
base.books.AddGermanBookText("Am 6. Januar fragt Fooser (FooserJohn) an, ob es Interesse an einer Farmer- und Bäcker Gilde gibt, diese Umfrage hat ein positives Ergebnis und die Cooperative Farmers Guild - CFG wird gegründet.",0,0,0)
base.books.AddGermanBookText("Am 6. Januar gründet Monsoon Ragingstorm The guild of wisdom and peace, doch scheint sie keinen Bestand zu haben.",0,0,0)
base.books.AddGermanBookText("Am 8. Januar beginnt die Wahl zum König von Silberbrand, welche Tialdin einstimmig gewinnt. Am 10. Januar wird die Halblinggilde Hobbiteers offiziell gegründet.",0,0,0)
base.books.AddGermanBookText("Am 10. Januar wird eine Umfrage im Volke gestartet, um den Fluss zwischen Bücherei und Taverne einen Namen zu geben, man stimmte für Troll's Vein ab.",0,0,0)
base.books.AddGermanBookText("Am 13. Januar gründet Salathe die englische Echsen Gilde Zelphia's Dragoons und wirbt für Echsen als Mitglieder. Sie scheint keinen Bestand zu haben.",0,0,0)
base.books.AddGermanBookText("Am 13. Januar wurde eine Umfrage in der Bevölkerung begonnen bezüglich des nördlichen Flusses, nach geraumer Zeit einigte man sich auf den Namen: Fairy's Tears. Beide Abstimmungen wurden von Dyluck durchgeführt.",0,0,0)
base.books.AddGermanBookText("Am 16. Januar hat die Elven Community nun einen neuen Namen, sie nennen sich Eldamar welches soviel wie Heimat der Elben heißt.",0,0,0)
base.books.AddGermanBookText("Am 17. Januar findet die erste größere Versteigerung von Bodenschätzen statt, die den Ruf nach einem Auktionshaus hervorrief und den Grundstein für viele weitere Auktionen legte.",0,0,0)
base.books.AddGermanBookText("Am 17. Januar bittet Tialdin im Gebet an Irmorom im Namen aller Zwerge für die Stärkung und den Erhalt der Zwergenstadt.",0,0,0)
base.books.AddGermanBookText("Am 18. Januar schlug ein Elf namens Freaper eine Modenschau vor und erarbeitete erste Pläne. Diese wurden allerdings mit Argwohn betrachtet und bis zum heutigen Tage verschmäht.",0,0,0)
base.books.AddGermanBookText("Am 19. Januar, zerstört Dyluck das Schwert im Manabrunnen, da er um dessen Missbrauch fürchtet.",0,0,0)
base.books.AddGermanBookText("Am 19. Januar kreisen Gerüchte, das der Schmied Josef sich an die Herstellung einer Feueraxt für Zwergenhände heranwagte. Der Clan der Axt sucht nun nach dem besten Schmied Illarions, welcher es schafft eine Feueraxt zu schmieden.",0,0,0)
base.books.AddGermanBookText("Am 20. Januar, beginnt ein Schattenwesen die Umgebung von Troll's Bane unsicher zu machen. Mehrere Opfer sind zu beklagen bevor das Wesen spurlos verschwindet. Ein Lichtwesen und mehrere Bürger sprechen der Stadt Mut zu.",0,0,0)
base.books.AddGermanBookText("Am 22. Januar entstand die Idee für die erste Herberge Troll's Bane und bestimmte die Zukunft des Gebäudes an der westlichen Küste.",0,0,0)
base.books.AddGermanBookText("Am 24. Januar schlägt Turin Ironhammer den Gilden Oberhäuptern einen Handel vor. Am 24. Januar lädt Dyluck die Graue Rose und das Graue Licht zu einem Bankett ein, um eine alte Gewohnheiten wieder aufleben zu lassen.",0,0,0)
base.books.AddGermanBookText("Am 27. Januar, richtet Fieps in seinem kürzlich erworbenen Haus eine Herberge ein. Der Grauen Rose werden Nutzungsrechte des Gartens eingeräumt. Genannt wird es: The Seahorse.",0,0,0)
base.books.AddGermanBookText("Am 27. Januar, gründet Paul Laffing ein Geschäft für Schneiderwaren. Am 28. Januar, findet die Tempeleinweihung des Tempels des Irmorom in Silberbrand durch Priester Rugosch statt.",0,0,0)
base.books.AddGermanBookText("Am 30. Januar, wird Tialdin zum König von Silberbrand gekrönt. Am 30. Januar fragt Tialdin an, welche Räumlichkeiten inSilberbrand noch gebraucht werden.",0,0,0)
base.books.AddGermanBookText("Am 31. Januar, ernennt Tialdin Rugosch zum Berater in Glaubensfragen, Bombor zum Herold und den Klan der Axt zur Stadtgarde von Silberbrand.",0,0,0)
base.books.AddGermanBookText("Am 1. Februar, finden kleinere Angriffe von Orks auf die Stadt statt. Ein größerer Angriff der Orks wird befürchtet. Am 5. Februar gründet Nilo die Gilde Intermediate Wizards Guild eine Schule und Gilde für Zauberer.",0,0,0)
base.books.AddGermanBookText("Am 7. Februar gründet Paul Laffing die Foundation for the Protection of Merchants, sie soll offensichtlich dem Schutz von Händlern und Arbeitern vor Dieben und anderen Verbrechern dienen.",0,0,0)
base.books.AddGermanBookText("Am 8. Februar, wird das Festival of Life gefeiert.",0,0,0)
base.books.AddGermanBookText("Am 12. Februar, startet der Elf Elkrim mit Dominikus Alleradis in die Wüste. Die Expedition endet in einem Disaster. Zwerge des Klans der Axt greifen Elkrim an, weil sie glauben er sei von einem Dämon besessen.",0,0,0)
base.books.AddGermanBookText("Darauf erhebt Elkrim schwere Anschuldigungen gegen den Klan der Axt.",0,0,0)
base.books.AddGermanBookText("Am 12. Februar beruft jemand mit Namen Callith The warrior priests of Malachin ein, es wirkt jedoch sehr fadenscheinig.Da sich selbige Person als hoher Priester Malachins ausgibt, aber völlig unbekannt in unserer Stadt ist.",0,0,0)
base.books.AddGermanBookText("Am 15. Februar, hängt Dominikus eine öffentliche Note aus, die den Klan der Axt schwer belastet. Die Anschuldigungen stellen sich später jedoch als unwahr heraus. Einen Tag später verlässt Dominikus die Insel.",0,0,0)
base.books.AddGermanBookText("Am 18. Februar gründet Asteron The Artemis Alliance Guild, Gemeinschaft von ausschließlich Barden, Druiden und Magiern. Öffentlich angegebene Ziele sollen das Besprechen von Magie und Auskundschaften neuer Informationen darüber sein.",0,0,0)
base.books.AddGermanBookText("Am 20. Februar findet eine Anhörung von Elkrim und den Zwergen unter Priesteraufsicht statt.",0,0,0)
base.books.AddGermanBookText("Im Laufe der Anhörung stellt sich heraus das Elkrim von einem parasitären Dämon befallen ist, der die Kontrolle über Elkrims Körper übernahm und sich mit Elkrims Körper daran machte Streit zwischen Elfen und Zwergen zu schüren.",0,0,0)
base.books.AddGermanBookText("Den anwesenden Priestern gelingt es den Parasiten zu entfernen. Auch ein vom Schattenwesen angefallener und zufällig anwesender Mensch wird geheilt.",0,0,0)
base.books.AddGermanBookText("König Tialdin erteilt infolge der jüngsten Ereignisse, allen Leuten die Beleidigungen gegen Bürger von Silberbrand ausgesprochen hatten Amnestie.",0,0,0)
base.books.AddGermanBookText("Am 22 Februar erstellt der Lizard Xerake die School of Ninjutsu, dabei handelt es sich offensichtlich um eine Schule die den Kämpfern einen besonderen Kampfstil lehrt und den Kampf trainiert.",0,0,0)
base.books.AddGermanBookText("Am 28 Februar gründet der Zwerg Dunthor die Druids of Troll's Bane, anscheinend weisen sie die gleichen Merkmale wie die Druiden des Waldes auf und stellen somit eine Konkurrenz für diese dar.",0,0,0)
base.books.AddGermanBookText("Man versucht erst eine Gemeinschaft der zwei Gilden zu schaffen, welche jedoch fehlschlägt aufgrund der Niedrigpreise der Druids of Troll's Bane.",0,0,0)
base.books.AddGermanBookText("Es ist auch wahrscheinlich, dass diese Gilde mittlerweile untergegangen ist, da Dunthor sich häufiger Verbrechen von Mord, Betrug bis Diebstahl schuldig gemacht hat.",0,0,0)
base.books.AddGermanBookText("Am 28 Februar versucht nach dem Scheitern von The Artemis Alliance Guild der Elf Asteron erneut und gründet The Magic Alliance.",0,0,0)
base.books.AddGermanBookText("Eine Vereinigung von Magiern, welche den Stadtregeln folgen und zur Hilfe und dem Schutz und der Heilung anderer dienen sollen.",0,0,0)
base.books.AddGermanBookText("Im Jahre 3 des neuen Zeitalters in den Märztagen wurde der Ruf nach einer Regierung laut, welche in der Lage wäre das Verbrechen in Troll's Bane zu bekämpfen. Längere Diskussionen erfolgen darauf.",0,0,0)
base.books.AddGermanBookText("Am 3. März, wird der Halbling Bado wegen seiner bösen Taten angeklagt und zu einer Haftstrafe verurteilt.",0,0,0)
base.books.AddGermanBookText("Am 8 März startet der Mensch Farmar die Gemeinschaft The Keepers of the Peace Guild, welche gegen das Böse und Zwietracht vorgehen sollen.",0,0,0)
base.books.AddGermanBookText("Am 9. März wird die Umbenennung der Hobbiteers in Evergreen Halflings bekannt gegeben.",0,0,0)
base.books.AddGermanBookText("Am 10 März wird von einer anonymen Person eine Diebesgilde ans Licht gebracht.",0,0,0)
base.books.AddGermanBookText("So ein dreistes Unternehmen konnte jedoch der Öffentlichkeit nicht ihre Mitglieder und dergleichen vorstellen, ist daher in den Untergrund abgetaucht, es ist jedoch zu vermuten das sie dort noch immer arbeiten.",0,0,0)
base.books.AddGermanBookText("Am 17 März gründet Bloodhearte den Cult of the Blackstone. Anscheinend eine Gemeinschaft von Anhängern Moshrans und somit von Wesen die dem Bösen folgen und Chaos, Krieg und Leid propagandieren.",0,0,0)
base.books.AddGermanBookText("Am 18. März, findet der befürchtete Orkangriff statt. Die Massen an Orks drohen die Stadt zu überrollen. Den Bewohnern gelingt es mit Mühe und Not die Angriffe abzuwehren.",0,0,0)
base.books.AddGermanBookText("Am 18. März, erkrankt Malinne an einer seltsamen Krankheit. Am 19. März, wird ein Kopfgeld auf Bloodhearte ausgesetzt.",0,0,0)
base.books.AddGermanBookText("Am 23 März wird von einem Unbekannten der Cult of the Diamond ausgerufen als Gegenpart zum Cult of the Blackstone.",0,0,0)
base.books.AddGermanBookText("Die Hauptidee soll jedoch vom Zwergen Randelf gestammt haben. Er ist bedeutungslos.",0,0,0)
base.books.AddGermanBookText("Am 24 März macht Randelf The Goldsmithing Guild öffentlich und wirbt um Mitglieder. Jedoch werden nur Personen mit guten Fähigkeiten in der Goldschmiedekunst aufgenommen.",0,0,0)
base.books.AddGermanBookText("Am 24. März, wird Bloodhearte von einer Gruppe Echsenmenschen im Kampf besiegt.",0,0,0)
base.books.AddGermanBookText("Am 24. März, veröffentlicht Bloodhearte das Buch The Definition of Evil. Das Buch enthält Pläne zur Erweckung Moshrans auf Illarion. Viel Protest und Warnungen ergehen.",0,0,0)
base.books.AddGermanBookText("Am 25. März wird von Cedric Kilmar die Gründung des Zirkels Ritter des Schicksals bekannt gegeben.",0,0,0)
base.books.AddGermanBookText("Ab dem 31. März verfasst ein unbekannter Dichter ein Spottlied über die Zwerge vom Klan der Axt.",0,0,0)
base.books.AddGermanBookText("Am 27. März, macht sich Cain Freemont auf die Suche nach einem Heilmittel für Malinne.",0,0,0)
base.books.AddGermanBookText("Am 2. April, brechen Sevious Helios, Cain Freemont, Fortinbris Bloodhearte, Boremier und Ezorock zu einer Reise auf das Festland im Norden auf.",0,0,0)
base.books.AddGermanBookText("Am 9. April, wird Elaralith in der Öffentlichkeit für ihr Verhalten kritisiert, das einer Elarapriesterin unwürdig ist.",0,0,0)
base.books.AddGermanBookText("Die Elder von Eldamar erteilen ihr daraufhin eine Rüge. Am 11. April, wurde die Lyrenzia Foundation der Öffentlichkeit präsentiert.",0,0,0)
base.books.AddGermanBookText("Sie wurde schon seit Monaten von den folgenden fünf Gilden geplant: Graue Rose, Graues Licht, Magic Academy, Rangers, Silverbrand.",0,0,0)
base.books.AddGermanBookText("Das Ziel dieses Zusammenschlusses ist es, Recht und Ordnung zu schaffen und zum Wohle der Stadt zusammen zu arbeiten. Gelenkt wird sie vom Rat von Lyrenzia bestehend aus je einem Vertreter der Gilden.",0,0,0)
base.books.AddGermanBookText("Lyrenzia will auch weitere Gilden einladen, beizutreten und mit zu arbeiten. Am 11 April treten die Silver Star Merchants der Lyrenzia Foundation bei.",0,0,0)
base.books.AddGermanBookText("Im 3. Jahr des neuen Zeitalters am 14. April erklärte Darlok als Führer einer Gruppe von Leuten fünf Hobbits unter der Führung von Crosis den Krieg.",0,0,0)
base.books.AddGermanBookText("Vorausgegangen war ein Konflikt mit dem Auftragskiller Xerake und den Hobbits, in dem Darlok eingriff und Xerake half. Die Meinungen gehen zwar auseinander, aber es erscheint wahrscheinlich, dass Darlok den Krieg provoziert hat.",0,0,0)
base.books.AddGermanBookText("Die Kämpfe zogen sich hin und es gab auf beiden base.books.AddGermanBookTextn Tote.",0,0,0)
base.books.AddGermanBookText("Am 15 April eröffnet Drathe die Vereinigung mit Namen Archers of Illar, welche wie der Titel besagt eine Gemeinschaft von Bogenschützen in Illarion darstellen.",0,0,0)
base.books.AddGermanBookText("Am 16 April können Die Druiden des Waldes zwei neue Mitglieder anwerben und erleben somit einen kleinen Wiederaufschwung.",0,0,0)
base.books.AddGermanBookText("Am 19. April treten die Druiden des Waldes der Lyrenzia Foundation bei. Am 19. April, entschließt sich Xerake seinen Beruf als Auftragsmörder aufzugeben.",0,0,0)
base.books.AddGermanBookText("Am 19. April, eröffnet Aragon den Vorschlag eines möglichen Friedens zwischen Darlok und den Halblingen. Der Vorschlag wird abgelehnt.",0,0,0)
base.books.AddGermanBookText("Im 3. Jahr des neuen Zeitalters am 19. April wurde ein Frieden zwischen Darlok und Crosis geschlossen, nachdem die Hobbits Reparationszahlungen an Darlok leisteten.",0,0,0)
base.books.AddGermanBookText("Am 20. April treten die Hobbiteers der Lyrenzia Foundation bei.",0,0,0)
base.books.AddGermanBookText("Am 20. April veröffentlicht die Lyrenzia Foundation erstmalig ein Besitzstandsbuch der bisherigen Häuser in Troll's Bane.",0,0,0)
base.books.AddGermanBookText("Am 22 April verkündet Galadria das die Followers of Sirani neue Anhänger gefunden haben: Loki Feuerhaar und Inioch Hope.",0,0,0)
base.books.AddGermanBookText("Am 23 April werden die Golden Tree Merchants von Tredric gegründet. Ihr Hauptaugenmerk liegt auf den sehr geringen Preisen für Holz, wie der Name aber besagt, ist es auch die einzige Ware die verkauft wird")
base.books.AddGermanBookText("Am 24 April gründet Nilo The New Illarion School of Magic in Zusammenarbeit mit Grant Herion. Offizielle Lehrer in dieser Schule sind ab 28 April: Drogla, Lenti, Deats und Nilo.",0,0,0)
base.books.AddGermanBookText("Am 26 April startet Deats (Hades) eine Umfrage über die Bargen Masters, offensichtliche Gründe scheinen zu sein, dass ihnen wieder mehr Augenmerk geschenkt werden soll und um deren Mitgliederzahl zu erhöhen.",0,0,0)
base.books.AddGermanBookText("Am 29 April gibt die Lyrenzia Foundation ein öffentliches Wahlverfahren für registrierte Bürger bekannt. Registrierte Bürger werden die genannt, die seit vier Monaten in Troll's Bane wohnen.",0,0,0)
base.books.AddGermanBookText("Sie dürfen eigene Vertreter in den Lyrenzia Rat wählen und an anderen Abstimmungen teilnehmen.",0,0,0)
base.books.AddGermanBookText("Am 29. April gibt die Lyrenzia Foundation die Gründung eines fünf Mitglieder umfassenden SMACC-Rates bekannt. Darin arbeiten Fieps, Mishrak, Lennier, Niniane und ein fünfter frei wählbarer Händler mit.",0,0,0)
base.books.AddGermanBookText("Am 1. Mai legen Samuel Sherwood und Allraune Nachtwind ein Ehegelübte im engsten Freundeskreise ab.",0,0,0)
base.books.AddGermanBookText("Am 2. Mai warnt Crosis alle Halblinge, dass Grant Herion und Bloodhearte versuchen Halblinge zu fangen. Er äußert außerdem den Verdacht, dass Viola Thistle unter der Kontrolle von Grant Herion steht.",0,0,0)
base.books.AddGermanBookText("Am 2. Mai zieht sich Fortinbris Bloodhearte aus der Stadt in die nördlichen Ruinen zurück um dort neue Kräfte zu sammeln und um Moshran um die Gabe Mumien zu beschwören zu bitten.",0,0,0)
base.books.AddGermanBookText("Am 5. Mai wirft John Irenicus Darlok vor sich mit dem Verkauf von verfluchten Spiegeln eine Burg finanzieren zu wollen. Darlok dementiert dies.",0,0,0)
base.books.AddGermanBookText("Am 10. Mai griffen ungefähr 40 Oger die Stadt an. Sie konnten an den Toren der Stadt von den Bürgern zurück geschlagen werden.",0,0,0)
base.books.AddGermanBookText("Am 11. Mai wurde Olivia Smallburrow, Tochter von Rosa Underhill und Crosis, geboren.",0,0,0)
base.books.AddGermanBookText("Am 11. Mai wurde die erste SMACC-Rat Wahl einberufen. Kandidaten sind: Hermie, Paul Laffing, Cain Freemont, Josef.",0,0,0)
base.books.AddGermanBookText("Am 11. Mai gibt die Lyrenzia Foundation bekannt, Pläne für eine Stadtmauer zum Wohle der Stadt in Auftrag gegeben zu haben. Und sie bittet um Spenden für den Bau. Der Bau der Stadtmauer bleibt umstritten.",0,0,0)
base.books.AddGermanBookText("Am 12. Mai werden mehrere Personen durch Hagen von Rabenfeld bei Lyrenzia angeklagt. Sie sollen Kreaturen beschworen, Ritualmorde begangen und einen geheimen Kult gegründet haben.",0,0,0)
base.books.AddGermanBookText("Drei von fünf Personen werden verurteilt, eine war vor Beginn des Verfahrens schon verstorben.",0,0,0)
base.books.AddGermanBookText("Am 13. Mai verlangten einige düstere Gesellen von den Stadtbewohnern ungerechtfertigt Steuern. Ihr Betrug fiel auf, als sich eines ihrer Opfer an die Öffentlichkeit gewendet hatte.",0,0,0)
base.books.AddGermanBookText("Am 14. Mai wurde Adicus, Sohn von Sabrina und Dyluck, geboren. Am 15. Mai schrieb Crosis eine erfolglose Petition gegen die Stadtmauer.",0,0,0)
base.books.AddGermanBookText("Am 15. Mai wird die Verödung des östlichen Inselteils festgestellt. Tiere verschwinden, Bäume sterben, die Temperatur steigt drastisch. Die Ursachen der Dürre bleiben noch unklar.",0,0,0)
base.books.AddGermanBookText("Am 17. Mai gewann Cain Freemont die SMACC Wahl mit ungefähr 70 % der Stimmen.",0,0,0)
base.books.AddGermanBookText("Am 18. Mai weist Moathia darauf hin, dass sich die Wüste ausbreitet. Mögliche Ursachen werden diskutiert.",0,0,0)
base.books.AddGermanBookText("Am 18. Mai startet eine Diskussion über den begonnen Bau der Stadtmauer. Ängste über Steuern und ein totalitäres Regime werden geschürt.",0,0,0)
base.books.AddGermanBookText("Am 19. Mai kehrt Belegi nach wochenlanger Abwesenheit nach Troll's Bane zurück. Am 19. Mai wird ein drastisches Baumsterben im südlichen Hain festgestellt.",0,0,0)
base.books.AddGermanBookText("Am 19. Mai ruft Seth Valor zu einer Suche nach den verschwundenen Tieren der Insel auf. Die Suche wird ergebnislos abgebrochen.",0,0,0)
base.books.AddGermanBookText("Am 20. Mai tauchen erstmals Advokaten auf. Sie versuchen sich am Rechtprozess zu bereichern.",0,0,0)
base.books.AddGermanBookText("Am 21. Mai klagt Cain Freemont die als Priesterin Elaras bekannte Elaralith wegen versuchten Mordes an seiner Person an. Ihr Priesteramt wird in Frage gestellt.",0,0,0)
base.books.AddGermanBookText("Am 21. Mai sucht Ikaron einen Priester wegen Besessenheit und vereinbart ein Treffen mit Nerevar Schattenaxt.",0,0,0)
base.books.AddGermanBookText("Am 24. Mai will Moyave einen unabhängigen Vertreter der unregistrierten Bürger Troll's Bane etablieren. Ihr Vorschlag findet kein Gehör.",0,0,0)
base.books.AddGermanBookText("Am 26. Mai wird die Elbin Reda von zwei Echsen beim Zelphiaschrein gefangengehalten. Reynu Thadiaol bittet um Hilfe.",0,0,0)
base.books.AddGermanBookText("Am 26. Mai sucht Armil Darken drei gute Magier für ein Ritual, um Insekten herbeizaubern zu können.",0,0,0)
base.books.AddGermanBookText("Am 27. Mai verkündet Paul Laffing, dass er die Stadt abfackeln will, damit Neues entstehen kann. Er wird deshalb später sicherheitshalber verwahrt.",0,0,0)
base.books.AddGermanBookText("Am 28. Mai wird aufgrund eines Feuers die Bibliothek für einige Tage geschlossen.",0,0,0)
base.books.AddGermanBookText("Am 29. Mai stößt Ikaron eine Diskussion über den Sinn von Lyrenzia an. Die Gegner bleiben aber wirklicher Argumente schuldig.",0,0,0)
base.books.AddGermanBookText("Am 30. Mai wird Paul Laffing ermordet. Jedoch taucht er später wieder auf und behauptet, durch eine Göttin neu geboren worden zu sein.",0,0,0)
base.books.AddGermanBookText("Am 31. Mai gibt die Lyrenzia Foundation bekannt, dass in ihrem Justizsystem die Strafe Exil abgeschafft wurde und nur noch Gefängnisstrafen verhängt werden.",0,0,0)
base.books.AddGermanBookText("Am 31. Mai wird von Elaralith festgestellt, dass die Bäume an Falkners Hain nicht mehr nachwachsen und verdorren. Einige Tage später scheint wieder alles in Ordnung zu sein.",0,0,0)
base.books.AddGermanBookText("Am 1. Juni öffnet Agons Geschenkladen wieder.",0,0,0)
base.books.AddGermanBookText("Am 2. Juni organisieren Kincent Nolatri und Pronom Palmsugar das Festival Days of Duell, ein Kampfturnier. Sieger wird Trice.",0,0,0)
base.books.AddGermanBookText("Am 2. Juni wird aufgrund der Dürre ein Fest für Tanora vorgeschlagen, welches aber nicht stattfindet.",0,0,0)
base.books.AddGermanBookText("Am 2. Juni entdeckt Brendan Mason in der Bibliothek alte Schriftrollen, die davon berichten, dass Oger in Dürrezeiten alles Essbare in ihren Höhlen horten.",0,0,0)
base.books.AddGermanBookText("Ein Hinweis auf die verschwundenen Nutztiere. Suchexpeditionen nach der Höhle werden gestartet.",0,0,0)
base.books.AddGermanBookText("Am 3. Juni berichtet Leinad von einem Necromancer, der vor seinen Augen Untote herbeizauberte. Es wird vermutet, dass dies Darlok sei.",0,0,0)
base.books.AddGermanBookText("Am 4. Juni greift eine Horde Oger Troll's Bane an und die Stadtmauer besteht ihre erste Feuerprobe. Hagen von Rabensfeld und Dhalsim tun sich bei der Verteidigung hervor.",0,0,0)
base.books.AddGermanBookText("Es wird vermutet, dass hinter dem Angriff mehr steckt. Einen Tag später greifen wieder Oger an.",0,0,0)
base.books.AddGermanBookText("Am 5. Juni, fand die Hochzeit von Andriel und Dhalsim statt.",0,0,0)
base.books.AddGermanBookText("Am 6. Juni setzt König Tialdin den Zwerg Josef als Inquisitor ein. Am 6. Juni tritt der Clan der Axt als neunte Gilde der Lyrenzia Foundation bei.",0,0,0)
base.books.AddGermanBookText("Am 9. Juni macht sich nun auch der Wasserverlust der Flüsse durch die Dürre bemerkbar.",0,0,0)
base.books.AddGermanBookText("Am 9. Juni, behauptet Kincent Nolatri, er wäre von einem Vampir gebissen worden. Wie sich herausstellte, war dies nur erfunden worden um Aufmerksamkeit zu erregen.",0,0,0)
base.books.AddGermanBookText("Am 10. Juni, startet Grant Herion eine Suchaktion nach der geheimen Ogerhöhle.",0,0,0)
base.books.AddGermanBookText("Am 11. Juni, wurde die Stadt wieder von ein paar Ogern angegriffen, die scheinbar auf der Suche nach Nahrung waren.",0,0,0)
base.books.AddGermanBookText("Am 12. Juni, ruft Leinad zu einer Expedition auf, die sich zur Aufgabe gemacht hat, die Insel zu kartographieren.",0,0,0)
base.books.AddGermanBookText("Am 13. Juni, gibt Lyria Argante ihre Verlobung mit Ultoris bekannt.",0,0,0)
base.books.AddGermanBookText("Am 14. Juni, ruft Elvin dazu auf, Waren und Lebensmittel zu horten, da alles auf eine langanhaltende große Dürre hinweist.",0,0,0)
base.books.AddGermanBookText("Am 14. Juni, setzt Nerevar Schattenaxt ein Kopfgeld auf Werwölfe aus. Wie sich herausstellte, hatten die Betroffenen Arvon und Sunny Holz nur vergammelte Pilze gegessen.",0,0,0)
base.books.AddGermanBookText("Am 15. Juni, wird die Ogerhöhle gefunden und die gefangenen Tiere werden nach langer Zeit endlich freigelassen.",0,0,0)
base.books.AddGermanBookText("Ein gefangener Hobbit, Necrophotius Funguis und eine Ogerfrau auf Suche nach ihrem König soll in diese Sache verwickelt gewesen sein.",0,0,0)
base.books.AddGermanBookText("Am 16. Juni, wird Demli Dogan angeklagt, dem König von Silberbrand, Tialdin eine große Menge an Tränken gestohlen zu haben.",0,0,0)
base.books.AddGermanBookText("Am 16. Juni, wird die Priesterin Elaralith von mehreren Leuten beschuldigt, gestohlen zu haben.",0,0,0)
base.books.AddGermanBookText("Am 18. Juni wird Belegi Zahar in den Rat der Weisen des Clans der Axt berufen.",0,0,0)
base.books.AddGermanBookText("Am 19. Juni, taucht ein mysteriöser Gerüchteschreiber auf, der Aragon ben Galwan eine Affäre mit Lyria Argante vorwirft.",0,0,0)
base.books.AddGermanBookText("Am 22. Juni, kehrt Josefine nach langer Reise nach Troll's Bane zurück.",0,0,0)
base.books.AddGermanBookText("Am 23. Juni, verlässt Sunny Holz die Insel per Boot. Einige Unbekannte verspotten ihn per anonymen Zetteln am Brett.",0,0,0)
base.books.AddGermanBookText("Am 24. Juni, wird verkündet, das Ultoris und Lyria Argante ihre Verlobung aufheben.",0,0,0)
base.books.AddGermanBookText("Am 25. Juni, stellt ein Unbekannter unter dem Pseudonym Jello Biafra, Tialdin's Herrschaft in Frage und bezeichnet ihn als Schafhirte.",0,0,0)
base.books.AddGermanBookText("Gerüchten zufolge handelt es sich bei dem Unbekannten um den Zwerg Ingrain.",0,0,0)
base.books.AddGermanBookText("Am 26. Juni, hängt Lúthien Falassion eine Nachricht aus, da sie nach einer Frau mit Namen Malinne sucht.",0,0,0)
base.books.AddGermanBookText("Am 27. Juni, warnt Hagen von Rabenfeld die Stadt vor dem gemeingefährlichen Dieb Ferdinand Kohlberg, welcher die Bürger bei der Arbeit überfällt und ausraubt.",0,0,0)
base.books.AddGermanBookText("Am 28. Juni, gehen die Gerüchte umher, Tialdin würde mit der Menschenfrau Tifareth heimlich turteln.",0,0,0)
base.books.AddGermanBookText("Am 29. Juni, sucht Obolon nach dem besten Schnitzer Illarions.",0,0,0)
base.books.AddGermanBookText("Am 29. Juni, findet Xaveria ein geheimnisvolles Buch über einen Totenbeschwörer, der Verashnia genannt wurde.",0,0,0)
base.books.AddGermanBookText("Am 30. Juni, sucht Tenchi Mahou nach einem Magie-Lehrmeister. Morgaine Le Fay nimmt das Angebot an.",0,0,0)
base.books.AddGermanBookText("Am 30. Juni, verlässt Malinne die Insel per Boot. Nach eigenen Aussagen, wird sie nie zurückkehren.",0,0,0)
base.books.AddGermanBookText("Am 1. Juli, weist Sun Long darauf hin, das die Wüste erneut gewachsen ist und Vorsichtsmassnahmen getroffen werden müssen.",0,0,0)
base.books.AddGermanBookText("Am 2. Juli, warnt Nartak Ironmaster die Stadt vor Insekten aller Art, die in die Häuser einfallen und die Nahrungsmittel fressen.",0,0,0)
base.books.AddGermanBookText("Am 3. Juli, ereignet sich die seltene Begebenheit das der Ork Robert Schwarzfuß verkündet, dass er ein Mönch und Schüler eines Elarapriesters werden möchte.",0,0,0)
base.books.AddGermanBookText("Am 3. Juli, wurde ein Anschlag auf Fedaykins Haus verübt, ein Brandstifter legte Feuer, welches nicht nur Fedaykin, sondern auch die gesamte Stadt bedrohte.",0,0,0)
base.books.AddGermanBookText("Am 4. Juli, gibt Aragon die Verlobung mit Lyria Argante bekannt und dass er deren uneheliche Tochter Taaria adoptiert. Wieder finden sich Spötter und Neider. Manche warnen ihn eindringlich vor ihr.",0,0,0)
base.books.AddGermanBookText("Am 5. Juli, wurde ein merkwürdiger glühender Stein im Skelettwald gesichtet. Man nimmt an, er wäre ein Zeichen der Götter über ihre Verärgerung und Unmut über die Schändigung von Falkners Hain.",0,0,0)
base.books.AddGermanBookText("Am 7. Juli, gibt die Menschenfrau Charsi die wunderliche Hochzeit mit ihrem erwählten Ork Leonardo bekannt.",0,0,0)
base.books.AddGermanBookText("Am 7. Juli, ruft der Bibliothekar Sir Giandor zu einer Versammlung auf, die anscheinend in ein Verbrechen und Randalen in der Bibliothek verwickelt waren, um so die Vorgänge zu ergründen, welche während seiner Abwesenheit statt fanden.",0,0,0)
base.books.AddGermanBookText("Am 7. Juli, geht eine lange und tragische Geschichte um den Schmied Fedaykin zu Ende.",0,0,0)
base.books.AddGermanBookText("Nachdem er mehrere Male um sein Leben fürchten musste, fand das Leben dieses Menschen mit dem Namen Vandun in einem Zweikampf sein Ende.Zum Gedenken an ihn und seine Schwester wurden Gräber aufgestellt.",0,0,0)
base.books.AddGermanBookText("Am 8. Juli bemerkten Wanderer, dass sich die Untiere nicht mehr an ihren gewohnten Plätzen befanden, sie waren verschwunden und erschienen nur zu gezielten Angriffen auf die Stadt, worauf hin sie so schnell gingen wie sie kamen.",0,0,0)
base.books.AddGermanBookText("Am 8. Juli wird bekanntgegeben dass ab jetzt eine Diebesgilde mit Namen Shadow Thieves in der Stadt ihr Unwesen treibt.",0,0,0)
base.books.AddGermanBookText("Am 9. Juli, erschienen seit langer Zeit wieder einmal Dämonen und begannen unaufhörlich die Stadtbewohner zu attackieren. Schon seit Tagen leidet die Stadt Troll's Bane auch unter den Angriffen von Fliegen und anderem Ungeziefer.",0,0,0)
base.books.AddGermanBookText("Am 10. Juli, gibt Ultoris die Verlobung mit Fienchen bekannt. Man hinterlässt ihm eine Menge Glückwünsche und Belobigungen.",0,0,0)
base.books.AddGermanBookText("Am 10. Juli gibt Ferdinand Kohlberg bekannt, seinDiebeshandwerk an den Nagel hängen zu wollen und bietet an, dass Geschädigte sich bei ihm wegen Schadensersatz melden können.",0,0,0)
base.books.AddGermanBookText("Am 10. Juli, beginnen die Bürger der Stadt zu wehklagen aufgrund der nun schon länger anhaltenden Dürre. Die Hitze forderte schon mehrere Opfer und die Tiere sind aus der Stadt geflohen, weshalb die Stadt Hunger leidet.",0,0,0)
base.books.AddGermanBookText("Am 11. Juli, werden wieder einmal haltlose Ketzerrufe und Anschuldigungen über Lyrenzia bekannt.",0,0,0)
base.books.AddGermanBookText("Am 11. Juli, sucht Crosis Smallburrow dringend Hilfe für seine Frau Rosa Smallburrow, welche noch am selbigen Tage erstochen wurde. Sie überlebt aber.",0,0,0)
base.books.AddGermanBookText("Am 13. Juli, wurde ein Anschlag auf den Menschen Ultoris verübt. Er wurde mit Pfeil und Bogen von einem Unbekannten angeschossen, entkam jedoch knapp mit dem Leben. Eine Arwenia wurde dafür verklagt.",0,0,0)
base.books.AddGermanBookText("Am 16. Juli, bemerken Reisende, dass sich die früher kleinere sich im Norden der Insel gelegene Wüste unaufhörlich ausbreitet. Die Angst um das Farmland und Wasser steigen.",0,0,0)
base.books.AddGermanBookText("Am 16. Juli, ist das Kloster Eldan von Falk vom Wald fertig gestellt. Es befindet sich auf der westlichen Halbinsel. Erste Wanderer erblickten es und erkundigten sich über das Gemäuer und dessen Besitzer.",0,0,0)
base.books.AddGermanBookText("Am 16. Juli gründet Elvin Shaeron einen Nomadenclan.",0,0,0)
base.books.AddGermanBookText("Am 16. Juli werden die Bargen Masters vorübergehend aufgelöst. Ungefähr einen Monat später erfolgt die Wiedergründung der Gilde und Aufnahme von Handelsbeziehungen mit Darlok.",0,0,0)
base.books.AddGermanBookText("Am 17. Juli, beruft die Lyrenzia Foundation ein Treffen ein, damit Erfahrungen über die Dürre ausgetauscht werden können und mögliche Lösungen gefunden werden können. Dieses soll am 22 Juli statt finden.",0,0,0)
base.books.AddGermanBookText("Am 18. Juli gibt Grogor die Gründung eines weiteren Orkclans bekannt. Die erste Amtshandlung des Clanführers ist, sich als im Krieg mit den anderen menschlichen Orkclans zu erklären. Sein Clan hat nur kurze Zeit bestand.",0,0,0)
base.books.AddGermanBookText("Am 21. Juli, beginnt die öffentliche Nominierung der Kandidaten für den Posten des öffentlichen Ratsherrn der Lyrenzia Foundation. Aufgestellt werden: Drogla, Dival, Zerbus und Fieps.",0,0,0)
base.books.AddGermanBookText("Am 23. Juli, beginnt die Nominierungsphase für die beiden Kandidaten, welche die freien Händler im SMACC Rat vertreten sollen. Nominiert werden: Fedaykin, Drogla und Moathia.",0,0,0)
base.books.AddGermanBookText("Am 25. Juli, gibt der Elf Elvin die Hochzeit mit der Menschenfrau Teranie bekannt. Am 27. Juli, gibt Agon bekannt, dass fortan der Halbling Benedikt Ackermann der Landwirt des Kloster Eldan´s sein wird.",0,0,0)
base.books.AddGermanBookText("Am 28. Juli, versammeln die Bürger sich ein weiteres mal um über die Elara Priesterin Elaralith zu sprechen, diese wurde in den letzten Monaten bekannt durch anrüchige und mysteriöse Taten.",0,0,0)
base.books.AddGermanBookText("Das Vertrauen in sie war geschmolzen und man überlegte sogar ihr offiziell den Titel als Priesterin abzuerkennen.",0,0,0)
base.books.AddGermanBookText("Am 28. Juli ruft Guingalan alle Sterblichen auf, sich zusammen zu tun um die bösartigen Einflüsse, welche auf die Insel einwirken, zu bekämpfen.",0,0,0)
base.books.AddGermanBookText("Am 28. Juli führt Kincent Nolatri einen Fire Seer Clan in Troll's Bane ein, offenbar eine Tradition seines Heimatlandes.",0,0,0)
base.books.AddGermanBookText("Am 28. Juli, stellt Darlok den Bürgern Troll's Banes ein Ultimatum: Entweder wird seine Burg wieder aufgebaut oder die ganze Insel wird der Dürre zum Opfer fallen.",0,0,0)
base.books.AddGermanBookText("Einige Bürger jedoch zweifeln Darloks Fähigkeiten, über die Dürre zu herrschen, an und Dyluck ruft die Bürger zur Verweigerung auf, da sie mehr zu verlieren hätten, als nur ihr Leben.",0,0,0)
base.books.AddGermanBookText("Einige der Einwohner folgen Dylucks Aufruf, andere kommen Darloks Forderungen nach.",0,0,0)
base.books.AddGermanBookText("Am 29. Juli, beschwert sich Drathe bei Lyrenzia, warum die Vereinigung nichts gegen den bei ihr registrierten Bürger Darlok unternimmt. Andere Bürger schließen sich seiner Beschwerde an.",0,0,0)
base.books.AddGermanBookText("Einige Tage später wird Darlok aus der Bürgerliste gestrichen.",0,0,0)
base.books.AddGermanBookText("Am 29. Juli, schlägt Damien den Bewohnern der Stadt und Darlok einen Handel vor: Darlok bekommt seine Burg und muss dafür die Dinge, die er benötigt um eine Dürre und Rotwürmer zu beschwören, ausgewählten Weisen überlassen.",0,0,0)
base.books.AddGermanBookText("Aber auch andere Vorschläge werden gemacht: So soll Darlok beispielsweise getötet werden.",0,0,0)
base.books.AddGermanBookText("Am 30. Juli gibt Darlok eine Liste derjenigen bekannt, die an den Schlossruinen arbeiten. Einige fangen an zu helfen, andere versuchen den Bau zu sabotieren.",0,0,0)
base.books.AddGermanBookText("Am 30. Juli, droht Darlok all denen, welche die Bauarbeiten an der Burg stören, mit fürchterlichen Strafen. Um seinen guten Willen zu beweisen, weist er darauf hin, dass er der Erde gestattet habe, sich etwas zu erholen.",0,0,0)
base.books.AddGermanBookText("Am 30. Juli, ernennt Lyrenzia Damien zu ihrem offiziellen Vertreter in Sachen Darlok und fordert Antworten auf einige Fragen. Außerdem kündigt sie den Aufbau einer Armee an um ein Druckmittel gegen Darlok in der Hand zu haben.",0,0,0)
base.books.AddGermanBookText("Am 30. Juli, lädt Galim in Tialdins Namen alle Zwerge der Insel zu einem großen Fest in Silberbrand ein, das am kommenden Sonntag stattfinden soll.",0,0,0)
base.books.AddGermanBookText("Am 31. Juli wird der Waffenstillstand zwischen der Grauen Rose und Darlok als von Darlok gebrochen erklärt. Es kommt aber vorerst nicht zu Feindseligkeiten zwischen beiden Parteien.",0,0,0)
base.books.AddGermanBookText("Am 31. Juli wird die Cooperative Farmers Guild wiedergegründet. Sie wird jedoch bald wieder inaktiv, aufgrund der Krankheit eines ihrer Führer.",0,0,0)
base.books.AddGermanBookText("Am 31. Juli, der Zwerg Nartak Ironmaster, welcher als Verräter und Spion bekannt wurde, starb unter mysteriösen Umständen, als man ihn gerade ergreifen wollte.",0,0,0)
base.books.AddGermanBookText("Am 1. August, fordert Dyluck alle Bürger auf, sich bei ihm, Crosis oder Korwin zu melden und der Armee für den Kampf gegen Darlok beizutreten. Viele schreiben sich in die aushängenden Listen ein.",0,0,0)
base.books.AddGermanBookText("Am 2. August erscheint die erste Ausgabe der von Elvin herausgegeben Troll's Bane Zeitung, einen Tag später wird die zweite Ausgabe veröffentlicht.",0,0,0)
base.books.AddGermanBookText("Am 4. August veröffentlicht der Clan der Axt eine Liste von ausgestoßenen Bürgern, die in Silberbrand nicht länger willkommen sind. Diese Liste wird stetig verlängert.",0,0,0)
base.books.AddGermanBookText("Am 5. August wird von Athian die Gründung des Order of the Seeker bekannt gegeben. Es ist ein Orden der Cherga verehrt und der seiner Göttin zu ihrer früheren Glorie verhelfen will.",0,0,0)
base.books.AddGermanBookText("Am 7. August, greift Elaralith Silberbrand an und attackiert dabei zwei Zwerge und den Irmorom geweihten Altar. Dafür wird sie ins Gefängnis geworfen.",0,0,0)
base.books.AddGermanBookText("Am 9. August, erscheint eine weitere und letzte Ausgabe der Zeitung.",0,0,0)
base.books.AddGermanBookText("Am 9. August, wird die Ogerhöhle vom Bloodskull Clan zur Stammeshöhle erklärt, unbefugtes Betreten wird mit dem Tode bestraft.",0,0,0)
base.books.AddGermanBookText("Am 9. August, schließen die Zwerge Silberbrands und der Blood Skull Clan einen Freundschaftsvertrag: Zwerge und Orks dürfen die Räume der anderen betreten, Angriffe aufeinander sind untersagt.",0,0,0)
base.books.AddGermanBookText("Am 9. August, verkündet Grant Herion in Darloks Namen, dass jeder, der in Darloks Territorium aufgegriffen wird, 200 Goldstücke Strafe bezahlen muss.",0,0,0)
base.books.AddGermanBookText("Außerdem ist es bei Todesstrafe verboten, die Ogerwächter anzugreifen oder zu töten.",0,0,0)
base.books.AddGermanBookText("Am 10. August gibt der Orden des Grauen Lichts den Umzug seiner öffentlichen Vertretung sowie die Beförderung einiger seiner Mitglieder bekannt.",0,0,0)
base.books.AddGermanBookText("Gleichzeitig wird Elaralith aufgrund wiederholter Missachtung des Kodex aus dem Orden verwiesen.",0,0,0)
base.books.AddGermanBookText("Am 11. August veröffentlicht Lyrenzia Foundation die Voraussetzungen, die eine Gilde oder Gruppierung erfüllen muss um registriert werden zu können.",0,0,0)
base.books.AddGermanBookText("Am 11. August, ruft Grant Herion Die Bewegung zum Kampf gegen Elaralith und deren Freunde auf.",0,0,0)
base.books.AddGermanBookText("Am 11. August, greift Elaralith die Bloodskullhöhle, Bürger der Stadt und Silberbrand mit der Begründung an, dass Silberbrand und die Bloodskulls böse seien und daher bekämpft werden müssten.",0,0,0)
base.books.AddGermanBookText("Am 12. August gründet Grant Herion The Movement, eine Vereinigung von Kriegern die auf eigene Faust dass zu bekämpfen trachten, was sie als Böse ansehen.",0,0,0)
base.books.AddGermanBookText("Da der Gründer als Anhänger Darloks bekannt ist, sind die Ziele dieser Gruppierung mehr als fragwürdig.",0,0,0)
base.books.AddGermanBookText("Am 13. August, erklärt die Graue Rose Darlok und seinen Anhängern den Krieg aufgrund Grabschändung und eines Angriffs auf einen Ritter.",0,0,0)
base.books.AddGermanBookText("Später stellt sich heraus, dass der Angriff nicht von Darlok selbst ausging, sondern von einem Darloks Land bewachenden Ork des Bloodskullclans namens Pok'Ash.",0,0,0)
base.books.AddGermanBookText("Am 13. August verkündet Elvymir die Wiedereröffnung Eldamars unter seiner Führung.",0,0,0)
base.books.AddGermanBookText("Da er so gut wie unbekannt ist trifft er damit auf großen Widerstand von base.books.AddGermanBookTextn der anderen Elfen. Da er sich zuletzt als ungeeignet entpuppt geht die Kontrolle über die Elven Community vorübergehend an Moathia Nethiala.",0,0,0)
base.books.AddGermanBookText("Am 13. August, entschuldigen sich Wiergraf und Pok'Ash bei der Grauen Rose und möchten mit deren Anführern reden. Die Gespräche Aragons mit Pok'Ash scheitern an dessen Unvernunft.",0,0,0)
base.books.AddGermanBookText("Am 13. August, sucht Gorr Tarak mutige Mitbürger/innen, die mit ihm zusammen aufbrechen und der Dürre ein Ende machen wollen.",0,0,0)
base.books.AddGermanBookText("Verschiedene Vorschläge werden gemacht, mehrere Bücher zitiert. Für die Mission melden sich schließlich Sunny Holz, Xaveria, Magor, Ultoris und Denon.",0,0,0)
base.books.AddGermanBookText("Am 14. August, werden aufgrund der Dürre sowohl die Ratsherrenwahl als auch die Wahl des SMACC Rates verschoben.",0,0,0)
base.books.AddGermanBookText("Am 14. August, macht die Graue Rose Darlok ein Friedensangebot, im Gegenzug soll Darlok die Dürre beenden. Darlok lehnt ab.",0,0,0)
base.books.AddGermanBookText("Am 14. August wird die renovierte Burg der Lyrenzia Foundation der Öffentlichkeit zugänglich gemacht.",0,0,0)
base.books.AddGermanBookText("Am 15. und 17. August verkündet Tialdin, dass Salathe und Croktin Skullcrusher nun ebenfalls der Tavernencrew angehören.",0,0,0)
base.books.AddGermanBookText("Am 16. August wird die Rückkehr von Lúthien Falassion und Alice bekannt.",0,0,0)
base.books.AddGermanBookText("Am 16. August beginnt die Wahl zum öffentlichen Ratsherrn von Lyrenzia. Fieps gewinnt diese Wahl mit 9 Stimmen. Zerbus bekam 4 und Drogla 1.",0,0,0)
base.books.AddGermanBookText("Am 16. August beginnt die Wahl für den SMACC-Rat. Moathia Nethiale, mit 5 Stimmen, und Fedaykin, mit 12 Stimmen, wurden gewählt.Drogla bekam 2 Stimmen.",0,0,0)
base.books.AddGermanBookText("Am 17. August, handeln die Graue Rose und der Bloodskull Clan einen Friedensvertrag aus, der von Veralion, dem Führer der Orks, jedoch nie ratifiziert wird. Die Bemühungen verlaufen somit im Sande.",0,0,0)
base.books.AddGermanBookText("Am 17. August, meldet der Ork Kzarak Zhoruch ganz entsetzt, dass alle Fische tot seien. Am 18. August, verkündet Sean Elaski alias The Returner seine Heimkehr offiziell.",0,0,0)
base.books.AddGermanBookText("Er, der sich in den Jahren der Abwesenheit gewandelt habe, sei gekommen, um den Bewohnern Troll's Banes während der furchtbaren Dürre Hilfe anzubieten.",0,0,0)
base.books.AddGermanBookText("Am 18. August stürzt ein glühender Felsen vom Himmel und viele fragen sich, ob dies eine Bedrohung darstellt, während andere denken, der Entdecker des Phänomens sei nicht zurechnungsfähig und man dürfe seinen Bericht nicht ernst nehmen.",0,0,0)
base.books.AddGermanBookText("Am 20. August laden Belegi und Draakon zu dem zweiten Tanzwettbewerb ein. Er findet planmäßig am 31. August statt. Am 20. August, beschwert sich Sean Elaski bei Veralion, dass dessen Orks ihn selbst und andere grundlos angegriffen hätten.",0,0,0)
base.books.AddGermanBookText("Er fordert den Führer der Bloodskulls auf, gegen diese Vergehen vorzugehen und Veralion verspricht ihm dies. Am 22. August warnt Alnerith Dencort vor Monstern in der Stadt. Viele berichten von ihren Erlebnissen mit Monstern.",0,0,0)
base.books.AddGermanBookText("Im Jahre 3 des neuen Zeitalters im Laufe des Monats August verfassen viele Autoren Schriften gegen Lyrenzia und weisen auf angebliche Fehler der Organisation hin, die sie persönlich meinen gefunden zu haben.",0,0,0)
base.books.AddGermanBookText("Andere wiederum rufen zum Krieg gegen Darlok auf, diese beiden Themen werden lange Zeit heftig diskutiert.",0,0,0)
base.books.AddGermanBookText("Am 26. August hängte eine unbekannte Person einen Zettel auf und fragte die Bürger von Troll's Bane ob sie Darlok wirklich als Herrscher wollen.",0,0,0)
base.books.AddGermanBookText("Ein Streit zwischen Grant Herion und der unbekannten Person brach aus. Am 26. August fragt Yataghan an, wo das Troll's Bane ist, welches er kannte. Es kann ihm keine genaue Antwort gegeben werden.",0,0,0)
base.books.AddGermanBookText("Am 26. August hängt Salathe einen leicht verbrannte Pergament auf und begibt sich somit auf eine Reise. Am 27. August fängt ein erneutes Gerichtsverfahren gegen Elaralith an, eine lange Diskussion über ihre Person bricht aus.",0,0,0)
base.books.AddGermanBookText("Elaralith wird in diesem Fall als nicht schuldig befunden. Am 28. August sucht Gnarr nach einer Echsenfrau, auch Saurin Talon ist nicht abgeneigt eine zu finden.",0,0,0)
base.books.AddGermanBookText("Am 29. August wird von Lyrenzia eine Liste ausgehängt die zeigt wer, wie lange im Gefängnis war, beginnend mit dem Verfahren #22.",0,0,0)
base.books.AddGermanBookText("Am 3. September werden einige Änderungen im Strafmass für von Lyrenzia verurteilte Straftäter bekannt gegeben. Am 4. September verfasst Algoran einen Brief in dem er Damien bittet mit Darlok zu reden.",0,0,0)
base.books.AddGermanBookText("Eine Diskussion bricht aus und wird von Aragon beendet. Am 4. September verabschiedet sie der Lizard Salathe von all seinen Freunden, da er Troll's Bane verlassen wird.",0,0,0)
base.books.AddGermanBookText("Am 5. September gibt Ikaron bekannt das er in das Gemäuer nordöstlich der Mumien eingezogen ist, auch wenn es nicht sein eigen ist.",0,0,0)
base.books.AddGermanBookText("Am 6. September verkündet Kincent Nolatri, vormals bekannt unter dem Namen Kincent Rashful, das er wiedergeboren wurde. Am 6. September sucht Gnarr nach Gelehrten die ihm mehr über die Göttin Zelphia sagen können.",0,0,0)
base.books.AddGermanBookText("Am 7. September startet Dyluck eine Umfrage um die Frage zu klären ob die Gerichtsverfahren lang genug sind. Die meisten sagen das 5 Tage nach wie vor in Ordnung sind.",0,0,0)
base.books.AddGermanBookText("Am 8. September entschuldigt Elaralith sich für ihre Taten und macht den Vorschlag eines gemeinsamen Gebets aller um die Dürre zu beenden und die Schändung von Falkners Schrein zu sühnen.",0,0,0)
base.books.AddGermanBookText("Es findet am 13. September statt und brachte Erfolg trotz vieler Diskussionen. Es finden sich Sämlinge, die um den Schrein eingepflanzt werden.",0,0,0)
base.books.AddGermanBookText("Am 8. September verabschiedet sich der Hobbit Fastolph. Er wird auf eine Reise gehen und die Ergebnisse dieser an Troll's Bane weitergeben nach seiner Rückkehr.",0,0,0)
base.books.AddGermanBookText("Am 9. September sucht Paul Laffing nach mutigen Minenarbeitern die ihm helfen nach Gold zu suchen. Am 10. September fragt Algoran an, ob Damien schon mit Darlok gesprochen hat.",0,0,0)
base.books.AddGermanBookText("Dyluck gibt bekannt das der Macht-Gegenstand im Besitz der Magic Academy ist. Am 14. September fragt Gnarr nach alten Büchern damit er daraus lernen kann.",0,0,0)
base.books.AddGermanBookText("Am 14. September macht Kincent Nolatri einen Vorschlag wie man die Dürre beenden kann. Durch das Kombinieren von Energie und Mana.",0,0,0)
base.books.AddGermanBookText("Am 14. September denkt Kasume öffentlich über einen Selbstmord nach, doch wird von Kincent Nolatri und Aristeaus abgehalten.",0,0,0)
base.books.AddGermanBookText("Am 15. September hängt Drathe ein Pergament auf im Auftrage Josefine von Irnarons um bekannt zugeben das sie die Spinnenkönigin ist.",0,0,0)
base.books.AddGermanBookText("Später wird bekannt das es nicht so ist, nachdem Ungoliath selber auftauchte. Am 16. September warnt Churion vor Erpressern die Geld haben wollen oder einen töten oder verletzen.",0,0,0)
base.books.AddGermanBookText("Am 21. September kündigt Zahra Fiarai die Wiedergeburt des Amazonenstammes an. Am 22. September werden die Bargen Masters erneut offiziell für aufgelöst erklärt.",0,0,0)
                --Ende Deutsche Bucheinträge

                --Englische Bucheinträge hinzu fügen
base.books.AddEnglishBookText("On January, the 1st small groups of orcs attack Troll's Bane.",0,0,0)
base.books.AddEnglishBookText("People suspect a bigger attack of orcs.",0,0,0)
base.books.AddEnglishBookText("On January, the 5th Nilo founds the guild Intermediate Wizards Guild a guild and a school for wizards.",0,0,0)
base.books.AddEnglishBookText("On January, the 7th Paul Laffing founds the Foundation for the Protection of Merchants a group to protect merchants for thieves and other crimes.",0,0,0)
base.books.AddEnglishBookText("On January, the 8th the Festival of Life is celebrated.",0,0,0)
base.books.AddEnglishBookText("On January, the 3rd asks Crosis if there is a wish for a Hobbit guild.",0,0,0)
base.books.AddEnglishBookText("The guild Hobbiteers is found.",0,0,0)
base.books.AddEnglishBookText("On January, the 6th ask Fooser (FooserJohn) if there is interest in a Farmer and Baker guild.",0,0,0)
base.books.AddEnglishBookText("The poll is positive and the Cooperative Farmers Guild - CFG is found.",0,0,0)
base.books.AddEnglishBookText("On January, the 6th Monsoon Raingstorm founds the The guild of wisdom and peace but it seems to have no existence.",0,0,0)
base.books.AddEnglishBookText("On January, the 8th starts the poll to the King of Silverbrand. Tialdin wins it unanimous.",0,0,0)
base.books.AddEnglishBookText("On January, the 10th the guild Hobbiteers is now officially found.",0,0,0)
base.books.AddEnglishBookText("On January, the 10th starts a poll to name the stream between library and Tavern, one vote for Troll's vein",0,0,0)
base.books.AddEnglishBookText("On January, the 13th Salathe founds the lizard guild Zelphia's Dragoons and looks for members.",0,0,0)
base.books.AddEnglishBookText("It seems to have no existence.",0,0,0)
base.books.AddEnglishBookText("On January, the 13th starts a poll to name the stream in the north.",0,0,0)
base.books.AddEnglishBookText("After a time one come to the agreement.",0,0,0)
base.books.AddEnglishBookText("The name is now Fairy's Tears.",0,0,0)
base.books.AddEnglishBookText("On January, the 16th the Elven Community becomes a new name.",0,0,0)
base.books.AddEnglishBookText("The new one is Eldamar which means Home of the Elves.",0,0,0)
base.books.AddEnglishBookText("On January, the 17th is a big archers auction.",0,0,0)
base.books.AddEnglishBookText("People ask for a Auction house and it is the beginning of many auctions.",0,0,0)
base.books.AddEnglishBookText("On January, the 17th Tialdin asks Irmorom in a prayer to strengthen and preserve the Dwarven city.",0,0,0)
base.books.AddEnglishBookText("On January, the 18th the Elf Freaper proposes a fashion show and starts to plan it.",0,0,0)
base.books.AddEnglishBookText("But many people don't agree with it.",0,0,0)
base.books.AddEnglishBookText("On January, the 19th Dyluck destroys the sword in the mana fountain because he is afraid of its abuse.",0,0,0)
base.books.AddEnglishBookText("On January, the 19th one can hear rumours about the dwarf Josef who tries to smith a fire axe for the hands of dwarves.",0,0,0)
base.books.AddEnglishBookText("The clan of axe looks for the best smith in town who can smith such an axe.",0,0,0)
base.books.AddEnglishBookText("On January, the 20th a shadowy person starts to walk around town.",0,0,0)
base.books.AddEnglishBookText("Some people die until the person leaves.",0,0,0)
base.books.AddEnglishBookText("A creature of light and some citizen support the city.",0,0,0)
base.books.AddEnglishBookText("On January, the 22nd the idea of the first Inn in Troll's Bane starts to come up and the building on the west coast became had a new future.",0,0,0)
base.books.AddEnglishBookText("On January, the 24th Turin Ironhammer proposes a trade to the guild leaders.",0,0,0)
base.books.AddEnglishBookText("On January, the 24th Dyluck invites the grey Rose and the grey Light for dinner to revive an old tradition.",0,0,0)
base.books.AddEnglishBookText("On January, the 27th Fieps establishes the new Inn in his house.",0,0,0)
base.books.AddEnglishBookText("The grey Rose is allowed to use it. It's called: The Seahorse.",0,0,0)
base.books.AddEnglishBookText("On January, the 27th Paul Laffing establishes a new shop for tailor goods.",0,0,0)
base.books.AddEnglishBookText("On January, the 28th the inauguration of the temple of Imromom takes place in Silverbrand through priest Rugosch.",0,0,0)
base.books.AddEnglishBookText("On January, the 30th Tialdin is now the official king of Silverbrand.",0,0,0)
base.books.AddEnglishBookText("On January, the 30th asks Tialdin which rooms are still needed in Silverbrand.",0,0,0)
base.books.AddEnglishBookText("On January, the 31st appoints Tialdin that Rugosch is the council in questions of faith, Bombor becomes Herold and the clan of axe the guard of Silverbrand.",0,0,0)
base.books.AddEnglishBookText("On January, the 12th the elf Elkrim and Dominikus Alleradis start their expedition into the desert.",0,0,0)
base.books.AddEnglishBookText("Members of the clan of axe attack Elkrim because they think he's obsessed by a demon.",0,0,0)
base.books.AddEnglishBookText("Elkrim criticizes the clan of axe.",0,0,0)
base.books.AddEnglishBookText("On January, the 12th someone with the name Callith founds a group named The warrior priests of Malachin he also calles himself a high priets of Malachin, but he's not known in our town.",0,0,0)
base.books.AddEnglishBookText("On January, the 15th Dominikus posts an official note that comprimises the clan of axe.",0,0,0)
base.books.AddEnglishBookText("A few days later it's official that the comprimise was untrue and Dominikus leaves the island.",0,0,0)
base.books.AddEnglishBookText("On January, the 18th Asteron establishes The Artemis Alliance Guild a group of druids, mages and bards.",0,0,0)
base.books.AddEnglishBookText("Officially announced goals are to discuss the magic and to find new information about it.",0,0,0)
base.books.AddEnglishBookText("On January, the 20th is the hearing of the elf Elkrim and the dwarves.",0,0,0)
base.books.AddEnglishBookText("During the meeting it comes to light that Elkrim is obsessed by a demon and it's controling his body and his mind.",0,0,0)
base.books.AddEnglishBookText("The demon is causing the fights between the elves and the dwarves.",0,0,0)
base.books.AddEnglishBookText("The priest is healing Elkrims body.",0,0,0)
base.books.AddEnglishBookText("Another man who's obsessed by a shadow creature gets healed.",0,0,0)
base.books.AddEnglishBookText("King Tialdin that none of this happened.",0,0,0)
base.books.AddEnglishBookText("On January, the 22nd the lizard Xerake founds the School of Ninjutsu it's a school that teaches warriors a certain type of martial art.",0,0,0)
base.books.AddEnglishBookText("On January, the 28th the dwarf Dunthor founds the Druids of Troll's Bane they show certain similarities with the Druid of the forest and become their concurrence.",0,0,0)
base.books.AddEnglishBookText("One tries to combine these to guilds but it does not work, because of the cheap prices of the Druids of Troll's Bane.",0,0,0)
base.books.AddEnglishBookText("It's possible that the guild is gone because Dunthor is guilty of some crimes like murder and theft.",0,0,0)
base.books.AddEnglishBookText("On January, the 28th after The Artemis Alliance Guild failed, the elf Asteron founds a new guild with the name The Magic Alliance an union of mages.",0,0,0)
base.books.AddEnglishBookText("They obey the law and defeating, healing and protect the people.",0,0,0)
base.books.AddEnglishBookText("In the 3rd year of the new century in the days of March citizen called at a regime, which would fight against the crime in Troll's Bane.",0,0,0)
base.books.AddEnglishBookText("Long discussions started.",0,0,0)
base.books.AddEnglishBookText("On March 3rd Bado the hobbit was accused of his bad things and got a punishment.",0,0,0)
base.books.AddEnglishBookText("On March 8th the human Farmar starts the guild The keepers of the peace, which is supposed to fight againts the crimes.",0,0,0)
base.books.AddEnglishBookText("On March 10th an anonymous founds a guild for thives.",0,0,0)
base.books.AddEnglishBookText("But they couldn't introdeuce their members and disappeart.",0,0,0)
base.books.AddEnglishBookText("It is not sure if they still work in the background.",0,0,0)
base.books.AddEnglishBookText("On March 17th Bloodheart founds the Cult of the Blackstone.",0,0,0)
base.books.AddEnglishBookText("A Guild for follower of Moshran who follow the dark path and propagate chaos, war and sorrow.",0,0,0)
base.books.AddEnglishBookText("On March 18th masses of orks attack the city but the citizen succeed and the city is save again.",0,0,0)
base.books.AddEnglishBookText("On March 18th Malinne gets a unknown sickness.",0,0,0)
base.books.AddEnglishBookText("On March 19th Bloodhaert becomes the most wanted person.",0,0,0)
base.books.AddEnglishBookText("On March 23rd an anonymous founds the Cult of the Diamond and is supposed to be a opposite of the Cult of the Blackstone.",0,0,0)
base.books.AddEnglishBookText("The main idea came from the dwarf Randelf.",0,0,0)
base.books.AddEnglishBookText("He is not important.",0,0,0)
base.books.AddEnglishBookText("On March 24th Randelf founds The Goldsmithing guild and looks for new members, but it is only for people with good goldsmithing skills.",0,0,0)
base.books.AddEnglishBookText("On March 24th Bloodhearte loses a fight against a group of Lizards.",0,0,0)
base.books.AddEnglishBookText("On March 24th Bloodheart publishes the book The Definition of Evil.",0,0,0)
base.books.AddEnglishBookText("The book shows ways to awake Moshran in Illarion.",0,0,0)
base.books.AddEnglishBookText("Many people protest.",0,0,0)
base.books.AddEnglishBookText("On March 27th Cain Freemont begins his search for medicine for Malinne.",0,0,0)
base.books.AddEnglishBookText("On March 31st an anonymous publishes a mockery song about the dwarves of the clan of the ax.",0,0,0)
base.books.AddEnglishBookText("On April 2nd Servious Helios, Cain Freemont, Fortinbris Bloodhearte, Boremier and Ezorock begin their journey to the north mainland.",0,0,0)
base.books.AddEnglishBookText("On April 9th Elaralith gets criticize for her behavior and called unwothy to be a priest of Elara.",0,0,0)
base.books.AddEnglishBookText("She gets a reprimand from the elders of Eladamar.",0,0,0)
base.books.AddEnglishBookText("On April 11th the Lyrenzia Foundation is presented to the public.",0,0,0)
base.books.AddEnglishBookText("Since 5 month the followings guilds planed it: Grey Rose, Grey Light, Magic Academy, Rangers, and Silverbrand.",0,0,0)
base.books.AddEnglishBookText("The goal of this foundation is to bring peace and fairness to Illarion and to work together for the well doing of the city.",0,0,0)
base.books.AddEnglishBookText("The head of the foundation is a council of the different guilds.",0,0,0)
base.books.AddEnglishBookText("Other guildes are welcome to join.",0,0,0)
base.books.AddEnglishBookText("On April 11th the Silver Start Merchants join the Lyrenzia Foundation.",0,0,0)
base.books.AddEnglishBookText("On April 14th Darlok, a leader of a group declares war to five hobbits under the leadership of Crosis.",0,0,0)
base.books.AddEnglishBookText("There had been a conflict between the killer Xerake and these hobbits where Darlok helped Xerake.",0,0,0)
base.books.AddEnglishBookText("It is not sure but some people think that Darlok provoked this war.",0,0,0)
base.books.AddEnglishBookText("People got killed on both sites.",0,0,0)
base.books.AddEnglishBookText("On April 15th Drathe founds the group Archers of Illar, which, like the name says, is a group of archers in Illarion.",0,0,0)
base.books.AddEnglishBookText("On April 16th the Druiden des Waldes get two new members and live a recovery.",0,0,0)
base.books.AddEnglishBookText("On April 19th the Druiden des Waldes join the Lyrenzia Foundation.",0,0,0)
base.books.AddEnglishBookText("On April 19th Xerake decides to end to be a killer.",0,0,0)
base.books.AddEnglishBookText("On April 19th Aragon proposes peace between Darlok and the group of hobbits.",0,0,0)
base.books.AddEnglishBookText("The proposel gets put down.",0,0,0)
base.books.AddEnglishBookText("On April 19th comes peace to Darlok and Crosis, after the hobbits paid money to Darlok.",0,0,0)
base.books.AddEnglishBookText("On April 20th the Hobbiteers join the Lyrenzia Foundation.",0,0,0)
base.books.AddEnglishBookText("On April 20th the Lyrenzia Foundation publishes a possession book of the buildings in Troll's Bane.",0,0,0)
base.books.AddEnglishBookText("On April 22nd Galadria gives known that the Followers of Sirani found to new members: Loki Feuerhaar and Inioch Hope.",0,0,0)
base.books.AddEnglishBookText("On April 23rd Redric founds the Golden Tree Merchants.",0,0,0)
base.books.AddEnglishBookText("The main things is to get low prices for wood.",0,0,0)
base.books.AddEnglishBookText("Like the name says it is also the only product they sell.",0,0,0)
base.books.AddEnglishBookText("On April 24th Nilo founds The New Illarion School of Magic together with Grant Herion.",0,0,0)
base.books.AddEnglishBookText("Official teachers at April 28th are Drogla, Lenti, Deats and Nilo.",0,0,0)
base.books.AddEnglishBookText("On April 26th Deats (Hades) starts a poll about the Bargen Masters the reason is that they should get more attention to become more members.",0,0,0)
base.books.AddEnglishBookText("On April 29th the Lyrenzia Foundation addresses a vote system for registered citizens.",0,0,0)
base.books.AddEnglishBookText("Registered citizens are people who live in Illarion for four months.",0,0,0)
base.books.AddEnglishBookText("They can vote for representatives of the Lyrenzia council.",0,0,0)
base.books.AddEnglishBookText("On April 29th the Lyrenzia Foundation addresses the founding of the SMACC-council.",0,0,0)
base.books.AddEnglishBookText("It has five members: Fieps, Mishrak, Lenier, Niniane and a fifth merchant who gets voted.",0,0,0)

          end
      end
      base.books.SendBookPage(User,SourceItem.data,Counter);
      User:learn(4,"library research",2,100)
  end
 
  function LookAtItem(User,Item)
      if base.books.InitTitle() then
         base.books.AddGermanBookTitle("Buch mit dem Titel \"Die Chroniken Illarions III\"",0);
         base.books.AddEnglishBookTitle("Book with the title \"The Illarion Chronicles III\"",0);
      end
      base.books.GetBookItemInform(User,Item);
  end