-- I_2606_book_chronicle_1.lua
-- by Falk
require("base.books")
 
function UseItem(User, SourceItem, TargetItem, Counter, Param)
   if ( TargetItem.id == 266 ) or ( TargetItem.id == 267 ) then
      world:erase(SourceItem,1);
   else
      if base.books.InitBook() then
         base.books.AddLanguage("common language",0);

base.books.AddGermanBookText("Am 20. Februar wurde eine neue Anschlagtafel im Laden von Troll's Bane feierlich eingeweiht.",0,0,0)
base.books.AddGermanBookText("Am 22. Februar wurde der Orden des Grauen Lichtes von Damien gegründet. Die Ziele sind Neutralität, Sicherheit auf den Straßen, Wissen anzusammeln und eine Bibliothek zu bauen.",0,0,0)
base.books.AddGermanBookText("Am 27. und 28. Februar befällt eine unbekannte Seuche die Schafe und lässt sie zu Killerschafen werden.",0,0,0)
base.books.AddGermanBookText("Die Taverne .nicht die heutige, ein Bretterverschlag im Norden der Stadt, welcher von Ghost Walker und Aries erbaut wurde und späterwieder einstürzte) wird von ihnen angegriffen. Ein Kind wird vermisst.",0,0,0)
base.books.AddGermanBookText("Fluffy erscheint resistent gegen diese Seuche und wird zur Bewachung der Taverne von Ghost Walker gehalten.",0,0,0)
base.books.AddGermanBookText("Am 28. Februar erfinden Aries und Damien das Fish Pong-Spiel.",0,0,0)
base.books.AddGermanBookText("Am 11. März entdeckte Galdriel im Nordwesten der Insel mitten im dichtesten Wald einen sich windenden Hohlweg. Bei einer weiteren Expedition fanden Galdriel und Bror Ruinen.",0,0,0)
base.books.AddGermanBookText("Eine Legende erzählt, dass dort ein Magier auf der Suche nach Macht in einem Tempel verbotene Schriftrollen der älteren Götter berührte, die ein Erdbeben auslösten, den Magier, den Wald und den Tempel vernichteten.",0,0,0)
base.books.AddGermanBookText("Am 11. März wird von Silver die Gilde Bruderschaft des Lichtes gegründet. Sie nennt sich die 3. Gilde auf der Insel. Ihre Ziele sind Neuankömmlinge unterstützen, die Straßen befrieden und Handel treiben.",0,0,0)
base.books.AddGermanBookText("Am 12. März wurde die Dämonenhöhle im Nordosten erstmalig erforscht und der Rote Baron gefunden.",0,0,0)
base.books.AddGermanBookText("Am 12. März gründet Master Gohan den Order of Demonic Light.",0,0,0)
base.books.AddGermanBookText("Am 21. März findet Master Gohan eine alte kaum leserliche Schriftrolle, die den Untergang Illarions prophezeit. Laut Damien sind aber auch viele falsche Rollen bekannt.",0,0,0)
base.books.AddGermanBookText("Zur gleichen Zeit werden drei Transistorfelder entdeckt, die Hitze ausstrahlen.",0,0,0)
base.books.AddGermanBookText("Sie scheinen Portale für Feuergeister zu sein, deren Stimmen von verschiedenen Personen gehört werden. Eine Tanorastatue wird gestohlen und umgeben von weiteren Portalen gefunden.",0,0,0)
base.books.AddGermanBookText("Durch verschiedene Rituale gelang es, dass Gleichgewicht zwischen Wasser und Feuer wieder herzustellen. Die Portale verschwanden wieder.",0,0,0)
base.books.AddGermanBookText("Am 27 März gelang es Bror, Neon Rift und Olorin entgültig, die gestohlene Tanorastatue zu befreien.",0,0,0)
base.books.AddGermanBookText("Sie bekam am östlichen Lagunensee einen neuen Platz und dient seither als Heiligtum für Tanora.",0,0,0)
base.books.AddGermanBookText("Neonfire und Olorin wurden mit seltenen Früchten belohnt.",0,0,0)
base.books.AddGermanBookText("Am 27. März wird erstmalig eine Warnung vor dem Massenmörder Darkwalker ausgesprochen. Er versuchte auch, den Orden des Grauen Lichtes und den Order of Demonic Light gegeneinander aufzuhetzen.",0,0,0)
base.books.AddGermanBookText("Im Grauen Licht laufen Anfang April Diskussionen, eine Polizeitruppe aufzustellen. Am 10. April wird Darkwalker hingerichtet.",0,0,0)
base.books.AddGermanBookText("Am 31. März hat Neon Rift eine Vision, in der er die zukünftige Bibliothek sieht. Aufgrund der Vision zeichnet er die Pläne und das Graue Licht beginnt mit den Baumaßnahmen.",0,0,0)
base.books.AddGermanBookText("Im Jahre 1 des neuen Zeitalters, Anfang April wird die Graue Rose als ein Teil des Grauen Lichtes gegründet.",0,0,0)
base.books.AddGermanBookText("Sie ist ein Ritterzirkel und die Kampftruppe des Grauen Lichtes gegen Gewaltverbrecher auf den Straßen Troll's Banes.",0,0,0)
base.books.AddGermanBookText("Ihr erster Anführer wird Sturm Feuerklinge.",0,0,0)
base.books.AddGermanBookText("Gründungsmitglieder sind des weiteren Sirius Fellfuß und Sir Antarion.",0,0,0)
base.books.AddGermanBookText("Damit entstand sie als eine Antwort auf die Bedrohung durch Darkwalker.",0,0,0)
base.books.AddGermanBookText("Am 10. April wird die vom Grauen Licht gebaute Bibliothek und die Fluffy Sheep Bar .die heutige Taverne) eröffnet.",0,0,0)
base.books.AddGermanBookText("Am 10. April findet sich die erste Erwähnung von Erdricks Laden im Nebensatz einer Schriftrolle.",0,0,0)
base.books.AddGermanBookText("Am 13. April wird von Sir Drakan und Cody die Gilde The Titans gegründet.",0,0,0)
base.books.AddGermanBookText("Am 19. April wird erstmalig von Kyuushiki ein Sänger- und Dichterwettstreit veranstaltet.",0,0,0)
base.books.AddGermanBookText("Am 23. April erklärt Kyuushiki die Ziele der Gilde The Tavern oder Tavernkeeper später genannt.",0,0,0)
base.books.AddGermanBookText("Damit treten sie erstmals ins Licht der Öffentlichkeit.",0,0,0)
base.books.AddGermanBookText("Ihr Ziel ist es, eine Taverne zu versorgen und zu führen.",0,0,0)
base.books.AddGermanBookText("Am 24 April, schloss die Graue Rose eine Allianz mit der Gilde The Titans.",0,0,0)
base.books.AddGermanBookText("Am 24 April, wird von Onyx die Gilde The Dark Mages erstmals erwähnt. Ihr Anführer ist Sir Crystal Star. In dieser Zeit fällt auch eine Auseinandersetzung zwischen den Dark Mages und den Tavernkeepern um die Vorherrschaft in der Taverne.",0,0,0)
base.books.AddGermanBookText("Durch ihre Niederlage ziehen sich die Dark Mages aus der Stadt zurück und schwören ihrer Terrorherrschaft ab.",0,0,0)
base.books.AddGermanBookText("Am 24. April gründet der Ork Boga Woga die Gilde Bloodtooth Tribe. Letzte Hinweise auf diesen Stamm finden sich Mitte Mai.",0,0,0)
base.books.AddGermanBookText("Am 26. April wird von Raziel die Gilde The Shadowen Empire gegründet. Ihr Ziel ist die Vorherrschaft in Illarion.",0,0,0)
base.books.AddGermanBookText("Am 26. April einigen sich die Tavernkeepers und das Graue Licht darauf, Fluffy Sheep Bar gemeinsam zu führen.",0,0,0)
base.books.AddGermanBookText("Am 9. Mai heiratet Kjallha und Tinari in Troll's Bane.",0,0,0)
base.books.AddGermanBookText("Es ist die erste urkundlich erwähnte Hochzeit.",0,0,0)
base.books.AddGermanBookText("Im Jahre 1 des neuen Zeitalters, Anfang Mai wurden die Ruinen nördlich der Stadt ausgegraben.",0,0,0)
base.books.AddGermanBookText("Doch sehr bald stellte es sich heraus, dass es ein verwunschener Ort ist, an dem nun die Geister früherer Verstorbener als Untote zum Leben erweckt wurden.",0,0,0)
base.books.AddGermanBookText("Am 18. Mai, fragte Damien vom Grauen Licht beim Shadow Empire an, ob gegenseitige Hilfe möglich wäre, da die Ziele ähnlich sind. Es kommt zu keiner offiziellen Vereinbarung.",0,0,0)
base.books.AddGermanBookText("Im Jahre 1 des neuen Zeitalters, in den Monaten Mai und Juni zerfällt die Graue Rose langsam durch häufige Abwesenheit ihres Anführers.",0,0,0)
base.books.AddGermanBookText("Kurz nach Aragons Beitritt verschwand Sturm Feuerklinge ein letztes Mal mit der Kasse des Zirkels und wart für Monate nicht mehr gesehen.",0,0,0)
base.books.AddGermanBookText("Zu diesem Zeitpunkt waren im Zirkel Sirius Fellfuß, Echnaton und Aragon aktiv.",0,0,0)
base.books.AddGermanBookText("Im Jahre 1 des neuen Zeitalters, Anfang August, wird der Kodex der Grauen Rose als Grundlage des Zirkels in der jetzigen Form beschlossen.",0,0,0)
base.books.AddGermanBookText("Der Orden des Grauen Lichtes übernimmt diese überarbeitete Form ihres früheren Kodex vom Zirkel.",0,0,0)
base.books.AddGermanBookText("Am 2. August veranstaltet Neon Rift einen Kunstwettbewerb, insgesamt werden 150 Silber Preisgeld ausgeschrieben, der Gewinner ist unbekannt...",0,0,0)
base.books.AddGermanBookText("Am 8. August gründet Dyluck The Magic Academy eine Schule für Magie.",0,0,0)
base.books.AddGermanBookText("Am 18. August, kommt es zu einer Allianz zwischen der Grauen Rose und der Amazonen.",0,0,0)
base.books.AddGermanBookText("Am 23. August schickt ein Hohepriester der Echsenmenschen, Lzzan'twa, seinen Diener Bror nach Troll's Bane, um eine Nachricht zum hiesigen Zelphia - Kult zu bringen.",0,0,0)
base.books.AddGermanBookText("Nachdem er diesen nicht finden kann, kehrt er zu seinem Meister zurück, der sehr verärgert ist und so muss Bror zum dritten Mal die Strecke nach Troll's Bane schwimmen, um den Brief an die the goddess-Priesterin Rydia zu übergeben.",0,0,0)
base.books.AddGermanBookText("Der Brief enthält eine wichtige Warnung vor Drakhen Vorkalion, einem bösartigem Priester, der plant, seinen Meister, den Bone Lord, zur Insel Troll's Bane zu bringen.",0,0,0)
base.books.AddGermanBookText("Sie ruft sämtliche Bürger Illarions dazu auf, sich gegen dieses Böse zu erwehren.",0,0,0)
base.books.AddGermanBookText("Am 24. August bietet Drakhen Vorkalion Dyluck Macht und Unsterblichkeit an, wenn er auf seine base.books.AddGermanBookText übergeht. Durch die Unterstützung vieler Freunde schafft es Dyluck, nicht darauf einzugehen.",0,0,0)
base.books.AddGermanBookText("Am 25. August, bedroht der Lich Drahken Vorkalion .ein Diener einer der Unsterblichen Moshrans) ganz Illarion und beschwört den Dämon Ashkatuul. Er setzt ein Ultimatum von drei Tagen.",0,0,0)
base.books.AddGermanBookText("Am 27. August, findet die große Schlacht gegen den Lich und seine Dämonen statt, die versuchen, durch ein schwarzes Ritual die Macht auf Illarion an sich zu reißen. Unter tatkräftiger Mithilfe der Grauen Rose wurde dies verhindert.",0,0,0)
base.books.AddGermanBookText("In den folgenden Tagen gibt es bis zum 4. September noch Rückzugsgefechte mit den geschwächten Dämonen.",0,0,0)
base.books.AddGermanBookText("Am 28. August findet Dyluck ein altes Tagebuch des Studenten Meridius einer Magic Academy in der magischen Stadt Ghalaveius.",0,0,0)
base.books.AddGermanBookText("Es erzählt über die Freundschaft und spätere Rivalität von Meridious und Eltaren und die Zerstörung der Stadt durch feindliche magische Mächte.",0,0,0)
base.books.AddGermanBookText("Am 1.September hielten die Bewohner von Troll's Bane, insbesondere die Zwerge des Ironhammer-Clans, eine Zeremonie ab zu Ehren des verstorbenen Königs Udan und zur Krönung Caranthirs, der neue König erschien erstaunlicherweise nicht.",0,0,0)
base.books.AddGermanBookText("Am 6.September wurde das dritte King of the Roof-Turnier abgehalten, welches Corrin für sich entscheiden konnte.",0,0,0)
base.books.AddGermanBookText("Am 7.September gründet Tal Rash eine Necromancer-Gilde. Sie wurde später Riders of Moshran genannt.",0,0,0)
base.books.AddGermanBookText("Am 17. September, ließ Uruk Beastazuk, ein Ork, der Monster beherrschen kann, diese die Stadt angreifen. Gründe für diesen Angriff finden sich nicht.",0,0,0)
base.books.AddGermanBookText("Am 20.September wird in Erinnerung an König Udan vom Ironhammer Clan ein Gedenkstein errichtet. Er findet sich am Fluss hinter Elizas Laden.",0,0,0)
base.books.AddGermanBookText("Am 21.September erklären die Ritter der Grauen Rose, sowie der Orden des Grauen Lichts Thoer aufgrund seiner andauernden Aggressionen und Angriffe auf Ritter und Bewohner Troll's Bane den Krieg.",0,0,0)
base.books.AddGermanBookText("In diesen Krieg werden weitere Gilden mit hineingezogen.",0,0,0)
base.books.AddGermanBookText("Am 24. September treffen sich die Gildenleiter der Ritter der Grauen Rose, des Ordens des Grauen Lichts, sowie des Amazon Tribe und des Ironhammer Clans um über das weiter Vorgehen in Bezug auf Thoer ein Urteil zu fällen.",0,0,0)
base.books.AddGermanBookText("Am selben Tag endete der Krieg nach vielen diplomatischen Verwicklungen siegreich durch das Eingreifen der Götter.",0,0,0)
base.books.AddGermanBookText("Ende September / Anfang Oktober, bedrohen die Ureinwohner unter dem Pseudonym The Blood Corpse Illarion und fordern ein Zeichen des guten Willens.",0,0,0)
base.books.AddGermanBookText("Am 28.September kursieren Gerüchte über ein Verschwinden der Bibliothek. The Blood Corpse wird beschuldigt, sie zerstört zu haben.",0,0,0)
base.books.AddGermanBookText("Durch das diplomatische Geschick des Grauen Lichtes und der Grauen Rose gelingt es, sich friedlich mit ihnen zu einigen und Schaden von Illarion abzuwenden. Die Bibliothek erscheint nach einiger Zeit auf magische Weise wieder.",0,0,0)
base.books.AddGermanBookText("Am 1.Oktober versucht Tal Rash ein Kampfturnier zu veranstalten, da jedoch bis zum Tod gekämpft werden soll, finden sich keine Teilnehmer.",0,0,0)
base.books.AddGermanBookText("Am 3. Oktober erklärten die Riders of Moshran unter Tal Rash dem Mephisto Empire unter Sean den Krieg aufgrund vorangegangener Übergriffe des Mephisto Empires auf Tal Rash.",0,0,0)
base.books.AddGermanBookText("Am 3. Oktober spricht Xarex's Reinkarnation von der Aufgabe, die ihm Zelphia nach seinem Tode übermittelt haben soll, einen Tempel ihr zu Ehren zu bauen. Anhänger Zelphias werden gesucht.",0,0,0)
base.books.AddGermanBookText("Am 3. Oktober errichtet Shardon eine Außenstelle der Knights of the Fellowship auf Illarion.",0,0,0)
base.books.AddGermanBookText("Am 4. Oktober sucht das Mephisto Empire unter Sean nach den Besten der Besten.",0,0,0)
base.books.AddGermanBookText("Sean .ME) erklärt Shardon .KotF) und Tal Rash .RoM) zu seinen Feinden.",0,0,0)
base.books.AddGermanBookText("Er bittet den Bloodskull Clan um Hilfe. Sein Hilfe-Gesuch wird abgelehnt.",0,0,0)
base.books.AddGermanBookText("Stattdessen scheint sich Gurok .BSC) auf die base.books.AddGermanBookText Shardons zu schlagen.",0,0,0)
base.books.AddGermanBookText("Am 6. Oktober veranstaltet Tal Rash ein Kampfturnier mit tödlichen Duellen.",0,0,0)
base.books.AddGermanBookText("Überlebender Gewinner ist Echnaton.",0,0,0)
base.books.AddGermanBookText("Am 6. Oktober erklärt Mephisto Empire unter Sean dem Grauen Licht den Krieg.",0,0,0)
base.books.AddGermanBookText("Nach Unterstützungserklärungen der Grauen Rose und der Silverstar Merchants für das Graue Licht zieht Sean seine Erklärung am nächsten Tag wieder zurück mit der Begründung, er wäre betrunken gewesen.",0,0,0)
base.books.AddGermanBookText("Im Jahre 1 des neuen Zeitalters, im Monat Oktober herrschen noch weitere Kleinkriege zwischen Mephisto Empire unter Sean und andere Gilden.",0,0,0)
base.books.AddGermanBookText("Am 14. Oktober greift die Brut einer sehr hungrigen Riesenspinne Troll's Bane an. Korwin entdeckt den Angriff und organisiert eine Verteidigung.",0,0,0)
base.books.AddGermanBookText("Besonders tun sich Sharpshooter Lynx, Kenil, Lillith und Sir Giandor in der Verteidigung vor.",0,0,0)
base.books.AddGermanBookText("Am 14. Oktober gründet Korwin die Ranger Guilde um den Wald zu schützen. Das Ziel wird später auf den Schutz der ganzen Stadt ausgedehnt.",0,0,0)
base.books.AddGermanBookText("Im Jahre 1 des neuen Zeitalters, im Monat Oktober gelang es Sabrina ihrem Meister zu entkommen, der sie in einem Gefängnisturm in der Wüste eingesperrt hatte. Auch Necrophotius Fungius spielt eine undurchsichtige Rolle bei der Flucht.",0,0,0)
base.books.AddGermanBookText("Am 29. Oktober bricht Dyluck zu einer Suchexpedition nach Sabrina in die Wüste auf. Davor hatte er in einem Alptraum die gefangene Sabrina gesehen.",0,0,0)
base.books.AddGermanBookText("Er findet sie in der Wüste bewusstlos und verhungert und bringt sie nach Troll's Bane zurück.",0,0,0)
base.books.AddGermanBookText("Im Jahre 1 des neuen Zeitalters, im Monat Oktober beginnen seltsame Kräfte an Aragon von der Grauen Rose zu wirken, ein Traum wird lebendig und Drakhen Vorkalion erscheint ihm zweimal.",0,0,0)
base.books.AddGermanBookText("Am 16. Oktober verabschiedet sich der alternde Ork Kzarak Zhoruch und zieht sich zum Sterben zurück.",0,0,0)
base.books.AddGermanBookText("Am 17. Oktober verlässt Angaria ihren Mann Sirius Fellfuß und die Insel mit unbekanntem Ziel.",0,0,0)
base.books.AddGermanBookText("Am 19. Oktober sucht Cube, Mitglied des UPM-Clans, die Stadt mit Feuerzaubern heim. Nach Ermahnung durch Jeron Giandor von dem Grauen Licht beginnt Cube und Freunde von ihm eine tagelange Hetzjagd auf Jeron Giandor.",0,0,0)
base.books.AddGermanBookText("Am 21. Oktober setzen Cube und Bluna .zwei Mitglieder der UPM) ein Kopfgeld auf Jeron Giandor aus und greifen diesen selber an. Damien forderte im Namen des Grauen Lichtes, das sofort zu unterlassen.",0,0,0)
base.books.AddGermanBookText("Er droht mit einer Kriegserklärung an den UPM-Clan falls diese sich nicht kooperativ zeigen. GL und GR fordern den UPM-Clan auf, 50 Silber Wiedergutmachung zu zahlen und deren Mitglieder Cube und Bluna zu bestrafen.",0,0,0)
base.books.AddGermanBookText("Es wird sich auf 25 Silber geeinigt.",0,0,0)
base.books.AddGermanBookText("Am 25. Oktober eröffnet Chubb Fire den Black-Tail-Laden für Schmiede- und Schneiderartikel.",0,0,0)
base.books.AddGermanBookText("Am 27. Oktober bringt Aragon seine frühere Geliebte Alara und deren ungeborenes Kind getrieben von den Mächten in ihm um. Daraufhin flüchtet er aus der Stadt. Später wird sich herausstellen, dass Alara ein Wesen Bjolmurs war.",0,0,0)
base.books.AddGermanBookText("Erst Wochen später taucht er wieder in der Stadt auf. Lillith kümmert sich in dieser Zeit um ihn.",0,0,0)
base.books.AddGermanBookText("Am 29. Oktober bricht Neon Rift auf, um auf dem Kontinent als Söldnerführer Dienst zu leisten.",0,0,0)
base.books.AddGermanBookText("Am 3. November schließen sich Mephisto Empire und Ranger zu einer Gilde zusammen. Ein offizieller Austritt aus den Rangern wird bekannt. Fathe Boron findet die Idee der Ranger nicht mehr verwirklicht.",0,0,0)
base.books.AddGermanBookText("Am 8. November wirft Astral die Idee der School of Combat auf. Sie soll vorzugsweise für Kämpfer sein und Neuankömmlingen unter die Arme greifen. Es gibt Kritik an dieser Einrichtung, da sie der Magic Academy ähnlichsieht.",0,0,0)
base.books.AddGermanBookText("Am 11. November erklärt Cube der Grauen Rose den Krieg.",0,0,0)
base.books.AddGermanBookText("Nachdem er sich des Mordes an Unbeteiligten brüstet und damit die Graue Rose verhöhnt, wird er von der Grauen Rose als vogelfrei erklärt. Zwei Tage später trifft Cube das verdiente Gericht der Götter und er stirbt schmachvoll.",0,0,0)
base.books.AddGermanBookText("Am 14. November wirbt Purple Dragons nun offiziell um Mitglieder. Sie verehren den König des Drachenlandes und glauben an eine Zeit der Veränderung, wo jedes Mitglied ein Drache wird und im Land der Drachen in Frieden leben wird.",0,0,0)
base.books.AddGermanBookText("Am 17. November setzt sich die School of Combat dennoch durch und akzeptiert ab nun jede Person, auch Mitglieder anderer Gilden.",0,0,0)
base.books.AddGermanBookText("Am 18. November veranstaltet Dyluck ein großes Konzert auf der Terasse der Bibliothek. Als Künstler treten Badmosche, Xaveria, Treason, Cosmaterra, Dyluck und als besonderer Gast Necrophotius Fungius mit einem Spottlied auf Cube auf.",0,0,0)
base.books.AddGermanBookText("Es war ein gelungener Konzertabend. Einzig ein eskalierender Streit zwischen zwei sich liebenden Paaren, Dyluck und Sabrina, sowie Olorin und Galadria störte den Ausgang des Abends.",0,0,0)
base.books.AddGermanBookText("Am 20. November überfällt Drakhen Vorkalion auf der Suche nach Aragon Troll's Bane und verlangt dessen Auslieferung.",0,0,0)
base.books.AddGermanBookText("Drakhen will ihn für seine Zwecke nutzen, da Aragon aus einer alten Priesterfamilie Malachins stammt, als Baby jedoch dem Knochenlord Cherass durch Ränke Drakhens geweiht wurde und beide Mächte in ihm miteinander ringen.",0,0,0)
base.books.AddGermanBookText("Eine alte von Damien gefundene Prophezeiung zeigt einen Ausweg.",0,0,0)
base.books.AddGermanBookText("Am 20. November findet Damien unter der Bibliothek die Reste eines schwarzen Rituals mit dem ein Fluch über Liebende durch Drakhen Vorkalion ausgesprochen wurde, wahrscheinlich während des Konzertes.",0,0,0)
base.books.AddGermanBookText("Aufgrund des Fluches will Sabrina keinen Menschen zum Mann haben und Dyluck in seiner Not will mit Drakhen aushandeln, dass er Aragon ausliefert und dafür elbenlanges Leben erhält. Eine Bote Siranis bringt Dyluck davon ab.",0,0,0)
base.books.AddGermanBookText("Am 20. November gründet Sean die Praetorian Guards und bittet gleichzeitig um viel Unterstützung der anderen Gilden.",0,0,0)
base.books.AddGermanBookText("Am 27. November wird auf Anregung von Jean Long ein Fest zu Ehren Siranis ausgerichtet, auf dem der Fluch Drakhens gelöst wird.",0,0,0)
base.books.AddGermanBookText("Am 26. November lädt Sean, Anführer der Praetorian Guards zu einem Treffen aller Gilden-Führer ein. Der Grund dieses Treffens ist unklar.",0,0,0)
base.books.AddGermanBookText("Am 27. November kommt es zu einem Zusammentreffen zwischen Drakhen und Aragon. Drakhen wird unter tatkräftiger Mithilfe, vor allem Franjel Salem Longs und sir Ganons, geschlagen.",0,0,0)
base.books.AddGermanBookText("In der Folge gelingt es Aragon durch eine Geistreise zu Chergas Ebene den Bann Cherass zu lösen und damit entgültig Priester Malachins zu werden.",0,0,0)
base.books.AddGermanBookText("Am 29. November zeichnet sich ein weiterer Zusammenschluss ab, der Ranger und der School of Combat.",0,0,0)
base.books.AddGermanBookText("Am 1. Dezember gibt Randar bekannt, dass er seine Stellung als einer der Führenden des Zelphia Tempels, an Dragonclaw abgibt.",0,0,0)
base.books.AddGermanBookText("Am 3. Dezember wird in der Bibliothek ein Mordanschlag durch einen Sniper verübt. Dyluck verdächtigt Sean, worauf sich tagelange Nachforschungen und Streitigkeiten entwickeln. Der Anschlag bleibt letztlich ungeklärt.",0,0,0)
base.books.AddGermanBookText("Am 7. Dezember gibt Galadria bekannt, aufgrund der Befreiung von dem Fluch durch Sirani, ihr Leben ihr zu weihen und Priesterin Siranis zu werden, sowie einen Tempel zu ihren Ehren bauen zu wollen.",0,0,0)
base.books.AddGermanBookText("Weitere Anhänger Siranis sind Jean Long, Xaveria und Rhandarjia.",0,0,0)
base.books.AddGermanBookText("Am 7. Dezember gibt Drunk Mage Dipstick bekannt, als Auftragsmörder zu arbeiten. Zwei Wochen später gibt er dies wieder auf.",0,0,0)
base.books.AddGermanBookText("Am 9. Dezember feiert die Graue Rose eine Dankesfeier zu Ehren Malachins für das gute Ende der Geschehnisse um Aragon. Am selben Tag verloben sich auch Aragon und Lillith.",0,0,0)
base.books.AddGermanBookText("Am 10. Dezember erklärt Riders of Moshran unter Tal Rash den Templern von Zelphia den Krieg. Trittbrettfahrer hängen sich an den Konflikt. Eine Zeit der Unsicherheit in der Stadt beginnt.",0,0,0)
base.books.AddGermanBookText("Mit Hilfe der Grauen Rose werden Tal Rash und Dipstick bei einer großen Schlacht, am 18. Dezember geschlagen und ziehen sich zurück.",0,0,0)
base.books.AddGermanBookText("Am 12. Dezember erklären die Rangers unter Astral den Dark Mages unter Sir Crystal Star den Krieg wegen zahlreicher Übergriffe auf die Bewohner der Stadt.",0,0,0)
base.books.AddGermanBookText("Am 14. Dezember gibt Pasha eine Zeitung für Illarion heraus.",0,0,0)
base.books.AddGermanBookText("Doch schon nach wenigen Tagen gibt er dies wieder auf.",0,0,0)
base.books.AddGermanBookText("Am 15. Dezember fischt Dyluck einen halbertrunkenen Schiffbrüchigen aus dem Meer. Er heißt Rogarian und stammt aus dem Land Romada, welches von dem Land Edin beherrscht wird.",0,0,0)
base.books.AddGermanBookText("Mitte Dezember sprechen sich die Eltern Lilliths gegen eine Hochzeit mit Aragon aus und vollziehen ein Ritual an ihrer Tochter, dass sie jeglicher Gefühle beraubt.",0,0,0)
base.books.AddGermanBookText("Galadria kümmert sich in Folge um Lillith und Jean Long um Aragon.",0,0,0)
base.books.AddGermanBookText("Am 19. Dezember erklärt Sean den Riders of Moshran den Krieg.",0,0,0)
base.books.AddGermanBookText("Am 20. Dezember gibt Dyluck bekannt, Wettspiele veranstalten zu wollen. Sie wurden mehrmals verschoben und fanden nie statt.",0,0,0)
base.books.AddGermanBookText("Am 22. Dezember gründet Thorfin Skull Spliter eine Gilde, die den Gott Bragon verehrt.",0,0,0)
base.books.AddGermanBookText("Am 23. Dezember gründet Dragonsoul die Gilde The Crimson Dragon. Sie hat nur wenige Mitglieder und wird Mitte Januar letztmalig erwähnt.",0,0,0)
base.books.AddGermanBookText("Ende Dezember und Anfang Januar terrorisieren Spaniard und seine Gruppe Gleichgesinnter mit heimtückischen Bogenangriffen die Stadt. Sie werden von den Rangers und Dyluck gejagt.",0,0,0)
base.books.AddGermanBookText("Ebenso terrorisiert Marlene mit einer anderen Gruppe die Stadt. Diese wird von der Grauen Rose gejagt.",0,0,0)
base.books.AddGermanBookText("Am 29. Dezember wird ein Gildenrat durch Roke auf Anregung von Sean einberufen. Als Vorsitzender wurde von Aragon Damien vorgeschlagen und allgemein akzeptiert.",0,0,0)
base.books.AddGermanBookText("Unter dessen Leitung werden Standards für die Zugehörigkeit zu diesem Rat erarbeitet. Intensiv arbeiten Damien, Dyluck, Astral, Roke, Tialdin und Aragon daran mit.",0,0,0)
base.books.AddGermanBookText("Nach diesen Standards bekommen folgende Gilden zwei Sitze: Graue Licht, Graue Rose, Magic Academy und folgende einen Sitz: Ironhammer, Titanen, Rangers, School of Combat.",0,0,0)
base.books.AddGermanBookText("Auf Nachfrage Erdricks bekommen die Silver Star Merchants am 29. Januar auch einen Sitz zugesprochen. Ein zweites Treffen Mitte Januar bestätigt diese Standards.",0,0,0)
base.books.AddGermanBookText("Ständige Streitigkeiten um Verfahrensfragen mit Sean und Peace Keeper ermüden den Prozess und führen zum Erliegen des Gildenrates.",0,0,0)
base.books.AddGermanBookText("Am 30. Dezember gründet Balderion den Order of the flaming fist.",0,0,0)
base.books.AddGermanBookText("Am 31. Dezember griff Drakhen Vorkalion Troll's Bane wieder an. Erdrick berichtet davon, dass Drakhen von vielen verlorenen Seelen begleitet war, die nicht mehr wiedererweckt werden konnten.",0,0,0)
base.books.AddGermanBookText("Am 31. Dezember geben Drunk Mage Dipstick und Spaniard das Ende der Servants of Darkness bekannt.",0,0,0)
        
--Englische Bucheinträge hinzu fügen
base.books.AddEnglishBookText("On february, the 20th, the opening of a new bulletin board in the shop of Troll's Bane was celebrated.",0,0,0)
base.books.AddEnglishBookText("On february, the 22nd, the Order of the Grey Light was founded by Damien.",0,0,0)
base.books.AddEnglishBookText("The goals of the Order are neutrality, safety on the streets of Troll's Bane, to collect knowledge and building of a library.",0,0,0)
base.books.AddEnglishBookText("On february, the 27th and 28th, an unknown epidemic struck the sheep and made them become killer sheep.",0,0,0)
base.books.AddEnglishBookText("The tavern (not todays tavern, a provisorical wooden building north of town which was built by Ghost Walker and later abandoned) was attacked by them.",0,0,0)
base.books.AddEnglishBookText("A child was missing.",0,0,0)
base.books.AddEnglishBookText("Fluffy seemed resistend against this epidemic and was kept by Ghost Walker to guard the tavern.",0,0,0)
base.books.AddEnglishBookText("On february, the 28th, Damien and Aries invent the game Fish Pong.",0,0,0)
base.books.AddEnglishBookText("On march, the 11th, Galdriel discovers a narrow pass in the dense forests in the north west of the island.",0,0,0)
base.books.AddEnglishBookText("On another expedition, Galdriel and Bror discover ruins.",0,0,0)
base.books.AddEnglishBookText("According to a legend, a mage, searching for power, touched forbidden scrolls of the elder Gods inside a temple, causing an earthquake which destroyed the temple and the mage, and causing the forests to grow in a matter of seconds.",0,0,0)
base.books.AddEnglishBookText("On march, the 11th, the Brotherhood of Light: is founded by Silver.",0,0,0)
base.books.AddEnglishBookText("They call themselves the third guild on the island.",0,0,0)
base.books.AddEnglishBookText("Their goals are to support newcomers, to pacify the streets and to trade.",0,0,0)
base.books.AddEnglishBookText("On march, the 12th, the demon cave in the north east was explored for the first time and the Red Baron was discovered.",0,0,0)
base.books.AddEnglishBookText("On march, the 12th, Master Gohan foundet the Order of Demonic Light.",0,0,0)
base.books.AddEnglishBookText("On march, the 21st, Master Gohan discovered an ancient, barely readable scroll, foretelling the fall of Illarion.",0,0,0)
base.books.AddEnglishBookText("However, according to Damien, many faked scrolls are known.",0,0,0)
base.books.AddEnglishBookText("At the same time three transistor fields, emitting heat, are discovered.",0,0,0)
base.books.AddEnglishBookText("They seem to be portals for fire spirits, whose voices are heard by several people.",0,0,0)
base.books.AddEnglishBookText("A statue of Tanora was stolen.",0,0,0)
base.books.AddEnglishBookText("Different rituals allowed to reestablish balance between water and fire.",0,0,0)
base.books.AddEnglishBookText("The portals vanished.",0,0,0)
base.books.AddEnglishBookText("On march, the 27th, finally Bror, Neon Rift and Olorin managed to free the statue of Tanora.",0,0,0)
base.books.AddEnglishBookText("It gets a new place on the eastern lagune and serves as a Tanora shrine since then.",0,0,0)
base.books.AddEnglishBookText("Neon Rift and Olorin are rewarded with rare fruits.",0,0,0)
base.books.AddEnglishBookText("On march, the 27th, a warning for the notorious killer Darkwalker was spoken out for the first time.",0,0,0)
base.books.AddEnglishBookText("He also tried to stir up the Order of the Grey Light and the Order of Demonic Light against each other.",0,0,0)
base.books.AddEnglishBookText("At the beginning of april there are discussions within the Grey Light about the introduction of a police force.",0,0,0)
base.books.AddEnglishBookText("Darkwalker is executed on april, the 10th.",0,0,0)
base.books.AddEnglishBookText("On march, the 31th, Neon Rift had a vision of the future library.",0,0,0)
base.books.AddEnglishBookText("He draws plans basing on the vision and the Grey Light begins the construction.",0,0,0)
base.books.AddEnglishBookText("In the year one of the new era at the beginning of April, the Grey Rose was founded as part of the order of the Grey Light.",0,0,0)
base.books.AddEnglishBookText("She's a circle of knights and the Grey Light's fighting unit against criminals in the streets of Troll's Bane.",0,0,0)
base.books.AddEnglishBookText("Her first leader was Sturm Feuerklinge.",0,0,0)
base.books.AddEnglishBookText("Original members were furthermore Sirius Fellfuß and Sir Antarion.",0,0,0)
base.books.AddEnglishBookText("She was formed as an answer to Darkwalker's threat.",0,0,0)
base.books.AddEnglishBookText("On April, the 10th, the library, which was built by the Grey Light, and the Fluffy Sheep Bar ( the today's tavern) were opened.",0,0,0)
base.books.AddEnglishBookText("On April, the 10th, Erdrick's shop was mentioned the first time in a scroll's subordinate clause.",0,0,0)
base.books.AddEnglishBookText("On April, the 13th, the guild The Titans was founded by Sir Drakan and Cody.",0,0,0)
base.books.AddEnglishBookText("On April, the 19th, Kyuushiki organised the first contest of poets and singers.",0,0,0)
base.books.AddEnglishBookText("On April, the 23rd, Kyuushiki explained the aims of the guild The Tavern which is later called Tavernkeepers.",0,0,0)
base.books.AddEnglishBookText("This guild appeared the first time in public, it's aim is to run the tavern.",0,0,0)
base.books.AddEnglishBookText("On April, the 24th, the Grey Rose formed an alliance with the guild The Titans.",0,0,0)
base.books.AddEnglishBookText("On April, the 24th, Onyx mentioned the Guild The Dark Mages the first time.",0,0,0)
base.books.AddEnglishBookText("Their leader is Sir Crystal Star.",0,0,0)
base.books.AddEnglishBookText("In these times there's also a question of hegemony in the tavern between the Dark Mages and the Tavernkeepers .",0,0,0)
base.books.AddEnglishBookText("After their defeat the Dark Mages left the town and their rule of terror ended.",0,0,0)
base.books.AddEnglishBookText("On April, the 24th, the orc Boga Woga founded the guild Bloodtooth Tribe.",0,0,0)
base.books.AddEnglishBookText("The last hints on this tribe can be found in the middle of May.",0,0,0)
base.books.AddEnglishBookText("On April, the 26th, Raziel founded the guild The Shadowen Empire.",0,0,0)
base.books.AddEnglishBookText("Their aim is the hegemony in Illarion.",0,0,0)
base.books.AddEnglishBookText("On April 26th, the Tavernkeepers and the Grey Light agreed on running the Fluffy Sheep Bar together.",0,0,0)
base.books.AddEnglishBookText("On may, the 9th, Khallja and Tinari married in Troll's Bane.",0,0,0)
base.books.AddEnglishBookText("It is the first wedding mentioned in the official documents.",0,0,0)
base.books.AddEnglishBookText("At the beginning of May, the ruins north of town were unearthed.",0,0,0)
base.books.AddEnglishBookText("Soon it was realised that the ruins are an execrated place where the ghosts of the dead are awaked to life as undeads.",0,0,0)
base.books.AddEnglishBookText("On may, the 18th, Damien of the Grey Light asked the people of the Shadow Empire if it would be possible to aid one another, due to similar aims.",0,0,0)
base.books.AddEnglishBookText("No official arrangement was made.",0,0,0)
base.books.AddEnglishBookText("In the year one of the new era during May und June, the Grey Rose became decomposed slowly due to frequent absence of her leader.",0,0,0)
base.books.AddEnglishBookText("Soon after Aragon's joining Sturm Feuerklinge disappeared with the circle's money and wasn't seen again during several months.",0,0,0)
base.books.AddEnglishBookText("At this time Sirius Fellfuss, Echnaton and Aragon were active circle members.",0,0,0)
base.books.AddEnglishBookText("On June, the 3rd a scroll with the legend of the transfixed virgin was found in the library.",0,0,0)
base.books.AddEnglishBookText("Enquiries in the north of the island proved this legend true.",0,0,0)
base.books.AddEnglishBookText("A mage and his financée were caught in a lavaspot and a stonefigur caused by an experiment.",0,0,0)
base.books.AddEnglishBookText("Leadmanaged by Damien and Darzog inhabitantes of Troll's Bane tried to free the mage and the maid.",0,0,0)
base.books.AddEnglishBookText("Damien became lunatic at one ritual and released fire everywhere.",0,0,0)
base.books.AddEnglishBookText("In the end a couple of inhabitantes were able to drive the daemon away and so the maid and the mage got layed to rest.",0,0,0)
base.books.AddEnglishBookText("On June, the 4th Sir Sirius was promoted to the adjutant of Sturm by the aboarded knights of the Grey Rose.",0,0,0)
base.books.AddEnglishBookText("Later he should carry on the circles business.",0,0,0)
base.books.AddEnglishBookText("In the year on of the new era on June, the 18th Sjealesh starts the attempt of an Illarion newspaper, which failed soon.",0,0,0)
base.books.AddEnglishBookText("On June, the 23th a name for the upcoming town on the island is searched, controled by Darzog.",0,0,0)
base.books.AddEnglishBookText("On June, the 24th theAmazan Tribe recruits new members.",0,0,0)
base.books.AddEnglishBookText("Its leader is Zhara Fiarai.",0,0,0)
base.books.AddEnglishBookText("On June, the 24th The Iron Hammer Guild recruits dwarfs as members.",0,0,0)
base.books.AddEnglishBookText("Ist king is Udan Trollbane.",0,0,0)
base.books.AddEnglishBookText("On July, the 2nd for the first time Neon Rift arranged a King of the roof-tournament (KOTR).",0,0,0)
base.books.AddEnglishBookText("The winner is Echnaton.",0,0,0)
base.books.AddEnglishBookText("On July, the 9th it comes to a second KOTR-tournament, which Peregrin won.",0,0,0)
base.books.AddEnglishBookText("On July, the 16th Griitash, Minran and Lindin founded the Loretrade Merchant Guild.",0,0,0)
base.books.AddEnglishBookText("On July, the 18th it comes to a memorable meeting of the aktiv knights of the Grey Rose with Elder Damien of the Order of the Grey Light.",0,0,0)
base.books.AddEnglishBookText("The meeting ends therewith, that the Cricle becomes a independent guild, allied with the Order of the Grey Light.",0,0,0)
base.books.AddEnglishBookText("The Circle serves Malachin.",0,0,0)
base.books.AddEnglishBookText("Herewith the newer history of Circle begins and a time of reconstruction.",0,0,0)
base.books.AddEnglishBookText("On July, the 21st Damien organises a new game named animal catching.",0,0,0)
base.books.AddEnglishBookText("The aim of the game is to hustle sheep and pig back to their enclosure.",0,0,0)
base.books.AddEnglishBookText("At large a prize money of 600 Goldpieces has been disbursed.",0,0,0)
base.books.AddEnglishBookText("On July, the 23rd Elminster proposed to finally find a name for the store, but in lack of a good name the name the shop remains the same.",0,0,0)
base.books.AddEnglishBookText("On July, the 26th Sirius Fellfuß and Angaria get married in attendance of many witnesses and leaded by the priest Falkner and the templar Aragon.",0,0,0)
base.books.AddEnglishBookText("On July, the 29th Galdriel acusses Mortai for attempted murder.",0,0,0)
base.books.AddEnglishBookText("In the year one of the new era, near end of july after long discussions of the citizens finally the name Troll´s Bane stands firm.",0,0,0)
base.books.AddEnglishBookText("In the year one of the new era, at the beginning of August the code of the Grey Rose was decided to be the basic principle of the Circle in its present form.",0,0,0)
base.books.AddEnglishBookText("The Order of the Grey Light takes over this revised form of their earlier code from the Circle.",0,0,0)
base.books.AddEnglishBookText("On August, the 2nd Neon Rift arranged an artcompetition, in total 150 Silver prize money has been announced, the winner is unknown.",0,0,0)
base.books.AddEnglishBookText("On August, the 8th Dyluck founds The Magic Academy , a school for magic.",0,0,0)
base.books.AddEnglishBookText("On August, the 18th it comes to an alliance between the Grey Rose and the Amazons.",0,0,0)
base.books.AddEnglishBookText("On August, the 23rd the archpriest of the lizzardmen, Lzzan`twa, sends his servant to Troll´s Bane, to get a message to the local Zelphiacult.",0,0,0)
base.books.AddEnglishBookText("After not finding them, he travels back to his master, who is angry about the inability of Bror and so Bror has to swim the distance to Troll´s Bane the third time, to deliver the letter to the goddess-priestress Rydia.",0,0,0)
base.books.AddEnglishBookText("The letter contains an important warning that Drakhen Voralion, an evil priest, is planing to get his master, the Bone Lord, to the island of Troll´s Bane.",0,0,0)
base.books.AddEnglishBookText("She calls on the citizens of Illarion, to resist the ill.",0,0,0)
base.books.AddEnglishBookText("On August, the 24th Drahken Vorkalion offers Dyluck power and immortality, if he joins his side.",0,0,0)
base.books.AddEnglishBookText("With support of many of his friends Dyluck resist this offer.",0,0,0)
base.books.AddEnglishBookText("On August, the 25th the lich Drahken Vorkalion (one of Moshran´s immortal servants) threatens whole Illarion and summons the demon Ashkatuul.",0,0,0)
base.books.AddEnglishBookText("He issues an ultimatum of three days.",0,0,0)
base.books.AddEnglishBookText("On August, the 27th the great battle against the lich and his demons takes place, which are attemted to assume power over Illarion by a black ritual.",0,0,0)
base.books.AddEnglishBookText("With the energeic aid of the Grey Rose this has been prevented.",0,0,0)
base.books.AddEnglishBookText("In the following days up to September the 4th several battles occur while the enfeebled demons withdraw.",0,0,0)
base.books.AddEnglishBookText("On August, the 28th Dyluck found the old diary of the Meridius, student at an Magic Acedemy of the magic town Ghalaveius.",0,0,0)
base.books.AddEnglishBookText("It told the story of the friendship and later rivalry between Meridius and Eltaren and the destruction of the town by hostile magic forces.",0,0,0)
base.books.AddEnglishBookText("On September, the 1st the inhabitants of Troll´s Bane, in particular the dwarves of the Ironhammer-Clan, are holding a ceremony in honour of their deceased king Udan and for the coronation of Caranthir to their new king.",0,0,0)
base.books.AddEnglishBookText("Surprisingly Caranthir failed to appear.",0,0,0)
base.books.AddEnglishBookText("On September, the 6th the third King of the Roof-tournament has been held, which Corrin won.",0,0,0)
base.books.AddEnglishBookText("On September, the 7th Tal Rash founds a necromancer-guild, later known as Riders of Moshran.",0,0,0)
base.books.AddEnglishBookText("On September, the 17th Uruk Beastazuk, an orc with the power to rule the monsters, let them attack the town for unknown reasons.",0,0,0)
base.books.AddEnglishBookText("On September, the 20th a memorial stone for the reminiscence of King Udan of the Ironhammer Clan has been raised.",0,0,0)
base.books.AddEnglishBookText("It can be found behind Eliza´s Store.",0,0,0)
base.books.AddEnglishBookText("On September, the 21st the Knights of the Grey Rose and the Order of the Grey Light declares war on Thoer for his continuous aggression and attacks on the knights and the inhabitants of Troll´s Bane.",0,0,0)
base.books.AddEnglishBookText("In this war more guilds has been involved.",0,0,0)
base.books.AddEnglishBookText("On September, the 24th the guildleader of the Knights of the Grey Rose, the Order of the Grey Rose, the Amazon Tribe and the Ironhammer Clan arranged a meeting to form an opinion about the further actions against Thoer.",0,0,0)
base.books.AddEnglishBookText("The same day the war ends, after many political implications, victourious with the intervention of the gods.",0,0,0)
base.books.AddEnglishBookText("In the year one of the new era , at the end of September/ beginning of Oktober the original inhabitants under the pseudonym The Blood Corpse threaten Illarion and demand a sign of good will.",0,0,0)
base.books.AddEnglishBookText("On September, the 28th rumours were afloat about a disappearance of the libary.",0,0,0)
base.books.AddEnglishBookText("The Blood Corpse has been accused for its destruction.",0,0,0)
base.books.AddEnglishBookText("With the diplomatic skill of the Grey light and the Grey Rose an peaceful agreement can be achieved and harm to Illarion can be prevented.",0,0,0)
base.books.AddEnglishBookText("The libary reappears magically after some time.",0,0,0)
base.books.AddEnglishBookText("On october, the 1st Tal Rash tried to organize a fighting competition.",0,0,0)
base.books.AddEnglishBookText("He never found fighters because Tal Rash wanted fights until death.",0,0,0)
base.books.AddEnglishBookText("On october, the 3rd the Riders of Moshran under Tal Rash started a war against the Mephisto Empire under Sean because of the attacks of Mephisto Empires at Tal Rash.",0,0,0)
base.books.AddEnglishBookText("On october, the 3rd Xarex's reinkarnation spoke about a quest to build a temple for Zelphia.",0,0,0)
base.books.AddEnglishBookText("Zelphia gave that quest to him after his dead.",0,0,0)
base.books.AddEnglishBookText("Xarex is searching for followers of Zelphia.",0,0,0)
base.books.AddEnglishBookText("On october, the 3rd Shadron built a house for the Knights of the Fellowship on Illarion.",0,0,0)
base.books.AddEnglishBookText("On october, the 4th the Mephisto Empire under Sean was searching after the Best of the Best.",0,0,0)
base.books.AddEnglishBookText("Sean (ME) said that Shadron (KotF) and Tal Rash (RoM) are his enemies.",0,0,0)
base.books.AddEnglishBookText("He asked the Bloodskull Clan for help.",0,0,0)
base.books.AddEnglishBookText("His biddings where not acceptet, but Gurok (BSC) helped him.",0,0,0)
base.books.AddEnglishBookText("On october, the 6th Tal Rash organized a fighting competition to death.",0,0,0)
base.books.AddEnglishBookText("The surviving winner was Echnaton.",0,0,0)
base.books.AddEnglishBookText("On october, the 6th the Mephisto Empire under Sean started a war against the Grey Light.",0,0,0)
base.books.AddEnglishBookText("After the Grey Rose and the Silverstar Merchants said they will help the Grey Light in war Sean stoped the war and said he was drunken when he started it.",0,0,0)
base.books.AddEnglishBookText("On october the Mephisto Empire started some small wars against some other guilds.",0,0,0)
base.books.AddEnglishBookText("On october, the 14th a brood of hungry giant spiders attacked Troll's Bane.",0,0,0)
base.books.AddEnglishBookText("Korwin saw the attack first and organized the defense.",0,0,0)
base.books.AddEnglishBookText("Sharpshooter Lynx, Kenil, Lillith and Sir Giandor did the best defense.",0,0,0)
base.books.AddEnglishBookText("On october, the 14th Korwin founded the Rangers Guild to defend the forest.",0,0,0)
base.books.AddEnglishBookText("Sometime later their goal is to defend the hole town.",0,0,0)
base.books.AddEnglishBookText("On october Sabrina succeeded to ran away from her master that was imprisoned in the Prisontower in desert.",0,0,0)
base.books.AddEnglishBookText("Also, Necrophotius Fungius played an obscure role at this escape.",0,0,0)
base.books.AddEnglishBookText("On october, the 29th Dyluck started an expedition to search after Sabrina in the desert.",0,0,0)
base.books.AddEnglishBookText("Before this he saw Sabrina imprisoned in his nightmare.",0,0,0)
base.books.AddEnglishBookText("He brings her back to Troll's Bane.",0,0,0)
base.books.AddEnglishBookText("On october strange things happen to Aragon of the Grey Rose.",0,0,0)
base.books.AddEnglishBookText("His dream becomes reality and Drakhen Vorkalion appears him twice.",0,0,0)
base.books.AddEnglishBookText("On october, the 16th the old orc Kzarak Zhoruch said goodbye and left for dieing.",0,0,0)
base.books.AddEnglishBookText("On october, the 17th Angaria left his husband Sirius Fellfuß and Illarion with an unknown goal.",0,0,0)
base.books.AddEnglishBookText("On october, the 19th Cube, member of the UPL-Clan burned Troll's Bane with firemagic.",0,0,0)
base.books.AddEnglishBookText("After Jeron Giandor from the Grey Light warned Cube, Cube and his friends started to hunt Jeron Giandor.",0,0,0)
base.books.AddEnglishBookText("On october, the 21th Cube and Blune (two members from the UPM) set a reward for killing Jeron Giandor and attacked him theirselfes.",0,0,0)
base.books.AddEnglishBookText("Damien from the Grey Light demand to stop the hunting.",0,0,0)
base.books.AddEnglishBookText("Hethreatend the UPM-Clan with a war if they would not cooperate.",0,0,0)
base.books.AddEnglishBookText("GL and GR wanted the UPM-Clan to pay 50 ingots and to punish Cube and Bluna.",0,0,0)
base.books.AddEnglishBookText("The UPM-Clan payed 25 ingots.",0,0,0)
base.books.AddEnglishBookText("On october, the 25th Chubb Fire started the Black-Tail-Shop for blacksmith and tailor ware.",0,0,0)
base.books.AddEnglishBookText("On october, the 27th Aragon kills Alara and their unborn child because he was controlled from some unknown forces.",0,0,0)
base.books.AddEnglishBookText("After that he flees out of town.",0,0,0)
base.books.AddEnglishBookText("Later it will turn out that Alara was a Nature of Bjolmurs.",0,0,0)
base.books.AddEnglishBookText("One week later he reappears in Troll's Bane.",0,0,0)
base.books.AddEnglishBookText("Lillith care for him in this time.",0,0,0)
base.books.AddEnglishBookText("On october, the 29th Neon Rift left Illarion to work as a mercenary leader on the continent.",0,0,0)
base.books.AddEnglishBookText("On november, the 3rd Mephisto Empire and Ranger fusion together to one guild.",0,0,0)
base.books.AddEnglishBookText("Fathe Boron leave the Rangers because he dont like the idea of this guild anymore.",0,0,0)
base.books.AddEnglishBookText("On november, the 8th Astral has the idea to build the School of Combat.",0,0,0)
base.books.AddEnglishBookText("They are fighters that want to help new people on Illarion.",0,0,0)
base.books.AddEnglishBookText("Some people criticize this because it's like the Magic Academy.",0,0,0)
base.books.AddEnglishBookText("On november, the 11th Cube starts a war against the Grey Rose.",0,0,0)
base.books.AddEnglishBookText("After he murders some innocent people the Grey Rose send people to kill him.",0,0,0)
base.books.AddEnglishBookText("Two days later Cube is killed by the gods.",0,0,0)
base.books.AddEnglishBookText("On november, the 14th Purple Dragons officialy start to search for members.",0,0,0)
base.books.AddEnglishBookText("They pray to the king of the Dragonland and believe to a Time of Change where every member becomes a dragon.",0,0,0)
base.books.AddEnglishBookText("On november, the 17th the School of Combat starts to search for members.",0,0,0)
base.books.AddEnglishBookText("On november, the 18th Dyluck organizes a great concert at the terasse of the library.",0,0,0)
base.books.AddEnglishBookText("The artists are Badmosche, Xaveria, Treason, Cosmaterra, Dyluck and as a special guest Necrophotius Fungius with a mockery song against Cube.",0,0,0)
base.books.AddEnglishBookText("It was a wonderful evening.",0,0,0)
base.books.AddEnglishBookText("Only one controversy happend between two couples: Dyluck and Sabrina against Olorin and Galadria.",0,0,0)
base.books.AddEnglishBookText("On november, the 20th Drakhen Vorkalion attacked Troll's Bane in the search of Aragon.",0,0,0)
base.books.AddEnglishBookText("Drakhen want to use Aragon for his own purposes because Aragon was born in a old priest family of Malachin.",0,0,0)
base.books.AddEnglishBookText("When Aragon was a baby he was blessed by the bonelord Cherass through Drakhen and both forces fight in his body.",0,0,0)
base.books.AddEnglishBookText("An old prophecy found by Damien helped Aragon.",0,0,0)
base.books.AddEnglishBookText("On november, the 20th Damien finds the rests of a dark ritual with a curse over all loving people through Drakhen Vorkalion, probably during the concert.",0,0,0)
base.books.AddEnglishBookText("Because of the curse Sabrina dont want to have any human as husband and Dyluck wants to deliver Aragon to Drakhen.",0,0,0)
base.books.AddEnglishBookText("As return he wants to become the life of an elf.",0,0,0)
base.books.AddEnglishBookText("A helper Siranis can stop Dyluck.",0,0,0)
base.books.AddEnglishBookText("On november, the 20th Sean founded the Praetorian Guards and bid other guilds for some help.",0,0,0)
base.books.AddEnglishBookText("On november, the 27th Jean Long organizes a celebration to Sirani.",0,0,0)
base.books.AddEnglishBookText("The curse of Drakhen breakes.",0,0,0)
base.books.AddEnglishBookText("On november, the 26th Sean, leader of the Praetorian Guards want to speak to every guildleader of Illarion.",0,0,0)
base.books.AddEnglishBookText("The reason of this meeting is unclearly.",0,0,0)
base.books.AddEnglishBookText("On november, the 27th Aragon meets Drakhen again.",0,0,0)
base.books.AddEnglishBookText("Drakhen lost the fight because of Franjel Salem Longs and Sir Ganons that helped Aragon.",0,0,0)
base.books.AddEnglishBookText("After this Aragon becomes a true priest of Malachin because of a ghostjourney to Chergas realm to solve the curse of Cherass.",0,0,0)
base.books.AddEnglishBookText("On november, the 29th the Rangers and the School of Combat fousion together.",0,0,0)
base.books.AddEnglishBookText("On december, the 1st Rendar leaves his position as a leader of Zelphia Shrine to Dragonclaw.",0,0,0)
base.books.AddEnglishBookText("On december, the 3rd a sniper murders someone in the library.",0,0,0)
base.books.AddEnglishBookText("Dyluck suspected Sean.",0,0,0)
base.books.AddEnglishBookText("The attack is still inexplicably.",0,0,0)
base.books.AddEnglishBookText("On december, the 7th Galadria decided to become a priestess of Sirani and build a shrine.",0,0,0)
base.books.AddEnglishBookText("Other priests of Sirani are Jean Long, Xaveria and Rhandarjia.",0,0,0)
base.books.AddEnglishBookText("On december, the 7th Drunk Mage Dipstick explained to work as an assasin.",0,0,0)
base.books.AddEnglishBookText("Two weaks later he surrenders.",0,0,0)
base.books.AddEnglishBookText("On december, the 9th the Grey Rose celebrate a party for Malachin for the happy end of Aragons happenings.",0,0,0)
base.books.AddEnglishBookText("Aragon get engaged with Lillith.",0,0,0)
base.books.AddEnglishBookText("On december, the 10th the Riders of Moshran unter Tal Rash starts a war against the priests of Zelphia.",0,0,0)
base.books.AddEnglishBookText("A time of uncertainty begins in town.",0,0,0)
base.books.AddEnglishBookText("With help of the Grey Rose Tal Rash and Dipstick get killed at a great battle on 18th of december.",0,0,0)
base.books.AddEnglishBookText("On december, the 12th the Rangers under Astral starts a war against the Dark Mages under Sir Crystal Star.",0,0,0)
base.books.AddEnglishBookText("On december, the 14th Pasha starts a magazine for Illarion but after a few days he get it up.",0,0,0)
base.books.AddEnglishBookText("On december, the 15th Dyluck fishes a half past dead Fisherman out of the sea.",0,0,0)
base.books.AddEnglishBookText("His name is Rogarian and comes from the land Romada which is lead by the land Edin.",0,0,0)
base.books.AddEnglishBookText("On the middle of december the parents of Lillith speak against a marriage with Aragon and do a ritual with her daughter that theft all her fealing for Aragon.",0,0,0)
base.books.AddEnglishBookText("Galadria helps Lillith and Jean Long helps Aragon.",0,0,0)
base.books.AddEnglishBookText("On december, the 19th Sean starts a war against the Riders of Moshran.",0,0,0)
base.books.AddEnglishBookText("On december, the 20th Dyluck had the idea to start some competitions.",0,0,0)
base.books.AddEnglishBookText("They never happend.",0,0,0)
base.books.AddEnglishBookText("On december, the 22th Thorfin Skull Spliter started a guild that prays to the god Bragon.",0,0,0)
base.books.AddEnglishBookText("On december, the 23th Dragonsoul starts the guild The Crimson Dragon.",0,0,0)
base.books.AddEnglishBookText("He never found members and will only last until january.",0,0,0)
base.books.AddEnglishBookText("On end of december Spaniard and his group of terrorists attack the town with sniperattacks.",0,0,0)
base.books.AddEnglishBookText("They where hunted by the Rangers and Dyluck.",0,0,0)
base.books.AddEnglishBookText("Marlene and her group also terrorised the town with attacks.",0,0,0)
base.books.AddEnglishBookText("They where hunted by the Grey Rose.",0,0,0)
base.books.AddEnglishBookText("On december, the 29th Roke and Sean startet a big guildadvice.",0,0,0)
base.books.AddEnglishBookText("As leader Aragon wanted Damien and he was common accepted.",0,0,0)
base.books.AddEnglishBookText("Under this lead they worked some standarts out.",0,0,0)
base.books.AddEnglishBookText("Damien, Dyluck, Astral, Roke, Tialdin and Aragon helped.",0,0,0)
base.books.AddEnglishBookText("After this standart following guilds become two seats in this advice: Grey Light, Grey Rose, Magic Academy and the following one seat: Ironhammers, Titans, Rangers, School of Combat.",0,0,0)
base.books.AddEnglishBookText("Because of Erdricks asks the Silver Star Merchants become one seat, too at the 29th of january.",0,0,0)
base.books.AddEnglishBookText("A second meeting in the middle of january accepts this standarts.",0,0,0)
base.books.AddEnglishBookText("Some controversys and fights made Sean and the Peace Keepers to close the guildadvice.",0,0,0)
base.books.AddEnglishBookText("On december, the 30th Balderion starts the Order of the flaming fist.",0,0,0)
base.books.AddEnglishBookText("On december, the 31th Drakhen Vorkalion attacks Troll's Bane again.",0,0,0)
base.books.AddEnglishBookText("Erdrick told about all the lost souls that where with Drakhen and could not be reincarnated.",0,0,0)
base.books.AddEnglishBookText("On december, the 31th Drunk Mage Dipstick and Spaniard closed the Servants of Darkness.",0,0,0)

          end
      end
      base.books.SendBookPage(User,SourceItem.data,Counter);
      User:learn(4,"library research",2,100)
  end
 
  function LookAtItem(User,Item)
      if base.books.InitTitle() then
         base.books.AddGermanBookTitle("Buch mit dem Titel \"Die Chroniken Illarions I\"",0);
         base.books.AddEnglishBookTitle("Book with the title \"The Illarion Chronicles I\"",0);
      end
      base.books.GetBookItemInform(User,Item);
  end
