-- triggerfields for better atmosphere

--[[ SQL Statements:
INSERT INTO triggerfields VALUES (X,Y,Z,'triggerfield.ambient');

]]

require("base.common")

module("triggerfield.ambient", package.seeall)

--[[
position: coordinates
direction: array with directions, 0=North,2=East,4=South,6=West. Set nil for always
german/english: text
hours: array with hours when text shall be shown, in range of 0 to 23. Set to nil for always.
months: array with months when text shall be shown, in range of 1 to 16. Set to nil for always.
chance: Chance that this triggerfield is triggered in percent (integer)

for script:
AmbientList:add( position(x,y,z), {0,1,7}, "german", "english", {0,1,23}, {1,2,16}, chance );

for db:
INSERT INTO triggerfields VALUES (x,y,z,'triggerfield.ambient');

Old stuff:

-62,-124,0), 4, "Du betrittst den Raum und merkst sofort, dass es zieht. Ein Mann auf einem der St?hle blickt sich ungeduldig um.", "You enter the room and immediately notice that there is draught. A man on one of the chairs looks around impatient.", {8,9,10,11,12,13,14,15,16,17,18,19,20,21}, {9,10,11,12} );
-62,-124,0), 4, "Es ist ziemlich warm im Raum, man sollte hier mal l?ften. Hinter der Theke steht eine g?hnende Echse, auf einem der St?hle schnarcht ein Mann vor sich hin.", "It is quite warm in the room, someone should open the windows. Behind the shop counter stands a yawning lizard, on one of the chairs you see a snoring man.", {22,23,0,1,2,3,4,5,6,7}, {5,6,7,8} );
-62,-124,0), 4, "Im Raum ist es etwas w?rmer als drau?en, du frierst aber trotzdem etwas. An der Theke steht eine Echse, die in einen dicken Mantel geh?llt ist.", "It's a little bit warmer inside than outside, but you still feel cold. At the shop counter stands a lizard, who wears a warm coat.", {8,9,10,11,12,13,14,15,16,17,18,19,20,21}, {13,14,15,16} );
-62,-124,0), 4, "In dieser Herbstnacht ist es ruhig im Laden. Wenn du umhergehst knarrt der Boden unter deinen F??en.", "This night, it is very quite in the shop. As you walk around the floor under your feets creaks a little.", {22,23,0,1,2,3,4,5,6,7}, {9,10,11,12} );
-62,-125,0), 0, "Der Boden im Raum ist nass, hier suchen wohl viele Leute Unterschlupf, wenn es regnet. Die Stimmung unter den H?ndlern scheint genau so schlecht zu sein wie das Wetter.", "The floor in the room is wet, it seems that many people seek shelter in here when it rains. The mood of the merchants appears to be as bad as the weather.", {8,9,10,11,12,13,14,15,16,17,18,19,20,21}, {9,10,11,12} );
-62,-125,0), 0, "Der Schnee glitzert durch die Fenster und bringt den Raum zum Leuchten. Es riecht nach Wintergeb?ck, die H?ndler sind in guter Stimmung.", "The glittering snow outside lights up the whole room. You can smell winter pastry, the merchants are in a very good mood.", {8,9,10,11,12,13,14,15,16,17,18,19,20,21}, {13,14,15,16} );
-62,-125,0), 0, "Sofort als du durch die T?r trittst, nimmst du die verschiedensten D?fte wahr, einige Kaufleute unterhalten sich, andere sortieren ihre Waren.", "As you go through the door, you immediately notice different fragrances, some merchants are having a conversation, others are sorting their goods.", {8,9,10,11,12,13,14,15,16,17,18,19,20,21}, {1,2,3,4} );
-62,-125,0), 0, "Vor dir steht ein reich gekleideter Mann, hinter dem einige Truhen randgef?llt mit Gold zu erkennen sind. Er sieht dich misstrauisch an.", "The man in front of you is clad in fine clothes, behind him you see many chests filled to the brim with gold. He eyes you suspiciously.", {8,9,10,11,12,13,14,15,16,17,18,19,20,21}, {5,6,7,8} );
-64,-129,0), 2, "Auch das Markthaus bleibt vom Winter nicht verschont: Der Raum ist eiskalt, du solltest deinen Mantel umwerfen, bevor du dich erk?ltest.", "Not even the shops can escape winter: It is icecold in here. You should put on your coat or you will get a cold.",  {22,23,0,1,2,3,4,5,6,7}, {13,14,15,16} );
-64,-129,0), 2, "Der Boden im Raum ist nass, hier suchen wohl viele Leute Unterschlupf, wenn es regnet. Die Stimmung unter den H?ndlern scheint genau so schlecht zu sein wie das Wetter.", "The floor in the room is wet, it seems that many people seek shelter in here when it rains. The mood of the merchants appears to be as bad as the weather.", {8,9,10,11,12,13,14,15,16,17,18,19,20,21}, {9,10,11,12} );
-64,-129,0), 2, "Der Schnee glitzert durch die Fenster und bringt den Raum zum Leuchten. Es riecht nach Wintergeb?ck, die H?ndler sind in guter Stimmung.", "The glittering snow outside lights up the whole room. You can smell winter pastry, the merchants are in a very good mood.", {8,9,10,11,12,13,14,15,16,17,18,19,20,21}, {13,14,15,16} );
-64,-129,0), 2, "Die n?chtliche Luft im Herbst scheint es den H?ndlern angetan zu haben, sie haben alle Fenster sperrangelweit offen. Im hinteren Teil des Raumes sitzt ein strickender Mann auf der Theke.", "The merchants seem to like the fresh air, all windows are opened. In the back of the room, someone sits on a counter knitting.",  {22,23,0,1,2,3,4,5,6,7}, {9,10,11,12} );
-64,-129,0), 2, "Es ist nicht mehr viel los im Raum, die meisten H?ndler bauen gerade ihre St?nde ab und reden nochmal ?ber den Tag.", "Not much is going on in the room. Most of the merchants are packing their bags and summing up the day.", {22,23,0,1,2,3,4,5,6,7}, {1,2,3,4} );
-64,-129,0), 2, "Hier drin riecht es nach den verschiedensten Sachen. Einige Kaufm?nner sind noch immer hier und preisen ihre Waren an.", "You smell the most different things in here. Some merchants are still touting for their goods.", {22,23,0,1,2,3,4,5,6,7}, {5,6,7,8} );
-64,-129,0), 2, "Links von dir steht ein reich gekleideter Mann, hinter dem einige Truhen randgef?llt mit Gold zu erkennen sind. Er sieht dich misstrauisch an.", "The man to the left of you is clad in fine clothes, behind him you see many chests filled to the brim with gold. He eyes you suspiciously.", {8,9,10,11,12,13,14,15,16,17,18,19,20,21}, {5,6,7,8} );
-64,-129,0), 2, "Sofort als du durch die T?r trittst, nimmst du die verschiedensten D?fte wahr, einige Kaufleute unterhalten sich, andere sortieren ihre Waren.", "As you go through the door, you immediately notice different fragrances, some merchants are having a conversation, others are sorting their goods.", {8,9,10,11,12,13,14,15,16,17,18,19,20,21}, {1,2,3,4} );
-66,-116,0), 0, "Auch das Markthaus bleibt vom Winter nicht verschont: Der Raum ist eiskalt, du solltest deinen Mantel umwerfen, bevor du dich erk?ltest.", "Not even the shops can escape winter: It is icecold in here. You should put on your coat or you will get a cold.", {22,23,0,1,2,3,4,5,6,7}, {13,14,15,16} );
-66,-116,0), 0, "Die n?chtliche Luft im Herbst scheint es den H?ndlern angetan zu haben, sie haben alle Fenster sperrangelweit offen. Im hinteren Teil des Raumes sitzt ein strickender Mann auf der Theke.", "The merchants seem to like the fresh air, all windows are opened. In the back of the room, someone sits on a counter knitting.", {22,23,0,1,2,3,4,5,6,7}, {9,10,11,12} );
-66,-116,0), 0, "Es ist nicht mehr viel los im Raum, die meisten H?ndler bauen gerade ihre St?nde ab und reden nochmal ?ber den Tag.", "Not much is going on in the room. Most of the merchants are packing their bags and summing up the day.", {22,23,0,1,2,3,4,5,6,7}, {1,2,3,4} );
-66,-116,0), 0, "Hier drin riecht es nach den verschiedensten Sachen. Einige Kaufm?nner sind noch immer hier und preisen ihre Waren an.", "You smell the most different things in here. Some merchants are still touting for their goods.", {22,23,0,1,2,3,4,5,6,7}, {5,6,7,8} );
-66,-116,0), 2, "Die Nacht ist kalt. An die Theke gelehnt steht eine schnarchende Echse, die sich ab und zu nach Kunden umsieht.", "The night is cold. Leaned at the shop counter is a snoring lizard, who sometimes looks around for customers.", {22,23,0,1,2,3,4,5,6,7}, {1,2,3,4} );
-66,-116,0), 2, "Du betrittst den Raum und merkst sofort, dass es zieht. Ein Mann auf einem der St?hle blickt sich ungeduldig um.", "You enter the room and immediately notice that there is draught. A man on one of the chairs looks around impatient.", {8,9,10,11,12,13,14,15,16,17,18,19,20,21}, {9,10,11,12} );
-66,-116,0), 2, "Es ist ziemlich warm im Raum, man sollte hier mal l?ften. Hinter der Theke steht eine g?hnende Echse, auf einem der St?hle schnarcht ein Mann vor sich hin.", "It is quite warm in the room, someone should open the windows. Behind the shop counter stands a yawning lizard, on one of the chairs you see a snoring man.", {22,23,0,1,2,3,4,5,6,7}, {5,6,7,8} );
-66,-116,0), 2, "Im Raum ist es etwas w?rmer als drau?en, du frierst aber trotzdem etwas. An der Theke steht eine Echse, die in einen dicken Mantel geh?llt ist.", "It's a little bit warmer inside than outside, but you still feel cold. At the shop counter stands a lizard, who wears a warm coat.", {8,9,10,11,12,13,14,15,16,17,18,19,20,21}, {13,14,15,16} );
-66,-116,0), 2, "In dieser Herbstnacht ist es ruhig im Laden. Wenn du umhergehst knarrt der Boden unter deinen F??en.", "This night, it is very quite in the shop. As you walk around the floor under your feets creaks a little.", {22,23,0,1,2,3,4,5,6,7}, {9,10,11,12} );
-86,-99,-3), 6, "Du verl?sst den Schankraum und steigst die knarrende Treppe in den k?hlen Keller hinab. Deine Augen gew?hnen sich langsam an die Dunkelheit.", "You leave the taproom and steps down the creaking stairs to the cool, dark cellar. Your eyes start adapting to the darkness slowly.", nil, nil );
-88,-116,1), 6, "Beim Betreten des Raumes fallen Dir die gedeckten Tische auf. Sie laden zum Verweilen ein.", "As you walk in the room, the set table catch your eyes. They invite to take a rest.", nil, nil );
-89,-90,0), 2, "Du betrittst die Taverne und sogleich umh?llt dich wohlige W?rme und der Geruch von starkem Bier str?mt in deine Nase.", "You are walking in the tavern and instantly the warmth encloses you and the smell of strong beer pours into your nose.", nil, nil );
-91,-115,0), 2, "Du betrittst den Altarraum und heute sp?rst du die g?ttliche Stille noch st?rker als sonst. Die G?tter stehen dir im Mas bei.", "You walk into the sanctuary and instantly you feel the divine silence stronger then otherwise. The gods stand by you in the time of Mas.", nil, {16} );
-91,-115,0), 2, "Du betrittst den Altarraum und sofort sp?rst du etwas wie g?ttliche Inspiration und g?ttliche Stille.", "You walk into the sanctuary and instantly you feel something like afflatus and divine silence.", nil, {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15} );
-94,-123,1), 4, "Beim Betreten des Raumes fallen Dir die gedeckten Tische auf. Sie laden zum Verweilen ein.", "As you walk in the room, the set table catch your eyes. They invite to take a rest.", nil, nil );
-94,-127,0), 2, "Du betrittst die Bibliothek und sofort umh?llt dich die Stille. Vereinzelt h?rst du raschelnde Pergamente.", "You walk in the libary and instantly silence surrounds you. Sporadicly you hear crinkly parchments.", nil, nil );
-95,-94,0), 0, "Du betrittst die Taverne und sogleich umh?llt dich wohlige W?rme und der Geruch von starkem Bier str?mt in deine Nase.", "You are walking in the tavern and instantly the warmth encloses you and the smell of strong beer pours into your nose.", nil, nil );
110,-200,-3), 6, "Dir schl?gt eine Hitze entgegen, die ihren Ursprung wohl bei den drei Heiz?fen hat. Die Ambosse sehen sehr abgenutzt aus und die Esse ist bedeckt von Ru?. Es ist sehr stickig und der Geruch von verbrannter Kohle liegt in der Luft.", "Some hot air streams straight into your face, probably coming from the three heat ovens. The anvils look quite used up and the forge is covered under a layer of ash. It is very stuffy and the smell of burned coal is in the air.", {nil}, {1,2,3,4,5,6,7,8,9,10,11,12} );
110,-200,-3), 6, "Nach der K?lte drau?en schl?gt dir hier eine angenehme W?rme entgegen, die ihren Ursprung wohl bei den drei Heiz?fen hat. Die Ambosse sehen sehr abgenutzt aus und die Esse ist bedeckt von Ru?. Es ist sehr stickig und der Geruch von verbrannter Kohle liegt in der Luft.", "After the coldness outside, you like the warm air, streaming your face, probably coming from the three heat ovens. The anvils look quite used up and the forge is covered under a layer of ash. It is very stuffy and the smell of burned coal is in the air", {nil}, {13,14,15,16} );
111,-200,-3), 6, "Dir schl?gt eine Hitze entgegen, die ihren Ursprung wohl bei den drei Heiz?fen hat. Die Ambosse sehen sehr abgenutzt aus und die Esse ist bedeckt von Ru?. Es ist sehr stickig und der Geruch von verbrannter Kohle liegt in der Luft.", "Some hot air streams straight into your face, probably coming from the three heat ovens. The anvils look quite used up and the forge is covered under a layer of ash. It is very stuffy and the smell of burned coal is in the air.", {nil}, {1,2,3,4,5,6,7,8,9,10,11,12} );
111,-200,-3), 6, "Nach der K?lte drau?en schl?gt dir hier eine angenehme W?rme entgegen, die ihren Ursprung wohl bei den drei Heiz?fen hat. Die Ambosse sehen sehr abgenutzt aus und die Esse ist bedeckt von Ru?. Es ist sehr stickig und der Geruch von verbrannter Kohle liegt in der Luft.", "After the coldness outside, you like the warm air, streaming your face, probably coming from the three heat ovens. The anvils look quite used up and the forge is covered under a layer of ash. It is very stuffy and the smell of burned coal is in the air", {nil}, {13,14,15,16} );
156,-433,0), 0,"Als du die H?hle betrittst, ist es dir als l?ufst du gegen eine k?hle unsichtbare Wand aus Luft die deinen K?rper in eiskaltes Wasser zu tauchen scheint. Beisender Rauch und der Gestank verdorbenen Fleisches durchdringen die Luft.","As you enter the cave you are met with an invisible wall of cold air, it feels like submerging your body in ice cold water after being burned by fire. The smell of smoke and decaying meat is overpowering",nil, {1,2,3,4,5,6,7,8,9,10,11,12} );
156,-433,0), 0,"Die W?rme in der H?hle vertreibt gem?chlich die K?lte aus deinen Gliedern und l?sst den Schnee auf deinen Schultern schmelzen. Der Geruch, ger?steten und ger?ucherten Fleisches steigt dir in die Nase."," The warm air inside the cave slowly thaws the snow and cold from your body, the stench of roasted meat and smoke fills your nostriles. ",nil, {13,14,15,16} );
156,-433,0), 4,"Als du ins Freie trittst, knacken die unz?hligen vereisten Stellen am Boden vor der H?hle unter deinen F??en. Die eisige Luft scheint dir die Brust zu verschn?ren und das Atmen f?llt dir schwer. Bald bemerkst du, dass deine Haare allm?hlich vereisen. ","A thin carpet of frost smoke covers the frozen ground, the soft cracking of ice is heard comming from above. The cold air fills your lungs with every breath you take making it hard to breath for a few moments as you get used to the biting cold air.",{19,20,21,22,23,0,1,2,3,4}, {13,14,15,16} );
156,-433,0), 4,"Angenehm warme Bergluft l?dt dich ein, kr?ftig durch zu atmen. In der Ferne l?sst sich manch mal das Br?llen eines l?ufigen Panthers vernehmen. ","The pleasing mountain air invites you to take a deep breath. Sometimes you hear the growl of a panther on the prowl. ",{5,6,7,8,9,10,11,12,13,14,15,16,17,18}, {1,2,3,4,5,6,7,8,9,10,11,12} );
156,-433,0), 4,"Trotz der Finsternis ist es noch angenehm Warm drau?en. Unz?hlige Grillen zirpen im hohen Gras auf dem Plateau. ","Despite the darkness it is pleasingly warm outside. Countless crickets chirr in the high grass on the plateu.",{19,20,21,22,23,0,1,2,3,4}, {1,2,3,4,5,6,7,8,9,10,11,12} );
157,-200,-6), 2, "In der Gruft riecht es abgestanden und modrig. Die W?nde sind mit uralten Zwergenrunen versehen. Es ist kalt und feucht hier untem im Berg, soweit weg von allem W?rmequellen. ", "In the crypt it smells moldy. On the walls you can see ancient dwarven runes. It is cold and clammy down here, far away from all sources of heat.", {nil}, {nil} );
157,-433,0), 0,"Als du die H?hle betrittst, ist es dir als l?ufst du gegen eine k?hle unsichtbare Wand aus Luft die deinen K?rper in eiskaltes Wasser zu tauchen scheint. Beisender Rauch und der Gestank verdorbenen Fleisches durchdringen die Luft.","As you enter the cave you are met with an invisible wall of cold air, it feels like submerging your body in ice cold water after being burned by fire. The smell of smoke and decaying meat is overpowering",nil, {1,2,3,4,5,6,7,8,9,10,11,12} );
157,-433,0), 0,"Die W?rme in der H?hle vertreibt gem?chlich die K?lte aus deinen Gliedern und l?sst den Schnee auf deinen Schultern schmelzen. Der Geruch, ger?steten und ger?ucherten Fleisches steigt dir in die Nase."," The warm air inside the cave slowly thaws the snow and cold from your body, the stench of roasted meat and smoke fills your nostriles. ",nil, {13,14,15,16} );
157,-433,0), 4,"Als du ins Freie trittst, knacken die unz?hligen vereisten Stellen am Boden vor der H?hle unter deinen F??en. Die eisige Luft scheint dir die Brust zu verschn?ren und das Atmen f?llt dir schwer. Bald bemerkst du, dass deine Haare allm?hlich vereisen. ","A thin carpet of frost smoke covers the frozen ground, the soft cracking of ice is heard comming from above. The cold air fills your lungs with every breath you take making it hard to breath for a few moments as you get used to the biting cold air.",{19,20,21,22,23,0,1,2,3,4}, {13,14,15,16} );
157,-433,0), 4,"Angenehm warme Bergluft l?dt dich ein, kr?ftig durch zu atmen. In der Ferne l?sst sich manch mal das Br?llen eines l?ufigen Panthers vernehmen. ","The pleasing mountain air invites you to take a deep breath. Sometimes you hear the growl of a panther on the prowl. ",{5,6,7,8,9,10,11,12,13,14,15,16,17,18}, {1,2,3,4,5,6,7,8,9,10,11,12} );
157,-433,0), 4,"Die eisige Luft, verwandelt deinen Atem in eine nebelige Schwade. Bei jedem Atemzug scheint sich deine Lunge zu verkrampfen und du ben?tigst einige Zeit, bis dein K?rper sich an die K?lte gew?hnt hat. Langsam beginnen deine Haare zu vereisen. ","The crisp cold air makes the sweat on your nostriles and forehead freeze instantly, it is difficult to breath for a few moments as your body gets used to the biting cold outside. ",{5,6,7,8,9,10,11,12,13,14,15,16,17,18}, {13,14,15,16} );
157,-433,0), 4,"Trotz der Finsternis ist es noch angenehm Warm drau?en. Unz?hlige Grillen zirpen im hohen Gras auf dem Plateau. ","Despite the darkness it is pleasingly warm outside. Countless crickets chirr in the high grass on the plateu.",{19,20,21,22,23,0,1,2,3,4}, {1,2,3,4,5,6,7,8,9,10,11,12} );
158,-200,-6), 2, "In der Gruft riecht es abgestanden und modrig. Die W?nde sind mit uralten Zwergenrunen versehen. Es ist kalt und feucht hier untem im Berg, soweit weg von allem W?rmequellen. ", "In the crypt it smells moldy. On the walls you can see ancient dwarven runes. It is cold and clammy down here, far away from all sources of heat.", {nil}, {nil} );
170,-194,-3), 0, "Der Geruch von Pergament dringt dir in die Nase. Die meisten B?cher in den Regalen sind verstaubt. In der Ecke liegen einige zusammengekn?llte Bl?tter. ", "The smell of pergament comes into your nose. Most of the books in the cupboard are dusty. In one corner there are waded papers.", {nil}, {nil} );
187,-443,1), 2,"Angenehm warme Bergluft l?dt dich ein, kr?ftig durch zu atmen. In der Ferne l?sst sich manch mal das Br?llen eines l?ufigen Panthers vernehmen. ","The pleasing mountain air invites you to take a deep breath. Sometimes you hear the growl of a panther on the prowl. ",{5,6,7,8,9,10,11,12,13,14,15,16,17,18}, {1,2,3,4,5,6,7,8,9,10,11,12} );
187,-443,1), 2,"Die eisige Luft, verwandelt deinen Atem in eine nebelige Schwade. Bei jedem Atemzug scheint sich deine Lunge zu verkrampfen und du ben?tigst einige Zeit, bis dein K?rper sich an die K?lte gew?hnt hat. Langsam beginnen deine Haare zu vereisen. ","The crisp cold air makes the sweat on your nostriles and forehead freeze instantly, it is difficult to breath for a few moments as your body gets used to the biting cold outside. ",{5,6,7,8,9,10,11,12,13,14,15,16,17,18}, {13,14,15,16} );
187,-443,1), 2,"Trotz der Finsternis ist es noch angenehm Warm drau?en. Unz?hlige Grillen zirpen im hohen Gras auf dem Plateau. ","Despite the darkness it is pleasingly warm outside. Countless crickets chirr in the high grass on the plateu.",{19,20,21,22,23,0,1,2,3,4}, {1,2,3,4,5,6,7,8,9,10,11,12} );
187,-443,1), 6,"Als du die H?hle betrittst, ist es dir als l?ufst du gegen eine k?hle unsichtbare Wand aus Luft die deinen K?rper in eiskaltes Wasser zu tauchen scheint. Beisender Rauch und der Gestank verdorbenen Fleisches durchdringen die Luft.","As you enter the cave you are met with an invisible wall of cold air, it feels like submerging your body in ice cold water after being burned by fire. The smell of smoke and decaying meat is overpowering",nil, {1,2,3,4,5,6,7,8,9,10,11,12} );
187,-443,1), 6,"Die W?rme in der H?hle vertreibt gem?chlich die K?lte aus deinen Gliedern und l?sst den Schnee auf deinen Schultern schmelzen. Der Geruch, ger?steten und ger?ucherten Fleisches steigt dir in die Nase."," The warm air inside the cave slowly thaws the snow and cold from your body, the stench of roasted meat and smoke fills your nostriles. ",nil, {13,14,15,16} );
187,-444,1), 2,"Als du ins Freie trittst, knacken die unz?hligen vereisten Stellen am Boden vor der H?hle unter deinen F??en. Die eisige Luft scheint dir die Brust zu verschn?ren und das Atmen f?llt dir schwer. Bald bemerkst du, dass deine Haare allm?hlich vereisen. ","A thin carpet of frost smoke covers the frozen ground, the soft cracking of ice is heard comming from above. The cold air fills your lungs with every breath you take making it hard to breath for a few moments as you get used to the biting cold air.",{19,20,21,22,23,0,1,2,3,4}, {13,14,15,16} );
187,-444,1), 2,"Angenehm warme Bergluft l?dt dich ein, kr?ftig durch zu atmen. In der Ferne l?sst sich manch mal das Br?llen eines l?ufigen Panthers vernehmen. ","The pleasing mountain air invites you to take a deep breath. Sometimes you hear the growl of a panther on the prowl. ",{5,6,7,8,9,10,11,12,13,14,15,16,17,18}, {1,2,3,4,5,6,7,8,9,10,11,12} );
187,-444,1), 2,"Die eisige Luft, verwandelt deinen Atem in eine nebelige Schwade. Bei jedem Atemzug scheint sich deine Lunge zu verkrampfen und du ben?tigst einige Zeit, bis dein K?rper sich an die K?lte gew?hnt hat. Langsam beginnen deine Haare zu vereisen. ","The crisp cold air makes the sweat on your nostriles and forehead freeze instantly, it is difficult to breath for a few moments as your body gets used to the biting cold outside. ",{5,6,7,8,9,10,11,12,13,14,15,16,17,18}, {13,14,15,16} );
187,-444,1), 2,"Trotz der Finsternis ist es noch angenehm Warm drau?en. Unz?hlige Grillen zirpen im hohen Gras auf dem Plateau. ","Despite the darkness it is pleasingly warm outside. Countless crickets chirr in the high grass on the plateu.",{19,20,21,22,23,0,1,2,3,4}, {1,2,3,4,5,6,7,8,9,10,11,12} );
187,-444,1), 6,"Als du die H?hle betrittst, ist es dir als l?ufst du gegen eine k?hle unsichtbare Wand aus Luft die deinen K?rper in eiskaltes Wasser zu tauchen scheint. Beisender Rauch und der Gestank verdorbenen Fleisches durchdringen die Luft.","As you enter the cave you are met with an invisible wall of cold air, it feels like submerging your body in ice cold water after being burned by fire. The smell of smoke and decaying meat is overpowering",nil, {1,2,3,4,5,6,7,8,9,10,11,12} );
187,-444,1), 6,"Die W?rme in der H?hle vertreibt gem?chlich die K?lte aus deinen Gliedern und l?sst den Schnee auf deinen Schultern schmelzen. Der Geruch, ger?steten und ger?ucherten Fleisches steigt dir in die Nase."," The warm air inside the cave slowly thaws the snow and cold from your body, the stench of roasted meat and smoke fills your nostriles. ",nil, {13,14,15,16} );

]]


AmbientList = {	add = function ( self, pos, direction, german, english, hours, months, chance )
						if not self[pos.x] then
							self[pos.x] = {};
						end
						if not self[pos.x][pos.y] then
							self[pos.x][pos.y] = {};
						end
						if not self[pos.x][pos.y][pos.z] then
							self[pos.x][pos.y][pos.z] = {};
						end
						local this = self[pos.x][pos.y][pos.z];
						table.insert(this, {
                            direction = direction or {0,1,2,3,4,5,6,7};
							german = german or "";
							english = english or "";
							hours = hours or {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23};
							months = months or {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16};
                            chance = chance or 100;
							} );
				end
}

--SW map by Estralis et al.

AmbientList:add( position(93,587,0),nil,"In der Ferne hörst du das Bellen eines Hundes.","In the distance, you can hear a barking dog.",nil,nil,1); --General Cadomyr
AmbientList:add( position(105,569,0),nil,"Ein scharfer Wind bläßt durch die Straßen Cadomyrs.","A strong wind blows in the streets of Cadomyr.",nil,nil,1); --General Cadomyr
AmbientList:add( position(121,551,0),nil,"Überall um dich herum spürst du den Stolz und die Ehre Cadomyrs.","All around you, you can feel the pride and honour of Cadomyr.",nil,nil,1); --General Cadomyr
AmbientList:add( position(130,587,0),nil,"In der Ferne hörst du Gelächter.","In the distance, you can hear laughter.",nil,nil,1); --General Cadomyr
AmbientList:add( position(130,606,0),nil,"Ein Hund bellt irgendwo im Norden. Oder ist es ein schnarchender Ork?","A dog barks in the north. Or was that a snoring orc?",nil,nil,1); --General Cadomyr
AmbientList:add( position(121,565,0),nil,"Die Wüstenblume Cadomyr erscheint heute in besonderer Blüte zu stehen.","The desert flower Cadomyr seems to blossom in a special way today.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,1); --General Cadomyr, daylight
AmbientList:add( position(251,528,0),nil,"Deine Füße hinterlassen flache Eindrücke im weichen Sand.","Your feet make shallow imprints into the shifting sand.",nil,nil,10); --General desert
AmbientList:add( position(259,570,0),nil,"Der Wind bläßt dir Sandkörner ins Gesicht.","The wind blows sand grains at your face.",nil,nil,10); --General desert
AmbientList:add( position(263,598,0),nil,"Die Sandlandschaft ist hier flach und eintönig, die Orientierung fällt dir schwer.","The sandy ground is flat, with no obvious landmarks. Judging distances becomes difficult.",nil,nil,10); --General desert
AmbientList:add( position(264,631,0),nil,"Ein starker Wind bläßt über die Dünen.","A strong wind blows in the dunes.",nil,nil,10); --General desert
AmbientList:add( position(298,677,0),nil,"Eine plötzliche Windböe blößt dir Sand ins Gesicht. Die Tränen schießen dir in die Augen und du reibst sie ausgiebig.","A sudden gust of wind blows sand into your face. Tears flood your eyes and you rub them profusely. ",nil,nil,10); --General desert
AmbientList:add( position(331,537,0),nil,"Der Sand knirscht unter deinen Füßen.","The sand gnashes under your feet.",nil,nil,10); --General desert
AmbientList:add( position(336,563,0),nil,"Vor dir erstrecken sich die Dünen, so weit das Auge reicht.","The dunes ahead of you seem to stretch endlessly",nil,nil,10); --General desert
AmbientList:add( position(348,710,0),nil,"Warmer Wind bläst durch die Wüste und Geheul ist in der Ferne zu hören.","A warm wind blows across the desert, and howls can be heard in the distance.",nil,nil,10); --General desert
AmbientList:add( position(349,576,0),nil,"Du wirst das Gefühl nicht los, dass dich jemand beobachtet.","You struggle to ignore the strange feeling that you are being watched. ",nil,nil,10); --General desert
AmbientList:add( position(365,619,0),nil,"Ein scharfer Wind wirbelt den Sand um dich herum auf als du dich dem Herz der Wüste Katanbi näherst.","The fierce wind bellows and blows the sand wildy around you, as you enter the heart of the Katanbi desert.",nil,nil,10); --General desert
AmbientList:add( position(400,709,0),nil,"Nach dem anstrengenden Marsch durch feinen Sand mutet es regelrecht erfrischend an, wieder festen Boden unter den Füßen zu haben. ","After the exhausting hike through the fine-grained sand, standing on solid ground again feels downright refreshing.",nil,nil,10); --General desert
AmbientList:add( position(402,707,0),nil,"Beim Umherstreifen in der Wüste rinnt dir immer wieder etwas Sand ins Schuhwerk und scheuert zwischen deinen Zehen. ","Whilst roaming the desert, sand trickles through your footgear over and over again, rubbing between your toes. ",nil,nil,10); --General desert
AmbientList:add( position(109,709,0),nil,"Vom sandigen Boden her steigt eine Hitze auf, die deine Augen austrocknet.","The heat of the sand is rising up to meet your dry eyes. ",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General desert, daylight
AmbientList:add( position(171,686,0),{0,1,7},"Weit im Norden erheben sich die Eisamen Berge, majestisch umkreisen mächtige Adler die Bergspitzen.","Far to the north, the Lonely Mountains rise. Proud eagles fly around the mountaintops majestically.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General desert, daylight
AmbientList:add( position(206,737,0),nil,"Sand schießt dir entgegen und prasselt in dein Gesicht, es wird schwierig, etwas zwischen den Dünen zu erkennen.","The sand drifts about and gets in your eyes and it becomes increasingly harder to see. ",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General desert, daylight
AmbientList:add( position(244,720,0),nil,"Die Sonne blendet dich auf dem Marsch durch die Wüste. Du setzt deinen Weg fort, doch schützt du deine Augen mit der Hand vor dem grellen Schein.","The bright sun dazzles you as you walk through the desert. You continue, shielding your eyes from its glare.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General desert, daylight
AmbientList:add( position(285,711,0),nil,"In der Ferne erblickst du eine Wolke von Sand und Staub, die auf dich zugeweht wird.","In the distance you see the sand and dust being blown in your direction. ",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General desert, daylight
AmbientList:add( position(330,752,0),nil,"Du bemerkst eine verlockende Oase in der Ferne. Als du dir aber die Augen reibst, verschwindet das Trugbild.","You notice an oasis in the distance, agonisingly close. As you rub your eyes, the mirage vanishes.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General desert, daylight
AmbientList:add( position(345,715,0),nil,"Hoch über dir zieht ein Geier seine Kreise, ein fürwahr unheilvolles Omen.","Above, a vulture soars through the skies. A troubling sign, indeed. ",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General desert, daylight
AmbientList:add( position(400,695,0),nil,"Ein Geier zieht seine Kreise über der Wüste.","A vulture flies in circles over the desert",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General desert, daylight
AmbientList:add( position(412,762,0),nil,"Eine kleine Echse läuft geschwind eine Sandverwehung herab.","A small lizard runs swiftly down a sand drift.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General desert, daylight
AmbientList:add( position(437,797,0),{5,6,7},"Die karge Wüste Katanbi erstreckt sich vor dir. Eine Sandhose bildet sich in der Ferne.","The sparse Katanbi desert stretches before you. You see a column of spiralling sand in the distance.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General desert, daylight
AmbientList:add( position(215,735,0),nil,"Die Sonne strahlt gnadenlos auf dich herab. Durst beginnt dich zu matern.","The high sun beats down on you harshly. You begin to feel thirsty very quickly.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(239,639,0),nil,"Der heiße Wüstenwind treibt sein munteres Spiel mit einer Windhose aus Sand.","The hot desert wind plays its game with a small vortex of sand.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(240,522,0),nil,"Die Hitze der Wüste wird unerträglich. Du fragst dich, wie du hier ohne Sonnenstich wieder herauskommst.","You are acutely aware of the heat of the desert. You wonder how you could avoid sunstroke.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(242,712,0),nil,"Die Sonne steht hoch am Himmel, deine Augenbrauen glitzern vom Schweiß.","The sun is high in the air, your brow glistens with sweat as you feel its heat.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(266,718,0),nil,"Es ist verdammt heiß, nicht wahr?","It is pretty hot, isn't it?",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(282,646,0),nil,"Die Sonne brennt gnadenlos auf die Wüste nieder.","The sun scorches the desert without mercy.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(300,592,0),nil,"Die Luft ist hier heiß und trocken.","The air here is hot and dry. ",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(321,529,0),nil,"Die Luft flimmert vor Hitze, gelegentliche Windböen versprechen keine Erleichterung sondern vielmehr Irritation, blasen sie doch Sand in deine Augen und deinen Mund.","The air is quivering with hot vapour. The occasional gust of wind grants no relief, but is more of a source of irritation as it blows sand into your eyes and mouth.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(324,763,0),nil,"Mit einem Blick in die Ferne bekommst du das Gefühl, dass die Wüste niemals enden wird.","As you look on, the sand seems to outstretch the horizon. You feel like this will never end.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(348,619,0),nil,"Die segenden Strahlen der Sonne fahren Speeren gleich auf jedes Wesen in der Wüste nieder.","Torrid sunbeams dart like spears at every being in the desert.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(352,712,0),nil,"Die unerträgliche Hitze macht jeden Schritt zu einer Tortur.","The unstandable heat tortures you with every step you take.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(371,569,0),nil,"Die schier endlosen Sandmassen verschwimmen in der Ferne zu einer wabernden Masse. Erbarmungslos brennt die Sonne von oben hernieder.","Vast lands of sand are stretching off into the distance before you, gradually blurring into a wafting mass. From above, the sun burns incessantly.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(427,743,0),nil,"Du spürst die unerträgliche Hitze der Sonnenstrahlen dieses Tages in der Wüste Katanbi auf deiner Haut.","You feel a heavy, almost unbearable heat from the sun's warm rays this day in the Katanbi desert.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(391,774,0),nil,"Eine angenehm kühle Brise bläßt dir ins Gesicht, dennoch wirkt die Wüste unwirtlich und feindlich.","A calm breeze blows in your face, however, the desert still looks unhospitable and hostile.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{13,14,15,16},10); --General desert, daylight, winter
AmbientList:add( position(73,770,0),{5,6,7},"Am Strand siehst du einen wundervollen Sonnenuntergang, der das Wasser und die fernen Wolken in ein anmutiges Licht taucht.","From the beach you can see the beautiful sunset, covering the distant waters and clouds in an orange glow.",{17,18,19,20},nil,10); --General desert, late daylight
AmbientList:add( position(214,606,0),nil,"Eine Sternschnuppe erhellt kurzzeitig den Nachthimmel, bevor sie am Horizont verschwindet.","A shooting star enlightens the sky before it vanishes at the horizon.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(236,666,0),nil,"Du kannst genau die Geräusche der Wüstentiere vernehmen, die die Gelegenheit zur Nahrungssuche unter dem Sternenhimmel wahrnehmen, nun, da die Hitze nicht so unerträglich ist wie tagsüber.","You can hear the wildlife of the desert, as the animals take the chance to find food under the bright countless stars in the coolness of the night.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(282,678,0),nil,"Die Sandmassen unter dem Nachhimmel sind zur Ruhe gekommen. Nur ihre starke Abwärme zeugt noch von der Hitze des vergangenen Tages.","The desert beneath the night sky has come to rest. The warming radiation the sand emits is the only testimony to the preceding day's heat.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(289,601,0),nil,"In der Wüste ist es kalt und still, wäre nicht das fahle Licht der Monde, könnte man sich schnell verlaufen.","The desert is dark and quiet. Were it not for the faint light of the moons you could easily get lost here.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(297,574,0),nil,"Eine Wolke umhüllt den kleinen Mond Illarions, bekannt als der jüngere Bruder.","A cloud engulfs the small moon of Illarion, known as the younger brother.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(325,517,0),nil,"Hoch am Firmament setzen die Monde ihre immerwährende Jagd fort.","High in the firmament, the moons continue their everlasting chase.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(337,655,0),nil,"Kühler Wind bläst über die Wüste und Geheul ist in der Ferne zu hören. Plötzlich hallt ein markerschütternder Schrei durch das Tal, ein kalter Schauer läuft dir über den Rücken.","A chill wind blows across the desert and howls can be heard in the distance. Suddenly, a scream echoes across the valley floor,sending chills up your spine.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(349,547,0),nil,"Es ist eigentlich bitterkalt, aber der Sand glüht noch immer vor Hitze. ","It's freezing, but the sand still carries some heat.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(358,626,0),nil,"Im fahlen Licht der Monde erscheint die Wüste als ein noch unwirtlicher Ort als sonst.","In the pale light of the moons, the desert appears to be an even more inhospatible place.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(380,645,0),nil,"In der Nacht ist es in der Wüste alles andere als heiß.","There is nothing warm about this place at night.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(401,732,0),nil,"Die Nacht in der Wüste ist ungleich kühler als der Tag, die Tiere des Wüstenbodens erwachen zu nächtlichen Spaziergängen.","The night in the desert is much colder than the day. The inhabitants of the desert ground awake for a small walk.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(422,790,0),nil,"Die Kakteen werfen im fahlen Licht der Monde obskure Schatten.","The pale moons make the cacti cast obsure shadows.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(112,668,-4),nil,"Ein fahler Verwesungsgeruch zieht dir in die Nase.","You can smell the mustiness of the air down here.",nil,nil,10); --Specific Cadomyr
AmbientList:add( position(113,586,0),{0,1,7},"Dir schlägt der Geruch von Wein und Bier entgegen. Doch scheinen die Bewohner Cadomyrs sogar noch im Suff ihre Ehre zu behalten.","You smell wine and beer, however, the citizens of Cadomyr look proud and noble, even if drunk.",nil,nil,10); --Specific Cadomyr
AmbientList:add( position(115,599,0),nil,"Das Plätschern des knappen Gutes Wasser übt eine ungemein beruhigende Wirkung aus.","The plashing of the rare good water makes you feel relaxed and comfortable.",nil,nil,10); --Specific Cadomyr
AmbientList:add( position(116,649,-4),nil,"Im Augenwinkel erspähst du einen dunklen Schatten in den Tiefen der Gruft, doch verschwindet er schneller, als du deinen Kopf drehen kannst.","You catch a glimpse of a silhoutte in the distant darkness of the tomb. It vanishes suddenly.",nil,nil,10); --Specific Cadomyr
AmbientList:add( position(127,667,-4),nil,"Während du durch die Gruft gehst, meinst du, Geflüster zu hören, aber es ist niemand zu sehen.","As you walk through the tomb, you hear whispering tongues, but you see nobody around. ",nil,nil,10); --Specific Cadomyr
AmbientList:add( position(133,589,0),nil,"Obwohl sie bereits abgewischt wurden, kann man noch einige Worte an der Mauer im Osten ausmachen: 'Hastings auf den Thron!'","Albeit wiped off, one can make out that words were written on the wall in the east: 'Hastings for the throne!'",nil,nil,10); --Specific Cadomyr
AmbientList:add( position(134,671,-4),nil,"Dieser Ort macht auf dich einen majestätischer Eindruck, die vergangene Macht des beinahe schon vergessenen Altkönigs ist allgegenwärtig. Jedoch kannst du nicht verleugnen, dass hier noch etwas anderes sein Unwesen treibt…","The feel of majesty and ancient power of the one almost forgotten; the choking feel of someone unseen leaning over your shoulder is undeniable. ",nil,nil,10); --Specific Cadomyr
AmbientList:add( position(146,664,-4),nil,"Der modrige Geruch der Verwesung erfüllt die Gruft.","A musty smell of decay fills the tomb.",nil,nil,10); --Specific Cadomyr
AmbientList:add( position(155,638,-4),nil,"In der Gruft riecht es abgestanden und modrig. Die Wände sind mit fein gearbeiteten Inschriften versehen. Es ist kalt und feucht hier unten.","In the crypt it smells mouldy. On the walls you can see impressive incriptions. It is cold and clammy down here",nil,nil,10); --Specific Cadomyr
AmbientList:add( position(120,594,0),nil,"Auf dem Markplatz von Cadomyr herrscht geschäftiges Treiben.","The marketplace of Cadomyr resounds from business and ado.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --Specific Cadomyr, daylight
AmbientList:add( position(120,602,0),nil,"Auf dem Marktplatz nimmst du die verschiedensten Düfte wahr. Einige Kaufleute unterhalten sich, andere sortieren ihre Waren.","At the marketplace, you notice different fragrances. Some merchants are having a conversation, others are sorting their goods.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --Specific Cadomyr, daylight
AmbientList:add( position(121,532,0),nil,"Der Palast der Edwards erscheint heute in besonderem Glanz.","The Edwards' palace eradiates a special lordliness today.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --Specific Cadomyr, daylight
AmbientList:add( position(121,546,0),{0,1,7},"Beim Betreten des Palastes hörst du das Keifen der Königin von den Mauern widerhallen: 'Wo bleibt Hassan!'","Upon entering the palace, you hear the queen jangle: 'Where is Hassan?!'",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --Specific Cadomyr, daylight
AmbientList:add( position(119,604,0),nil,"Es ist nicht mehr viel los auf dem Marktplatz von Cadomyr. Die meisten Händler bauen gerade ihre Stände ab und reden nochmal über den Tag.","Not much is going on at the market place of Cadomyr. Most of the merchants are packing their bags and summing up the day.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --Specific Cadomyr, night
AmbientList:add( position(134,543,0),nil,"Die Nacht hat sich über den Palast gelegt, hier und da hört man das Schnarchen der Wachen.","The night has fallen on the palace. Here and there one can hear the guards snoring.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --Specific Cadomyr, night
AmbientList:add( position(29,543,0),nil,"Unter das Meeresrauschen mischen sich auch bärbeißige Männerstimmen - es wird viel gespottet und geflucht. Bei genauerem Hinsehen kannst du einige bullige Silhouetten ausmachen. Sei auf der Hut! ","A number of abrasive male voices interfuse the swoosh from the seaside - there's a lot of foul language and mockery going on. Upon closer examination, you're able to spot several burly silhouettes. Be on your guard! ",nil,nil,100); --Specific location
AmbientList:add( position(101,623,0),{5,6,7},"Als den den Tempel betrittst, durchfährt dich ein gesegnetes Gefühl, wie ein Prickeln in den Muskeln.","As you enter the temple, a blessed feeling rises in you. Your muscles start to prickle.",nil,nil,100); --Specific location
AmbientList:add( position(127,636,-4),{0,1,7},"An der Wand im Norden kann man lesen: 'Hastings gehört Cadomyr!'","At the wall in the north one can read: 'Hastings owns… Cadomyr.'",nil,nil,100); --Specific location
AmbientList:add( position(136,696,0),nil,"Du hörst das Klacken von Metall auf Stein, die Luft hier ist staubig und trocken. Die Enge würde einfache Gemüter wahnsinnig machen.","You hear the clinking of metal on stone. The dusty air and tight space would drive those weak of mind to madness. ",nil,nil,100); --Specific location
AmbientList:add( position(157,665,-4),nil,"Die Überreste prunkvoller Grabbeigaben liegen zerwühlt auf dem Boden herum.","The remnants of pompous burial objects are scattered over the ground.",nil,nil,100); --Specific location
AmbientList:add( position(226,513,0),{0,1,7},"In der Ferne sichtest du ein schäbig anmutendes Lager, in dem sich eine Rotte aus zwielichtigen Gestalten tummelt. Für rastende Kaufleute sehen sie definitv zu ungepflegt und rauhbeinig aus. Sei auf der Hut! ","You spot a shabby looking camp in the distance, populated by a mob of ragtag individuals. For resting merchants, they definitely look far too gruff and unkempt. Be on your guard!",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,100); --Specific location
AmbientList:add( position(250,512,0),{0,1,7},"Irgendwie fühlst du dich beobachtet von jemanden, den du besser nicht treffen willst. Umkehren ist eine gute Idee, mit mehr Gold wirst du sicher nicht zurückkehren…","You feel as if someone is watching you. Someone, you most likely don't want to meet. Perhaps you should turn back before you find your wallet disappearing... ",nil,nil,100); --Specific location
AmbientList:add( position(359,689,0),nil,"Wie ein Farbklecks auf einer kahlen Wand ragt dieser grüne Streifen aus der Einöde heraus. Eine kleine Zahl von schlanken Palmen, Blumen und Büschen rankt sich um eine Wassergrube, welche von einem Bächlein gespeist wird. ","This strip of green sticks out of the desert like a blur of colour on a blank wall. A small number of slim palm trees, flowers and shrubs entwine around a small pool of water, supplied by a close streamlet. ",nil,nil,100); --Specific location
AmbientList:add( position(440,739,0),{1,2,3},"Als du die Höhle betrittst, ist es dir als läufst du gegen eine kühle unsichtbare Wand aus Luft die deinen Körper in eiskaltes Wasser zu tauchen scheint. Beisender Rauch und der Gestank verdorbenen Fleisches durchdringen die Luft.","As you enter the cave you are met with an invisible wall of cold air. It feels like submerging your body in ice cold water after being burned by fire. The smell of smoke and decaying meat is overpowering",nil,nil,100); --Specific location
AmbientList:add( position(454,795,0),{5,6,7},"Die Straße nach Cadomyr führt durch die unwirtliche Wüste, die von manchen 'Wüste der Verzweiflung' genannt wird.","The road to Cadomyr crosses the inhospitable desert, known to some as 'Desert of Desperation'.",nil,nil,100); --Specific location
AmbientList:add( position(477,795,0),{5,6,7},"Dies scheint eine Grenze zu sein. Wenige Schritte weiter und du betrittst das stolze Königreich Cadomyr.","This looks like a border. A few steps further and you enter the proud kingdom of Cadomyr.",nil,nil,100); --Specific location
AmbientList:add( position(117,629,0),{0,1,7},"Der Anblick Cadomyrs ist beeindruckend, eine Zitadelle der Menschheit, die der Wüste trotzt.","Beholding Cadomyr leaves you in awe, a citadel of mankind that resists the desert.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,100); --Specific location, daylight 

function MoveToField(Char)
	local this = getAmbient(Char);
	if this then
		base.common.TempInformNLS(Char,this.german,this.english);
	end
end

function getAmbient(Char)
	local pos = Char.pos;
	local dir = Char:get_face_to();
	if AmbientList[pos.x] and AmbientList[pos.x][pos.y] and AmbientList[pos.x][pos.y][pos.z] then
		local this = AmbientList[pos.x][pos.y][pos.z];
		local list = {};
		for _,ambient in pairs(this) do
			local timeOk, monthOk, dirOk = false, false, false;
			for _,that in pairs(ambient.hours) do
				if that==world:getTime("hour") then
					timeOk = true;
					break;
				end
			end
			for _,that in pairs(ambient.months) do
				if that==world:getTime("month") then
					monthOk = true;
					break;
				end
			end
			for _,that in pairs(ambient.direction) do
				if that==dir then
					dirOk = true;
					break;
				end
			end
			if timeOk and monthOk and dirOk and math.random(0,99)<ambient.chance then --chance!
				table.insert(list,ambient);
			end
		end
		if table.getn(list)>0 then
			return list[math.random(1,table.getn(list))];
		end
	end
	return nil;
end