--[[
Illarion Server

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
details.

You should have received a copy of the GNU Affero General Public License along
with this program.  If not, see <http://www.gnu.org/licenses/>. 
]]
-- INSERT INTO "quests" ("qst_id", "qst_script") VALUES (162, 'quest.palis_nestros_162_cadomyr');

require("base.common")
module("quest.palis_nestros_162_cadomyr", package.seeall)

GERMAN = Player.german
ENGLISH = Player.english

-- Insert the quest title here, in both languages
Title = {}
Title[GERMAN] = "Ruhmhafte Kopfgeldjagd"
Title[ENGLISH] = "Glorious Bounty"

-- Insert an extensive description of each status here, in both languages
-- Make sure that the player knows exactly where to go and what to do
Description = {}
Description[GERMAN] = {}
Description[ENGLISH] = {}

Description[GERMAN][1] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von einem Silberstück an denjenigen auszuzahlen, der vier Käfer erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][2] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von einem Silberstück an denjenigen auszuzahlen, der vier Käfer erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][3] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von einem Silberstück an denjenigen auszuzahlen, der vier Käfer erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][4] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von einem Silberstück an denjenigen auszuzahlen, der vier Käfer erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][5] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][6] = "Ihre Majestät hat ein Kopfgeld auf acht Käfer ausgesetzt. Wenn ihr euch zwei Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][7] = "Ihre Majestät hat ein Kopfgeld auf acht Käfer ausgesetzt. Wenn ihr euch zwei Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][8] = "Ihre Majestät hat ein Kopfgeld auf acht Käfer ausgesetzt. Wenn ihr euch zwei Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][9] = "Ihre Majestät hat ein Kopfgeld auf acht Käfer ausgesetzt. Wenn ihr euch zwei Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][10] = "Ihre Majestät hat ein Kopfgeld auf acht Käfer ausgesetzt. Wenn ihr euch zwei Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][11] = "Ihre Majestät hat ein Kopfgeld auf acht Käfer ausgesetzt. Wenn ihr euch zwei Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][12] = "Ihre Majestät hat ein Kopfgeld auf acht Käfer ausgesetzt. Wenn ihr euch zwei Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][13] = "Ihre Majestät hat ein Kopfgeld auf acht Käfer ausgesetzt. Wenn ihr euch zwei Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][14] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][15] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][16] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][17] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][18] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][19] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][20] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][21] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][22] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][23] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][24] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][25] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][26] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Käfer ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, drei Silberstücke werden eure Belohnung sein."
Description[GERMAN][27] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][28] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zwei Silberstücken an denjenigen auszuzahlen, der vier Wespen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][29] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zwei Silberstücken an denjenigen auszuzahlen, der vier Wespen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][30] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zwei Silberstücken an denjenigen auszuzahlen, der vier Wespen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][31] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zwei Silberstücken an denjenigen auszuzahlen, der vier Wespen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][32] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][33] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][34] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][35] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][36] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][37] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][38] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][39] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][40] = "Ihre Majestät hat ein Kopfgeld auf acht Wespen ausgesetzt. Wenn ihr euch vier Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][41] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][42] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][43] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][44] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][45] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][46] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][47] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][48] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][49] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][50] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][51] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][52] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][53] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Wespen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, sechs Silberstücke werden eure Belohnung sein."
Description[GERMAN][54] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][55] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von drei Silberstücken an denjenigen auszuzahlen, der vier Hunde erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][56] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von drei Silberstücken an denjenigen auszuzahlen, der vier Hunde erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][57] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von drei Silberstücken an denjenigen auszuzahlen, der vier Hunde erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][58] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von drei Silberstücken an denjenigen auszuzahlen, der vier Hunde erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][59] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][60] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][61] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][62] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][63] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][64] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][65] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][66] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][67] = "Ihre Majestät hat ein Kopfgeld auf acht Hunde ausgesetzt. Wenn ihr euch sechs Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][68] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][69] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][70] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][71] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][72] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][73] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][74] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][75] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][76] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][77] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][78] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][79] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][80] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Hunde ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, neun Silberstücke werden eure Belohnung sein."
Description[GERMAN][81] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][82] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von vier Silberstücken an denjenigen auszuzahlen, der vier Füchse erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][83] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von vier Silberstücken an denjenigen auszuzahlen, der vier Füchse erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][84] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von vier Silberstücken an denjenigen auszuzahlen, der vier Füchse erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][85] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von vier Silberstücken an denjenigen auszuzahlen, der vier Füchse erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][86] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][87] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][88] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][89] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][90] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][91] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][92] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][93] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][94] = "Ihre Majestät hat ein Kopfgeld auf acht Füchse ausgesetzt. Wenn ihr euch acht Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][95] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][96] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][97] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][98] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][99] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][100] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][101] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][102] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][103] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][104] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][105] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][106] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][107] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Füchse ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, zwölf Silberstücke werden eure Belohnung sein."
Description[GERMAN][108] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][109] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von sechs Silberstücken an denjenigen auszuzahlen, der vier Menschen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][110] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von sechs Silberstücken an denjenigen auszuzahlen, der vier Menschen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][111] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von sechs Silberstücken an denjenigen auszuzahlen, der vier Menschen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][112] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von sechs Silberstücken an denjenigen auszuzahlen, der vier Menschen erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][113] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][114] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][115] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][116] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][117] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][118] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][119] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][120] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][121] = "Ihre Majestät hat ein Kopfgeld auf acht Menschen ausgesetzt. Wenn ihr euch zwölf Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][122] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][123] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][124] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][125] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][126] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][127] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][128] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][129] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][130] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][131] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][132] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][133] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][134] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Menschen ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, achtzehn Silberstücke werden eure Belohnung sein."
Description[GERMAN][135] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][136] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von acht Silberstücken an denjenigen auszuzahlen, der vier Orks erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][137] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von acht Silberstücken an denjenigen auszuzahlen, der vier Orks erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][138] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von acht Silberstücken an denjenigen auszuzahlen, der vier Orks erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][139] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von acht Silberstücken an denjenigen auszuzahlen, der vier Orks erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][140] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][141] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][142] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][143] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][144] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][145] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][146] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][147] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][148] = "Ihre Majestät hat ein Kopfgeld auf acht Orks ausgesetzt. Wenn ihr euch sechzehn Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][149] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][150] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][151] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][152] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][153] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][154] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][155] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][156] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][157] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][158] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][159] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][160] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][161] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Orks ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, vierundzwanzig Silberstücke werden eure Belohnung sein."
Description[GERMAN][162] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][163] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zehn Silberstücken an denjenigen auszuzahlen, der vier Golems erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][164] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zehn Silberstücken an denjenigen auszuzahlen, der vier Golems erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][165] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zehn Silberstücken an denjenigen auszuzahlen, der vier Golems erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][166] = "Zeit für eine Kopfgeldjagd! Ihre Majestät hat mich ermächtigt, ein Kopfgeld von zehn Silberstücken an denjenigen auszuzahlen, der vier Golems erschlägt. Geht in die Kantabiwüste und macht sie zu einem besseren Ort."
Description[GERMAN][167] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][168] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][169] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][170] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][171] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][172] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][173] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][174] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][175] = "Ihre Majestät hat ein Kopfgeld auf acht Golems ausgesetzt. Wenn ihr euch zwanzig Silberstücke verdienen möchtet, beendet ihr Leben in der Kantabiwüste. Tot oder nicht lebendig!"
Description[GERMAN][176] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."
Description[GERMAN][177] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][178] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][179] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][180] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][181] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][182] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][183] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][184] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][185] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][186] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][187] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][188] = "Die Kantabiwüste ist zu einem gefährlichen Ort geworden. Ein Kopfgeld ist auf zwölf Golems ausgesetzt, um die Wüste wieder friedvoller zu machen. Geht nun und erledigt sie, dreißig Silberstücke werden eure Belohnung sein."
Description[GERMAN][189] = "Kehre zu Palis Nestros zurück, um deine Belohnung zu erhalten."

Description[ENGLISH][1] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of one silver coin for the heads of four beetles. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][2] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of one silver coin for the heads of four beetles. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][3] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of one silver coin for the heads of four beetles. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][4] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of one silver coin for the heads of four beetles. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][5] = "Return to Palis Nestros to claim your reward."
Description[ENGLISH][6] = "Her Majesty put a bounty on the heads of eight beetles. If you want to earn two silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][7] = "Her Majesty put a bounty on the heads of eight beetles. If you want to earn two silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][8] = "Her Majesty put a bounty on the heads of eight beetles. If you want to earn two silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][9] = "Her Majesty put a bounty on the heads of eight beetles. If you want to earn two silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][10] = "Her Majesty put a bounty on the heads of eight beetles. If you want to earn two silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][11] = "Her Majesty put a bounty on the heads of eight beetles. If you want to earn two silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][12] = "Her Majesty put a bounty on the heads of eight beetles. If you want to earn two silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][13] = "Her Majesty put a bounty on the heads of eight beetles. If you want to earn two silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][14] = "Return to Palis Nestros to claim your reward."
Description[ENGLISH][15] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve beetles to make the desert peaceful again. Set out and kill them, three silver coins will be your reward."
Description[ENGLISH][16] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve beetles to make the desert peaceful again. Set out and kill them, three silver coins will be your reward."
Description[ENGLISH][17] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve beetles to make the desert peaceful again. Set out and kill them, three silver coins will be your reward."
Description[ENGLISH][18] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve beetles to make the desert peaceful again. Set out and kill them, three silver coins will be your reward."
Description[ENGLISH][19] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve beetles to make the desert peaceful again. Set out and kill them, three silver coins will be your reward."
Description[ENGLISH][20] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve beetles to make the desert peaceful again. Set out and kill them, three silver coins will be your reward."
Description[ENGLISH][21] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve beetles to make the desert peaceful again. Set out and kill them, three silver coins will be your reward."
Description[ENGLISH][22] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve beetles to make the desert peaceful again. Set out and kill them, three silver coins will be your reward."
Description[ENGLISH][23] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve beetles to make the desert peaceful again. Set out and kill them, three silver coins will be your reward."
Description[ENGLISH][24] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve beetles to make the desert peaceful again. Set out and kill them, three silver coins will be your reward."
Description[ENGLISH][25] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve beetles to make the desert peaceful again. Set out and kill them, three silver coins will be your reward."
Description[ENGLISH][26] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve beetles to make the desert peaceful again. Set out and kill them, three silver coins will be your reward."
Description[ENGLISH][27] = "Return to Palis Nestros to claim your reward."
Description[ENGLISH][28] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of two silver coins for the heads of four wasps. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][29] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of two silver coins for the heads of four wasps. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][30] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of two silver coins for the heads of four wasps. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][31] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of two silver coins for the heads of four wasps. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][32] = "Return to Palis Nestros to claim your reward."
Description[ENGLISH][33] = "Her Majesty put a bounty on the heads of eight wasps. If you want to earn four silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][34] = "Her Majesty put a bounty on the heads of eight wasps. If you want to earn four silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][35] = "Her Majesty put a bounty on the heads of eight wasps. If you want to earn four silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][36] = "Her Majesty put a bounty on the heads of eight wasps. If you want to earn four silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][37] = "Her Majesty put a bounty on the heads of eight wasps. If you want to earn four silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][38] = "Her Majesty put a bounty on the heads of eight wasps. If you want to earn four silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][39] = "Her Majesty put a bounty on the heads of eight wasps. If you want to earn four silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][40] = "Her Majesty put a bounty on the heads of eight wasps. If you want to earn four silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][41] = "Return to Palis Nestros to claim your reward."
Description[ENGLISH][42] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve wasps to make the desert peaceful again. Set out and kill them, six silver coins will be your reward."
Description[ENGLISH][43] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve wasps to make the desert peaceful again. Set out and kill them, six silver coins will be your reward."
Description[ENGLISH][44] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve wasps to make the desert peaceful again. Set out and kill them, six silver coins will be your reward."
Description[ENGLISH][45] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve wasps to make the desert peaceful again. Set out and kill them, six silver coins will be your reward."
Description[ENGLISH][46] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve wasps to make the desert peaceful again. Set out and kill them, six silver coins will be your reward."
Description[ENGLISH][47] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve wasps to make the desert peaceful again. Set out and kill them, six silver coins will be your reward."
Description[ENGLISH][48] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve wasps to make the desert peaceful again. Set out and kill them, six silver coins will be your reward."
Description[ENGLISH][49] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve wasps to make the desert peaceful again. Set out and kill them, six silver coins will be your reward."
Description[ENGLISH][50] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve wasps to make the desert peaceful again. Set out and kill them, six silver coins will be your reward."
Description[ENGLISH][51] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve wasps to make the desert peaceful again. Set out and kill them, six silver coins will be your reward."
Description[ENGLISH][52] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve wasps to make the desert peaceful again. Set out and kill them, six silver coins will be your reward."
Description[ENGLISH][53] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve wasps to make the desert peaceful again. Set out and kill them, six silver coins will be your reward."
Description[ENGLISH][54] = "Return to Palis Nestros to claim your reward."
Description[ENGLISH][55] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of three silver coins for the heads of four dogs. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][56] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of three silver coins for the heads of four dogs. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][57] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of three silver coins for the heads of four dogs. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][58] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of three silver coins for the heads of four dogs. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][59] = "Return to Palis Nestros to claim your reward."
Description[ENGLISH][60] = "Her Majesty put a bounty on the heads of eight dogs. If you want to earn six silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][61] = "Her Majesty put a bounty on the heads of eight dogs. If you want to earn six silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][62] = "Her Majesty put a bounty on the heads of eight dogs. If you want to earn six silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][63] = "Her Majesty put a bounty on the heads of eight dogs. If you want to earn six silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][64] = "Her Majesty put a bounty on the heads of eight dogs. If you want to earn six silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][65] = "Her Majesty put a bounty on the heads of eight dogs. If you want to earn six silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][66] = "Her Majesty put a bounty on the heads of eight dogs. If you want to earn six silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][67] = "Her Majesty put a bounty on the heads of eight dogs. If you want to earn six silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][68] = "Return to Palis Nestros to claim your reward."
Description[ENGLISH][69] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve dogs to make the desert peaceful again. Set out and kill them, nine silver coins will be your reward."
Description[ENGLISH][70] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve dogs to make the desert peaceful again. Set out and kill them, nine silver coins will be your reward."
Description[ENGLISH][71] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve dogs to make the desert peaceful again. Set out and kill them, nine silver coins will be your reward."
Description[ENGLISH][72] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve dogs to make the desert peaceful again. Set out and kill them, nine silver coins will be your reward."
Description[ENGLISH][73] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve dogs to make the desert peaceful again. Set out and kill them, nine silver coins will be your reward."
Description[ENGLISH][74] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve dogs to make the desert peaceful again. Set out and kill them, nine silver coins will be your reward."
Description[ENGLISH][75] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve dogs to make the desert peaceful again. Set out and kill them, nine silver coins will be your reward."
Description[ENGLISH][76] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve dogs to make the desert peaceful again. Set out and kill them, nine silver coins will be your reward."
Description[ENGLISH][77] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve dogs to make the desert peaceful again. Set out and kill them, nine silver coins will be your reward."
Description[ENGLISH][78] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve dogs to make the desert peaceful again. Set out and kill them, nine silver coins will be your reward."
Description[ENGLISH][79] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve dogs to make the desert peaceful again. Set out and kill them, nine silver coins will be your reward."
Description[ENGLISH][80] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve dogs to make the desert peaceful again. Set out and kill them, nine silver coins will be your reward."
Description[ENGLISH][81] = "Return to Palis Nestros to claim your reward."
Description[ENGLISH][82] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of four silver coins for the heads of four foxes. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][83] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of four silver coins for the heads of four foxes. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][84] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of four silver coins for the heads of four foxes. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][85] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of four silver coins for the heads of four foxes. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][86] = "Return to Palis Nestros to claim your reward."
Description[ENGLISH][87] = "Her Majesty put a bounty on the heads of eight foxes. If you want to earn eight silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][88] = "Her Majesty put a bounty on the heads of eight foxes. If you want to earn eight silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][89] = "Her Majesty put a bounty on the heads of eight foxes. If you want to earn eight silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][90] = "Her Majesty put a bounty on the heads of eight foxes. If you want to earn eight silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][91] = "Her Majesty put a bounty on the heads of eight foxes. If you want to earn eight silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][92] = "Her Majesty put a bounty on the heads of eight foxes. If you want to earn eight silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][93] = "Her Majesty put a bounty on the heads of eight foxes. If you want to earn eight silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][94] = "Her Majesty put a bounty on the heads of eight foxes. If you want to earn eight silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][95] = "Return to Palis Nestros to claim your reward."
Description[ENGLISH][96] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve foxes to make the desert peaceful again. Set out and kill them, twelve silver coins will be your reward."
Description[ENGLISH][97] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve foxes to make the desert peaceful again. Set out and kill them, twelve silver coins will be your reward."
Description[ENGLISH][98] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve foxes to make the desert peaceful again. Set out and kill them, twelve silver coins will be your reward."
Description[ENGLISH][99] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve foxes to make the desert peaceful again. Set out and kill them, twelve silver coins will be your reward."
Description[ENGLISH][100] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve foxes to make the desert peaceful again. Set out and kill them, twelve silver coins will be your reward."
Description[ENGLISH][101] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve foxes to make the desert peaceful again. Set out and kill them, twelve silver coins will be your reward."
Description[ENGLISH][102] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve foxes to make the desert peaceful again. Set out and kill them, twelve silver coins will be your reward."
Description[ENGLISH][103] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve foxes to make the desert peaceful again. Set out and kill them, twelve silver coins will be your reward."
Description[ENGLISH][104] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve foxes to make the desert peaceful again. Set out and kill them, twelve silver coins will be your reward."
Description[ENGLISH][105] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve foxes to make the desert peaceful again. Set out and kill them, twelve silver coins will be your reward."
Description[ENGLISH][106] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve foxes to make the desert peaceful again. Set out and kill them, twelve silver coins will be your reward."
Description[ENGLISH][107] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve foxes to make the desert peaceful again. Set out and kill them, twelve silver coins will be your reward."
Description[ENGLISH][108] = "Return to Palis Nestros to claim your reward."
Description[ENGLISH][109] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of six silver coins for the heads of four humans. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][110] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of six silver coins for the heads of four humans. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][111] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of six silver coins for the heads of four humans. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][112] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of six silver coins for the heads of four humans. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][113] = "Return to Palis Nestros to claim your reward."
Description[ENGLISH][114] = "Her Majesty put a bounty on the heads of eight humans. If you want to earn twelve silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][115] = "Her Majesty put a bounty on the heads of eight humans. If you want to earn twelve silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][116] = "Her Majesty put a bounty on the heads of eight humans. If you want to earn twelve silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][117] = "Her Majesty put a bounty on the heads of eight humans. If you want to earn twelve silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][118] = "Her Majesty put a bounty on the heads of eight humans. If you want to earn twelve silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][119] = "Her Majesty put a bounty on the heads of eight humans. If you want to earn twelve silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][120] = "Her Majesty put a bounty on the heads of eight humans. If you want to earn twelve silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][121] = "Her Majesty put a bounty on the heads of eight humans. If you want to earn twelve silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][122] = "Return to Palis Nestros to claim your reward."
Description[ENGLISH][123] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve humans to make the desert peaceful again. Set out and kill them, eighteen silver coins will be your reward."
Description[ENGLISH][124] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve humans to make the desert peaceful again. Set out and kill them, eighteen silver coins will be your reward."
Description[ENGLISH][125] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve humans to make the desert peaceful again. Set out and kill them, eighteen silver coins will be your reward."
Description[ENGLISH][126] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve humans to make the desert peaceful again. Set out and kill them, eighteen silver coins will be your reward."
Description[ENGLISH][127] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve humans to make the desert peaceful again. Set out and kill them, eighteen silver coins will be your reward."
Description[ENGLISH][128] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve humans to make the desert peaceful again. Set out and kill them, eighteen silver coins will be your reward."
Description[ENGLISH][129] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve humans to make the desert peaceful again. Set out and kill them, eighteen silver coins will be your reward."
Description[ENGLISH][130] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve humans to make the desert peaceful again. Set out and kill them, eighteen silver coins will be your reward."
Description[ENGLISH][131] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve humans to make the desert peaceful again. Set out and kill them, eighteen silver coins will be your reward."
Description[ENGLISH][132] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve humans to make the desert peaceful again. Set out and kill them, eighteen silver coins will be your reward."
Description[ENGLISH][133] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve humans to make the desert peaceful again. Set out and kill them, eighteen silver coins will be your reward."
Description[ENGLISH][134] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve humans to make the desert peaceful again. Set out and kill them, eighteen silver coins will be your reward."
Description[ENGLISH][135] = "Return to Palis Nestros to claim your reward."
Description[ENGLISH][136] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of eight silver coins for the heads of four orcs. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][137] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of eight silver coins for the heads of four orcs. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][138] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of eight silver coins for the heads of four orcs. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][139] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of eight silver coins for the heads of four orcs. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][140] = "Return to Palis Nestros to claim your reward."
Description[ENGLISH][141] = "Her Majesty put a bounty on the heads of eight orcs. If you want to earn sixteen silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][142] = "Her Majesty put a bounty on the heads of eight orcs. If you want to earn sixteen silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][143] = "Her Majesty put a bounty on the heads of eight orcs. If you want to earn sixteen silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][144] = "Her Majesty put a bounty on the heads of eight orcs. If you want to earn sixteen silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][145] = "Her Majesty put a bounty on the heads of eight orcs. If you want to earn sixteen silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][146] = "Her Majesty put a bounty on the heads of eight orcs. If you want to earn sixteen silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][147] = "Her Majesty put a bounty on the heads of eight orcs. If you want to earn sixteen silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][148] = "Her Majesty put a bounty on the heads of eight orcs. If you want to earn sixteen silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][149] = "Return to Palis Nestros to claim your reward."
Description[ENGLISH][150] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve orcs to make the desert peaceful again. Set out and kill them, twenty four silver coins will be your reward."
Description[ENGLISH][151] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve orcs to make the desert peaceful again. Set out and kill them, twenty four silver coins will be your reward."
Description[ENGLISH][152] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve orcs to make the desert peaceful again. Set out and kill them, twenty four silver coins will be your reward."
Description[ENGLISH][153] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve orcs to make the desert peaceful again. Set out and kill them, twenty four silver coins will be your reward."
Description[ENGLISH][154] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve orcs to make the desert peaceful again. Set out and kill them, twenty four silver coins will be your reward."
Description[ENGLISH][155] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve orcs to make the desert peaceful again. Set out and kill them, twenty four silver coins will be your reward."
Description[ENGLISH][156] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve orcs to make the desert peaceful again. Set out and kill them, twenty four silver coins will be your reward."
Description[ENGLISH][157] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve orcs to make the desert peaceful again. Set out and kill them, twenty four silver coins will be your reward."
Description[ENGLISH][158] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve orcs to make the desert peaceful again. Set out and kill them, twenty four silver coins will be your reward."
Description[ENGLISH][159] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve orcs to make the desert peaceful again. Set out and kill them, twenty four silver coins will be your reward."
Description[ENGLISH][160] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve orcs to make the desert peaceful again. Set out and kill them, twenty four silver coins will be your reward."
Description[ENGLISH][161] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve orcs to make the desert peaceful again. Set out and kill them, twenty four silver coins will be your reward."
Description[ENGLISH][162] = "Return to Palis Nestros to claim your reward."
Description[ENGLISH][163] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of ten silver coins for the heads of four golems. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][164] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of ten silver coins for the heads of four golems. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][165] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of ten silver coins for the heads of four golems. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][166] = "Time for a bounty hunt! Her Majesty has authorised me to pay a bounty of ten silver coins for the heads of four golems. Set out to the Kantabi desert and make it a better place."
Description[ENGLISH][167] = "Return to Palis Nestros to claim your reward."
Description[ENGLISH][168] = "Her Majesty put a bounty on the heads of eight golems. If you want to earn twenty silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][169] = "Her Majesty put a bounty on the heads of eight golems. If you want to earn twenty silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][170] = "Her Majesty put a bounty on the heads of eight golems. If you want to earn twenty silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][171] = "Her Majesty put a bounty on the heads of eight golems. If you want to earn twenty silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][172] = "Her Majesty put a bounty on the heads of eight golems. If you want to earn twenty silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][173] = "Her Majesty put a bounty on the heads of eight golems. If you want to earn twenty silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][174] = "Her Majesty put a bounty on the heads of eight golems. If you want to earn twenty silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][175] = "Her Majesty put a bounty on the heads of eight golems. If you want to earn twenty silver coins, end their life in the Kantabi desert. Dead or not alive!"
Description[ENGLISH][176] = "Return to Palis Nestros to claim your reward."
Description[ENGLISH][177] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve golems to make the desert peaceful again. Set out and kill them, thirty silver coins will be your reward."
Description[ENGLISH][178] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve golems to make the desert peaceful again. Set out and kill them, thirty silver coins will be your reward."
Description[ENGLISH][179] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve golems to make the desert peaceful again. Set out and kill them, thirty silver coins will be your reward."
Description[ENGLISH][180] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve golems to make the desert peaceful again. Set out and kill them, thirty silver coins will be your reward."
Description[ENGLISH][181] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve golems to make the desert peaceful again. Set out and kill them, thirty silver coins will be your reward."
Description[ENGLISH][182] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve golems to make the desert peaceful again. Set out and kill them, thirty silver coins will be your reward."
Description[ENGLISH][183] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve golems to make the desert peaceful again. Set out and kill them, thirty silver coins will be your reward."
Description[ENGLISH][184] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve golems to make the desert peaceful again. Set out and kill them, thirty silver coins will be your reward."
Description[ENGLISH][185] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve golems to make the desert peaceful again. Set out and kill them, thirty silver coins will be your reward."
Description[ENGLISH][186] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve golems to make the desert peaceful again. Set out and kill them, thirty silver coins will be your reward."
Description[ENGLISH][187] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve golems to make the desert peaceful again. Set out and kill them, thirty silver coins will be your reward."
Description[ENGLISH][188] = "The Kantabi desert has become a dangerous place. There is a bounty put on twelve golems to make the desert peaceful again. Set out and kill them, thirty silver coins will be your reward."
Description[ENGLISH][189] = "Return to Palis Nestros to claim your reward."


-- Insert the position of the quest start here (probably the position of an NPC or item)
Start = {93, 618, 0}

-- For each status insert a list of positions where the quest will continue, i.e. a new status can be reached there
QuestTarget = {}
QuestTarget[1] = {position(93, 618, 0)} -- Palis
QuestTarget[2] = {position(93, 618, 0)} -- Palis
QuestTarget[3] = {position(93, 618, 0)} -- Palis
QuestTarget[4] = {position(93, 618, 0)} -- Palis
QuestTarget[5] = {position(93, 618, 0)} -- Palis
QuestTarget[6] = {position(93, 618, 0)} -- Palis
QuestTarget[7] = {position(93, 618, 0)} -- Palis
QuestTarget[8] = {position(93, 618, 0)} -- Palis
QuestTarget[9] = {position(93, 618, 0)} -- Palis
QuestTarget[10] = {position(93, 618, 0)} -- Palis
QuestTarget[11] = {position(93, 618, 0)} -- Palis
QuestTarget[12] = {position(93, 618, 0)} -- Palis
QuestTarget[13] = {position(93, 618, 0)} -- Palis
QuestTarget[14] = {position(93, 618, 0)} -- Palis
QuestTarget[15] = {position(93, 618, 0)} -- Palis
QuestTarget[16] = {position(93, 618, 0)} -- Palis
QuestTarget[17] = {position(93, 618, 0)} -- Palis
QuestTarget[18] = {position(93, 618, 0)} -- Palis
QuestTarget[19] = {position(93, 618, 0)} -- Palis
QuestTarget[20] = {position(93, 618, 0)} -- Palis
QuestTarget[21] = {position(93, 618, 0)} -- Palis
QuestTarget[22] = {position(93, 618, 0)} -- Palis
QuestTarget[23] = {position(93, 618, 0)} -- Palis
QuestTarget[24] = {position(93, 618, 0)} -- Palis
QuestTarget[25] = {position(93, 618, 0)} -- Palis
QuestTarget[26] = {position(93, 618, 0)} -- Palis
QuestTarget[27] = {position(93, 618, 0)} -- Palis
QuestTarget[28] = {position(93, 618, 0)} -- Palis
QuestTarget[29] = {position(93, 618, 0)} -- Palis
QuestTarget[30] = {position(93, 618, 0)} -- Palis
QuestTarget[31] = {position(93, 618, 0)} -- Palis
QuestTarget[32] = {position(93, 618, 0)} -- Palis
QuestTarget[33] = {position(93, 618, 0)} -- Palis
QuestTarget[34] = {position(93, 618, 0)} -- Palis
QuestTarget[35] = {position(93, 618, 0)} -- Palis
QuestTarget[36] = {position(93, 618, 0)} -- Palis
QuestTarget[37] = {position(93, 618, 0)} -- Palis
QuestTarget[38] = {position(93, 618, 0)} -- Palis
QuestTarget[39] = {position(93, 618, 0)} -- Palis
QuestTarget[40] = {position(93, 618, 0)} -- Palis
QuestTarget[41] = {position(93, 618, 0)} -- Palis
QuestTarget[42] = {position(93, 618, 0)} -- Palis
QuestTarget[43] = {position(93, 618, 0)} -- Palis
QuestTarget[44] = {position(93, 618, 0)} -- Palis
QuestTarget[45] = {position(93, 618, 0)} -- Palis
QuestTarget[46] = {position(93, 618, 0)} -- Palis
QuestTarget[47] = {position(93, 618, 0)} -- Palis
QuestTarget[48] = {position(93, 618, 0)} -- Palis
QuestTarget[49] = {position(93, 618, 0)} -- Palis
QuestTarget[50] = {position(93, 618, 0)} -- Palis
QuestTarget[51] = {position(93, 618, 0)} -- Palis
QuestTarget[52] = {position(93, 618, 0)} -- Palis
QuestTarget[53] = {position(93, 618, 0)} -- Palis
QuestTarget[54] = {position(93, 618, 0)} -- Palis
QuestTarget[55] = {position(93, 618, 0)} -- Palis
QuestTarget[56] = {position(93, 618, 0)} -- Palis
QuestTarget[57] = {position(93, 618, 0)} -- Palis
QuestTarget[58] = {position(93, 618, 0)} -- Palis
QuestTarget[59] = {position(93, 618, 0)} -- Palis
QuestTarget[60] = {position(93, 618, 0)} -- Palis
QuestTarget[61] = {position(93, 618, 0)} -- Palis
QuestTarget[62] = {position(93, 618, 0)} -- Palis
QuestTarget[63] = {position(93, 618, 0)} -- Palis
QuestTarget[64] = {position(93, 618, 0)} -- Palis
QuestTarget[65] = {position(93, 618, 0)} -- Palis
QuestTarget[66] = {position(93, 618, 0)} -- Palis
QuestTarget[67] = {position(93, 618, 0)} -- Palis
QuestTarget[68] = {position(93, 618, 0)} -- Palis
QuestTarget[69] = {position(93, 618, 0)} -- Palis
QuestTarget[70] = {position(93, 618, 0)} -- Palis
QuestTarget[71] = {position(93, 618, 0)} -- Palis
QuestTarget[72] = {position(93, 618, 0)} -- Palis
QuestTarget[73] = {position(93, 618, 0)} -- Palis
QuestTarget[74] = {position(93, 618, 0)} -- Palis
QuestTarget[75] = {position(93, 618, 0)} -- Palis
QuestTarget[76] = {position(93, 618, 0)} -- Palis
QuestTarget[77] = {position(93, 618, 0)} -- Palis
QuestTarget[78] = {position(93, 618, 0)} -- Palis
QuestTarget[79] = {position(93, 618, 0)} -- Palis
QuestTarget[80] = {position(93, 618, 0)} -- Palis
QuestTarget[81] = {position(93, 618, 0)} -- Palis
QuestTarget[82] = {position(93, 618, 0)} -- Palis
QuestTarget[83] = {position(93, 618, 0)} -- Palis
QuestTarget[84] = {position(93, 618, 0)} -- Palis
QuestTarget[85] = {position(93, 618, 0)} -- Palis
QuestTarget[86] = {position(93, 618, 0)} -- Palis
QuestTarget[87] = {position(93, 618, 0)} -- Palis
QuestTarget[88] = {position(93, 618, 0)} -- Palis
QuestTarget[89] = {position(93, 618, 0)} -- Palis
QuestTarget[90] = {position(93, 618, 0)} -- Palis
QuestTarget[91] = {position(93, 618, 0)} -- Palis
QuestTarget[92] = {position(93, 618, 0)} -- Palis
QuestTarget[93] = {position(93, 618, 0)} -- Palis
QuestTarget[94] = {position(93, 618, 0)} -- Palis
QuestTarget[95] = {position(93, 618, 0)} -- Palis
QuestTarget[96] = {position(93, 618, 0)} -- Palis
QuestTarget[97] = {position(93, 618, 0)} -- Palis
QuestTarget[98] = {position(93, 618, 0)} -- Palis
QuestTarget[99] = {position(93, 618, 0)} -- Palis
QuestTarget[100] = {position(93, 618, 0)} -- Palis
QuestTarget[101] = {position(93, 618, 0)} -- Palis
QuestTarget[102] = {position(93, 618, 0)} -- Palis
QuestTarget[103] = {position(93, 618, 0)} -- Palis
QuestTarget[104] = {position(93, 618, 0)} -- Palis
QuestTarget[105] = {position(93, 618, 0)} -- Palis
QuestTarget[106] = {position(93, 618, 0)} -- Palis
QuestTarget[107] = {position(93, 618, 0)} -- Palis
QuestTarget[108] = {position(93, 618, 0)} -- Palis
QuestTarget[109] = {position(93, 618, 0)} -- Palis
QuestTarget[110] = {position(93, 618, 0)} -- Palis
QuestTarget[111] = {position(93, 618, 0)} -- Palis
QuestTarget[112] = {position(93, 618, 0)} -- Palis
QuestTarget[113] = {position(93, 618, 0)} -- Palis
QuestTarget[114] = {position(93, 618, 0)} -- Palis
QuestTarget[115] = {position(93, 618, 0)} -- Palis
QuestTarget[116] = {position(93, 618, 0)} -- Palis
QuestTarget[117] = {position(93, 618, 0)} -- Palis
QuestTarget[118] = {position(93, 618, 0)} -- Palis
QuestTarget[119] = {position(93, 618, 0)} -- Palis
QuestTarget[120] = {position(93, 618, 0)} -- Palis
QuestTarget[121] = {position(93, 618, 0)} -- Palis
QuestTarget[122] = {position(93, 618, 0)} -- Palis
QuestTarget[123] = {position(93, 618, 0)} -- Palis
QuestTarget[124] = {position(93, 618, 0)} -- Palis
QuestTarget[125] = {position(93, 618, 0)} -- Palis
QuestTarget[126] = {position(93, 618, 0)} -- Palis
QuestTarget[127] = {position(93, 618, 0)} -- Palis
QuestTarget[128] = {position(93, 618, 0)} -- Palis
QuestTarget[129] = {position(93, 618, 0)} -- Palis
QuestTarget[130] = {position(93, 618, 0)} -- Palis
QuestTarget[131] = {position(93, 618, 0)} -- Palis
QuestTarget[132] = {position(93, 618, 0)} -- Palis
QuestTarget[133] = {position(93, 618, 0)} -- Palis
QuestTarget[134] = {position(93, 618, 0)} -- Palis
QuestTarget[135] = {position(93, 618, 0)} -- Palis
QuestTarget[136] = {position(93, 618, 0)} -- Palis
QuestTarget[137] = {position(93, 618, 0)} -- Palis
QuestTarget[138] = {position(93, 618, 0)} -- Palis
QuestTarget[139] = {position(93, 618, 0)} -- Palis
QuestTarget[140] = {position(93, 618, 0)} -- Palis
QuestTarget[141] = {position(93, 618, 0)} -- Palis
QuestTarget[142] = {position(93, 618, 0)} -- Palis
QuestTarget[143] = {position(93, 618, 0)} -- Palis
QuestTarget[144] = {position(93, 618, 0)} -- Palis
QuestTarget[145] = {position(93, 618, 0)} -- Palis
QuestTarget[146] = {position(93, 618, 0)} -- Palis
QuestTarget[147] = {position(93, 618, 0)} -- Palis
QuestTarget[148] = {position(93, 618, 0)} -- Palis
QuestTarget[149] = {position(93, 618, 0)} -- Palis
QuestTarget[150] = {position(93, 618, 0)} -- Palis
QuestTarget[151] = {position(93, 618, 0)} -- Palis
QuestTarget[152] = {position(93, 618, 0)} -- Palis
QuestTarget[153] = {position(93, 618, 0)} -- Palis
QuestTarget[154] = {position(93, 618, 0)} -- Palis
QuestTarget[155] = {position(93, 618, 0)} -- Palis
QuestTarget[156] = {position(93, 618, 0)} -- Palis
QuestTarget[157] = {position(93, 618, 0)} -- Palis
QuestTarget[158] = {position(93, 618, 0)} -- Palis
QuestTarget[159] = {position(93, 618, 0)} -- Palis
QuestTarget[160] = {position(93, 618, 0)} -- Palis
QuestTarget[161] = {position(93, 618, 0)} -- Palis
QuestTarget[162] = {position(93, 618, 0)} -- Palis
QuestTarget[163] = {position(93, 618, 0)} -- Palis
QuestTarget[164] = {position(93, 618, 0)} -- Palis
QuestTarget[165] = {position(93, 618, 0)} -- Palis
QuestTarget[166] = {position(93, 618, 0)} -- Palis
QuestTarget[167] = {position(93, 618, 0)} -- Palis
QuestTarget[168] = {position(93, 618, 0)} -- Palis
QuestTarget[169] = {position(93, 618, 0)} -- Palis
QuestTarget[170] = {position(93, 618, 0)} -- Palis
QuestTarget[171] = {position(93, 618, 0)} -- Palis
QuestTarget[172] = {position(93, 618, 0)} -- Palis
QuestTarget[173] = {position(93, 618, 0)} -- Palis
QuestTarget[174] = {position(93, 618, 0)} -- Palis
QuestTarget[175] = {position(93, 618, 0)} -- Palis
QuestTarget[176] = {position(93, 618, 0)} -- Palis
QuestTarget[177] = {position(93, 618, 0)} -- Palis
QuestTarget[178] = {position(93, 618, 0)} -- Palis
QuestTarget[179] = {position(93, 618, 0)} -- Palis
QuestTarget[180] = {position(93, 618, 0)} -- Palis
QuestTarget[181] = {position(93, 618, 0)} -- Palis
QuestTarget[182] = {position(93, 618, 0)} -- Palis
QuestTarget[183] = {position(93, 618, 0)} -- Palis
QuestTarget[184] = {position(93, 618, 0)} -- Palis
QuestTarget[185] = {position(93, 618, 0)} -- Palis
QuestTarget[186] = {position(93, 618, 0)} -- Palis
QuestTarget[187] = {position(93, 618, 0)} -- Palis
QuestTarget[188] = {position(93, 618, 0)} -- Palis
QuestTarget[189] = {position(93, 618, 0)} -- Palis

-- Insert the quest status which is reached at the end of the quest
FINAL_QUEST_STATUS = 0


function QuestTitle(user)
    return base.common.GetNLS(user, Title[GERMAN], Title[ENGLISH])
end

function QuestDescription(user, status)
    local german = Description[GERMAN][status] or ""
    local english = Description[ENGLISH][status] or ""

    return base.common.GetNLS(user, german, english)
end

function QuestStart()
    return Start
end

function QuestTargets(user, status)
    return QuestTarget[status]
end

function QuestFinalStatus()
    return FINAL_QUEST_STATUS
end
