module("content.dailymessage", package.seeall());

GoodBadDayMessages = {};

function GetMessage( Lang, Attrib, Race, Effect )
    if not GoodBadDayMessages then
        return false;
    end
    if not GoodBadDayMessages[Lang] then
        return false;
    end
    if not GoodBadDayMessages[Lang][Attrib] then
        return false;
    end
    if not GoodBadDayMessages[Lang][Attrib][Race] then
        return false;
    end
    return GoodBadDayMessages[Lang][Attrib][Race][Effect];
end

function initMessages()
    local currentLang;
    local currentAttrib;
    local currentRace;

    local SetLanguage = function( newLang )
        currentLang = newLang;
    end;

    local SetAttribute = function( newAttrib )
        currentAttrib = newAttrib;
    end;

    local SetRace = function( newRace )
        currentRace = newRace;
    end;

    local SetMessage = function( Effect, Message )
        if not GoodBadDayMessages[currentLang] then
            GoodBadDayMessages[currentLang] = {};
        end
        if not GoodBadDayMessages[currentLang][currentAttrib] then
            GoodBadDayMessages[currentLang][currentAttrib] = {};
        end
        if not GoodBadDayMessages[currentLang][currentAttrib][currentRace] then
            GoodBadDayMessages[currentLang][currentAttrib][currentRace] = {};
        end
        GoodBadDayMessages[currentLang][currentAttrib][currentRace][Effect] = Message;
    end;

    SetLanguage( CPlayer.german );
    SetAttribute( "strength" );
    SetRace( CCharacter.fairy );
    SetMessage(1,"Heute fühlst du dich, als könntest du einen ganzen Kuchen heben!");
    SetMessage(2,"Deine Arme sind wie Grashalme aus Eisen, heute kriegst du bestimmt einen ganzen Kuchen und einen ganzen halben hoch!");
    SetMessage(-1,"Deine Arme sind so schlaff, mehr als ein Kuchenstück wirst du heute kaum lupfen können.");
    SetRace( CCharacter.gnome );
    SetMessage(1,"Lass dir deine Waren heute ruhig in Kupfermünzen bezahlen, die wiegen doch heute kaum was.");
    SetMessage(2,"Auf die Kuh könntest du heute verzichten, bist doch zur Zeit selbst stark wie ein laufender Meter purer Kraft.");
    SetMessage(-1,"Dein großer Kopf pendelt hin und her, so schlecht kannst du sein Gewicht heute tragen.");
    SetRace( CCharacter.halfling );
    SetMessage(1,"Wenn du heute vor hattest, deine süßen Kuchen und Brote zu verkaufen, dann am besten in großen Portionen, die buckelst du heute locker..");
    SetMessage(2,"Deine kurzen Beine fühlen sich heute an wie Baumstämme, so sehr strotzt du vor Kraft.");
    SetMessage(-1,"Du scheinst heute nicht so viel tragen zu können. Such dir lieber wen, der dir deine Kochwerkzeuge und Zutaten schleppt.");
    SetRace( CCharacter.goblin );
    SetMessage(-1,"Deine Ohren hängen heute lasch hinab, um Kraft zu sparen.");
    SetMessage(1,"Wolltest du heute nicht besonders viele \"nutzlose\" Dinge einsammeln? Dann los und keine Angst, du könntest dich übernehmen.");
    SetMessage(2,"Soll dir heute bloß mal einer von den Orks unter die Nase kommen, dann gibt es einen Tritt gegen das Knie, dass das halbe Bein abreißt!");
    SetRace( CCharacter.elf );
    SetMessage(1,"Heute siehst du nicht nur elegant und edel aus, heute hast du auch Kraft genug, um mal ein neues Baumhaus zu bauen.");
    SetMessage(2,"Sollten wieder frevelnde Menschen im Wald zu Gange sein, werf sie am besten gleich in die Baumkrone. Soviel traust du deinen Armen zumindest zu.");
    SetMessage(-1,"Dünn zu sein hat auch Nachteile, deine Muskeln fühlen sich heute einfach schlapp an.");
    SetRace( CCharacter.dwarf );
    SetMessage(-1,"Als du das letzte Mal geschürft hast, muss dir ein Hexenschuss reingefahren sein, richtig viel tragen ist heute zumindest nicht drin.");
    SetMessage(1,"Wenn dich heute jemand deiner Größe wegen aufziehen will, zögere nicht, ihn zurechtweisen, denn deine Arme sind vom vielen Bier fest wie Eisen.");
    SetMessage(2,"Wie wärs mit einer Lektion im Bierfassstemmen für die Kleinen? Einige Dutzend bekommst du heute sicher so...");
    SetRace( CCharacter.lizardman );
    SetMessage(1,"Deine Schuppen wollen heute schon ausfallen, um deinen aufgeblühten Muskeln Platz zu machen!");
    SetMessage(-1,"Wie gut, dass es auch kleine Fische gibt, die Großen hättest du kaum in dein Lager schleppen können.");
    SetMessage(2,"Vermutlich steht heute ein Kampf mit einem Hai an der Tagesordnung, du fühlst dich zumindest so, als könntest du einen in die Flucht schlagen.");
    SetRace( CCharacter.human );
    SetMessage(1,"Alles lässt sich heute etwas leichter bewegen als sonst. Hast du in letzter Zeit ein wenig was für deine Arme getan?");
    SetMessage(2,"Niemand wird dich heute ärgern, denn deine Muskeln schrecken alle ab.");
    SetMessage(-1,"Setz dich lieber nicht hin, am Ende schaffst du es nicht mal mehr auf die eigenen Beine, so schwer fühlst du dich heute.");
    SetRace( CCharacter.orc );
    SetMessage(2,"Niemand wird es heute wagen, dich herauszufordern! Deine schon beeindruckenden Muskeln wirken noch größer.");
    SetMessage(1,"Du solltest es heute wohl schaffen, etwas mehr Fleisch von deiner erlegten Beute in die Höhle zu schleppen.");
    SetMessage(-1,"Armdrücken mit deinen Brüdern oder Schwestern solltest du heute unterlassen.");

    SetAttribute( "constitution" );
    SetRace( CCharacter.orc );
    SetMessage(-1,"Deine Arme werden schneller lahm als sonst, wenn du mal wieder jemanden aufmischt.");
    SetMessage(1,"Soll sich heute doch ruhig ein Oger an dir vergreifen, die paar Schläge deines größeren Artverwandten steckst du locker ein.");
    SetMessage(2,"Heute kann dir ruhig ein wilder Mob Zwerge begegnen, bei deiner Ausdauer werden sie sich die Zähne an dir ausbeißen.");
    SetRace( CCharacter.halfling );
    SetMessage(1,"Heute wirst du sicher einige Treffer mehr beim Zwiebelballspiel aushalten.");
    SetMessage(-1,"Vielleicht solltest du mal mehr Kuchen essen, dein Magen fühlt sich nicht ganz so gut an.");
    SetMessage(2,"Heute kannst du den ganzen Tag damit verbringen, Kuchen zu backen, du scheinst einfach nicht müde zu werden.");
    SetRace( CCharacter.gnome );
    SetMessage(1,"Beim Münzen polieren werden deine Finger gar nicht mehr so schnell wund wie sonst.");
    SetMessage(2,"Du feilscht noch lange und lautstark, während andere schon mit entzündetem Kehlkopf vor dir zu Boden kriechen.");
    SetMessage(-1,"Dein großer Kopf brummt, als hätte dich wer mit einer Socke voller Kleingeld verhaun, wag dich lieber nicht an größere Gegner heran.");
    SetRace( CCharacter.goblin );
    SetMessage(1,"Ob es nun die Flasche Goblinbräu zum Morgen war oder nicht, du fühlst dich so richtig gesund. Möge die Suche nach einer verlorenen Münze beginnen!");
    SetMessage(-1,"Die vielen beunruhigenden Dinge dieser Welt haben deinen Körper in letzter Zeit arg mitgenommen. Vielleicht solltest du ein wenig ausruhen, bevor du den Tag beginnst oder gehst ihn locker an.");
    SetMessage(2,"Sollen die Orks dir heute ruhig an den Ohren ziehen, du spürst es kaum, so widerstandsfähig ist dein Körper heute.");
    SetRace( CCharacter.fairy );
    SetMessage(1,"Heute solltest du auch längere Flüge meistern können, du ermüdest nicht all zu sehr.");
    SetMessage(2,"Spiel heute ruhig \"Fangen\" mit den Hasen, denn sie mögen zwar schneller sein aber du hast den längeren Atem.");
    SetMessage(-1,"Du fühlst dich heute äußerst verspannt und auch deine Flügel sind zerbrechlicher als sonst. Vielleicht wäre es das beste, zu Hause zu bleiben und auszuruhen.");
    SetRace( CCharacter.elf );
    SetMessage(1,"Du magst groß und schmal aussehen aber du bist definitiv nicht schwach. Zumindest heute nicht..");
    SetMessage(2,"Es gibt einen Grund, wieso Elfen länger leben als jeder andere. Du spürst die Kraft deiner Rasse in dir am heutigen Tag.");
    SetMessage(-1,"Die vielen Errinnerungen, die sich in so einem Elfenleben ansammeln, drücken dir heute ziemlich aufs Gemüt, so ganz gesund ist dir heute zumindest nicht zumute.");
    SetRace( CCharacter.dwarf );
    SetMessage(2,"War für heute eigentlich ein Wetttrinken angesetzt? Ja? Großartig, denn du fühlst dich, als könntest du deine Rekordmarke knacken!");
    SetMessage(1,"Verbringe heute ruhig den ganzen Tag und auch die ganze Nacht in der Mine damit, nach wertvollen Metallen zu suchen, müde wird ein Zwerg wie du nicht.");
    SetMessage(-1,"Ein Mordskater plagt dich, sei es vom vielen Trinken oder vom vielen Schürfen, auf jeden Fall glaubst du nicht, dass du sehr großen Anstrengungen heute gewachsen bist.");
    SetRace( CCharacter.lizardman );
    SetMessage(1,"Du bist dir nicht sicher, ob es Einbildung ist oder nicht aber deine Schuppen fühlen sich heute robuster an.");
    SetMessage(2,"Tanora hat dich heute wohl gesegnet mit ihren Wassern, du fühlst dich kräftig und energiegeladen.");
    SetMessage(-1,"Deine Schuppen jucken, deine Zähne schmerzen und deine Augen tränen, so richtig zum Auftauchen ist dir heut gar nicht.");
    SetRace( CCharacter.human );
    SetMessage(-1,"Ein Muskelkater plagt dich und protestiert spürbar gegen längere, körperliche Anstrengungen.");
    SetMessage(1,"Heute scheint ein guter Tag für Erkundungen zu sein, dein Körper ist richtig erfrischt und bereit für Anstrengung.");
    SetMessage(2,"Du hattest eine Vision von einem Golem, der dich schlug, doch du hast nicht mal ein blaues davongetragen! Vielleicht lässt sich das ja in der Realität auch mal probieren.");

    SetAttribute( "agility" );
    SetRace( CCharacter.human );
    SetMessage(2,"Du bist heute gespannt wie ein Flitzebogen und hast das Gefühl, selbst Borgate könnte sein Bier heute nicht so schnell trinken, wie du drei Mal um die Taverne rennst.");
    SetMessage(1,"Ausnahmsweise gelang es dir heute, eine anhängliche Fliege mit einer schnellen Bewegung deiner Hand zu plätten und du meinst, dies könnte nicht die letzte gewesen sein.");
    SetMessage(-1,"Beim Aufstehen hast du eine Schnecke bemerkt, die sich schneller anzog, als du es tatest... merkwürdig.");
    SetRace( CCharacter.lizardman );
    SetMessage(2,"Deine Geschwindigkeit im Wasser ist heute enorm, dein Körper bewegt sich koordiniert und elegant.");
    SetMessage(1,"Kein Fisch schwimmt dir heute mehr davon!");
    SetMessage(-1,"Jeder Fisch scheint dir heute durch die Krallen zu gehen, kein gutes Zeichen.");
    SetRace( CCharacter.fairy );
    SetMessage(-1,"Deine Flügel sind heute so steif und möchten sich nicht recht entfalten, nur mit Mühe gelingt es dir, etwas schneller zu fliegen. Wettrennen gegen den Wind fallen heute wohl flach");
    SetMessage(2,"Heute fliegst du mit dem Wind um die Wette und gewinnst.");
    SetMessage(1,"Die Vögel hast du heute schon überrundet.");
    SetRace( CCharacter.halfling );
    SetMessage(1,"Trotz deiner kurzen Beine bist du heut doch um einiges schneller als so manch Großer.");
    SetMessage(2,"Hat da gerade wer zum Zwischenimbiss gerufen?! Schnell, heute wirst du Erster sein!");
    SetMessage(-1,"So große Füße sind zwar gut für festen Stand aber auch eher für gemächliches Laufen gedacht, oder?");
    SetRace( CCharacter.dwarf );
    SetMessage(1,"Heute warst du als Erster in der Mine.");
    SetMessage(2,"Keiner leert sein Bier heute so schnell wie du, nicht mal Borgate...");
    SetMessage(-1,"Klein und dick bist du und was klein und dick ist, ist nicht schnell. Zumindest nicht heute!");
    SetRace( CCharacter.gnome );
    SetMessage(1,"Heute hast du dein Geld erstaunlich schnell durchgezählt.");
    SetMessage(2,"Heute läufst du schneller als die meisten und sackst deshalb auch die besten Handelsgeschäfte ein.");
    SetMessage(-1,"Sollen Geschäfte doch Geschäfte sein, du bist heute mal so richtig faul und gemütlich.");
    SetRace( CCharacter.goblin );
    SetMessage(1,"Den Popel, der dir schon gestern nervigerweise im Ohr hing, entfernst du heute mit verblüffender Geschwindigkeit.");
    SetMessage(-1,"Eine großzügige Person könnte heute deine geliebten scheinenden Münzen verteilen, doch alle anderen Goblins wären wohl schneller.");
    SetMessage(2,"Orks mögen größer sein, doch sie werden dich heute nicht zu fassen kriegen.");
    SetRace( CCharacter.elf );
    SetMessage(1,"Lange Beine sind schnell, das beweißt du heute mal wieder allen.");
    SetMessage(2,"Würde man dich nicht Elf nennen, wärst du heute \"Fegender Wind\" !");
    SetMessage(-1,"Lange Beine sind ja schön gut aber heute wollen auch die einfach nur übereinander geschlagen werden, nicht zum Rennen benutzt.");
    SetRace( CCharacter.orc );
    SetMessage(1,"Welchen Sinn würde es machen, heute vor dir wegzulaufen? Deine Opfer könnten sich doch auch einfach ergeben.");
    SetMessage(2,"Wie wär es denn, wenn du zur Abwechslung mal dich jagen lässt? Wegzukommen sollte zumindest keine Schwierigkeit werden.");
    SetMessage(-1,"Such dir diesen Tag lieber langsamere Beute, einen Zwergen vielleicht?");

    SetAttribute( "intelligence" );
    SetRace( CCharacter.human );
    SetMessage(-1,"Nachdem du heute Morgen längere Zeit brauchtest, um zu erkennen, dass deine Hände nicht in die Schuhe gehören, solltest du dich wohl gar nicht erst an anspruchsvolle Aufgaben heranwagen.");
    SetMessage(2,"Nichts, was dir heute jemand sagt, kann dich verwirren, nicht mal das sinnloses Gebrabbel Aughams, denn du hast heute den Scharfsinn gepachtet!");
    SetMessage(1,"Dein Kopf würde heute gerne etwas komplizierteres unternehmen, als nur den stumpfen Alltag mitzuerleben. Ließ doch mal ein Buch, du wirst sehen, so schwer fällt dir das nicht!");
    SetRace( CCharacter.orc );
    SetMessage(1,"Richtig! Ork schreibt man mit k! Hoffentlich behältst du das bis morgen.");
    SetMessage(2,"Heute sind dir drei Sätze ohne Rechtschreibfehler gelungen, Respekt.");
    SetMessage(-1,"Deinen Namen, der dir für gewöhnlich schon Probleme bereitet, bekommst du heute erst gar nicht hin, muss an deinem Schreibknochen liegen..., oder?");
    SetRace( CCharacter.dwarf );
    SetMessage(-1,"Es hat dich einige Zeit gekostet, bis du erkannt hast, dass dein Frühstücksbier aus dem Fass, nicht aus dem Amboss kommt. Ob der neue Zapfhahn auffallen wird...?");
    SetMessage(2,"Dir spuken Gedanken von höchst komplizierten Schmiedemethoden durch den Kopf aber du blickst schnell durch und könntest sie in die Tat umsetzen.");
    SetMessage(1,"Der Hammer haut auf das Eisen und formt es...so schwer ist das nicht! Du bist zuversichtlich, dass du dir die nächsten Lektionen eher einprägen kannst!");
    SetRace( CCharacter.gnome );
    SetMessage(1,"Dein großer Kopf war ja ohnehin nie leer aber heute bist du noch gescheiter als sonst! Du wirst schon sehen.");
    SetMessage(2,"Wenn man Elfen nachsagt, dass sie intelligent sind, so sagt man dir nach, dass du der geschrumpfte Urelf seist.");
    SetMessage(-1,"Heute scheint dir das Zählen nicht leicht zu fallen...irgendwie hast du nicht genug Finger dazu.");
    SetRace( CCharacter.goblin );
    SetMessage(1,"Viele Goblins sind dumm und laufen im Kreis herum..., doch du bist heute immerhin so schlau, dass du weißt, wie du wieder stehen bleiben könntest.");
    SetMessage(2,"Gibt es nicht diesen einen Goblin, der Magier in Lor-Angur ist? Menschliche Gelehrte sehen dir heute in die Augen und fragen dich, ob du nicht mit ihm verwandt bist!");
    SetMessage(-1,"So richtig was sinnvolles will dir heute nicht einfallen aber es bleiben ja noch immer deine Ohren, vielleicht kann man mit denen was spielen...");
    SetRace( CCharacter.fairy );
    SetMessage(1,"Wäre es nicht besser, Kirschen aus den höchsten Baumkronen zu werfen, damit der Getroffene dich gar nicht erst entdecken kann? Solche und mehr Geistesblitze gehen dir zur Zeit durch den Kopf.");
    SetMessage(2,"Deine Streiche heute sind wohl durchdacht und werden dir sicherlich viel Gekicher einbringen.");
    SetMessage(-1,"Wie gut, dass deine Flügel sich schon von alleine bewegen, diese ganze Koordinationsgeschichte wäre dir heute schon zuviel gewesen.");
    SetRace( CCharacter.halfling );
    SetMessage(2,"Dir gehen geniale Ideen durch den Kopf: Wenn du Morgens, Mittags, Nachts und des Öfteren was dazwischen isst...wieso machst du dann eigentlich noch Pausen?");
    SetMessage(1,"Die viele frische Luft, die du auf dem Feld einatmest bringt eben wohl was, dein Kopf ist ganz frei geblasen und offen für Neues!");
    SetMessage(-1,"Wärst du grün, nicht so haarig und hättest größere Ohren, würd man dich in eine Schule für Goblins stecken!");
    SetRace( CCharacter.elf );
    SetMessage(1,"Heute spürst du einmal mehr, dass du, was zumindest den Bildungsgrad angeht, den Menschen noch überlegener bist als sonst.");
    SetMessage(-1,"Heute fühlst du dich einfach nicht so aufgeweckt, wie sonst. Du fragst dich, woran das liegen mag.");
    SetMessage(2,"Teile deine Weisheit und die halbe Welt wäre schlau genug, Magie zu lernen.");
    SetRace( CCharacter.lizardman );
    SetMessage(2,"Du solltest den Tanz der Fische vor der Küste beobachten, heute kannst du sicherlich mit Leichtigkeit einen Plan entwickeln, der dich in kürzerer Zeit mehr Fische fangen lässt.");
    SetMessage(-1,"Viel mehr als \"Fisch\" kannst du heute nicht groß denken.");
    SetMessage(1,"Heute fühlst du die so richtig aufgeweckt. Zeit, den Landwesen mal zu zeigen, welche Rasse die schlauste ist.");

    SetAttribute( "willpower" );
    SetRace( CCharacter.human );
    SetMessage(1,"Heute weißt du, was du möchtest und Andere scheinen eher gewillt zu sein, dir dabei zu helfen.");
    SetMessage(2,"Am heutigen Tage könnte nicht mal die gewitzteste Fee dich dazu bringen, zu tun, was sie möchte.");
    SetMessage(-1,"Die Welt scheint heute voll mit Versuchungen, welchen du scheinbar nicht widerstehen kannst.");
    SetRace( CCharacter.halfling );
    SetMessage(-1,"Wenn dir Todd heute wieder einen seiner Kuchen anbietet, wirst du kaum widerstehen können...");
    SetMessage(1,"Heute schüchtert dich gar nichts ein!");
    SetMessage(2,"Heute könntest du den bockigsten Esel ausleihen und er würde sich deinem Willen beugen.");
    SetRace( CCharacter.orc );
    SetMessage(-1,"Du fragst dich, wieso heute alle über dich zu lachen scheinen...");
    SetMessage(1,"Es könnte heute schon so manch Spannung geben mit deiner Umwelt, denn du fühlst dich heute nicht wie einer, der nachgibt.");
    SetMessage(2,"Heute reicht schon das leiseste Knurren deinerseits aus, um alle Tiere flüchten und Personen verstummen zu lassen.");
    SetRace( CCharacter.gnome );
    SetMessage(-1,"Gold und Silber locken dich heute noch mehr als sonst, beinah möchtest du dich selbst verkaufen.");
    SetMessage(1,"Sollen die Großen nur reden, du magst klein sein aber dennoch zu allem bereit.");
    SetMessage(2,"Du bist heute mehr als zuversichtlich genug fürs Feilschen und wirst wohl die besten Preise für deine Waren heraus handeln.");
    SetRace( CCharacter.dwarf );
    SetMessage(-1,"Eine gierige Stimme in deinem Kopf singt lallend: Bier, Bier, Bier, gib mir Bier und ich gehorch nur dir!");
    SetMessage(1,"Borgate schrieb dir eine Nachricht und lud dich zu Freibier ein aber du kannst sogar dem widerstehen.");
    SetMessage(2,"Du fühlst dich wie ein Fels in der Brandung, unbeugsam und stolz.");
    SetRace( CCharacter.fairy );
    SetMessage(1,"Riechst du grad nicht Kuchen?! Schnell, weiterfliegen! Ein bischen noch..jetzt..gnn..pfu, vorbei. Beinah hätte dich das von deinen heutigen Plänen abgelenkt aber du hast widerstanden!");
    SetMessage(2,"Nichts wird dir deine heutigen Pläne durcheinander bringen, nicht einmal wenn du den ... zweitgrößten Kuchen der Welt finden würdest.");
    SetMessage(-1,"Dir ist heute nicht wirklich nach Streiche spielen, dein Selbstvertrauen muss verdampft sein.");
    SetRace( CCharacter.elf );
    SetMessage(-1,"Heute ist dir gar nicht mal so sehr nach edlem Benehmen, viel lieber würdest du die Fassade fallen lassen und dir ein Bier genehmigen.");
    SetMessage(1,"Ein langes Leben kann eine Belastung sein, doch nicht für dich, du bist so motiviert wie eh und je.");
    SetMessage(2,"Du gehst heute sehr anmutig und schnell merkt jeder um dich herum, wie weise und charmant du bist.");
    SetRace( CCharacter.lizardman );
    SetMessage(-1,"Du lässt den Schwanz und Kopf hängen, fühlst dich auch nicht so wohl auf dem Land.");
    SetMessage(2,"Stolz und aufrecht ist dein Gang heute, würdig einem Wesen, das von einer Göttin geschaffen wurde.");
    SetMessage(1,"Die Sonne scheint, das Wasser ist angenehm warm und darinnen schwimmen tonnenweise die Fische...aber du hast anderes vor und bleibst dabei.");
    SetRace( CCharacter.goblin );
    SetMessage(-1,"Sicher, Goblins sind ängstlich, doch dir jagt heute schon dein eigener Schatten leichte Schauer durch die Ohren.");
    SetMessage(1,"Sollen die Orks dich doch angrollen, heute bist du zuversichtlich, dass du zumindest nicht schreien wirst.");
    SetMessage(2,"Hoffentlich bietet dir heute keiner eine schöne Münze an, denn du bist so entschlossen, dass du diese prompt ablehnen würdest, schon allein aus Prinzip.");

    SetAttribute( "perception" );
    SetRace( CCharacter.human );
    SetMessage(-1,"Ein Oger schlich sich heute unbemerkt an dir vorbei...");
    SetMessage(2,"Dank deines scharfen Gehörs bemerktest du glücklicherweise noch rechtzeitig die Fee mit dem Wassereimer über dir");
    SetMessage(1,"Du hast heute diese vermaledeite Stufe, die dir schon den einen oder anderen Zeh gekostet hat, eher bemerkt als sonst.");
    SetRace( CCharacter.elf );
    SetMessage(1,"Deine spitzen Ohren zucken heute schon bei geringerem Lärm, deine Gehörgänge scheinen richtig durchgeputzt..");
    SetMessage(2,"Deine Augen sind so scharf wie die eines Adlers und deine Ohren so empfindlich wie die eines Hasens.");
    SetMessage(-1,"Sehr aufmerksam kannst du dich heute nicht nennen.");
    SetRace( CCharacter.fairy );
    SetMessage(-1,"Sei heute besonders auf der Hut, wenn Streiche spielende Feen unterwegs sind. Deine Flügel hören sich so laut an, dass du keinen bemerkst, der sich anpirscht.");
    SetMessage(2,"Du spürst selbst die leichteste Brise und kannst zudem jede Person, egal wie weit entfernt, erkennen.");
    SetMessage(1,"Heute riechst du mit Leichtigkeit den Nektar der Blumen und kannst sogar die Insekten darauf ausmachen.");
    SetRace( CCharacter.lizardman );
    SetMessage(1,"Du schmeckst deinen Fisch heute viel intensiver als für gewöhnlich.");
    SetMessage(2,"Nichts kann deine Nase heute trügen und selbst deine Augen blicken an Land so scharf wie im Wasser.");
    SetMessage(-1,"Die Fische schwimmen heute oft an dir vorbei, ohne dass du es bemerkst.");
    SetRace( CCharacter.dwarf );
    SetMessage(-1,"Das viele Bier, dass du so gerne trinkst, hat dich ein wenig benebelt und du hörst nicht so gut. Sehen war sowieso nie dein Ding, könnte man heute meinen.");
    SetMessage(1,"Dir fallen schon die kleinsten Risse in deinen Schmiedearbeiten auf, es wird Zeit, sie mal alle unter die Lupe zu nehmen.");
    SetMessage(2,"Heute wird dir niemand dein Bier stehlen, denn du bekommst alles mit, was um dich herum passiert.");
    SetRace( CCharacter.gnome );
    SetMessage(1,"Heute sollte keiner versuchen, dir minderwertige Ware anzubieten, denn dir würde das nicht entgehen.");
    SetMessage(2,"Deine Waage kannst du heute zu Hause lassen, Gewichte werden heute mit bloßer Hand bestimmt.");
    SetMessage(-1,"Irgendwas muss dir ins Auge geflogen sein, denn du siehst nicht so gut!");
    SetRace( CCharacter.goblin );
    SetMessage(1,"Deine Ohren vibrieren sanft, wenn jemand näher kommt und auch deine Nase nimmt alles viel intensiver wahr.");
    SetMessage(-1,"Du hast dir einen scheußlichen Schnupfen eingefangen, der dir deinen unbestechlichen Geruchssinn trübt.");
    SetMessage(2,"Echsen mögen Fische im Wasser sehen, wenn andere von der spiegelnden Oberfläche geblendet sind, doch du hast schon die Schuppen gezählt.");
    SetRace( CCharacter.orc );
    SetMessage(-1,"Du isst heute eigentlich nur schlechtes Fleisch, doch du merkst es nicht.");
    SetMessage(2,"Heute bemerkst du die Elfen, bevor sie dich auch nur gehört haben.");
    SetMessage(1,"Heute witterst du deine Beute mit Leichtigkeit, nichts entgeht dir.");
    SetRace( CCharacter.halfling );
    SetMessage(2,"Jeder Kuchen und jedes Brot duftet für dich wie das Paradies.");
    SetMessage(-1,"Einige Feen haben sich einen Spaß daraus gemacht, dein Haar zu verknoten aber bisher ist dir davon noch nichts bekannt.");
    SetMessage(1,"Vorhin hattest du dir mal wieder die Ohren geputzt und siehe da, du hörst so gut wie noch nie.");

    SetAttribute( "essence" );
    SetRace( CCharacter.halfling );
    SetMessage(1,"Heute bist du im Einklang mit der Natur und sehr viel fröhlicher als sonst.");
    SetMessage(2,"Offenbar hast du eine spirituelle Verbindung mit allem um dich herum, du scheinst sogar die Pflanzen zu verstehen, die im Garten wachsen.");
    SetMessage(-1,"Du fühlst dich leer und nicht zu vielem aufgelegt.");
    SetRace( CCharacter.dwarf );
    SetMessage(-1,"Du fühlst dich so trocken wie die Felsen, die dich umgeben.");
    SetMessage(1,"Heute fühlst du dich anders. Du hast keine Ahnung, was es ist, aber es ist gut.");
    SetMessage(2,"Irmoroms Geist ist heute stark in dir, er schaut dir spürbar über die Schulter.");
    SetRace( CCharacter.fairy );
    SetMessage(2,"Deine magischen Illusionen erscheinen heute viel realer.");
    SetMessage(1,"Du bist heute einfach nur fröhlich.");
    SetMessage(-1,"Deine Streiche scheinen heute nicht so perfekt, wie sie sein sollten, du fragst dich, wieso.");
    SetRace( CCharacter.orc );
    SetMessage(2,"Malachin ist heute bei dir und beschützt dich.");
    SetMessage(-1,"Haben die Götter dich verlassen? Du scheinst heute nicht sehr glücklich über die Jagd.");
    SetMessage(1,"Du spürst, was sich heute um dich herum tut. Beinah nimmst du sogar wahr, was in sich in deinen Opfern abspielt.");
    SetRace( CCharacter.elf );
    SetMessage(2,"Du kontrollierst die arkanen Künste heute mit Leichtigkeit, du bist im reinen mit dir selbst.");
    SetMessage(-1,"Du fühlst eine Unebenmäßigkeit zwischen deinem Geist und deiner Seele, kein sehr angenehmes Gefühl.");
    SetMessage(1,"Du bist eins mit deinem Inneren.");
    SetRace( CCharacter.human );
    SetMessage(2,"Die Meditation zahlt sich aus, du fühlst dich wohl.");
    SetMessage(1,"Wahrscheinlich hatte dein Traum etwas zu bedeuten, es scheint dir, dass ein freundlicher Geist sich mit dir in Verbindung setzt.");
    SetMessage(-1,"Du fühlst dich heute wie die leere Hülle eines Menschen.");
    SetRace( CCharacter.goblin );
    SetMessage(2,"Die Götter scheinen über dich zu wachen und das steigert deine Zuversicht.");
    SetMessage(1,"Obwohl physisch schwächer als die meisten Orks, bist du zumindest heute geistig stärker als sie.");
    SetMessage(-1,"Du scheinst heute richtig viel Pech zu haben, was wohl nur mit dir los ist.");
    SetRace( CCharacter.gnome );
    SetMessage(1,"Deine handwerklichen Arbeiten scheinen heute einen Funken Magie in sich zu bergen, alle Geräte funktionieren wie von Zauberhand geführt.");
    SetMessage(2,"Alles scheint heute einfach besser zu sein, als würde jemand von weit oben dir über die Schulter blicken.");
    SetMessage(-1,"Nichts mag dir heute so richtig gelingen und du fühlst dich komisch.");
    SetRace( CCharacter.lizardman );
    SetMessage(-1,"Hat Tanora sich heute von dir abgewendet? Du bist unsicher über dein Verhältnis zu ihr.");
    SetMessage(1,"Zelphia sieht gütig auf dich herab heute und macht dein Leben lebenswert.");
    SetMessage(2,"Tanora hat dir heute ihren Segen erteilt, du fühlst dich ihr so viel mehr verbunden als sonst.");

    SetAttribute( "dexterity" );
    SetRace( CCharacter.human );
    SetMessage(-1,"Als du versuchst, dir die Haare zu kämmen, fällt dir der Kamm aus der Hand zu Boden. Vielleicht solltest du deinen Fingern eine Pause gewähren.");
    SetMessage(2,"Deine Finger machen heute die verrücktesten Bewegungen mit, von denen du vorher gar nicht gedacht hättest, dass sie möglich sind.");
    SetMessage(1,"Als du vorhin einen Popel weggeschnippt hast, ist er genau auf einem Astloch gelandet, wo es sonst kein anderes gibt, gut geschossen.");
    SetRace( CCharacter.dwarf );
    SetMessage(-1,"Beim Schmieden haust du dir öfters auf die Finger, als sonst.");
    SetMessage(2,"Deine Klingen werden heute so scharf und gerade wie noch nie!");
    SetMessage(1,"Die Schmiedewaren, die du heute herstellst, sehen richtig ordentlich aus.");
    SetRace( CCharacter.elf );
    SetMessage(1,"Wie es sich für Elfen gehört, könntest du heute sicherlich jemanden einen Apfel vom Kopf schießen, egal ob mit Pfeil und Bogen oder mit etwas anderem.");
    SetMessage(-1,"Lange Finger müssen nicht auch präzise Finger sein. Zumindest nicht heute.");
    SetMessage(2,"Deine Schnitzereien scheinen heute sehr viel genauer. Es gibt also doch noch Gründe, wieso Elfen berühmt sind für ihre handwerkliche Begabung.");
    SetRace( CCharacter.halfling );
    SetMessage(-1,"Du bleibst heute überall mit deinen haarigen Füßen hängen.");
    SetMessage(1,"Wenn Todd heute vielleicht ein bischen unachtsam ist, sollte es dir gelingen, einen seiner Kuchen zu stibitzen.");
    SetMessage(2,"Wie so oft hast du vorhin mal wahllos eine faule Zwiebel durch die Gegend geworfen, um nicht aus der Übung zu kommen...und hast eine Fliege im Flug erwischt!");
    SetRace( CCharacter.lizardman );
    SetMessage(1,"Kein Fisch kann deinen flinken Krallen heute entschlüpfen.");
    SetMessage(-1,"Als du dich vorhin am Rücken kratzen wolltest, mussten einige Schuppen daran glauben. Erst die Krallen einfahren!");
    SetMessage(2,"Eine Schuppe an deiner Schulter hat sich vorhin quer gestellt und in kunstvollen Verrenkungen, die dir so schnell keiner nachmacht, ist es dir gelungen, den Fehler zu beheben.");
    SetRace( CCharacter.gnome );
    SetMessage(2,"Du hattest einen Traum, in dem du eine geheimnisvolle Schatztruhe mit nur einem Zentimeter Draht öffnen msstest. Es gelang erstaunlicherweise und du glaubst, es könnte ein Omen gewesen sein.");
    SetMessage(1,"Deine Handschrift ist heute richtig ansehnlich.");
    SetMessage(-1,"Flaschen rutschen dir heute aus den Fingern und zerbrechen am Boden. Du solltest vorsichtiger sein.");
    SetRace( CCharacter.goblin );
    SetMessage(1,"Du schnippst heute Münzen mit soviel Können wie fast nie und selbst das Stibitzen von Geld anderer sollte dir nicht schwer fallen.");
    SetMessage(2,"Mit deinen flinken Fingern eröffnen sich dir heute ganz neue Dimensionen des Nasebohrens!");
    SetMessage(-1,"Jetzt hätte dich aber beinah die Panik gepackt, eine ganze Minute lang hast du deine steifen Finger nicht mehr aus den Ohren bekommen!");
    SetRace( CCharacter.fairy );
    SetMessage(1,"Kirschkuchen zu werfen erscheint dir heute soviel einfacher, du triffst einfach beinah alles.");
    SetMessage(2,"Das Aufdröseln von anderer Leute Schnürsenkel während sie nicht gucken, das wäre heute lustig...und fiele dir auch nicht schwer.");
    SetMessage(-1,"Du hast ein Kuchenstück fallen lassen, als du es gerade essen wolltest und hast deine Kleidung eingesaut, böse Finger!");
    SetRace( CCharacter.orc );
    SetMessage(-1,"Du versuchst, einen Stein nach einem Schwein zu werfen, triffst aber jemand anderes.");
    SetMessage(2,"Du hast deine Beute säuberlich ausgeweidet und das Fleisch von den Knochen getrennt, ohne auch nur einen Bissen zu verschwenden.");
    SetMessage(1,"Deine stummeligen und harten Finger wirken heute lockerer als sonst.");

    SetLanguage( CPlayer.english );
    SetAttribute( "perception" );
    SetRace( CCharacter.human );
    SetMessage(-1,"An ogre could sneak past you unnoticed today.");
    SetMessage(2,"Due to your sharp sense of hearing you could notice a fairy flying above your head.");
    SetMessage(1,"Today you actually noticed the ladder step which you had stubbed your toe on one too many times.");
    SetRace( CCharacter.elf );
    SetMessage(1,"Your pointed ears twitch at the slightest noise today, they seem to be highly sensitive today.");
    SetMessage(2,"Your eyes are as sharp as a hawk's and your ears as sensitive as a rabbit's");
    SetMessage(-1,"Today you cannot consider yourself being very vigilant.");
    SetRace( CCharacter.fairy );
    SetMessage(-1,"Watch out for other fairies playing tricks on you today. Your wings sound so loud that you do not hear anyone approaching you.");
    SetMessage(2,"You feel the slightest breeze today, and hear the footsteps of even the most distant person");
    SetMessage(1,"You can easily smell the nectar of flowers, and even spot insects with ease.");
    SetRace( CCharacter.lizardman );
    SetMessage(1,"Fish tastes much stronger and tastier today.");
    SetMessage(2,"Nothing can fool your nose today, and even your eyes can clearly see on land.");
    SetMessage(-1,"A fish could pass by your nose with ease today.");
    SetRace( CCharacter.dwarf );
    SetMessage(-1,"It seems the beers you had yesterday effected your hearing a tad. In fact, seeing does not seem to be your forte either.");
    SetMessage(1,"You recognise the tiniest flaws in your smithing works today, it is about time to check them all closely.");
    SetMessage(2,"Nobody will be stealing your beer today because you are aware of everything that happens around you.");
    SetRace( CCharacter.gnome );
    SetMessage(1,"If anyone tries to sell you inferior quality goods, today is not their lucky day. Your eyes appear keen to notice any flaws.");
    SetMessage(2,"Your hands appear to be able to judge the weight of objects quite perfectly. You won't be needing your scales today..");
    SetMessage(-1,"Something must have found itself into your eyes because you don't see very clearly today.");
    SetRace( CCharacter.goblin );
    SetMessage(1,"Your ears vibrate softly as soon as someone approaches you and your nose works much more sensitively today.");
    SetMessage(-1,"Your usually-perfect sense of smell appears to be blocked by a minor cold.");
    SetMessage(2,"Lizards might see fishes underneath the surface, but today you could even count their scales.");
    SetRace( CCharacter.orc );
    SetMessage(-1,"You don't appear to notice that the meat you ate today is all rotten.");
    SetMessage(2,"Today you notice elves before they hear you.");
    SetMessage(1,"You can smell your prey with ease today, nothing is getting past you today.");
    SetRace( CCharacter.halfling );
    SetMessage(2,"Every cake and every loaf of bread smell like paradise today.");
    SetMessage(-1,"Some fairies made fun of you and put knots in your hair, but you didn't even notice until now.");
    SetMessage(1,"You just cleaned your ears and unsurprisingly, you can hear much better now.");

    SetAttribute( "willpower" );
    SetRace( CCharacter.human );
    SetMessage(1,"Today you know what you want, and others appear to be more open to giving it to you.");
    SetMessage(2,"Today even the most skilled fairy couldn't entice you to do what she wants.");
    SetMessage(-1,"Today the island appears to be full of temptations which you can't appear to stay away from.");
    SetRace( CCharacter.halfling );
    SetMessage(-1,"If Todd offers you one of his cakes today you simply won't be able to resist.");
    SetMessage(1,"Nothing appears to be frightening to you at all today!");
    SetMessage(2,"Today you can rent the most stubborn donkey in town, and it would still do what you want.");
    SetRace( CCharacter.orc );
    SetMessage(-1,"You wonder why everyone appears to be laughing at you today...");
    SetMessage(1,"Today there could be some tension between yourself and the others ... you simply don't feel like giving in.");
    SetMessage(2,"Even with a small snarl, all the animals run into hiding and people stop talking in fear.");
    SetRace( CCharacter.gnome );
    SetMessage(-1,"Gold and silver attract you even more today ... you'd nearly sell yourself.");
    SetMessage(1,"Let the tall ones talk. You might be small but you are prepared for everything.");
    SetMessage(2,"Today you are confident enough to haggle and get the best prices for your wares.");
    SetRace( CCharacter.dwarf );
    SetMessage(-1,"A greedy voice inside your head keeps singing: Beer, beer is all I need, for a beer I'd do any deed.");
    SetMessage(1,"Borgate sent you a dove and told you that there will be free beer today, but you could even resist that.");
    SetMessage(2,"Today your head is as hard as the rocks you are usually around.");
    SetRace( CCharacter.fairy );
    SetMessage(1,"Is that the smell of fresh cake? Hurry on, a bit further, phew, well done. This nearly spoiled your plans today, but you were able to resist.");
    SetMessage(2,"Nothing is going to spoil your plans today, not even if you saw the … seccond biggest cake in the world lying in your path.");
    SetMessage(-1,"You don't really feel like playing jokes today, your confidence appears to have evaporated.");
    SetRace( CCharacter.elf );
    SetMessage(-1,"Today you don't really feel like showing off your nobility, you'd rather let down this facade and have a beer instead.");
    SetMessage(1,"A long life can be a heavy burden ... but not for you, you feel so motivated today.");
    SetMessage(2,"You walk with a noble stride today, and people quickly notice your wisdom and charisma.");
    SetRace( CCharacter.lizardman );
    SetMessage(-1,"You hang your tail down low and lower your head. You don't feel so very confident on the land today.");
    SetMessage(2,"You walk with a proud stride, worthy of someone created by the Goddess.");
    SetMessage(1,"The sun is shining, the water is just the right temperature and there are tons of delicious fish ... but you have other plans and stick to them.");
    SetRace( CCharacter.goblin );
    SetMessage(-1,"True, goblins are easy to scare, but already your own shadow frightens you today, making your ears shake.");
    SetMessage(1,"Even if an orc growls at you today you feel quite confident that you will not scream.");
    SetMessage(2,"Let's hope that nobody would offer you a shiny coin today. You are determined to refuse it as a matter of principle today.");

    SetAttribute( "intelligence" );
    SetRace( CCharacter.human );
    SetMessage(-1,"After having noticed after quite some time that your hands do not belong into your shoes, you'd rather stay away from challenging work today.");
    SetMessage(2,"Nothing can confuse you today, not even the senseless murmuring of Augham. Seems like your mind is working brilliantly today.");
    SetMessage(1,"Your brain is yearning for some challenge today. How about reading a book, you will see it's not that difficult.");
    SetRace( CCharacter.orc );
    SetMessage(1,"Correct! Orc is spelled with a c. Will you remember this tomorrow?");
    SetMessage(2,"Today you managed to write down three sentences without misspelling a single word. Congratulations!");
    SetMessage(-1,"Today you are not even able to write your name ... must be your writing-bone, huh?!");
    SetRace( CCharacter.dwarf );
    SetMessage(-1,"It took you some time to notice that your breakfast beer is in the barrel, not in the anvil. If someone wonders about the new tap ...?");
    SetMessage(2,"You are pondering about some very complicated smithing methods, but today you even got behind their secrets and would be able to realise them.");
    SetMessage(1,"The hammer falls down onto the iron and forms it ... not that difficult, is it! You are confident that you will learn the next lessons easily.");
    SetRace( CCharacter.gnome );
    SetMessage(1,"Your huge head never was really empty, but today you seem to be even smarter, just wait and see!");
    SetMessage(2,"If elves are said to be intelligent, then you must be a shrunken version of an elf.");
    SetMessage(-1,"You seem to have some problems with counting... you don't have enough fingers it seems");
    SetRace( CCharacter.goblin );
    SetMessage(1,"Many goblins are stupid and keep running in circles ... but you are today smart enough to recognise how to stop.");
    SetMessage(2,"Wasn't there a goblin mage in Lor-Angur? Today human scholars look into your eyes and wonder whether you're related to them.");
    SetMessage(-1,"You cannot think of anything really smart today. Well ... you still got your ears, why don't you play a bit with them?");
    SetRace( CCharacter.fairy );
    SetMessage(1,"Wouldn't it be better to throw cherries from the highest top of the trees so that you cannot be spotted at all? This and other flashes of genius come into your mind today.");
    SetMessage(2,"The tricks you play on your victims today are well-thought out and will surely result in a lot of giggles.");
    SetMessage(-1,"Lucky you that your wings move automatically, all this coordination thing would be way too much for you today.");
    SetRace( CCharacter.halfling );
    SetMessage(2,"Flashes of brilliance come into your mind: if you already have snacks in the morning, with lunch and dinner and in-betweens ...you won't even need to take a break.");
    SetMessage(1,"The fresh air blowing across the fields is quite pleasant. Your head feels clear and prepared for new things.");
    SetMessage(-1,"If you were green, not that hairy and had larger ears ... you would have probably fit in quite perfectally in a goblin school today!");
    SetRace( CCharacter.elf );
    SetMessage(1,"Today you really feel that you actually DO outsmart humans.");
    SetMessage(-1,"You don't feel quite as intelligent as usual today. You wonder what may have happened.");
    SetMessage(2,"If you could share your intelligence today, half of the isle would be smart enough to study the arcane arts.");
    SetRace( CCharacter.lizardman );
    SetMessage(2,"You should watch and study the fishes and their dances at the shore today, you will easily think up a way of catching more fish in less time.");
    SetMessage(-1,"You are not able to think much more than the fish you eat today.");
    SetMessage(1,"You feel more intelligent today, time to show those landlings which is the most intelligent race.");

    SetAttribute( "agility" );
    SetRace( CCharacter.human );
    SetMessage(2,"Your nerves and muscles are tensed like the string of a bow. You have the feeling that you could run three times around the tavern before Borgate empties one mug of beer.");
    SetMessage(1,"You managed to get rid of an annoying fly just with a swift move of your hand ... and you feel like this was not the last one of those fast actions today.");
    SetMessage(-1,"After getting up this morning you noticed a snail getting dressed faster than you did ... very strange.");
    SetRace( CCharacter.lizardman );
    SetMessage(2,"Your speed in the water is incredible today, your body moves coordinated and gracefully.");
    SetMessage(1,"Today you will be able to catch every single fish that you can see.");
    SetMessage(-1,"Every fish you catch appears to slip from your claws, not a good sign.");
    SetRace( CCharacter.fairy );
    SetMessage(-1,"Your wings feel stiff today, only with huge effort you manage to fly a bit faster. No races against the wind today for you.");
    SetMessage(2,"Today you can race against the wind and you will win.");
    SetMessage(1,"You are faster than the birds today.");
    SetRace( CCharacter.halfling );
    SetMessage(1,"In spite of your short legs you still are faster than some of the long-legs today.");
    SetMessage(2,"Did just somebody call for a snack? Quick, today you will surely be the first!");
    SetMessage(-1,"Such huge feet are good for standing steadily, but also made for rather strolling than running, right?");
    SetRace( CCharacter.dwarf );
    SetMessage(1,"Today you were the first in the mine.");
    SetMessage(2,"Today nobody manages to empty his mug faster than you, not even Borgate...");
    SetMessage(-1,"You are small and fat and being small and fat does not go together well with being fast. At least not today.");
    SetRace( CCharacter.gnome );
    SetMessage(1,"Today you were really quick with counting your coins.");
    SetMessage(2,"You rush faster than most, and bag all the best deals..");
    SetMessage(-1,"Let business be business today, you rather feel like being lazy and making yourself comfortable.");
    SetRace( CCharacter.goblin );
    SetMessage(1,"You manage to clean your ears in no time today.");
    SetMessage(-1,"A generous person could give out those beloved shiny coins today, but every other goblin would be faster than you.");
    SetMessage(2,"Orcs may be bigger, but they're not going to catch you today.");
    SetRace( CCharacter.elf );
    SetMessage(1,"Long legs are quicker, which you prove again today.");
    SetMessage(2,"If you wouldn't be called an elf, everyone would name you \"running wind\" today.");
    SetMessage(-1,"Long legs are nice for running bot today they simply want to be stretched instead of carrying your weight.");
    SetRace( CCharacter.orc );
    SetMessage(1,"What's the point of running from you today? It won't do them any more good than just giving up..");
    SetMessage(2,"How about getting chased yourself today? You would not have the slightest problem to escape today.");
    SetMessage(-1,"Today you'd rather look for a slow victim, maybe a dwarf?");

    SetAttribute( "constitution" );
    SetRace( CCharacter.orc );
    SetMessage(-1,"Your arms get tired more easily when beating up somebody.");
    SetMessage(1,"No problem if an ogre beats you up today, you can easily bear a few hits from your larger kinsman.");
    SetMessage(2,"Today you won't have any problem to encounter a raging bunch of dwarves; with your persistence you will be a hard nut to crack.");
    SetRace( CCharacter.halfling );
    SetMessage(1,"Today you can easily bear a few more hits when playing onionball.");
    SetMessage(-1,"Maybe you should eat a cake more today, you stomach does not feel that well.");
    SetMessage(2,"You can spend all day baking cakes today, you don't seem to be getting tired anytime soon");
    SetRace( CCharacter.gnome );
    SetMessage(1,"Your fingers do not become that easily sore today when polishing your coins.");
    SetMessage(2,"You will be able to bargain loudly for quit some time even if others already crawl on the ground with a sore throat.");
    SetMessage(-1,"Your huge head is buzzing as if someone had whacked you with a sock full of coins; perhaps it would be best to avoid fights.");
    SetRace( CCharacter.goblin );
    SetMessage(1,"Whether it was due to the bottle of goblin-brew in the morning or not, you feel really healthy. Let the search a the lost coin begin!");
    SetMessage(-1,"The many worrying happenings on this isle weakened your body recently. Maybe you should take another rest before starting the day or not start it at all.");
    SetMessage(2,"May the orcs pull your ears today, you will hardly feel it. Your body is so resistant today.");
    SetRace( CCharacter.fairy );
    SetMessage(1,"Today you should also manage longer flights, you don't feel tired at all.");
    SetMessage(2,"Today you can play 'catch' with the rabbits, they may be faster but you're not going to tire easily.");
    SetMessage(-1,"You feel rather sore today, and your wings more fragile than usual. Perhaps its best to stay at home and rest.");
    SetRace( CCharacter.elf );
    SetMessage(1,"You may look tall and thin, but you're definitely not weak. Not today at least..");
    SetMessage(2,"There's a reason elves live longer than everyone, you feel very healthy today.");
    SetMessage(-1,"The numerous memories collected in your long elven life really depress you today, at least you don't feel really healthy.");
    SetRace( CCharacter.dwarf );
    SetMessage(2,"Wasn't there a drinking contest today? Awesome, you feel like being able to beat the records!");
    SetMessage(1,"You can spend all day and all night looking for precious metals today, you don't feel tired at all.");
    SetMessage(-1,"You have a bad hungover, you don't know if it was too much of drinking or mining. In any case you feel like not being able to bear any effort today.");
    SetRace( CCharacter.lizardman );
    SetMessage(1,"You're not sure if its your imagination or not, but your scales feel harder today.");
    SetMessage(2,"Tanora appears to have blessed you with her waters, you feel healthy and energetic.");
    SetMessage(-1,"Your scales itch, your teeth hurt, your eyes are watery ... you don't really feel like facing the day.");
    SetRace( CCharacter.human );
    SetMessage(-1,"Your aching muscles are really annoying today and protest against long, physical effort.");
    SetMessage(1,"Perhaps today may be a good day for exploring, you're not going to get tired.");
    SetMessage(2,"You had a vision of a golem beating you but you didn't even take a scratch. Maybe you should really try this today?!");

    SetAttribute( "essence" );
    SetRace( CCharacter.halfling );
    SetMessage(1,"Today you feel in touch with nature and far more cheerful than usual.");
    SetMessage(2,"You seem to have a spiritual connection with everything today, you even appear to understand the plants growing in the garden.");
    SetMessage(-1,"You feel empty and not willing to do much. ");
    SetRace( CCharacter.dwarf );
    SetMessage(-1,"You feel as dry as the rocks that are around you.. ");
    SetMessage(1,"You feel different today. You have no idea what it is, but it feels good.");
    SetMessage(2,"Irmorom's spirit is strong in you today, he is clearly watching over you.");
    SetRace( CCharacter.fairy );
    SetMessage(2,"Your magical illusions appear more realistic today.");
    SetMessage(1,"You feel more cheerful, for no good reason though.");
    SetMessage(-1,"Your tricks don't appear to be as perfect as they used to be; you wonder why. ");
    SetRace( CCharacter.orc );
    SetMessage(2,"Malachin is in your soul,  watching over you.. ");
    SetMessage(-1,"Have the gods abandoned you? You don't appear to be very lucky with the hunt today. ");
    SetMessage(1,"You appear to know what's going on around you... you can almost.. sense the spirits of your victims today.");
    SetRace( CCharacter.elf );
    SetMessage(2,"You control the arcane arts without problems today, you are in touch with oneself. ");
    SetMessage(-1,"You feel a disturbance between the mind and the soul today, not a very nice feeling. ");
    SetMessage(1,"You feel in touch with your inner self.");
    SetRace( CCharacter.human );
    SetMessage(2,"The meditation really paid off, you feel good about yourself. ");
    SetMessage(1,"Perhaps the dreams you had today meant something, you feel as if a friendly spirit is communicating to you. ");
    SetMessage(-1,"You feel like an empty shell of a person, something is missing. ");
    SetRace( CCharacter.goblin );
    SetMessage(2,"The gods appear to be watching over you today, and you feel more confident. ");
    SetMessage(1,"Although physically weaker than most orcs, you feel spiritually stronger then they are today. ");
    SetMessage(-1,"You seem to be very unlucky today, you wonder what's wrong with you. ");
    SetRace( CCharacter.gnome );
    SetMessage(1,"Your mechanical works seem to have a hint of magic inside them, they're working like a charm. ");
    SetMessage(2,"Everything you do today seems better than usual, somebody from above is watching over you. ");
    SetMessage(-1,"You can't get anything right today, and you feel strange. ");
    SetRace( CCharacter.lizardman );
    SetMessage(-1,"Has the Goddess abandoned you? You feel insecure about your standing with her. ");
    SetMessage(1,"Zelphia smiles over you today, making your life feel worthwhile. ");
    SetMessage(2,"Tanora has given you a blessing today, you feel much closer to her than usual.");

    SetAttribute( "dexterity" );
    SetRace( CCharacter.human );
    SetMessage(-1,"While attempting to brush your hair, your comb flies out of your hands and onto the floor. Perhaps you should give your fingers a break.");
    SetMessage(2,"Your fingers seem to be capable of the craziest movements, which you had never thought possible! ");
    SetMessage(1,"You should go play darts in the tavern today, you'll probably hit a bullseye without much effort. ");
    SetRace( CCharacter.dwarf );
    SetMessage(-1,"While smithing your hammer hits your fingers more often than usual. ");
    SetMessage(2,"You manage to smith your blades as sharp and shiny as never before. ");
    SetMessage(1,"The goods you smith today look really neat. ");
    SetRace( CCharacter.elf );
    SetMessage(1,"As it is fitting for elves to do, you could definitely shoot an apple off somebody's head today, either with bow and arrow or even something else. ");
    SetMessage(-1,"Long fingers don't seem to be very precise fingers. Not today at least. ");
    SetMessage(2,"Your carving appears to be more precise than usual. There is a reason elves are known for their artistic talents, and this is it. ");
    SetRace( CCharacter.halfling );
    SetMessage(-1,"Today you get stuck everywhere with your hairy feet. ");
    SetMessage(1,"One of Todd's nicest cakes appears to have disappeared right off the shelf without him noticing...and comfortably found itself in your pocket.");
    SetMessage(2,"Your opponents better beware in today's onionball competition. There's no way they're going to dodge one of your onions today. ");
    SetRace( CCharacter.lizardman );
    SetMessage(1,"A quick swipe in the water, and a fish finds itself in your claws. ");
    SetMessage(-1,"You try to scratch your back but end up clawing a deep mark in it. Your fingers aren't very obedient today. ");
    SetMessage(2,"Your claws are useful for much more things than fighting. Especially the way they move so gracefully today.");
    SetRace( CCharacter.gnome );
    SetMessage(2,"You had a dream in which you had to open a treasure chest with nothing but an inch of wire. You had succeeded and now wonder whether this could have been an omen. ");
    SetMessage(1,"Your hand-writing is really neat today. ");
    SetMessage(-1,"Bottles slip out of your hand today and smash on the ground. You should be more careful.. ");
    SetRace( CCharacter.goblin );
    SetMessage(1,"You flip coins around in the air with ease today, you can even grab someone else's coins without much trouble.");
    SetMessage(2,"With your quick fingers you see many new ways of picking your nose today! ");
    SetMessage(-1,"You just almost panicked as you could not get your stiff finger out of your ear! ");
    SetRace( CCharacter.fairy );
    SetMessage(1,"Throwing cherry pips at people appears to be much easier for you today, you can hit them wherever you wish.");
    SetMessage(2,"Untying people's shoes while they're not looking was never so fun... and never so easy either. ");
    SetMessage(-1,"You drop a piece of the cake you were eating and dirty your clothes, naughty fingers.");
    SetRace( CCharacter.orc );
    SetMessage(-1,"You try throwing a stone at the pig and end up hitting someone else by accident.");
    SetMessage(2,"You skilfully clean your prey, separating the meat from the bones without any waste at all. ");
    SetMessage(1,"Your stubby and hard fingers appear to be looser and more allowing today.");

    SetAttribute( "strength" );
    SetRace( CCharacter.fairy );
    SetMessage(1,"Today you feel like you can lift an entire cake! ");
    SetMessage(2,"Your arms seem like strongest blades of grass today, you are surely able to life an entire cake and a half. ");
    SetMessage(-1,"Your arms are so saggy, you'll barely be able to lift even the smallest cake. ");
    SetRace( CCharacter.gnome );
    SetMessage(1,"Get your wares paid in copper coins today, they don't weigh much today. ");
    SetMessage(2,"The cow won't need to carry your coins today, you feel as strong as anything. ");
    SetMessage(-1,"Your large head swings from side to side, you seem hardly able to carry its weight today. ");
    SetRace( CCharacter.halfling );
    SetMessage(1,"If you intend to sell your sweet cakes and bread today, do so in huge amounts, you will carry them with no effort. ");
    SetMessage(2,"Your short legs feel like tree logs today, teeming with strength. ");
    SetMessage(-1,"You don't seem to be able to carry too much today, perhaps someone else should carry your cooking ingredients ");
    SetRace( CCharacter.goblin );
    SetMessage(1,"Did you plan to collect many \"useless\" things today? Go ahead and don't worry about them being too heavy. ");
    SetMessage(2,"Do not fear an encounter with an orc today, you could kick his knee and half his leg would fall off. ");
    SetMessage(-1,"Your ears hang low today in order to not waste much strength. ");
    SetRace( CCharacter.elf );
    SetMessage(1,"Today you don't only look elegant and neat, you also feel strong enough to build a new tree house. ");
    SetMessage(2,"If today any raging humans should be in the forest, throw them to a treetop... at least your arms feel like you'll be able to. ");
    SetMessage(-1,"Being thin seems to have its disadvantages, your muscles don't feel too strong today ");
    SetRace( CCharacter.dwarf );
    SetMessage(1,"If someone mocks you today because of your height, don't hesitate to punch him, your arms are as hard as iron today thanks to the beer. ");
    SetMessage(2,"How about a lesson in lifting beer barrels today? Some dozen you will surely be able to lift ... ");
    SetMessage(-1,"When mining recently you must have caught a lumbago ... no chance today of carrying heavy weights. ");
    SetRace( CCharacter.lizardman );
    SetMessage(1,"Your scales would want to fall out today to make room for your growing muscles. ");
    SetMessage(2,"Perhaps a fight with a shark is in order today, you feel strong enough to send him swimming away for his life ");
    SetMessage(-1,"Lucky for you that there are smaller fishes, the large ones you could not lift today. ");
    SetRace( CCharacter.human );
    SetMessage(1,"Today everything seems to be lighter to you. Did you train your biceps recently? ");
    SetMessage(2,"Nobody's going to try to mug you today, your muscles will scare them away ");
    SetMessage(-1,"You shouldn't sit down today, otherwise you will run the risk of not being able to get back on your feet. ");
    SetRace( CCharacter.orc );
    SetMessage(1,"Today it should be possible for you to carry a bit of meat more from your hunt to your cave. ");
    SetMessage(2,"Nobody is going to challenge you today! Your already-impressive muscles look far more impressive today. ");
    SetMessage(-1,"You shouldn't challenge your brothers and sisters in arm wrestling today.");
end;

initMessages();

initMessages = nil;