module("content.dailymessage", package.seeall);

GoodBadDayMessages = {};

function GetMessage( Lang, Attrib, Race, Effect )
    if not GoodBadDayMessages then
        return false;
    end
    if not GoodBadDayMessages[Lang] then
        return false;
    end
    if not GoodBadDayMessages[Lang][Attrib] then
        return false;
    end
    if not GoodBadDayMessages[Lang][Attrib][Race] then
        return false;
    end
    return GoodBadDayMessages[Lang][Attrib][Race][Effect];
end

function initMessages()
    local currentLang;
    local currentAttrib;
    local currentRace;

    local SetLanguage = function( newLang )
        currentLang = newLang;
    end;

    local SetAttribute = function( newAttrib )
        currentAttrib = newAttrib;
    end;

    local SetRace = function( newRace )
        currentRace = newRace;
    end;

    local SetMessage = function( Effect, Message )
        if not GoodBadDayMessages[currentLang] then
            GoodBadDayMessages[currentLang] = {};
        end
        if not GoodBadDayMessages[currentLang][currentAttrib] then
            GoodBadDayMessages[currentLang][currentAttrib] = {};
        end
        if not GoodBadDayMessages[currentLang][currentAttrib][currentRace] then
            GoodBadDayMessages[currentLang][currentAttrib][currentRace] = {};
        end
        GoodBadDayMessages[currentLang][currentAttrib][currentRace][Effect] = Message;
    end;

    SetLanguage( Player.german );
    SetAttribute( "strength" );
    SetRace( Character.fairy );
    SetMessage(1,"Heute fühlst du dich, als könntest du einen ganzen Kuchen heben!");
    SetMessage(2,"Deine Arme sind wie Grashalme aus Eisen, heute kriegst du bestimmt einen ganzen Kuchen und einen ganzen halben hoch!");
    SetMessage(-1,"Deine Arme sind so schlaff, mehr als ein Kuchenstück wirst du heute kaum lupfen können.");
    SetRace( Character.gnome );
    SetMessage(1,"Lass dir deine Waren heute ruhig in Kupfermünzen bezahlen, die wiegen doch heute kaum was.");
    SetMessage(2,"Auf die Kuh könntest du heute verzichten, bist doch zur Zeit selbst stark wie ein laufender Meter purer Kraft.");
    SetMessage(-1,"Dein großer Kopf pendelt hin und her, so schlecht kannst du sein Gewicht heute tragen.");
    SetRace( Character.halfling );
    SetMessage(1,"Wenn du heute vor hattest, deine süßen Kuchen und Brote zu verkaufen, dann am besten in großen Portionen, die buckelst du heute locker..");
    SetMessage(2,"Deine kurzen Beine fühlen sich heute an wie Baumstämme, so sehr strotzt du vor Kraft.");
    SetMessage(-1,"Du scheinst heute nicht so viel tragen zu können. Such dir lieber wen, der dir deine Kochwerkzeuge und Zutaten schleppt.");
    SetRace( Character.goblin );
    SetMessage(-1,"Deine Ohren hängen heute lasch hinab, um Kraft zu sparen.");
    SetMessage(1,"Wolltest du heute nicht besonders viele \"nutzlose\" Dinge einsammeln? Dann los und keine Angst, du könntest dich bernehmen.");
    SetMessage(2,"Soll dir heute bloß mal einer von den Orks unter die Nase kommen, dann gibt es einen Tritt gegen das Knie, dass das halbe Bein abreißt!");
    SetRace( Character.elf );
    SetMessage(1,"Heute siehst du nicht nur elegant und edel aus, heute hast du auch Kraft genug, um mal ein neues Baumhaus zu bauen.");
    SetMessage(2,"Sollten wieder frevelnde Menschen im Wald zu Gange sein, werf sie am besten gleich in die Baumkrone. Soviel traust du deinen Armen zumindest zu.");
    SetMessage(-1,"Dünn zu sein hat auch Nachteile, deine Muskeln fühlen sich heute einfach schlapp an.");
    SetRace( Character.dwarf );
    SetMessage(-1,"Als du das letzte Mal geschürft hast, muss dir ein Hexenschuss reingefahren sein, richtig viel tragen ist heute zumindest nicht drin.");
    SetMessage(1,"Wenn dich heute jemand deiner Größe wegen aufziehen will, zögere nicht, ihn zurechtweisen, denn deine Arme sind vom vielen Bier fest wie Eisen.");
    SetMessage(2,"Wie wärs mit einer Lektion im Bierfassstemmen für die Kleinen? Einige Dutzend bekommst du heute sicher so...");
    SetRace( Character.lizardman );
    SetMessage(1,"Deine Schuppen wollen heute schon ausfallen, um deinen aufgeblähten Muskeln Platz zu machen!");
    SetMessage(-1,"Wie gut, dass es auch kleine Fische gibt, die Großen hättest du kaum in dein Lager schleppen können.");
    SetMessage(2,"Vermutlich steht heute ein Kampf mit einem Hai an der Tagesordnung, du fühlst dich zumindest so, als könntest du einen in die Flucht schlagen.");
    SetRace( Character.human );
    SetMessage(1,"Alles lässt sich heute etwas leichter bewegen als sonst. Hast du in letzter Zeit ein wenig was für deine Arme getan?");
    SetMessage(2,"Niemand wird dich heute ärgern, denn deine Muskeln schrecken alle ab.");
    SetMessage(-1,"Setz dich lieber nicht hin, am Ende schaffst du es nicht mal mehr auf die eigenen Beine, so schwer fühlst du dich heute.");
    SetRace( Character.orc );
    SetMessage(2,"Niemand wird es heute wagen, dich herauszufordern! Deine schon beeindruckenden Muskeln wirken noch größer.");
    SetMessage(1,"Du solltest es heute wohl schaffen, etwas mehr Fleisch von deiner erlegten Beute in die Höhle zu schleppen.");
    SetMessage(-1,"Armdrücken mit deinen Brüdern oder Schwestern solltest du heute unterlassen.");

    SetAttribute( "constitution" );
    SetRace( Character.orc );
    SetMessage(-1,"Deine Arme werden schneller lahm als sonst, wenn du mal wieder jemanden aufmischt.");
    SetMessage(1,"Soll sich heute doch ruhig ein Oger an dir vergreifen, die paar Schläge deines größeren Artverwandten steckst du locker ein.");
    SetMessage(2,"Heute kann dir ruhig ein wilder Mob Zwerge begegnen, bei deiner Ausdauer werden sie sich die Zähne an dir ausbeißen.");
    SetRace( Character.halfling );
    SetMessage(1,"Heute wirst du sicher einige Treffer mehr beim Zwiebelballspiel aushalten.");
    SetMessage(-1,"Vielleicht solltest du mal mehr Kuchen essen, dein Magen fühlt sich nicht ganz so gut an.");
    SetMessage(2,"Heute kannst du den ganzen Tag damit verbringen, Kuchen zu backen, du scheinst einfach nicht müde zu werden.");
    SetRace( Character.gnome );
    SetMessage(1,"Beim Münzen polieren werden deine Finger gar nicht mehr so schnell wund wie sonst.");
    SetMessage(2,"Du feilscht noch lange und lautstark, während andere schon mit entzündetem Kehlkopf vor dir zu Boden kriechen.");
    SetMessage(-1,"Dein großer Kopf brummt, als hätte dich wer mit einer Socke voller Kleingeld verhaun, wag dich lieber nicht an größere Gegner heran.");
    SetRace( Character.goblin );
    SetMessage(1,"Ob es nun die Flasche Goblinbräu zum Morgen war oder nicht, du fühlst dich so richtig gesund. Möge die Suche nach einer verlorenen Münze beginnen!");
    SetMessage(-1,"Die vielen beunruhigenden Dinge dieser Welt haben deinen Körper in letzter Zeit arg mitgenommen. Vielleicht solltest du ein wenig ausruhen, bevor du den Tag beginnst oder gehst ihn locker an.");
    SetMessage(2,"Sollen die Orks dir heute ruhig an den Ohren ziehen, du spürst es kaum, so widerstandsfähig ist dein Körper heute.");
    SetRace( Character.fairy );
    SetMessage(1,"Heute solltest du auch längere Flüge meistern können, du ermüdest nicht all zu sehr.");
    SetMessage(2,"Spiel heute ruhig \"Fangen\" mit den Hasen, denn sie mögen zwar schneller sein aber du hast den längeren Atem.");
    SetMessage(-1,"Du fühlst dich heute äußerst verspannt und auch deine Flügel sind zerbrechlicher als sonst. Vielleicht wäre es das beste, zu Hause zu bleiben und auszuruhen.");
    SetRace( Character.elf );
    SetMessage(1,"Du magst groß und schmal aussehen aber du bist definitiv nicht schwach. Zumindest heute nicht..");
    SetMessage(2,"Es gibt einen Grund, wieso Elfen länger leben als jeder andere. Du spürst die Kraft deiner Rasse in dir am heutigen Tag.");
    SetMessage(-1,"Die vielen Errinnerungen, die sich in so einem Elfenleben ansammeln, drücken dir heute ziemlich aufs Gemüt, so ganz gesund ist dir heute zumindest nicht zumute.");
    SetRace( Character.dwarf );
    SetMessage(2,"War für heute eigentlich ein Wetttrinken angesetzt? Ja? Großartig, denn du fühlst dich, als könntest du deine Rekordmarke knacken!");
    SetMessage(1,"Verbringe heute ruhig den ganzen Tag und auch die ganze Nacht in der Mine damit, nach wertvollen Metallen zu suchen, müde wird ein Zwerg wie du nicht.");
    SetMessage(-1,"Ein Mordskater plagt dich, sei es vom vielen Trinken oder vom vielen Schürfen, auf jeden Fall glaubst du nicht, dass du sehr großen Anstrengungen heute gewachsen bist.");
    SetRace( Character.lizardman );
    SetMessage(1,"Du bist dir nicht sicher, ob es Einbildung ist oder nicht aber deine Schuppen fühlen sich heute robuster an.");
    SetMessage(2,"Tanora hat dich heute wohl gesegnet mit ihren Wassern, du fühlst dich kräftig und energiegeladen.");
    SetMessage(-1,"Deine Schuppen jucken, deine Zähne schmerzen und deine Augen tränen, so richtig zum Auftauchen ist dir heut gar nicht.");
    SetRace( Character.human );
    SetMessage(-1,"Ein Muskelkater plagt dich und protestiert spürbar gegen längere, körperliche Anstrengungen.");
    SetMessage(1,"Heute scheint ein guter Tag für Erkundungen zu sein, dein Körper ist richtig erfrischt und bereit für Anstrengung.");
    SetMessage(2,"Du hattest eine Vision von einem Golem, der dich schlug, doch du hast nicht mal ein blaues davongetragen! Vielleicht lässt sich das ja in der Realität auch mal probieren.");

    SetAttribute( "agility" );
    SetRace( Character.human );
    SetMessage(2,"Du bist heute gespannt wie ein Flitzebogen und hast das Gefühl, selbst Adron könnte sein Bier heute nicht so schnell trinken, wie du drei Mal um die Taverne rennst.");
    SetMessage(1,"Ausnahmsweise gelang es dir heute, eine anhängliche Fliege mit einer schnellen Bewegung deiner Hand zu plätten und du meinst, dies könnte nicht die letzte gewesen sein.");
    SetMessage(-1,"Beim Aufstehen hast du eine Schnecke bemerkt, die sich schneller anzog, als du es tatest... merkwürdig.");
    SetRace( Character.lizardman );
    SetMessage(2,"Deine Geschwindigkeit im Wasser ist heute enorm, dein Körper bewegt sich koordiniert und elegant.");
    SetMessage(1,"Kein Fisch schwimmt dir heute mehr davon!");
    SetMessage(-1,"Jeder Fisch scheint dir heute durch die Krallen zu gehen, kein gutes Zeichen.");
    SetRace( Character.fairy );
    SetMessage(-1,"Deine Flügel sind heute so steif und möchten sich nicht recht entfalten, nur mit Mühe gelingt es dir, etwas schneller zu fliegen. Wettrennen gegen den Wind fallen heute wohl flach");
    SetMessage(2,"Heute fliegst du mit dem Wind um die Wette und gewinnst.");
    SetMessage(1,"Die Vögel hast du heute schon überrundet.");
    SetRace( Character.halfling );
    SetMessage(1,"Trotz deiner kurzen Beine bist du heut doch um einiges schneller als so manch Großer.");
    SetMessage(2,"Hat da gerade wer zum Zwischenimbiss gerufen?! Schnell, heute wirst du Erster sein!");
    SetMessage(-1,"So große Füße sind zwar gut für festen Stand aber auch eher für gemächliches Laufen gedacht, oder?");
    SetRace( Character.dwarf );
    SetMessage(1,"Heute warst du als Erster in der Mine.");
    SetMessage(2,"Keiner leert sein Bier heute so schnell wie du, nicht mal Adron...");
    SetMessage(-1,"Klein und dick bist du und was klein und dick ist, ist nicht schnell. Zumindest nicht heute!");
    SetRace( Character.gnome );
    SetMessage(1,"Heute hast du dein Geld erstaunlich schnell durchgezählt.");
    SetMessage(2,"Heute läufst du schneller als die meisten und sackst deshalb auch die besten Handelsgeschäfte ein.");
    SetMessage(-1,"Sollen Geschäfte doch Geschäfte sein, du bist heute mal so richtig faul und gemütlich.");
    SetRace( Character.goblin );
    SetMessage(1,"Den Popel, der dir schon gestern nervigerweise im Ohr hing, entfernst du heute mit verblüffender Geschwindigkeit.");
    SetMessage(-1,"Eine großzügige Person könnte heute deine geliebten scheinenden Münzen verteilen, doch alle anderen Goblins wären wohl schneller.");
    SetMessage(2,"Orks mögen größer sein, doch sie werden dich heute nicht zu fassen kriegen.");
    SetRace( Character.elf );
    SetMessage(1,"Lange Beine sind schnell, das beweißt du heute mal wieder allen.");
    SetMessage(2,"Würde man dich nicht Elf nennen, wärst du heute \"Fegender Wind\" !");
    SetMessage(-1,"Lange Beine sind ja schön gut aber heute wollen auch die einfach nur übereinander geschlagen werden, nicht zum Rennen benutzt.");
    SetRace( Character.orc );
    SetMessage(1,"Welchen Sinn würde es machen, heute vor dir wegzulaufen? Deine Opfer könnten sich doch auch einfach ergeben.");
    SetMessage(2,"Wie wär es denn, wenn du zur Abwechslung mal dich jagen lässt? Wegzukommen sollte zumindest keine Schwierigkeit werden.");
    SetMessage(-1,"Such dir diesen Tag lieber langsamere Beute, einen Zwergen vielleicht?");

    SetAttribute( "intelligence" );
    SetRace( Character.human );
    SetMessage(-1,"Nachdem du heute Morgen längere Zeit brauchtest, um zu erkennen, dass deine Hände nicht in die Schuhe gehören, solltest du dich wohl gar nicht erst an anspruchsvolle Aufgaben heranwagen.");
    SetMessage(2,"Nichts, was dir heute jemand sagt, kann dich verwirren, nicht mal sinnloses Gebrabbel, denn du hast heute den Scharfsinn gepachtet!");
    SetMessage(1,"Deine heutige Verfassung: Dein Kopf würde heute gerne etwas komplizierteres unternehmen, als nur den stumpfen Alltag mitzuerleben. Lies doch mal ein Buch, du wirst sehen, so schwer fällt dir das nicht!");
    SetRace( Character.orc );
    SetMessage(1,"Richtig! Ork schreibt man mit k! Hoffentlich behältst du das bis morgen.");
    SetMessage(2,"Heute sind dir drei Sätze ohne Rechtschreibfehler gelungen, Respekt.");
    SetMessage(-1,"Deinen Namen, der dir für gewöhnlich schon Probleme bereitet, bekommst du heute erst gar nicht hin, muss an deinem Schreibknochen liegen..., oder?");
    SetRace( Character.dwarf );
    SetMessage(-1,"Es hat dich einige Zeit gekostet, bis du erkannt hast, dass dein Frühstücksbier aus dem Fass, nicht aus dem Amboss kommt. Ob der neue Zapfhahn auffallen wird...?");
    SetMessage(2,"Dir spuken Gedanken von höchst komplizierten Schmiedemethoden durch den Kopf aber du blickst schnell durch und könntest sie in die Tat umsetzen.");
    SetMessage(1,"Der Hammer haut auf das Eisen und formt es...so schwer ist das nicht! Du bist zuversichtlich, dass du dir die nächsten Lektionen eher einprägen kannst!");
    SetRace( Character.gnome );
    SetMessage(1,"Dein großer Kopf war ja ohnehin nie leer aber heute bist du noch gescheiter als sonst! Du wirst schon sehen.");
    SetMessage(2,"Wenn man Elfen nachsagt, dass sie intelligent sind, so sagt man dir nach, dass du der geschrumpfte Urelf seist.");
    SetMessage(-1,"Heute scheint dir das Zählen nicht leicht zu fallen...irgendwie hast du nicht genug Finger dazu.");
    SetRace( Character.goblin );
    SetMessage(1,"Viele Goblins sind dumm und laufen im Kreis herum..., doch du bist heute immerhin so schlau, dass du weißt, wie du wieder stehen bleiben könntest.");
    SetMessage(2,"Gibt es nicht diesen einen Goblin, der Magier in Lor-Angur ist? Menschliche Gelehrte sehen dir heute in die Augen und fragen dich, ob du nicht mit ihm verwandt bist!");
    SetMessage(-1,"So richtig was sinnvolles will dir heute nicht einfallen aber es bleiben ja noch immer deine Ohren, vielleicht kann man mit denen was spielen...");
    SetRace( Character.fairy );
    SetMessage(1,"Wäre es nicht besser, Kirschen aus den höchsten Baumkronen zu werfen, damit der Getroffene dich gar nicht erst entdecken kann? Solche und mehr Geistesblitze gehen dir zur Zeit durch den Kopf.");
    SetMessage(2,"Deine Streiche heute sind wohl durchdacht und werden dir sicherlich viel Gekicher einbringen.");
    SetMessage(-1,"Wie gut, dass deine Flügel sich schon von alleine bewegen, diese ganze Koordinationsgeschichte wäre dir heute schon zuviel gewesen.");
    SetRace( Character.halfling );
    SetMessage(2,"Dir gehen geniale Ideen durch den Kopf: Wenn du Morgens, Mittags, Nachts und des Öfteren was dazwischen isst...wieso machst du dann eigentlich noch Pausen?");
    SetMessage(1,"Die viele frische Luft, die du auf dem Feld einatmest bringt eben wohl was, dein Kopf ist ganz frei geblasen und offen für Neues!");
    SetMessage(-1,"Wärst du grün, nicht so haarig und hättest größere Ohren, würd man dich in eine Schule für Goblins stecken!");
    SetRace( Character.elf );
    SetMessage(1,"Heute spürst du einmal mehr, dass du, was zumindest den Bildungsgrad angeht, den Menschen noch überlegener bist als sonst.");
    SetMessage(-1,"Heute fühlst du dich einfach nicht so aufgeweckt, wie sonst. Du fragst dich, woran das liegen mag.");
    SetMessage(2,"Teile deine Weisheit und die halbe Welt wäre schlau genug, Magie zu lernen.");
    SetRace( Character.lizardman );
    SetMessage(2,"Du solltest den Tanz der Fische vor der Küste beobachten, heute kannst du sicherlich mit Leichtigkeit einen Plan entwickeln, der dich in kürzerer Zeit mehr Fische fangen lässt.");
    SetMessage(-1,"Viel mehr als \"Fisch\" kannst du heute nicht groß denken.");
    SetMessage(1,"Heute fühlst du dich so richtig aufgeweckt. Zeit, den Landwesen mal zu zeigen, welche Rasse die schlauste ist.");

    SetAttribute( "willpower" );
    SetRace( Character.human );
    SetMessage(1,"Heute weißt du, was du möchtest und Andere scheinen eher gewillt zu sein, dir dabei zu helfen.");
    SetMessage(2,"Am heutigen Tage könnte nicht mal die gewitzteste Fee dich dazu bringen, zu tun, was sie möchte.");
    SetMessage(-1,"Die Welt scheint heute voll mit Versuchungen, welchen du scheinbar nicht widerstehen kannst.");
    SetRace( Character.halfling );
    SetMessage(-1,"Wenn dir Todd heute wieder einen seiner Kuchen anbietet, wirst du kaum widerstehen können...");
    SetMessage(1,"Heute schüchtert dich gar nichts ein!");
    SetMessage(2,"Heute könntest du den bockigsten Esel ausleihen und er würde sich deinem Willen beugen.");
    SetRace( Character.orc );
    SetMessage(-1,"Du fragst dich, wieso heute alle über dich zu lachen scheinen...");
    SetMessage(1,"Es könnte heute schon so manch Spannung geben mit deiner Umwelt, denn du fühlst dich heute nicht wie einer, der nachgibt.");
    SetMessage(2,"Heute reicht schon das leiseste Knurren deinerseits aus, um alle Tiere flüchten und Personen verstummen zu lassen.");
    SetRace( Character.gnome );
    SetMessage(-1,"Gold und Silber locken dich heute noch mehr als sonst, beinah möchtest du dich selbst verkaufen.");
    SetMessage(1,"Sollen die Großen nur reden, du magst klein sein aber dennoch zu allem bereit.");
    SetMessage(2,"Du bist heute mehr als zuversichtlich genug fürs Feilschen und wirst wohl die besten Preise für deine Waren heraus handeln.");
    SetRace( Character.dwarf );
    SetMessage(-1,"Eine gierige Stimme in deinem Kopf singt lallend: Bier, Bier, Bier, gib mir Bier und ich gehorch nur dir!");
    SetMessage(1,"Adron sandte dir ein göttliches Zeichen und lud dich zu Freibier ein aber du kannst sogar dem widerstehen.");
    SetMessage(2,"Du fühlst dich wie ein Fels in der Brandung, unbeugsam und stolz.");
    SetRace( Character.fairy );
    SetMessage(1,"Riechst du grad nicht Kuchen?! Schnell, weiterfliegen! Ein bischen noch..jetzt..gnn..pfu, vorbei. Beinah hätte dich das von deinen heutigen Plänen abgelenkt aber du hast widerstanden!");
    SetMessage(2,"Nichts wird dir deine heutigen Pläne durcheinander bringen, nicht einmal wenn du den ... zweitgrößten Kuchen der Welt finden würdest.");
    SetMessage(-1,"Dir ist heute nicht wirklich nach Streiche spielen, dein Selbstvertrauen muss verdampft sein.");
    SetRace( Character.elf );
    SetMessage(-1,"Heute ist dir gar nicht mal so sehr nach edlem Benehmen, viel lieber würdest du die Fassade fallen lassen und dir ein Bier genehmigen.");
    SetMessage(1,"Ein langes Leben kann eine Belastung sein, doch nicht für dich, du bist so motiviert wie eh und je.");
    SetMessage(2,"Du gehst heute sehr anmutig und schnell merkt jeder um dich herum, wie weise und charmant du bist.");
    SetRace( Character.lizardman );
    SetMessage(-1,"Du lässt den Schwanz und Kopf hängen, fühlst dich auch nicht so wohl auf dem Land.");
    SetMessage(2,"Stolz und aufrecht ist dein Gang heute, würdig einem Wesen, das von einer Göttin geschaffen wurde.");
    SetMessage(1,"Die Sonne scheint, das Wasser ist angenehm warm und darinnen schwimmen tonnenweise die Fische...aber du hast anderes vor und bleibst dabei.");
    SetRace( Character.goblin );
    SetMessage(-1,"Sicher, Goblins sind ängstlich, doch dir jagt heute schon dein eigener Schatten leichte Schauer durch die Ohren.");
    SetMessage(1,"Sollen die Orks dich doch angrollen, heute bist du zuversichtlich, dass du zumindest nicht schreien wirst.");
    SetMessage(2,"Hoffentlich bietet dir heute keiner eine schöne Münze an, denn du bist so entschlossen, dass du diese prompt ablehnen würdest, schon allein aus Prinzip.");

    SetAttribute( "perception" );
    SetRace( Character.human );
    SetMessage(-1,"Ein Oger schlich sich heute unbemerkt an dir vorbei...");
    SetMessage(2,"Dank deines scharfen Gehörs bemerktest du glücklicherweise noch rechtzeitig die Fee mit dem Wassereimer über dir");
    SetMessage(1,"Du hast heute diese vermaledeite Stufe, die dir schon den einen oder anderen Zeh gekostet hat, eher bemerkt als sonst.");
    SetRace( Character.elf );
    SetMessage(1,"Deine spitzen Ohren zucken heute schon bei geringerem Lärm, deine Gehörgänge scheinen richtig durchgeputzt..");
    SetMessage(2,"Deine Augen sind so scharf wie die eines Adlers und deine Ohren so empfindlich wie die eines Hasens.");
    SetMessage(-1,"Sehr aufmerksam kannst du dich heute nicht nennen.");
    SetRace( Character.fairy );
    SetMessage(-1,"Sei heute besonders auf der Hut, wenn Streiche spielende Feen unterwegs sind. Deine Flügel hören sich so laut an, dass du keinen bemerkst, der sich anpirscht.");
    SetMessage(2,"Du spürst selbst die leichteste Brise und kannst zudem jede Person, egal wie weit entfernt, erkennen.");
    SetMessage(1,"Heute riechst du mit Leichtigkeit den Nektar der Blumen und kannst sogar die Insekten darauf ausmachen.");
    SetRace( Character.lizardman );
    SetMessage(1,"Du schmeckst deinen Fisch heute viel intensiver als für gewöhnlich.");
    SetMessage(2,"Nichts kann deine Nase heute trügen und selbst deine Augen blicken an Land so scharf wie im Wasser.");
    SetMessage(-1,"Die Fische schwimmen heute oft an dir vorbei, ohne dass du es bemerkst.");
    SetRace( Character.dwarf );
    SetMessage(-1,"Das viele Bier, dass du so gerne trinkst, hat dich ein wenig benebelt und du hörst nicht so gut. Sehen war sowieso nie dein Ding, könnte man heute meinen.");
    SetMessage(1,"Dir fallen schon die kleinsten Risse in deinen Schmiedearbeiten auf, es wird Zeit, sie mal alle unter die Lupe zu nehmen.");
    SetMessage(2,"Heute wird dir niemand dein Bier stehlen, denn du bekommst alles mit, was um dich herum passiert.");
    SetRace( Character.gnome );
    SetMessage(1,"Heute sollte keiner versuchen, dir minderwertige Ware anzubieten, denn dir würde das nicht entgehen.");
    SetMessage(2,"Deine Waage kannst du heute zu Hause lassen, Gewichte werden heute mit bloßer Hand bestimmt.");
    SetMessage(-1,"Irgendwas muss dir ins Auge geflogen sein, denn du siehst nicht so gut!");
    SetRace( Character.goblin );
    SetMessage(1,"Deine Ohren vibrieren sanft, wenn jemand näher kommt und auch deine Nase nimmt alles viel intensiver wahr.");
    SetMessage(-1,"Du hast dir einen scheußlichen Schnupfen eingefangen, der dir deinen unbestechlichen Geruchssinn trübt.");
    SetMessage(2,"Echsen mögen Fische im Wasser sehen, wenn andere von der spiegelnden Oberfläche geblendet sind, doch du hast schon die Schuppen gezählt.");
    SetRace( Character.orc );
    SetMessage(-1,"Du isst heute eigentlich nur schlechtes Fleisch, doch du merkst es nicht.");
    SetMessage(2,"Heute bemerkst du die Elfen, bevor sie dich auch nur gehört haben.");
    SetMessage(1,"Heute witterst du deine Beute mit Leichtigkeit, nichts entgeht dir.");
    SetRace( Character.halfling );
    SetMessage(2,"Jeder Kuchen und jedes Brot duftet für dich wie das Paradies.");
    SetMessage(-1,"Einige Feen haben sich einen Spaß daraus gemacht, dein Haar zu verknoten aber bisher ist dir davon noch nichts bekannt.");
    SetMessage(1,"Vorhin hattest du dir mal wieder die Ohren geputzt und siehe da, du hörst so gut wie noch nie.");

    SetAttribute( "essence" );
    SetRace( Character.halfling );
    SetMessage(1,"Heute bist du im Einklang mit der Natur und sehr viel fröhlicher als sonst.");
    SetMessage(2,"Offenbar hast du eine spirituelle Verbindung mit allem um dich herum, du scheinst sogar die Pflanzen zu verstehen, die im Garten wachsen.");
    SetMessage(-1,"Du fühlst dich leer und nicht zu vielem aufgelegt.");
    SetRace( Character.dwarf );
    SetMessage(-1,"Du fühlst dich so trocken wie die Felsen, die dich umgeben.");
    SetMessage(1,"Heute fühlst du dich anders. Du hast keine Ahnung, was es ist, aber es ist gut.");
    SetMessage(2,"Irmoroms Geist ist heute stark in dir, er schaut dir spürbar über die Schulter.");
    SetRace( Character.fairy );
    SetMessage(2,"Deine magischen Illusionen erscheinen heute viel realer.");
    SetMessage(1,"Du bist heute einfach nur fröhlich.");
    SetMessage(-1,"Deine Streiche scheinen heute nicht so perfekt, wie sie sein sollten, du fragst dich, wieso.");
    SetRace( Character.orc );
    SetMessage(2,"Malachin ist heute bei dir und beschützt dich.");
    SetMessage(-1,"Haben die Götter dich verlassen? Du scheinst heute nicht sehr glücklich über die Jagd.");
    SetMessage(1,"Du spürst, was sich heute um dich herum tut. Beinah nimmst du sogar wahr, was in sich in deinen Opfern abspielt.");
    SetRace( Character.elf );
    SetMessage(2,"Du kontrollierst die arkanen Könste heute mit Leichtigkeit, du bist im reinen mit dir selbst.");
    SetMessage(-1,"Du fühlst eine Unebenmäßigkeit zwischen deinem Geist und deiner Seele, kein sehr angenehmes Gefühl.");
    SetMessage(1,"Du bist eins mit deinem Inneren.");
    SetRace( Character.human );
    SetMessage(2,"Die Meditation zahlt sich aus, du fühlst dich wohl.");
    SetMessage(1,"Wahrscheinlich hatte dein Traum etwas zu bedeuten, es scheint dir, dass ein freundlicher Geist sich mit dir in Verbindung setzt.");
    SetMessage(-1,"Du fühlst dich heute wie die leere Hülle eines Menschen.");
    SetRace( Character.goblin );
    SetMessage(2,"Die Götter scheinen über dich zu wachen und das steigert deine Zuversicht.");
    SetMessage(1,"Obwohl physisch schwächer als die meisten Orks, bist du zumindest heute geistig Stärker als sie.");
    SetMessage(-1,"Du scheinst heute richtig viel Pech zu haben, was wohl nur mit dir los ist.");
    SetRace( Character.gnome );
    SetMessage(1,"Deine handwerklichen Arbeiten scheinen heute einen Funken Magie in sich zu bergen, alle Geräte funktionieren wie von Zauberhand geführt.");
    SetMessage(2,"Alles scheint heute einfach besser zu sein, als würde jemand von weit oben dir über die Schulter blicken.");
    SetMessage(-1,"Nichts mag dir heute so richtig gelingen und du fühlst dich komisch.");
    SetRace( Character.lizardman );
    SetMessage(-1,"Hat Tanora sich heute von dir abgewendet? Du bist unsicher über dein Verhältnis zu ihr.");
    SetMessage(1,"Zelphia sieht gütig auf dich herab heute und macht dein Leben lebenswert.");
    SetMessage(2,"Tanora hat dir heute ihren Segen erteilt, du fühlst dich ihr so viel mehr verbunden als sonst.");

    SetAttribute( "dexterity" );
    SetRace( Character.human );
    SetMessage(-1,"Als du versuchst, dir die Haare zu kämmen, fällt dir der Kamm aus der Hand zu Boden. Vielleicht solltest du deinen Fingern eine Pause gewähren.");
    SetMessage(2,"Deine Finger machen heute die verrücktesten Bewegungen mit, von denen du vorher gar nicht gedacht hättest, dass sie möglich sind.");
    SetMessage(1,"Als du vorhin einen Popel weggeschnippt hast, ist er genau in einem Astloch gelandet, wo es sonst kein anderes gibt, gut geschossen.");
    SetRace( Character.dwarf );
    SetMessage(-1,"Beim Schmieden haust du dir öfters auf die Finger, als sonst.");
    SetMessage(2,"Deine Klingen werden heute so scharf und gerade wie noch nie!");
    SetMessage(1,"Die Schmiedewaren, die du heute herstellst, sehen richtig ordentlich aus.");
    SetRace( Character.elf );
    SetMessage(1,"Wie es sich für Elfen gehört, könntest du heute sicherlich jemanden einen Apfel vom Kopf schießen, egal ob mit Pfeil und Bogen oder mit etwas anderem.");
    SetMessage(-1,"Lange Finger müssen nicht auch präzise Finger sein. Zumindest nicht heute.");
    SetMessage(2,"Deine Schnitzereien scheinen heute sehr viel genauer. Es gibt also doch noch Gründe, wieso Elfen berühmt sind für ihre handwerkliche Begabung.");
    SetRace( Character.halfling );
    SetMessage(-1,"Du bleibst heute überall mit deinen haarigen Füßen hängen.");
    SetMessage(1,"Wenn Todd heute vielleicht ein bischen unachtsam ist, sollte es dir gelingen, einen seiner Kuchen zu stibitzen.");
    SetMessage(2,"Wie so oft hast du vorhin mal wahllos eine faule Zwiebel durch die Gegend geworfen, um nicht aus der Übung zu kommen...und hast eine Fliege im Flug erwischt!");
    SetRace( Character.lizardman );
    SetMessage(1,"Kein Fisch kann deinen flinken Krallen heute entschlüpfen.");
    SetMessage(-1,"Als du dich vorhin am Rücken kratzen wolltest, mussten einige Schuppen daran glauben. Erst die Krallen einfahren!");
    SetMessage(2,"Eine Schuppe an deiner Schulter hat sich vorhin quer gestellt und in kunstvollen Verrenkungen, die dir so schnell keiner nachmacht, ist es dir gelungen, den Fehler zu beheben.");
    SetRace( Character.gnome );
    SetMessage(2,"Du hattest einen Traum, in dem du eine geheimnisvolle Schatztruhe mit nur einem Zentimeter Draht öffnen musstest. Es gelang erstaunlicherweise und du glaubst, es könnte ein Omen gewesen sein.");
    SetMessage(1,"Deine Handschrift ist heute richtig ansehnlich.");
    SetMessage(-1,"Flaschen rutschen dir heute aus den Fingern und zerbrechen am Boden. Du solltest vorsichtiger sein.");
    SetRace( Character.goblin );
    SetMessage(1,"Du schnippst heute Münzen mit soviel Können wie fast nie und selbst das Stibitzen von Geld anderer sollte dir nicht schwer fallen.");
    SetMessage(2,"Mit deinen flinken Fingern eröffnen sich dir heute ganz neue Dimensionen des Nasebohrens!");
    SetMessage(-1,"Jetzt hätte dich aber beinah die Panik gepackt, eine ganze Minute lang hast du deine steifen Finger nicht mehr aus den Ohren bekommen!");
    SetRace( Character.fairy );
    SetMessage(1,"Kirschkuchen zu werfen erscheint dir heute soviel einfacher, du triffst einfach beinah alles.");
    SetMessage(2,"Das Aufdröseln von anderer Leute Schnürsenkel während sie nicht gucken, das wäre heute lustig...und fiele dir auch nicht schwer.");
    SetMessage(-1,"Du hast ein Kuchenstück fallen lassen, als du es gerade essen wolltest und hast deine Kleidung eingesaut, böse Finger!");
    SetRace( Character.orc );
    SetMessage(-1,"Du versuchst, einen Stein nach einem Schwein zu werfen, triffst aber jemand anderes.");
    SetMessage(2,"Du hast deine Beute säuberlich ausgeweidet und das Fleisch von den Knochen getrennt, ohne auch nur einen Bissen zu verschwenden.");
    SetMessage(1,"Deine stummeligen und harten Finger wirken heute lockerer als sonst.");

    SetLanguage( Player.english );
    SetAttribute( "perception" );
    SetRace( Character.human );
    SetMessage(-1,"You must have rubbed your eyes raw in your sleep because they aren't quite as sharp as usual.");
    SetMessage(2,"Things around you come into clear focus like never before, and you have a strong sense of awareness.");
    SetMessage(1,"Your feet move smoothly today even over otherwise difficult terrain.");
    SetRace( Character.elf );
    SetMessage(1,"Your pointed ears twitch at the slightest noise today, and you have a better sense of your surroundings as well.");
    SetMessage(2,"Your eyes feel as sharp as a hawk's today and your ears are as sensitive as a rabbit's.");
    SetMessage(-1,"Your natural senses feel disconnected today.");
    SetRace( Character.fairy );
    SetMessage(-1,"Watch out for other fairies playing tricks on you today, your hearing doesn't feel as keen.");
    SetMessage(2,"You feel the slightest breeze today, and hear the footsteps of even the most distant person.");
    SetMessage(1,"You can easily smell the nectar of flowers, and even spot insects with ease.");
    SetRace( Character.lizardman );
    SetMessage(1,"The fish seem to be moving slower today and easier to catch.");
    SetMessage(2,"Nothing can fool your nose today, and even your eyes can clearly see on land.");
    SetMessage(-1,"Fish that you would normally catch escape your grasp today.");
    SetRace( Character.dwarf );
    SetMessage(-1,"The brew you consumed must have been stronger than usual because your hearing and sight are dull today.");
    SetMessage(1,"You see minor flaws in your work effortlessly today.");
    SetMessage(2,"Your focus is impeccable today and you feel like nothing could escape your attention.");
    SetRace( Character.gnome );
    SetMessage(1,"If anyone tries to sell you inferior goods today you'll be able to spot even the slightest of imperfections.");
    SetMessage(2,"Everything from sight to touch today feels perfect and you are completely aware of your surroundings.");
    SetMessage(-1,"Something must have found itself into your eyes because your vision is rather murky today.");
    SetRace( Character.goblin );
    SetMessage(1,"Your nose is keen today and your sense of sound feels heightened.");
    SetMessage(-1,"Your nose is stopped up today and is really affecting your sense of smell.");
    SetMessage(2,"Your senses feel sharp today- prey beware.");
    SetRace( Character.orc );
    SetMessage(-1,"Your sense of smell is off today and you have difficulty telling if food is fresh.");
    SetMessage(2,"You feel like not even an elf could match your senses today.");
    SetMessage(1,"It will be easy to avoid mating today, you can track that scent from afar.");
    SetRace( Character.halfling );
    SetMessage(2,"Your going to find it hard to focus today with food smelling this unbelievably good!");
    SetMessage(-1,"What tragedy when bread smells so dull, and you find it far too easy to stub your toe.");
    SetMessage(1,"Someone must have cleaned your ears while you slept because you can hear much better today.");

    SetAttribute( "willpower" );
    SetRace( Character.human );
    SetMessage(1,"Your ambition is strong today and you feel confident.");
    SetMessage(2,"By the gods you feel focused today. No task is too small or too big to complete this day.");
    SetMessage(-1,"Nargùn has got to be tempting you today for every vice seems to be calling all at once.");
    SetRace( Character.halfling );
    SetMessage(-1,"Cake, pie, mulligan, wine, beer, and a feast set for a king distracts your throughts from work today.");
    SetMessage(1,"For some reason you feel rather brave today.");
    SetMessage(2,"You feel in control like never before and all you can think is watch out world!");
    SetRace( Character.orc );
    SetMessage(-1,"You almost succumbed to mating rituals today, better get a grip.");
    SetMessage(1,"Today there could be some tension between yourself and the others ... and you feel stuburn.");
    SetMessage(2,"The creator beckons for your pride today and nothing feels impossible.");
    SetRace( Character.gnome );
    SetMessage(-1,"Gold and silver attract you even more today ... you'd nearly sell yourself.");
    SetMessage(1,"You feel seven feet tall today and ready to complete a big task.");
    SetMessage(2,"You feel like nothing could stop you today from creating something truly magnificent.");
    SetRace( Character.dwarf );
    SetMessage(-1,"A greedy voice inside your head keeps singing: Beer, beer is all I need, for a beer I'd do any deed.");
    SetMessage(1,"Your mind is focused today on making your will come true.");
    SetMessage(2,"Your intestinal fortitude could even draw Irmorom's attention today.");
    SetRace( Character.fairy );
    SetMessage(1,"No amount of fun or trepidation could deter you today.");
    SetMessage(2,"The elements bend to your will today and nature seems to beckon your call.");
    SetMessage(-1,"You don't really feel like playing jokes today, your confidence appears to have evaporated.");
    SetRace( Character.elf );
    SetMessage(-1,"Temptation is strong today and several vices call to you.");
    SetMessage(1,"A long life can be a heavy burden ... but not for you, you feel motivated today.");
    SetMessage(2,"Nature bends to your will today and you feel a rushing confidence in your heart.");
    SetRace( Character.lizardman );
    SetMessage(-1,"Today might be a day for humble reflection.");
    SetMessage(2,"The Mother seems to walk beside you today as you feel a cool confidence over your scales.");
    SetMessage(1,"Your plans are in clear sight today and temptation is easily avoided.");
    SetRace( Character.goblin );
    SetMessage(-1,"You feel a chill on your spine having nothing to do with the weather.");
    SetMessage(1,"Today you feel like getting some work done.");
    SetMessage(2,"You feel like you could punch an orc today and get away with it.");

    SetAttribute( "intelligence" );
    SetRace( Character.human );
    SetMessage(-1,"Your head simply hurts and thinking makes it worse.");
    SetMessage(2,"Your brain recalls information effortlessly today even some thoughts better left forgotten.");
    SetMessage(1,"Your responses are sharp and quick today.");
    SetRace( Character.orc );
    SetMessage(1,"Thinking doesn't hurt as much today.");
    SetMessage(2,"The Father has called upon you to devise a scheme worthy of his praise.");
    SetMessage(-1,"Your head is pounding today, every thought feels like a splinter digging into your brain.");
    SetRace( Character.dwarf );
    SetMessage(-1,"How could you have forgotten so much in just one day?");
    SetMessage(2,"A sudden rush of understanding washes over you giving you visions of complex schematics and inventions.");
    SetMessage(1,"You feel a spark of understanding about a subject you were trying to learn.");
    SetRace( Character.gnome );
    SetMessage(1,"Your huge head has never been empty, but today you seem to be even smarter, just wait and see.");
    SetMessage(2,"If elves are said to be supremely intelligent, then you must be a shrunken version of one!");
    SetMessage(-1,"You seem to have some problems with counting... you don't have enough fingers it seems.");
    SetRace( Character.goblin );
    SetMessage(1,"For a moment you ponder why goblins should be afraid of orcs- surely you could outsmart them, but then you look at your kin and fully understand their shortcomings.");
    SetMessage(2,"You feel cunning today and know you could outsmart any foe.");
    SetMessage(-1,"You feel nothing between your ears today.");
    SetRace( Character.fairy );
    SetMessage(1,"You think of several tricks and pranks to pull today.");
    SetMessage(2,"Your mind knows no limits today and everything seems obtainable.");
    SetMessage(-1,"Even flying requires mental effort today; your brain just doesn't want to work.");
    SetRace( Character.halfling );
    SetMessage(2,"You feel more cunning than a fox today. What will you do: bake wondrous treats, craft something magnificent, or play a good joke on a friend?");
    SetMessage(1,"The fresh air blowing across the fields is quite pleasant. Your head feels clear and prepared for new things.");
    SetMessage(-1,"If only your skin was green and your ears a bit longer could you have an excuse to why you feel so dumb today.");
    SetRace( Character.elf );
    SetMessage(1,"Even the memories of your early youth come to your mind quickly; age and experience are with you today.");
    SetMessage(-1,"The day feels melancholy and despite your efforts your thoughts seem lax and unfocused.");
    SetMessage(2,"Truly the Five bless you this day, your mind has never been clearer or more focused.");
    SetRace( Character.lizardman );
    SetMessage(2,"You feel a divine enlightenment and things you might have struggled with yesterday will come easy today.");
    SetMessage(-1,"Despite any effort your thoughts remain murky as a cow pond.");
    SetMessage(1,"Your thoughts flow like cool water and your mind yearns for a challenge.");

    SetAttribute( "agility" );
    SetRace( Character.human );
    SetMessage(2,"As you awake a surge of raw energy flows through you, and you notice a considerable difference in your flexibility.");
    SetMessage(1,"You must have slept well, your body feels poised and ready for some action.");
    SetMessage(-1,"Your bones ache, your feet hurt, and there is a creak in your neck. Today is not going to be a good day for a race.");
    SetRace( Character.lizardman );
    SetMessage(2,"The Mother blesses you this day and you can feel the limberness from snout to tail.");
    SetMessage(1,"Your movements are less restricted than usual.");
    SetMessage(-1,"You must have slept on your tail wrong because your balance and limberness is off.");
    SetRace( Character.fairy );
    SetMessage(-1,"Your wings feel stiff today, only with huge effort you manage to fly a bit faster. No races against the wind today!");
    SetMessage(2,"You wings beat faster than ever giving you great speed.");
    SetMessage(1,"You are faster than the birds today.");
    SetRace( Character.halfling );
    SetMessage(1,"You feel a skip in your step today and know you could run if you had to.");
    SetMessage(2,"Jack might be nimble but today you feel like you could catch him.");
    SetMessage(-1,"Your legs feel like bread pudding and don't care to walk.");
    SetRace( Character.dwarf );
    SetMessage(1,"Although dwarves aren't known for their limberness today you feel quite different about that oppinion.");
    SetMessage(2,"Your legs must be well rested because they've never felt so poised to run.");
    SetMessage(-1,"You must have worked your legs too hard yesterday because they feel like lead.");
    SetRace( Character.gnome );
    SetMessage(1,"For some reason you feel like dancing, better make a bunch of coins to have a reason.");
    SetMessage(2,"A fairy must have sprinkled you with its dust because you feel incredibly nimble today.");
    SetMessage(-1,"Your legs don't want to get up this morning- hope an orc doesn't try to catch you today.");
    SetRace( Character.goblin );
    SetMessage(1,"You feel quite limber today; running shouldn't be a problem.");
    SetMessage(-1,"You can't help noticing you've lost a step today in your quickness.");
    SetMessage(2,"No prey is going to escape your quickness today.");
    SetRace( Character.elf );
    SetMessage(1,"You feel the explosiveness in your legs today, and coupled with your long legs you should outrun most.");
    SetMessage(2,"Your body feels incredible today, like a taught bow ready to unleash your stored potential.");
    SetMessage(-1,"Your legs are tight and will require much stretching if you plan to run today.");
    SetRace( Character.orc );
    SetMessage(1,"You feel like an animal today, each muscle is poised for a chase.");
    SetMessage(2,"Is it mating season? Who cares you feel like you could outrun a panther today!");
    SetMessage(-1,"Today you'd rather look for a slow victim, maybe a dwarf?");

    SetAttribute( "constitution" );
    SetRace( Character.orc );
    SetMessage(-1,"You must have eaten some bad meat because your body feels weak and vulnerable.");
    SetMessage(1,"Your blood boils for a fight today and you know you won't go down easily.");
    SetMessage(2,"The powerful aura of the Father inspires you today, and any foe willing to strike might not be able to outlast your endurance.");
    SetRace( Character.halfling );
    SetMessage(1,"Today you can easily bear a few more hits when playing onionball.");
    SetMessage(-1,"Maybe you should eat more cake today, your stomach does not feel too well.");
    SetMessage(2,"Oldra must have given you her blessing today because you feel full of energy and life.");
    SetRace( Character.gnome );
    SetMessage(1,"Work won't be difficult today when you feel this good all over.");
    SetMessage(2,"You've never felt better! Your ready to haggle and work for however many hours it takes to get your reward.");
    SetMessage(-1,"You feel like a dwarf beat you with a sack full of coins all over your body. You're pretty sure a fly could beat you up today.");
    SetRace( Character.goblin );
    SetMessage(1,"Your body feels like a wood nymph sprinkled magic dust on it while you slept because you feel so healthy and energetic.");
    SetMessage(-1,"Perhaps a scorned mate poisoned you in your sleep because you feel terrible.");
    SetMessage(2,"You must've ate well yesterday because your body has never felt this strong and healthy.");
    SetRace( Character.fairy );
    SetMessage(1,"Managing a long flight won't be difficult today, you feel great!");
    SetMessage(2,"Today you can play 'catch' with the rabbits, they may be faster but you're not going to tire at all it seems.");
    SetMessage(-1,"You feel rather sore today, and your wings more fragile than usual. Perhaps its best to stay at home and rest.");
    SetRace( Character.elf );
    SetMessage(1,"Your meditations must be paying off because your body feels great.");
    SetMessage(2,"It is no wonder why elves live longer than any other race when you feel this incredibly fabulous.");
    SetMessage(-1,"The numerous memories collected in your long elven life really depresses you today, and your health suffers as a result.");
    SetRace( Character.dwarf );
    SetMessage(2,"If there is a record for consuming beer you feel like you could break it ten fold!");
    SetMessage(1,"Your energy level is quite high today and you know you could last a few more rounds wrestling if you had to.");
    SetMessage(-1,"There is no mistaking this feeling, hangover.");
    SetRace( Character.lizardman );
    SetMessage(1,"You're not sure if it's your imagination or not, but your scales feel harder today.");
    SetMessage(2,"The Mother appears to have blessed you with her waters, you feel healthy and energetic!");
    SetMessage(-1,"Your scales itch, your teeth hurt, your eyes are watery ... you don't really feel like facing the day.");
    SetRace( Character.human );
    SetMessage(-1,"For some reason you have a pounding headache and your body feels weak and faint.");
    SetMessage(1,"Perhaps today may be a good day for exploring because you body feels quite capable of a long journey.");
    SetMessage(2,"You awake feeling more confident and resilient than ever after dreaming about going toe-to-toe with a golem!");

    SetAttribute( "essence" );
    SetRace( Character.halfling );
    SetMessage(1,"Today you feel in touch with nature and far more cheerful than usual.");
    SetMessage(2,"You seem to have a spiritual connection with everything today- you even sense the flowers nearby need watering.");
    SetMessage(-1,"You feel empty and not willing to do much.");
    SetRace( Character.dwarf );
    SetMessage(-1,"Your spirit feels as dry and empty as a mug without beer.");
    SetMessage(1,"You feel different today. You have no idea what it is, but it feels good.");
    SetMessage(2,"Irmorom's spirit is strong in you today, he is clearly watching over you.");
    SetRace( Character.fairy );
    SetMessage(2,"Your magical illusions appear more realistic today.");
    SetMessage(1,"You feel more cheerful for no apparent reason.");
    SetMessage(-1,"Your tricks don't appear to be as perfect as they used to be; you wonder why.");
    SetRace( Character.orc );
    SetMessage(2,"You feel a divine presences inspiring you today.");
    SetMessage(-1,"Has the Father abandoned you? You don't appear to be very lucky with the hunt today.");
    SetMessage(1,"Your heart has a lightness to it today. Love or heartburn perhaps?");
    SetRace( Character.elf );
    SetMessage(2,"Nature, spirit, and life seem to come together perfectly everywhere you go.");
    SetMessage(-1,"You feel a disturbance between mind and soul today, not a pleasant feeling.");
    SetMessage(1,"You feel in touch with your inner self.");
    SetRace( Character.human );
    SetMessage(2,"A powerful aura surrounds you today uplifting your spirits and overall mood.");
    SetMessage(1,"As you awake from an inspirational dream you feel it transcend into reality.");
    SetMessage(-1,"You feel a slight empties as you awake making you wonder what is missing.");
    SetRace( Character.goblin );
    SetMessage(2,"You feel a strong confidence as if the gods are watching over you this day.");
    SetMessage(1,"You can't place your bony finger on it, but something is lifting your spirits noticeably today.");
    SetMessage(-1,"You seem to be very unlucky today, you wonder what's wrong with you.");
    SetRace( Character.gnome );
    SetMessage(1,"Your mechanical works seem to have a hint of magic inside them, they're working like a charm.");
    SetMessage(2,"Everything you do today seems better than usual,  as if somebody from above is watching over you.");
    SetMessage(-1,"You can't get anything right today, and you feel strange.");
    SetRace( Character.lizardman );
    SetMessage(-1,"Has the Goddess abandoned you? You feel insecure about your standing with her.");
    SetMessage(1,"Zelphia smiles over you today, making your life feel worthwhile.");
    SetMessage(2,"The Mother has given you a blessing today and you've never felt closer.");

    SetAttribute( "dexterity" );
    SetRace( Character.human );
    SetMessage(-1,"Your fingers ache a bit today. Perhaps not the best day to try and make something.");
    SetMessage(2,"There must be something supernatural going on because your fingers move like never before.");
    SetMessage(1,"You feel confident in using your hands today. Perhaps a game of knife throwing at the tavern?");
    SetRace( Character.dwarf );
    SetMessage(-1,"Irmorom must be trying to humble you because your hands aren't working like they normally do.");
    SetMessage(2,"Soon after you wake you realize your hands are itching to create something truly incredible.");
    SetMessage(1,"Your faculty to create things is suddenly heightened when you discover an astonishing new strength in your hands.");
    SetRace( Character.elf );
    SetMessage(1,"With a new found strength in your hands craftwork or bowhunting should come easier today.");
    SetMessage(-1,"Finer details in crafting will be difficult if your hands continue to hurt this way.");
    SetMessage(2,"Your fingers are magic today and respond to your every whim.");
    SetRace( Character.halfling );
    SetMessage(-1,"Perhaps you have been working too hard because your poor little hands hurt and ache.");
    SetMessage(1,"Your fingers are nimble today. How best to use them?");
    SetMessage(2,"Your hands are strong and nimble like never before. Watch out whoever decides to play you in onionball!");
    SetRace( Character.lizardman );
    SetMessage(1,"Your claws will be lethal today with this uncanny precision you have with your hands.");
    SetMessage(-1,"Try as you may you can't seem to get your fingers to function properly.");
    SetMessage(2,"There must be some kind of blessing on your hands today because they move and respond flawlessly.");
    SetRace( Character.gnome );
    SetMessage(2,"You awake from a dream where you picked a lock to a grand treasure chest. Perhaps your fingers are indeed magical.");
    SetMessage(1,"Your fingers are itching for something to do.");
    SetMessage(-1,"Try as you may but your fingers are not responding correctly.");
    SetRace( Character.goblin );
    SetMessage(1,"Your fingers are nimble today, making it easier to pick your nose.");
    SetMessage(2,"You have effortless command over your hands and fingers today. Pickpocketing would be a cinch for sure.");
    SetMessage(-1,"It feels like an orc slept on your hands last night because they tingle and hurt.");
    SetRace( Character.fairy );
    SetMessage(1,"Throwing cherry pits at people appears to be much easier for you today, you can hit them wherever you wish.");
    SetMessage(2,"Untying people's shoes while they're not looking was never so fun... and never so easy either.");
    SetMessage(-1,"Your little fingers hurt today. How ever will you play pranks?");
    SetRace( Character.orc );
    SetMessage(-1,"Don't try to throw rocks at an annoying human today you might just end up breaking your own finger.");
    SetMessage(2,"The Father must want you to slap the Hellbriar out of someone with hands as powerful and precise as these!");
    SetMessage(1,"You seem to have greater control of your hands and fingers today. Perhaps some stumpy boxing, goblin snatching, or just some crafting is in order?");

    SetAttribute( "strength" );
    SetRace( Character.fairy );
    SetMessage(1,"Today you feel like you could lift an entire cake!");
    SetMessage(2,"Watch out world we might have the strongest fairy in all the land today!");
    SetMessage(-1,"No one expects fairies to be strong but you might struggle lifting your arms today.");
    SetRace( Character.gnome );
    SetMessage(1,"Is that a muscle!? It is! It is!");
    SetMessage(2,"Nargùn must be playing tricks on you because you feel remarkably strong today.");
    SetMessage(-1,"Today is going to be a bad day if you continue to struggle holding your own head up.");
    SetRace( Character.halfling );
    SetMessage(1,"You notice your right forearm muscle is more pronounced and so is your left!");
    SetMessage(2,"Look out onionball players! Your arm is feeling strong and you might just smash someone's face in if you get a throw.");
    SetMessage(-1,"Your relaxed muscles are relaxing further today, success!");
    SetRace( Character.goblin );
    SetMessage(1,"Oh yah! Your kleptomania might run rampant today with you feeling this strong.");
    SetMessage(2,"You feel usually strong today but do you really think you could take an orc?");
    SetMessage(-1,"Even holding your ears up has become difficult. Gods you feel weak.");
    SetRace( Character.elf );
    SetMessage(1,"Living this long does not come without advantages. You can feel without a doubt that you are a bit stronger today.");
    SetMessage(2,"You work ethic and diet has paid off today. You can tell you are at the peak of your physical strength.");
    SetMessage(-1,"Not all days can be perfect and your muscles are living proof today. They feel weak and tired for some reason.");
    SetRace( Character.dwarf );
    SetMessage(1,"Must be the beer surging through your veins because you definitely feel stronger!");
    SetMessage(2,"Holy Irmorom! You feel like an ox today. Watch-out long legs and green faced slime!");
    SetMessage(-1,"Your suffering from a case of lumbago today good luck doing any heavy lifting.");
    SetRace( Character.lizardman );
    SetMessage(1,"You feel a noticeable difference in your strength. Hard work won't be a problem for you today!");
    SetMessage(2,"Your beloved Mother must have blessed you with her cool waters because you feel a torrent of power flowing throughout your entire body.");
    SetMessage(-1,"As you wake your lower back feels sore, there's a tightness in your chest, and you feel slightly nauseated. Is this how being pregnant feels?");
    SetRace( Character.human );
    SetMessage(1,"It's not your imagination your butt is firmer today. Lifting should be easier for sure!");
    SetMessage(2,"You had a dream in which you uppercutted a gnome ten feet in the air. Then as you awake you immediately notice a resounding vigor in your muscles.");
    SetMessage(-1,"It feels like Nargùn infused your muscles with sand and salt today because you are sore beyond belief.");
    SetRace( Character.orc );
    SetMessage(1,"Just let someone try to mate with you today and you'll over power them with ease.");
    SetMessage(2,"Bloodlust is in your veins today making you feel dramatically stronger.");
    SetMessage(-1,"Perhaps the Father is displeased with you today because you feel weaker than usual.");
end;

initMessages();

initMessages = nil;
