-- INSERT INTO npc VALUES (nextval('npc_seq'),0,75,80,100,4,false,'Hirk','npc_hirk.lua',0);

require("npc.base.autonpcfunctions")
module("npc.hirk", package.seeall)

function useNPC(user,counter,param)
    thisNPC:increaseSkill(1,"common language",100);
    thisNPC:talkLanguage(Character.say, Player.german, "Finger weg!");
    thisNPC:talkLanguage(Character.say, Player.english, "Dont you touch me!");
end

function initializeNpc()
    if TraderFirst then
        return true;
    end

    npc.base.autonpcfunctions.InitTalkLists();
    
	QuestID = 987;
    -- ********* START DYNAMIC PART ********

    -- Farmer NPC on Noobia (written by Greisling) 
    -- Noobgelaber
    npc.base.autonpcfunctions.AddTraderTrigger("noob","I will not talk to you any more if you don't stop this gibberish.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddAdditionalTrigger("n[o]b");
    npc.base.autonpcfunctions.AddAdditionalTrigger("n[0]b");
    npc.base.autonpcfunctions.AddAdditionalTrigger(1337);
    npc.base.autonpcfunctions.AddAdditionalTrigger("newb");
    npc.base.autonpcfunctions.AddAdditionalTrigger("pwn");
    npc.base.autonpcfunctions.AddAdditionalTrigger("kill");
    npc.base.autonpcfunctions.AddAdditionalTrigger("lol");
    npc.base.autonpcfunctions.AddAdditionalTrigger("rofl");
    npc.base.autonpcfunctions.AddAdditionalTrigger(", k3wl");
    npc.base.autonpcfunctions.AddAdditionalTrigger("shit");
    npc.base.autonpcfunctions.AddAdditionalTrigger("smile");
    npc.base.autonpcfunctions.AddAdditionalTrigger("dunno");
    npc.base.autonpcfunctions.AddAdditionalTrigger("[:;][()]");
    npc.base.autonpcfunctions.AddAdditionalTrigger("[:;][-][()]");
    npc.base.autonpcfunctions.AddAdditionalTrigger("[:;][dp]");
    npc.base.autonpcfunctions.AddAdditionalTrigger("[:;][-][dp]");
    npc.base.autonpcfunctions.AddAdditionalTrigger("xd");
    npc.base.autonpcfunctions.AddTraderTrigger("n[o]b","Ich werde nicht mit Euch reden, wenn Ihr weiter solch unverständliches Zeug faselt.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddAdditionalTrigger("n[0]b");
    npc.base.autonpcfunctions.AddAdditionalTrigger(1337);
    npc.base.autonpcfunctions.AddAdditionalTrigger("newb");
    npc.base.autonpcfunctions.AddAdditionalTrigger("pwn");
    npc.base.autonpcfunctions.AddAdditionalTrigger("kill");
    npc.base.autonpcfunctions.AddAdditionalTrigger("lol");
    npc.base.autonpcfunctions.AddAdditionalTrigger("rofl");
    npc.base.autonpcfunctions.AddAdditionalTrigger(", k3wl");
    npc.base.autonpcfunctions.AddAdditionalTrigger("shit");
    npc.base.autonpcfunctions.AddAdditionalTrigger("smile");
    npc.base.autonpcfunctions.AddAdditionalTrigger("dunno");
    npc.base.autonpcfunctions.AddAdditionalTrigger("[:;][()]");
    npc.base.autonpcfunctions.AddAdditionalTrigger("[:;][-][()]");
    npc.base.autonpcfunctions.AddAdditionalTrigger("[:;][dp]");
    npc.base.autonpcfunctions.AddAdditionalTrigger("[:;][-][dp]");
    npc.base.autonpcfunctions.AddAdditionalTrigger("xd");
    npc.base.autonpcfunctions.AddAdditionalTrigger("töte");
    npc.base.autonpcfunctions.AddAdditionalTrigger("schei[ßs]");
    -- small talk, queststaus=0
    npc.base.autonpcfunctions.AddTraderTrigger("help","I would be glad to help you. I could tell you something about farming.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("hilf mir","Gerne helfe ich Euch. Ich könnte Euch etwas über den Ackerbau erzählen.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddAdditionalTrigger("hilfe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("helft mir");
    npc.base.autonpcfunctions.AddAdditionalTrigger("helfen");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("Gobaith","You are travelling to Gobaith, right? Indeed, you must be brave to travel to an island people are used to tell so many... mysterious.. stories about. Anyway, I wish you a good journey.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("Gobaith","Ihr seid auf der Durchreise nach Gobaith, nicht wahr? Ihr müsst wahrhaftig mutig sein, Euch zu diese sagenumwobene Insel zu begeben, von denen man so viel... merkwürdiges... hört. Wie dem auch sei - ich wünsche Euch einen angehme Reise.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("Illarion","Illarion? Well, you should go to a library and read some books to read something about this world! However, in Troll's Bane on Gobaith is a large library you can get more information, I suppose.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("Illarion","Illarion? Ihr fragt mich nach dem Namen dieser Welt? Ihr solltet lieber eine Bibliothek aufsuchen, als mich von einer ganzen Welt zu berichten zu lassen! In Troll's Bane auf Gobaith befindet sich die größte Bibliothek, die ich kenne.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("Troll[s ]+Bane","Troll's Bane is the largest town on the isle Gobaith. Troll's Bane is located in the centre of the isle. Many merchants are there. I would say you can get anything you need in this town.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("Troll[s ]+Bane","Troll's Bane ist die größte Stadt auf der Insel Gobaith. Sie befindet sich im Zentrum der Insel. Es ist eine Stadt der Händler und ich würde sagen, in dieser Stadt bekommt Ihr alles, was Ihr Euch nur wünschen könntet.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("Where am","You are on a small island not far away from Gobaith. Many travelers come here first to learn the local conventions of the islanders.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("Wo bin","Ihr seid auf einem kleinen Eiland nicht fern von der sagenumwobenen Insel Gobaith. Viele Reisende kommen zunächst hierher, um sich mit den Sitten und Bräuchen der Inselbewohner vertraut zu machen.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("Monster","#me laughs: 'Ha, you truely are looking for an adventure! Be careful that it will not cost your life somewhen, my friend.'");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddAdditionalTrigger("fight");
    npc.base.autonpcfunctions.AddAdditionalTrigger("weapon");
    npc.base.autonpcfunctions.AddAdditionalTrigger("sword");
    npc.base.autonpcfunctions.AddAdditionalTrigger("kill");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("Monster","#me lacht auf: 'Ha, Ihr seid wahrhaftig auf der Suche nach einem Abenteuer, wie es mir scheint! Gebt acht, dass es Euch nicht einst das Leben kosten wird, mein Freund.'");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddAdditionalTrigger("kampf");
    npc.base.autonpcfunctions.AddAdditionalTrigger("k[aeä]mpf");
    npc.base.autonpcfunctions.AddAdditionalTrigger("t[oeö]te");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("%NPCNAME","Indeed, that is my name, my friend. I am farmer and like to teach people something about my profession.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("%NPCNAME","In der Tat, dies ist mein Name. Ich bin Bauer und ich liebe es über meinen Beruf zu berichten und anderen beizubringen ein anständiger Bauer zu werden.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("Greebas","Hello, my name is "..thisNPC.name..". I am a farmer... and a happy one. *he grins as he sais so*");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Greebs");
    npc.base.autonpcfunctions.AddAdditionalTrigger("be greet");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Hallo");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Hello");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Greeting");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("Guten Tag","Hallo, mein Name ist "..thisNPC.name..". Ich bin ein Bauer... und ein glücklicher noch dazu. *er hat ein breites Grinsen im Gesicht, als er dies sagt*");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Tach");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Hallo");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Gr[üu][ßs]");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("Profession","I am "..thisNPC.name..", a farmer. I do help all people who are willing to learn.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Who you");
    npc.base.autonpcfunctions.AddAdditionalTrigger("What you");
    npc.base.autonpcfunctions.AddAdditionalTrigger("name");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("Beruf","Ich bin "..thisNPC.name..", ein Bauer. Ich helfe allen Leuten, die bereit sind zu lernen.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Wer du");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Wer Ihr");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Was du");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Was Ihr");
    npc.base.autonpcfunctions.AddAdditionalTrigger("name");
    npc.base.autonpcfunctions.AddAdditionalTrigger("hei[ssß]");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("how are you","Oh, I am fine. I hope you too.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("wie geht dir","Oh, mir geht es gut. Ich hoffe Euch auch.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("wie geht euch");
    npc.base.autonpcfunctions.AddAdditionalTrigger("wohlbefinden");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("hi","Do you have so little time that you just say 'hi'? Folks here prefer more formal phrases. Just like 'greetings' for example. Remember that, my friend.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("hi","Habt Ihr so wenig Zeit, dass ihr Fremde in einer so kurzen Form nur begrüßt? Die Bewohner dieser Inseln hier bevorzugen eigentlich längere Grußwörter - wie 'Ich grüße Euch'. Merkt Euch dies, mein Freund.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("sell","I am sorry. I do not sell anything nor do I buy anything. I am just a farmer.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("ware");
    npc.base.autonpcfunctions.AddAdditionalTrigger("buy");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddCondition("state","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("verkauf","Tut mir Leid. Weder verkaufe, noch kaufe ich etwas. Ich bin nur ein einfacher Bauer.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("kauf");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Ware");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddCondition("state","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("bye","Be well.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("farewell");
    npc.base.autonpcfunctions.AddAdditionalTrigger("be well");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddAdditionalText("Farewell.");
    npc.base.autonpcfunctions.AddAdditionalText("Good bye.");
    npc.base.autonpcfunctions.AddTraderTrigger("auf bald","Auf bald.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("bis bald");
    npc.base.autonpcfunctions.AddAdditionalTrigger("leb.+wohl");
    npc.base.autonpcfunctions.AddAdditionalTrigger("tsch[üu][ßs]");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mach.+gut");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddAdditionalText("Bis bald.");
    npc.base.autonpcfunctions.AddAdditionalText("Lebt wohl.");
    npc.base.autonpcfunctions.AddAdditionalText("Gehabt Euch wohl.");
    npc.base.autonpcfunctions.AddTraderTrigger("bye","Farewell, my friend. Come back if you want to learn more about farming. Thanks for the buckets.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("farewell");
    npc.base.autonpcfunctions.AddAdditionalTrigger("be well");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",52,2);
    npc.base.autonpcfunctions.AddTraderTrigger("bye","Gehabt Euch wohl, mein Freund. Kehrt zurück, falls Ihr mehr über den Ackerbau erfahren wollt. Danke für die Eimer!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("farewell");
    npc.base.autonpcfunctions.AddAdditionalTrigger("be well");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",51,2);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",52,2);
    npc.base.autonpcfunctions.AddTraderTrigger("bye","Be well.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("farewell");
    npc.base.autonpcfunctions.AddAdditionalTrigger("be well");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddAdditionalText("Farewell.");
    npc.base.autonpcfunctions.AddAdditionalText("Good bye.");
    npc.base.autonpcfunctions.AddTraderTrigger("auf bald","Auf bald.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("bis bald");
    npc.base.autonpcfunctions.AddAdditionalTrigger("leb.+wohl");
    npc.base.autonpcfunctions.AddAdditionalTrigger("tsch[üu][ßs]");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mach.+gut");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddAdditionalText("Bis bald.");
    npc.base.autonpcfunctions.AddAdditionalText("Lebt wohl.");
    npc.base.autonpcfunctions.AddAdditionalText("Gehabt Euch wohl.");
    npc.base.autonpcfunctions.AddTraderTrigger("bye","Farewell, my friend. Come back if you want to learn more about farming.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("farewell");
    npc.base.autonpcfunctions.AddAdditionalTrigger("be well");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddTraderTrigger("bye","Gehabt Euch wohl, mein Freund. Kehrt zurück, falls Ihr mehr über den Ackerbau erfahren wollt.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("farewell");
    npc.base.autonpcfunctions.AddAdditionalTrigger("be well");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    -- Begrüßung, Ackerbau lernen?
    npc.base.autonpcfunctions.AddTraderTrigger("happy","Oh, is is 'that' obvious that I thank the gods every day that they allow me to be a farmer? Perhaps you want to try farming as well?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("grin");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("state","=",0);
    npc.base.autonpcfunctions.AddConsequence("state","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("gl[ueü]ck","Oh, ist es tatsächlich 'so' auffällig, dass ich den Göttern jeden Tag aus Neue danke, dass sie mir das Glück dieses Berufes bescherten? Vielleicht wollt Ihr Euch ebenso am Ackerbau versuchen?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("grins");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("state","=",0);
    npc.base.autonpcfunctions.AddConsequence("state","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("field","Indeed, that is my field. But you can use it of course. Do you want to learn farming?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("acre");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("state","=",0);
    npc.base.autonpcfunctions.AddConsequence("state","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("Feld","Ja, in der Tat. Dieser Acker dort gehört mir. Wollt Ihr etwas über den Ackerbau erfahren?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Acker");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("state","=",0);
    npc.base.autonpcfunctions.AddConsequence("state","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("farm","So, you would like to learn something about farming?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("learn");
    npc.base.autonpcfunctions.AddAdditionalTrigger("teach");
    npc.base.autonpcfunctions.AddAdditionalTrigger("plant");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("state","=",0);
    npc.base.autonpcfunctions.AddConsequence("state","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("Landwirt","Ihr wollt also etwas über den Ackerbau erfahren?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("lern");
    npc.base.autonpcfunctions.AddAdditionalTrigger("lehr");
    npc.base.autonpcfunctions.AddAdditionalTrigger("pflanz");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Bauer");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("state","=",0);
    npc.base.autonpcfunctions.AddConsequence("state","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","#me looks at you a bit confused and says: 'Well, that is quite a strange way to say hello... anyway - be greeted. My name is "..thisNPC.name..". I am a farmer. Are you interested in learning something about farming?'");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("state","=",0);
    npc.base.autonpcfunctions.AddConsequence("state","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","#me sieht Dich etwas verwundert an und sagt: 'Nun, in der Tat eine etwas merkwürdige Art jemanden zu begrüßen... wie dem auch sei - Ich grüße Euch. Mein Name ist "..thisNPC.name..". Ich bin ein Bauer. Soll ich Euch etwas über den Ackerbau erzählen?'");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("state","=",0);
    npc.base.autonpcfunctions.AddConsequence("state","=",1);
    -- Sicher?
    npc.base.autonpcfunctions.AddTraderTrigger("Sorry","#me laughs in a friendly way: '...no need to excuse yourself. I am sure you had a long journey and have heard a lot of information so far. So, should I teach you farming?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Excuse me");
    npc.base.autonpcfunctions.AddAdditionalTrigger("hello");
    npc.base.autonpcfunctions.AddAdditionalTrigger("hallo");
    npc.base.autonpcfunctions.AddAdditionalTrigger("be greeted");
    npc.base.autonpcfunctions.AddAdditionalTrigger("greetings");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("state","=",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("Tut leid","#me lacht kurz freundlich auf: '...Ihr braucht Euch nicht zu entschuldigen. Ihr hattet bestimmt eine weite Reise und vielerlei Leute bereits kennen gelernt. Bitte, sagt, soll ich Euch etwas über den Ackerbau erzählen?'");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Entschuldig");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Verzeihung");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Hallo");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Guten Tag");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Tach");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Gr[üu][ßs]");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("state","=",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("Yes","I am glad to hear so. Well, first you should now that farming is one of the most relaxing professions, though it takes quite some time. Should we go ahead anyway?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aye");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Yeah");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Of course");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("state","=",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("Ja","Es freut mich sehr dies zu hören. Nundenn, zunächst solltet Ihr wissen, dass es kaum etwas entspannteres gibt, als die Zeit auf dem Felde zu verbringen. Doch nimmt dies auch einige Zeit in Anspruch. Sollen wir dennoch forfahren?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aye");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Fahr[t] fort");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Natürlich");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Unbedingt");
    npc.base.autonpcfunctions.AddAdditionalTrigger("klar");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("state","=",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("No","Well, then I wish you nice day and good jounrey to Gobaith. Maybe you are interested in learning something from other people here around? Have a nice day.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Nay");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Never");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("state","=",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("Nein","In diesem Falle wünsche ich Euch einen angenehmen Tag und eine gute Reise nach Gobaith. Vielleicht seid Ihr ja daran interssiert von anderen etwas zu lernen, bevor Ihr nach Gobaith aufbrecht? Gehabt Euch wohl.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Nay");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Niemals");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("state","=",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Excuse me, I did not understand your answer to my question: Do you want to learn farming?");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("state","=",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Tut mir Leid, ich habe Eure Antwort auf meine Frage nicht recht verstanden: Soll ich Euch etwas über den Ackerbau beibringen?");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("state","=",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",1);
    -- Was lernen? Bäume pflanzen // Getreide anbauen
    npc.base.autonpcfunctions.AddTraderTrigger("Yes","#me smiles at you in a friendly way and says: 'Very well. What do you want to learn? Planting trees? Or cultivating grain?'");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aye");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Yeah");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Of course");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("state","=",2);
    npc.base.autonpcfunctions.AddConsequence("state","=",3);
    npc.base.autonpcfunctions.AddTraderTrigger("Ja","#me lächelt Dich freundlich an und sagt: 'Wunderbar. Was wollt Ihr lernen? Bäume pflanzen? Oder Getreide anbauen?'");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aye");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Fahr[t] fort");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Natürlich");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Unbedingt");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("state","=",2);
    npc.base.autonpcfunctions.AddConsequence("state","=",3);
    npc.base.autonpcfunctions.AddTraderTrigger("No","Well, then I wish you nice day and good journey to Gobaith. Maybe you are interested in learning something from other people here around? Have a nice day.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Nay");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Never");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("state","=",2);
    npc.base.autonpcfunctions.AddConsequence("state","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("Nein","In diesem Falle wünsche ich Euch einen angenehmen Tag und eine gute Reise nach Gobaith. Vielleicht seid Ihr ja daran interssiert von anderen etwas zu lernen, bevor Ihr nach Gobaith aufbrecht? Gehabt Euch wohl.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Nay");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Niemals");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("state","=",2);
    npc.base.autonpcfunctions.AddConsequence("state","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Excuse me, I did not understand your answer to my question: Should I continue to explain you how to farm? But remember that plants don't grow faster just because of your hurry.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("state","=",2);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Tut mir Leid, ich habe Eure Antwort auf meine Frage nicht recht verstanden: Soll ich forfahren Euch beizubringen Ackerbau zu betreiben? Doch bedenkt, dass Pflanzen durch Eure Eile nicht schneller wachsen.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("state","=",2);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    -- Antwort: Getreide anbauen -> Verweis auf queststatus=3
    npc.base.autonpcfunctions.AddTraderTrigger("grain","Very well. I am sure you will be successfull in cultivating grain! So, let's get started... do you already have some seeds?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("cultivate");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("state","=",3);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npc.base.autonpcfunctions.AddConsequence("state","=",21);
    npc.base.autonpcfunctions.AddTraderTrigger("Getreide","Das freut mich sehr!Ich bin mir sicher, dass wir es gemeinsam schaffen werden Getreide anzubauen! Nundenn, fangen wir an... sagt, habt Ihr bereits einige Getreidesamen bei Euch?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("anbauen");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("state","=",3);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npc.base.autonpcfunctions.AddConsequence("state","=",21);
    -- Hilfe beim Wasserschöpfen, queststatus=1
    npc.base.autonpcfunctions.AddTraderTrigger("help","Do you want to know where the bucket is? Or how to take the bucket into your hand? Or do you want to know how to fill the bucket with water?");
    npc.base.autonpcfunctions.AddCondition("item",51,"all",">=",2);
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("rat","Wollt Ihr wissen, wo der Eimer ist? Oder wie Ihr den Eimer in die Hand nehmt? Oder vielleicht, wie Ihr den Eimer mit Wasser füllt?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("hilf");
    npc.base.autonpcfunctions.AddAdditionalTrigger("helf");
    npc.base.autonpcfunctions.AddCondition("item",51,"all",">=",2);
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("where","The buckets are either in your hand, your belt, or in your bag. ['The belt' = the 6 fields of the inventory under the figure on the right edge of the screen. 'Bag' = the field left to the head of the figure. Open it by rightclick - open bag]");
    npc.base.autonpcfunctions.AddAdditionalTrigger("first");
    npc.base.autonpcfunctions.AddCondition("item",51,"all",">=",2);
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("wo","Die Eimer sind entweder in Euren Händen, Eurem Gürtel oder in Eurer Ledertasche. ['Gürtel' = die 6 Inventarfelder unter der Figur am rechten Bildschirmrand. 'Ledertasche' = in dem Inventarfeld links neben dem Kopf der Figur. Rechtsclick - Tasche öffnen]");
    npc.base.autonpcfunctions.AddAdditionalTrigger("erst");
    npc.base.autonpcfunctions.AddCondition("item",51,"all",">=",2);
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("hand","Now, just take one bucket in your hand. [set the counter on 0, e.g. by clicking the keyboard button 'end'. Then drag&drop the bucket from the inventory to the empty inventory field which is located where the hands of the character sketch would be]");
    npc.base.autonpcfunctions.AddAdditionalTrigger("take");
    npc.base.autonpcfunctions.AddAdditionalTrigger("second");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("item",51,"all",">=",2);
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("hand","Nehmt einen Eimer einfach in Eure Hand. [setze den Counter auf 0, z.B. mit der 'Ende'-Taste auf der Tastatur. Ziehe dann per Drag/Drop den Eimer aus dem Inventarfeld auf das freie Inventarfeld, welches sich dort befindet, wo die Hände der Figur sein sollten]");
    npc.base.autonpcfunctions.AddAdditionalTrigger("nehm");
    npc.base.autonpcfunctions.AddAdditionalTrigger("zweit");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("item",51,"all",">=",2);
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("bucket","Indeed, you need to fill the bucket with water [stand next to water/well with a bucket in your hand - rightclick the bucket in your hand - 'use with...' - righclick water/well - 'use' water/well]");
    npc.base.autonpcfunctions.AddAdditionalTrigger("water");
    npc.base.autonpcfunctions.AddAdditionalTrigger("fill");
    npc.base.autonpcfunctions.AddAdditionalTrigger("third");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger(", Wasser","Jawohl, nehmt einen Eimer in die Hand und schöpft Wasser [neben Wasser/Brunnen stehen mit einem Eimer in der Hand - Rechtsclick auf Eimer in der Hand - 'benutzen mit...' - Rechtsclick Wasser/Brunnen -'benutze' Wasser/Brunnen]");
    npc.base.autonpcfunctions.AddAdditionalTrigger("f[üue]ll");
    npc.base.autonpcfunctions.AddAdditionalTrigger("dritt");
    npc.base.autonpcfunctions.AddAdditionalTrigger("letzt");
    npc.base.autonpcfunctions.AddCondition("item",51,"all",">=",2);
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    -- Quest: Bäume pflanzen; Eimer leer; queststatus=1
    npc.base.autonpcfunctions.AddTraderTrigger("plant","Very well. The first lesson is to fill these buckets with water. Take one bucket each in your hands and go to a well or river. Fill the buckets with water and return to me then. Don't hesitate to ask me for help, if needed.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("tree");
    npc.base.autonpcfunctions.AddCondition("state","=",3);
    npc.base.autonpcfunctions.AddConsequence("item",51,2,333,0);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("pflanz","Wunderbar. Als erste Aufgabe habt Ihr diese zwei Eimer hier mit Wasser zu füllen. Nehmt jeweils einen in Eure Hände und geht zu einem Brunnen oder Fluss. Kehrt zurück, wenn die Eimer gefüllt sind oder Ihr meine Hilfe braucht.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("B[aeä]um");
    npc.base.autonpcfunctions.AddCondition("state","=",3);
    npc.base.autonpcfunctions.AddConsequence("item",51,2,333,0);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Where are the two buckets I have given to you? Anyway, here you have two more buckets. Take care of them while you'll fill them with water.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("item",51,"all","=",0);
    npc.base.autonpcfunctions.AddCondition("item",52,"all","=",0);
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddConsequence("item",51,2,333,0);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Wo sind die beiden Eimer, die ich Euch gab? Wie dem auch sei, hier habt Ihr nochmals zwei Eimer. Gebt auf sie acht, wenn ihr mit ihnen Wasser schöpft.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("item",51,"all","=",0);
    npc.base.autonpcfunctions.AddCondition("item",52,"all","=",0);
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddConsequence("item",51,2,333,0);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Where is the second bucket I have given to you? Anyway, here you have another bucket to put some water into.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("item",51,"all","=",0);
    npc.base.autonpcfunctions.AddCondition("item",52,"all","=",1);
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddConsequence("item",51,1,333,0);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Wo ist der zweite Eimer, den ich Euch gab? Wie dem auch sei, hier habt ihr einen zweiten Eimer, um ihn mit Wasser zu füllen.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("item",51,"all","=",0);
    npc.base.autonpcfunctions.AddCondition("item",52,"all","=",1);
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddConsequence("item",51,1,333,0);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Where is the second bucket I have given to you? Anyway, here you have another bucket to put some water into.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("item",51,"all","=",1);
    npc.base.autonpcfunctions.AddCondition("item",52,"all","=",0);
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddConsequence("item",51,1,333,0);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Wo ist der zweite Eimer, den ich Euch gab? Wie dem auch sei, hier habt ihr einen zweiten Eimer, um ihn mit Wasser zu füllen.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("item",51,"all","=",1);
    npc.base.autonpcfunctions.AddCondition("item",52,"all","=",0);
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddConsequence("item",51,1,333,0);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Well, you should fill the two buckets with water. Come back to me, when you have done so. If there is anything unclear, just ask me for help. I will be more than happy to help you out.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("item",51,"all",">=",2);
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Nun, bitte füllt doch die beiden Eimer, welche ich Euch gegeben habe, mit Wasser und kommt dann zu mir zurück. Sagt nur frei heraus, falls ihr Hilfe benötigt.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("item",51,"all",">=",2);
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    -- Baum bereits gepfanzt?, queststatus=2
    npc.base.autonpcfunctions.AddTraderTrigger("Yes","#me nods with a smile on his lips: 'Well done. You learn fast, indeed. I think now you are ready to learn more about farming. Do you want to learn to cultivate grain now?'");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aye");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Yeah");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Of course");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddCondition("state","=",11);
    npc.base.autonpcfunctions.AddConsequence("state","=",12);
    npc.base.autonpcfunctions.AddTraderTrigger("Ja","#me nickt mit einem Lächeln auf seinen Lippen: 'Gut gemacht! ihr lernt wirklich schnell, ich bin beeindruckt! Ich denke Ihr seid nun bereit mehr über den Ackerbau zu lernen. Wollt Ihr jetzt lernen Getreide anzubauen?'");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aye");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Fahr[t] fort");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Natürlich");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Unbedingt");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddCondition("state","=",11);
    npc.base.autonpcfunctions.AddConsequence("state","=",12);
    npc.base.autonpcfunctions.AddTraderTrigger("No","Well, I see... if you need some help in planting a tree just say so.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Nay");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddCondition("state","=",11);
    npc.base.autonpcfunctions.AddTraderTrigger("Nein","Ich verstehe... nun, wenn Ihr Hilfe braucht, sagt es frei heraus.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Nay");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddCondition("state","=",11);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Excuse me, I did not understand your answer: Have you already planted an apple tree?");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddCondition("state","=",11);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Verzeihung, ich habe Eure Antwort nicht verstanden: Habt ihr bereits einen Apfelbaum gepflanzt?");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddCondition("state","=",11);
    -- Nachdem der Baum gepflanzt ist: Jetzt Getreide anbauen?, queststatus=2
    npc.base.autonpcfunctions.AddTraderTrigger("Yes","Very well. I am sure you will be successfull in cultivating grain! So, let's get started... do you already have some seeds?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aye");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Yeah");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Of course");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddCondition("state","=",12);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npc.base.autonpcfunctions.AddConsequence("state","=",21);
    npc.base.autonpcfunctions.AddTraderTrigger("Ja","Euer Durchhaltevermögen lobe ich mir! Ich bin mir sicher, dass Ihr es schaffen werdet Getreide anzubauen! Nundenn, fangen wir an... sagt, habt Ihr bereits einige Getreidesamen bei Euch?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aye");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Natürlich");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Unbedingt");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddCondition("state","=",12);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npc.base.autonpcfunctions.AddConsequence("state","=",21);
    npc.base.autonpcfunctions.AddTraderTrigger("No","Well, I see. If you want to learn cultivate grain later, just come back and talk to me again. Farewell, my friend");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Nay");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddCondition("state","=",12);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",0);
    npc.base.autonpcfunctions.AddConsequence("state","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("Nein","Ich verstehe. Falls Ihr später lernen wollt Getreide anzubauen, kommt zurück und sprecht mich an. Gehabt Euch wohl, mein Freund.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Nay");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddCondition("state","=",12);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",0);
    npc.base.autonpcfunctions.AddConsequence("state","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Excuse me, I did not understand your answer: Do you want to learn to cultivate grain right now?");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddCondition("state","=",12);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Verzeihung, ich habe Eure Antwort nicht verstanden: Möchtet Ihr nun lernen Getreide anzubauen?");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddCondition("state","=",12);
    -- Quest: Baum pflanzen; Eimer voll, queststatus=2
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Well done! Now you have a bucket full of water, you should plant a tree. Here you have some apple seed. Lay them on a sunny spot on fertile soil and water it. Don't hesitate to ask for help, if needed.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("item",52,"all",">=",1);
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npc.base.autonpcfunctions.AddConsequence("item",15,5,333,0);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Gut gemacht! Nun, da Ihr einen Eimer voll Wasser habt, könnt Ihr einen Baum pflanzen. Hier habt ihr ein paar Apfelkerne. Legt sie auf fruchtbaren, sonnenbeschienen Untergrund und bewässert ihn. Zögert nicht mich nach Hilfe zu fragen.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("item",52,"all",">=",1);
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npc.base.autonpcfunctions.AddConsequence("item",15,5,333,0);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","I have kept an eye on you... here you have some more apple seeds.");
    npc.base.autonpcfunctions.AddCondition("item",15,"all","<",2);
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddConsequence("item",15,5,333,0);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Ich habe Euch beobachtet... hier habt Ihr noch ein eine handvoll Apfelkerne.");
    npc.base.autonpcfunctions.AddCondition("item",15,"all","<",2);
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddConsequence("item",15,5,333,0);
    npc.base.autonpcfunctions.AddTraderTrigger("help","What do you want to know: Where the seed is? Where to place the apple seed? How to water the seed? Or how often you have to water the seed?");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("rat","Was wollt Ihr wissen: Wo die Apfelkerne sind? Wohin Ihr die Apfelkerne legen müsst? Oder wie und wie oft Ihr die Apfelkerne bewässern müsst?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("hilf");
    npc.base.autonpcfunctions.AddAdditionalTrigger("helf");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("where place","You have to put the apple sees on a sunny and fertile spot on the ground, at best some grasland in some distance to other plants. [to move items: drag and drop the apply from your inventory to a spot in the map]");
    npc.base.autonpcfunctions.AddAdditionalTrigger("where plant");
    npc.base.autonpcfunctions.AddAdditionalTrigger("second");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("wo legen","Ihr solltet die Apfelkerne auf einen unbeschatteten, fruchtbaren Flecken Erde streuen. [Um Items abzulegen: Drag & drop die Apfelkerne aus deinem Inventar auf ein freies Feld in der Spielwelt]");
    npc.base.autonpcfunctions.AddAdditionalTrigger("wo pflanz");
    npc.base.autonpcfunctions.AddAdditionalTrigger("erst");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("where seed","The seed is either in your bag or belt. ['Belt'= the 6 fields of the inventory under the figure on the right edge of the screen. 'Bag'= the field left to the head of the figure. Open it by rightclick - open bag]");
    npc.base.autonpcfunctions.AddAdditionalTrigger("first");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("wo kern","Die Apfelkerne sind entweder in Euren Händen, Eurem Gürtel oder in Eurer Ledertasche. ['Gürtel'= die 6 Inventarfelder unter der Figur am rechten Bildschirmrand. 'Ledertasche'= in dem Inventarfeld links neben dem Kopf der Figur. Rechtsclick - Tasche öffnen]");
    npc.base.autonpcfunctions.AddAdditionalTrigger("erst");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("water"," - Sound & message: 'platsch']");
    npc.base.autonpcfunctions.AddAdditionalTrigger("how often");
    npc.base.autonpcfunctions.AddAdditionalTrigger("third");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("bew[äae]sser"," - nachricht: 'platsch']");
    npc.base.autonpcfunctions.AddAdditionalTrigger(", dritt");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","If you need some help, don't hesitate to tell me... or have you already planted an apple tree?");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddConsequence("state","=",11);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Falls Ihr meine Hilfe braucht, sagt es frei heraus... oder habt ihr bereits einen Apfelbaum gepflanzt?");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddConsequence("state","=",11);
    -- 2. Quest: Lernen Getreide anzubauen, queststatus=3
    npc.base.autonpcfunctions.AddTraderTrigger(".+","#me smiles friendly at you: 'Anyway, here you have some seeds. Place some of them on the field and wait till the grain starts to grow. If you made it to let little plants grow, come back to me and tell me so. Ask for help if needed, of course.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("item",259,"all","=",0);
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state","=",21);
    npc.base.autonpcfunctions.AddConsequence("state","=",22);
    npc.base.autonpcfunctions.AddConsequence("item",259,5,333,0);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Nungut, hier habt Ihr ein paar Getreidekörner. Verstreut sie über den Acker und ihr werdet dem Getreide beim Sprießen zusehen können. Sobald das erste Pflänzlein sprießt, kommt und sagt mir bescheid! Fragt ruhig, falls Ihr etwas wissen wollt.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("item",259,"all","=",0);
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state","=",21);
    npc.base.autonpcfunctions.AddConsequence("state","=",22);
    npc.base.autonpcfunctions.AddConsequence("item",259,5,333,0);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","#me smiles friendly at you: 'Very well. Place some of them on the field and wait till the grain starts to grow. If you made it to let little plants grow, come back to me and tell me so. Ask for help if needed, of course.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("item",259,"all",">=",1);
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state","=",21);
    npc.base.autonpcfunctions.AddConsequence("state","=",22);
    npc.base.autonpcfunctions.AddConsequence("item",259,5,333,0);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Nungut, verstreut die Getreidekörner über den Acker und ihr werdet dem Getreide beim Sprießen zusehen können. Sobald das erste Pflänzlein gedeiht, kommt und sagt mir bescheid! Fragt ruhig, falls Ihr etwas wissen wollt.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("item",259,"all",">=",1);
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state","=",21);
    npc.base.autonpcfunctions.AddConsequence("state","=",22);
    npc.base.autonpcfunctions.AddConsequence("item",259,5,333,0);
    -- Noch alles da?
    npc.base.autonpcfunctions.AddTraderTrigger(".+","I see that you do not have any Grain seeds any more. Here you have some. If there is anything you want to know, just ask me for help.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state","=",22);
    npc.base.autonpcfunctions.AddCondition("item",259,"all","=",0);
    npc.base.autonpcfunctions.AddConsequence("item",259,5,333,0);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Das Getreide ist Euch ausgegangen? Keine Bange, hier habt Ihr etwas mehr der Körner. Vergesst nicht dass ich Euch stets helfe, falls Ihr nicht weiter wisst. Sprecht mich nur an.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state","=",22);
    npc.base.autonpcfunctions.AddCondition("item",259,"all","=",0);
    npc.base.autonpcfunctions.AddConsequence("item",259,5,333,0);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","I see that you have lost the scythe. Here you have another one. Let me know if you need any help.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state","=",23);
    npc.base.autonpcfunctions.AddCondition("item",271,"all","=",0);
    npc.base.autonpcfunctions.AddConsequence("item",271,1,333,0);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","So, Ihr habt also Eure Sense verloren? Keine Sorge, hier habt Ihr eine andere. Bitte sprecht mich an, falls Ihr meine Hilfe braucht.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state","=",23);
    npc.base.autonpcfunctions.AddCondition("item",271,"all","=",0);
    npc.base.autonpcfunctions.AddConsequence("item",271,1,333,0);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","I see that you have lost the flail. Here you have another one. Just tell me if you need some help.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state","=",24);
    npc.base.autonpcfunctions.AddCondition("item",258,"all","=",0);
    npc.base.autonpcfunctions.AddConsequence("item",258,1,333,0);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Euren Dreschflegel habt Ihr verloren? Kein Grund zur Sorge, hier habt Ihr einen anderen. Zögert nicht mich nach Hilfe zu bitten, falls Ihr nich tweiter wisst.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state","=",24);
    npc.base.autonpcfunctions.AddCondition("item",258,"all","=",0);
    npc.base.autonpcfunctions.AddConsequence("item",258,1,333,0);
    -- Hilfe
    npc.base.autonpcfunctions.AddTraderTrigger("help","What do you want to know: How to seed the grain? When you will be able to harvest the grain? How to cut the mature grain? How to use the flail?");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state",">=",22);
    npc.base.autonpcfunctions.AddCondition("state","<=",27);
    npc.base.autonpcfunctions.AddTraderTrigger("hil","Was wollt Ihr wissen: Wie Ihr Getreide säht? Wann Ihr das Getreide ernten könnt? Wie Ihr das Getreide ernten könnt? Oder wie Ihr den Dreschflegel benutzt?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("helf");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state",">=",22);
    npc.base.autonpcfunctions.AddCondition("state","<=",27);
    npc.base.autonpcfunctions.AddTraderTrigger("seed","Put the grain seeds into your belt. Then step on the field and throw some seeds in front of you on the ground. You'll see the grain sprout out of the soil, if it worked correct. [rightclick the grain while it is in the belt inventory - 'use']");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state",">=",22);
    npc.base.autonpcfunctions.AddCondition("state","<=",27);
    npc.base.autonpcfunctions.AddTraderTrigger("s[aeä]h","Legt die Samen in Euren Gürtel. Schreitet dann auf den Acker und verstreut die Körner vor Euch auf den Boden. Wenn Ihr es richtig anstellt, werdet Ihr sofort, wie die Samen sprießen. [Rechtsclick auf das Getreide im Gürtel - 'use']");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state",">=",22);
    npc.base.autonpcfunctions.AddCondition("state","<=",27);
    npc.base.autonpcfunctions.AddTraderTrigger("harvest","The grain needs a while till it is mature. First it will grow in height. Finally it will become golden brown, then you can go and cut the grain with the scythe. Though, this place here is special, I can let the grain grow faster.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("when");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state",">=",22);
    npc.base.autonpcfunctions.AddCondition("state","<=",27);
    npc.base.autonpcfunctions.AddTraderTrigger("ernt","Das Getreide braucht eine Weile zur Reife. Zunächst wird es nur in die Höhe wachsen. Danach wird es sich goldbraun färben. Eben dann ist das Getreide reif, um die Halme mit der Sense abzuschneiden. Jedoch kann ich Getreide auf dieser Insel für Euch schneller wachsen zu lassen.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("wann");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state",">=",22);
    npc.base.autonpcfunctions.AddCondition("state","<=",27);
    npc.base.autonpcfunctions.AddTraderTrigger("scythe","Take the scythe in both your hands when the grain is mature. Then step in front of the grain and cut it to bundles of grain. [Put scythe in hands - rightclick scythe - 'use']");
    npc.base.autonpcfunctions.AddAdditionalTrigger("cut");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mature");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state",">=",22);
    npc.base.autonpcfunctions.AddCondition("state","<=",27);
    npc.base.autonpcfunctions.AddTraderTrigger("Sense","Nehmt die Sense in beide Hände sobald das Getreide reif ist. Stellt Euch vor das Getreide und schwingt die Sense. So werdet Ihr Getreidebündel abschneiden. [Sense in der Hand - Rechtsclick - 'benutzen']");
    npc.base.autonpcfunctions.AddAdditionalTrigger("schneid");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state",">=",22);
    npc.base.autonpcfunctions.AddCondition("state","<=",27);
    npc.base.autonpcfunctions.AddTraderTrigger("flail","When you have cut some grain, you have to take the flail into your hands instead of the scythe. Then flail the bundles of grain. You will get grain seeds then. [put flail in hands - rightclick - 'use']");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state",">=",22);
    npc.base.autonpcfunctions.AddCondition("state","<=",27);
    npc.base.autonpcfunctions.AddTraderTrigger("Dresch","Sobald Ihr das Getreide mit er Sense geerntet hab, müst ihr den Dreschflegel in Eure Hände nehmen und auf die Getreidebündel eindreschen. [Dreschflegel in die Hande nehmen - 'rechtscklick' - 'benutzen']");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Flegel");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state",">=",22);
    npc.base.autonpcfunctions.AddCondition("state","<=",27);
    -- Samen gesähnt: state=23 ; nicht gesäht: state=24 ; wachsen lassen: state=25
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Well done my friend. You sow some grain! Look how fast it is growing on this magic soil! Now take this scythe and cut the grain into bundles of grain. Come back to me if you did so... or ask for help.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state","=",23);
    npc.base.autonpcfunctions.AddConsequence("item",271,1,333,0);
    npc.base.autonpcfunctions.AddConsequence("state","=",25);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Gut gemacht, mein Freund! Seht nur, wie schnell es auf diesem magischen Boden wächst! Nehmt nun dieses Sense hier und erntet das Getreide und schnürt es zu Getreidebündeln zusammen. Sobald Ihr da getan habt, kommt zurück und zeigt es mir.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state","=",23);
    npc.base.autonpcfunctions.AddConsequence("item",271,1,333,0);
    npc.base.autonpcfunctions.AddConsequence("state","=",25);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Do not give up, my friend! I am sure you can seed some grain. Just take the seeds into your hand and seed them. Please, do ask me for help if you do not know how to do so.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state","=",24);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Gebt nicht auf, mein Freund! Ich bin mir sicher, dass Ihr es schaffen werdet Getreide zu säen. Fragt mich jedoch ruhig nach Hilfe, falls etwas unklar sein sollte.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state","=",24);
    -- > lasse Getreide wachsen, state=26 * * * *]]
    npc.base.autonpcfunctions.AddTraderTrigger(".+","My friend, I am proud of you! You made it to cut the grain with the scythe! Now there is one thing left to do: Take this flail here and flail the grain so we get grain seeds out of it. Tell me when you are done or need help");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("item",249,"all",">=",1);
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state","=",26);
    npc.base.autonpcfunctions.AddConsequence("state","=",27);
    npc.base.autonpcfunctions.AddConsequence("item",258,1,333,0);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",259,250);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Ich bin stolz auf Euch, mein Freund! Ihr habt das Getreide geerntet und zu Bündeln verschnürt! Nun bleibt noch eines zu tun: Drescht die Körner mit diesem Dreschflegel aus dem Getreide heraus. Gebt Laut sobald Ihr damit fertig seid oder Ihr Hilfe benötigt.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("item",249,"all",">=",1);
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state","=",26);
    npc.base.autonpcfunctions.AddConsequence("state","=",27);
    npc.base.autonpcfunctions.AddConsequence("item",258,1,333,0);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",259,250);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Keep up, my friend! Just take the scythe in your hands, stand in front of the grain and cut the grain! Sounds easy, aye? However, you also can ask me for help.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("item",249,"all","=",0);
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state","=",26);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Haltet durch, mein Freund! Nehmt einfach die Sense in Eure Hände, stellt Euch vor das Getreide und säbelt die Halme ab. Fragt ruhig nach Hilfe, falls noch etwas unklar ist.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("item",249,"all","=",0);
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state","=",26);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Hang in, my friend! Take the flail in both hand and flail the seeds out of the bundles of grain! I am sure you can do it!");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("item",259,"all","=",0);
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state","=",27);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Jetzt nur nicht aufgeben, mein Freund! Drescht die Körner mit ordentlich Schmackes aus dem Getreide! Dann ist es geschafft!");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("item",259,"all","=",0);
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state","=",27);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Fabulous, my friend, indeed! You know know everything about harvesting grain now! Well, there are far more crops to grow on Gobaith... well, there is one thing you whould know about the soil on Gobaith.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("item",259,"all",">=",1);
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state","=",27);
    npc.base.autonpcfunctions.AddConsequence("state","=",28);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",51,250);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",52,250);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",259,250);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",249,250);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",258,250);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",271,250);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Ganz famos, mein Freund! Nun wisst Ihr alles über den Getreideanbau. Auf Gobaith werdet Ihr noch mehr Pflanzenarten anbauen können, hört Euch einfach um... uhm.. da ist eine Sache, die Ihr noch wissen solltet.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("item",259,"all",">=",1);
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state","=",27);
    npc.base.autonpcfunctions.AddConsequence("state","=",28);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",51,250);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",52,250);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",259,250);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",249,250);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",258,250);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",271,250);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","You surely have noticed that the grain grew quite fast on this soil. Keep in mind that on Gobaith it will take a while until the grain will grow. Well, that's it. Just ask people on Gobaith for help. I cannot teach you anything else. Have a good journey!");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("state","=",28);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",0);
    npc.base.autonpcfunctions.AddConsequence("state","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Ihr habt sicher bemerkt, dass das Getreide hier rasch empor geschossen ist. Auf Gobaith werden die Pflanzen langsamer wachsen, als auf diesen magischen Böden hier. Nundenn, ich kan Euch nichts mehr beibringen, so wünsche ich Euch eine angenehme Reise!");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddCondition("state","=",28);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",0);
    npc.base.autonpcfunctions.AddConsequence("state","=",0);
    -- ********* END DYNAMIC PART ********
    TradSpeakLang={0,1};
    TradStdLang=0;

    npc.base.autonpcfunctions.increaseLangSkill(TradSpeakLang);
    thisNPC.activeLanguage=TradStdLang;

end

function nextCycle()  -- ~10 times per second
    initializeNpc();
    npc.base.autonpcfunctions.SpeakerCycle();
end

function receiveText(texttype, message, originator)
    if npc.base.autonpcfunctions.BasicNPCChecks(originator,2) then
        if npc.base.autonpcfunctions.LangOK(originator,TradSpeakLang) then
            npc.base.autonpcfunctions.TellSmallTalk(message,originator);
        else
            npc.base.autonpcfunctions.Confused(
               "#me sieht dich leicht verwirrt an",
               "#me looks at you a little confused"
            );
        end
    end
end
