--------------------------------------------------------------------------------
-- NPC Name: Natiana Banius                                          Runewick --
-- NPC Job:  Sickly Housewife                                                 --
--                                                                            --
-- NPC Race: human                      NPC Position:  891, 540, 0            --
-- NPC Sex:  female                     NPC Direction: south                  --
--                                                                            --
-- Author:   Grokk                                                            --
--                                                       easyNPC Parser v1.21 --
--------------------------------------------------------------------------------

--[[SQL
INSERT INTO "npc" ("npc_type", "npc_posx", "npc_posy", "npc_posz", "npc_faceto", "npc_name", "npc_script", "npc_sex", "npc_hair", "npc_beard", "npc_hairred", "npc_hairgreen", "npc_hairblue", "npc_skinred", "npc_skingreen", "npc_skinblue") 
VALUES (0, 891, 540, 0, 4, 'Natiana Banius', 'npc.natiana_banius', 1, 1, 0, 218, 162, 39, 255, 228, 186);
---]]

require("npc.base.basic")
require("npc.base.condition.chance")
require("npc.base.condition.language")
require("npc.base.condition.quest")
require("npc.base.consequence.inform")
require("npc.base.talk")
module("npc.natiana_banius", package.seeall)

function initNpc()
mainNPC = npc.base.basic.baseNPC();
local talkingNPC = npc.base.talk.talkNPC(mainNPC);
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.quest.quest(322, ">", 11));
talkEntry:addTrigger(".+");
talkEntry:addConsequence(npc.base.consequence.inform.inform("[Error] Something went wrong, please inform a developer."));
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Help");
talkEntry:addConsequence(npc.base.consequence.inform.inform("[Game Help] This NPC is Natiana Banius the farmer's wife. Keywords: quest"));
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Hilfe");
talkEntry:addConsequence(npc.base.consequence.inform.inform("[Spielhilfe] Dieser NPC ist Natiana Banius die Frau des Bauern. Schlüsselwörter: Auftrag"));
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Hello");
talkEntry:addTrigger("Greet");
talkEntry:addTrigger("Hail");
talkEntry:addTrigger("Good day");
talkEntry:addTrigger("Good morning");
talkEntry:addTrigger("Good evening");
talkEntry:addTrigger("Good night");
talkEntry:addResponse("#me struggles to open her eyes, looking up at you.");
talkEntry:addResponse("#me smiles weakly.");
talkEntry:addResponse("H...h...hello.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Grüß");
talkEntry:addTrigger("Gruß");
talkEntry:addTrigger("Guten Morgen");
talkEntry:addTrigger("Guten Tag");
talkEntry:addTrigger("Guten Abend");
talkEntry:addTrigger("Gute Nacht");
talkEntry:addTrigger("Mahlzeit");
talkEntry:addTrigger("Tach");
talkEntry:addTrigger("Moin");
talkEntry:addTrigger("Mohltied");
talkEntry:addResponse("#me bemüht sich ihre Augen zu öffnen um dich anzusehen.");
talkEntry:addResponse("#me lächelt schwach.");
talkEntry:addResponse("H...h...hallo.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Hiho");
talkEntry:addTrigger("Hallo");
talkEntry:addTrigger("Hey");
talkEntry:addTrigger("Greeb");
talkEntry:addResponse("#me struggles to open her eyes, looking up at you.");
talkEntry:addResponse("#me smiles weakly.");
talkEntry:addResponse("H...h...hello.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Hiho");
talkEntry:addTrigger("Hallo");
talkEntry:addTrigger("Hey");
talkEntry:addTrigger("Greeb");
talkEntry:addResponse("#me bemüht sich ihre Augen zu öffnen um dich anzusehen.");
talkEntry:addResponse("#me lächelt schwach.");
talkEntry:addResponse("H...h...hallo.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Farewell");
talkEntry:addTrigger("Bye");
talkEntry:addTrigger("Fare well");
talkEntry:addTrigger("See you");
talkEntry:addResponse("T...t...take...care.");
talkEntry:addResponse("#me lightly taps your hand in acknowledgment.");
talkEntry:addResponse("#me slightly inclines her head.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Tschüß");
talkEntry:addTrigger("Tschüss");
talkEntry:addTrigger("Wiedersehen");
talkEntry:addTrigger("Gehab wohl");
talkEntry:addResponse("P...passt auf E...Euch auf.");
talkEntry:addResponse("#me drückt sanft deine Hand zur Bestätigung.");
talkEntry:addResponse("#me neigt leicht ihren Kopf.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Ciao");
talkEntry:addTrigger("Adieu");
talkEntry:addTrigger("Au revoir");
talkEntry:addTrigger("Farebba");
talkEntry:addResponse("T...t...take...care.");
talkEntry:addResponse("#me lightly taps your hand in acknowledgment.");
talkEntry:addResponse("#me slightly inclines her head.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Ciao");
talkEntry:addTrigger("Adieu");
talkEntry:addTrigger("Au revoir");
talkEntry:addTrigger("Farebba");
talkEntry:addResponse("P...passt auf E...Euch auf.");
talkEntry:addResponse("#me drückt sanft deine Hand zur Bestätigung.");
talkEntry:addResponse("#me neigt leicht ihren Kopf.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("How are you");
talkEntry:addTrigger("How feel");
talkEntry:addTrigger("How do you do");
talkEntry:addResponse("I am...v...very...sick.");
talkEntry:addResponse("T...the...medico does...doesn't know what...i...is wrong...with me.");
talkEntry:addResponse("#me coughs into a handkerchief, stained red.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Wie geht");
talkEntry:addTrigger("Wie fühlst");
talkEntry:addTrigger("Wie ist es ergangen");
talkEntry:addTrigger("Wie Befind");
talkEntry:addResponse("Ich...ich bin...s...sehr krank.");
talkEntry:addResponse("D...der...Heiler, w...weiß nicht, was mit mir n...nicht stimmt.");
talkEntry:addResponse("#me hustet in ein blutbeflecktes Taschentuch.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("your name");
talkEntry:addTrigger("who are you");
talkEntry:addTrigger("who art thou");
talkEntry:addResponse("I am...N...Natiana.");
talkEntry:addResponse("M...m...my name...is Natiana...Banius.");
talkEntry:addResponse("N...Natiana Banius. I...I am...the wife...o...of Rowan.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("ihr name");
talkEntry:addTrigger("dein name");
talkEntry:addTrigger("wer bist du");
talkEntry:addTrigger("wer seid ihr");
talkEntry:addTrigger("wie heißt");
talkEntry:addResponse("I...Ich bin...Natiana...Banius.");
talkEntry:addResponse("N...Natiana Banius. I...Ich... bin...Rowans...F...Frau.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.quest.quest(322, "<", 11));
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("quest");
talkEntry:addTrigger("mission");
talkEntry:addResponse("P...please...help my husband.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.quest.quest(322, "<", 11));
talkEntry:addTrigger("quest");
talkEntry:addTrigger("mission");
talkEntry:addResponse("B...bitte...helft meinem Mann.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.quest.quest(322, "<", 11));
talkEntry:addTrigger("task");
talkEntry:addTrigger("adventure");
talkEntry:addResponse("M...my...husband.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.quest.quest(322, "<", 11));
talkEntry:addTrigger("Auftrag");
talkEntry:addTrigger("Aufgabe");
talkEntry:addTrigger("Abenteuer");
talkEntry:addResponse("M..Mein...Mann.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.quest.quest(1337, "=", 11));
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger(".+");
talkEntry:addResponse("#me forces a smile, 'Thank you.'");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.quest.quest(1337, "=", 11));
talkEntry:addTrigger(".+");
talkEntry:addResponse("#me ringt sich ein Lächeln ab,'Habt Dank'.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("profession");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("beruf");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("job");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("job");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Gobaith");
talkEntry:addTrigger("Gobiath");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Gobaith");
talkEntry:addTrigger("Gobiath");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("my name");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("mein Name");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("archmage");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Erzmagier");
talkEntry:addResponse("GERMAN1.");
talkEntry:addResponse("GERMAN2.");
talkEntry:addResponse("GERMAN3.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Elvaine");
talkEntry:addTrigger("Morgan");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Elvaine");
talkEntry:addTrigger("Morgan");
talkEntry:addResponse("GERMAN1.");
talkEntry:addResponse("GERMAN2.");
talkEntry:addResponse("GERMAN3.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Runewick");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Runewick");
talkEntry:addResponse("GERMAN1.");
talkEntry:addResponse("GERMAN2.");
talkEntry:addResponse("GERMAN3.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Valerio");
talkEntry:addTrigger("Guilianni");
talkEntry:addTrigger("Don");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Valerio");
talkEntry:addTrigger("Guilianni");
talkEntry:addTrigger("Don");
talkEntry:addResponse("GERMAN1.");
talkEntry:addResponse("GERMAN2.");
talkEntry:addResponse("GERMAN3.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Galmair");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Galmair");
talkEntry:addResponse("GERMAN1.");
talkEntry:addResponse("GERMAN2.");
talkEntry:addResponse("GERMAN3.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Queen");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Königin");
talkEntry:addResponse("GERMAN1.");
talkEntry:addResponse("GERMAN2.");
talkEntry:addResponse("GERMAN3.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("rosaline");
talkEntry:addTrigger("edwards");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("rosaline");
talkEntry:addTrigger("edwards");
talkEntry:addResponse("GERMAN1.");
talkEntry:addResponse("GERMAN2.");
talkEntry:addResponse("GERMAN3.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Cadomyr");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Cadomyr");
talkEntry:addResponse("GERMAN1.");
talkEntry:addResponse("GERMAN2.");
talkEntry:addResponse("GERMAN3.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("albar");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("albar");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("gynk");
talkEntry:addTrigger("gync");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("gync");
talkEntry:addTrigger("gynk");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("salkama");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("salkama");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("god");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Gott");
talkEntry:addTrigger("Götter");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("B...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Adron");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Adron");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Bragon");
talkEntry:addTrigger("Brágon");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Bragon");
talkEntry:addTrigger("Brágon");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Cherga");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Cherga");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Elara");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Elara");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Eldan");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Eldan");
talkEntry:addResponse("GERMAN1.");
talkEntry:addResponse("GERMAN2.");
talkEntry:addResponse("GERMAN3.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Findari");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Findari");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Irmorom");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Irmorom");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Malachin");
talkEntry:addTrigger("Malachín");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Malachin");
talkEntry:addTrigger("Malachín");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Moshran");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Nargun");
talkEntry:addTrigger("Nargún");
talkEntry:addTrigger("Nargùn");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Nargun");
talkEntry:addTrigger("Nargún");
talkEntry:addTrigger("Nargùn");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Oldra");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Oldra");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Ronagan");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Ronagan");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Sirani");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Sirani");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Tanora");
talkEntry:addTrigger("Zelphia");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Tanora");
talkEntry:addTrigger("Zelphia");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Ushara");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Ushara");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Zhambra");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Zhambra");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Aurora");
talkEntry:addResponse("#me forces a weak smile at the mention of the name.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Aurora");
talkEntry:addResponse("#me ringt sich ein schwaches Lächen ab, als sie den Namen hört.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("what sell");
talkEntry:addTrigger("what buy");
talkEntry:addTrigger("list wares");
talkEntry:addTrigger("price of");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("was verkauf");
talkEntry:addTrigger("was kauf");
talkEntry:addTrigger("warenliste");
talkEntry:addTrigger("preis von");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("tell something");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("erzähl was");
talkEntry:addTrigger("erzähl etwas");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addTrigger("Natiana");
talkEntry:addTrigger("Banius");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Natiana");
talkEntry:addTrigger("Banius");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Yes");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Ja");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("No");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addTrigger("Nein");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("english"));
talkEntry:addCondition(npc.base.condition.chance.chance(20.0));
talkEntry:addTrigger(".*");
talkEntry:addResponse("F...forgive me...I...m...must rest.");
talkEntry:addResponse("#me's eyes flicker for a few moments, before falling completely shut. Faint breaths can only just be made out.");
talkEntry:addResponse("P...please...let me...rest.");
talkEntry:addResponse("#me's head slowly lolls about. She seems unfocused upon the conversation.");
talkEntry:addResponse("I m...must save my...strength.");
talkEntry:addResponse("I should...s...save...my breath.");
talkEntry:addResponse("P...please...h...help...my husband.");
talkEntry:addResponse("Rowan...n...needs help.");
talkEntry:addResponse("#me coughs sharply, wincing in pain.");
talkingNPC:addTalkingEntry(talkEntry);
end;
if (true) then
local talkEntry = npc.base.talk.talkNPCEntry();
talkEntry:addCondition(npc.base.condition.language.language("german"));
talkEntry:addCondition(npc.base.condition.chance.chance(20.0));
talkEntry:addTrigger(".*");
talkEntry:addResponse("Ver...vergebt mir, ... ich muss ausruhen.");
talkEntry:addResponse("#mes Augen zucken unruhig, bevor sie entgültig zufallen. Man kann gerade noch ihren schwachen Atem erahnen.");
talkEntry:addResponse("b...bitte, lasst mich ausruhen.");
talkEntry:addResponse("#me's head neigt sich langsam. Sie ist scheinbar zu unkonzentiert für ein Gespräch.");
talkEntry:addResponse("Ich... muss...mein...K...Kräfte...sparen.");
talkEntry:addResponse("B..Bitte,...h..helft m...mein...Mann.");
talkEntry:addResponse("Rowan...b...braucht...E...Eure Hilfe.");
talkEntry:addResponse("#me hustet bellend/keuchend und zuckt vor Schmerz krampfhaft zu sammen.");
talkingNPC:addTalkingEntry(talkEntry);
end;
talkingNPC:addCycleText("#me lächelt schwach.", "#me smiles weakly.");
talkingNPC:addCycleText("#me hustet in ein blutgetränktes Taschentuch.", "#me coughs into a stained-red handkerchief.");
talkingNPC:addCycleText("#me blickt mit frendlicher Mine zu ihrem Mann.", "#me glaces at her husband a warm expression on her face.");
talkingNPC:addCycleText("#me schließt ihre Augen, und dämmert weg in unruhigen Schlaf.", "#me closes her eyes, drifting into a fitful sleep.");
talkingNPC:addCycleText("#me seuftz schwach.", "#me sighs faintly.");
talkingNPC:addCycleText("#me lächelt ihrem Mann zu.", "#me smiles at her husband.");
talkingNPC:addCycleText("#me's Augenlieder flackern ein paar mal, dann schläft sie.", "#me's eyes flicker a few times, before falling shut.");
talkingNPC:addCycleText("#me wendet ihren leicht.", "#me turns her head slightly.");
talkingNPC:addCycleText("#me nickt schwach.", "#me nods weakly.");
talkingNPC:addCycleText("#me hustet keuchend und zuckt vor Schmerz krampfhaft zusammen.", "#me lets out a sharp cough, wincing in pain.");
mainNPC:addLanguage(0);
mainNPC:addLanguage(1);
mainNPC:setDefaultLanguage(0);
mainNPC:setLookat("Dieser NPC ist Natiana die Frau des Bauern.", "This NPC is Natiana Banius the Farmer's Wife.");
mainNPC:setUseMessage("#me zittert, 'k...ko...komm mir n...nicht z..z..zu nahe.'", "#me shivers, 'D...d...don't...get...t...too...close.'");
mainNPC:setConfusedMessage("#me schüttelt schwach ihren Kopf.", "#me weakly shakes her head.");
mainNPC:setEquipment(1, 0);
mainNPC:setEquipment(3, 182);
mainNPC:setEquipment(11, 0);
mainNPC:setEquipment(5, 0);
mainNPC:setEquipment(6, 0);
mainNPC:setEquipment(4, 48);
mainNPC:setEquipment(9, 841);
mainNPC:setEquipment(10, 53);
mainNPC:setAutoIntroduceMode(true);

mainNPC:initDone();
end;

function receiveText(npcChar, texttype, message, speaker) mainNPC:receiveText(npcChar, speaker, message); end;
function nextCycle(npcChar) mainNPC:nextCycle(npcChar); end;
function lookAtNpc(npcChar, char, mode) mainNPC:lookAt(npcChar, char, mode); end;
function useNPC(npcChar, char, counter, param) mainNPC:use(npcChar, char); end;
initNpc();
initNpc = nil;
-- END