-- triggerfields for better atmosphere

--[[ SQL Statements:
INSERT INTO triggerfields VALUES (X,Y,Z,'triggerfield.ambient');

]]

require("base.common")

module("triggerfield.ambient", package.seeall)

--[[
position: coordinates
direction: array with directions, 0=North,2=East,4=South,6=West. Set nil for always
german/english: text
hours: array with hours when text shall be shown, in range of 0 to 23. Set to nil for always.
months: array with months when text shall be shown, in range of 1 to 16. Set to nil for always.
chance: Chance that this triggerfield is triggered in percent (integer)

for script:
AmbientList:add( position(x,y,z), {0,1,7}, "german", "english", {0,1,23}, {1,2,16}, chance );

for db:
INSERT INTO triggerfields VALUES (x,y,z,'triggerfield.ambient');
]]


AmbientList = {	add = function ( self, pos, direction, german, english, hours, months, chance )
						if not self[pos.x] then
							self[pos.x] = {};
						end
						if not self[pos.x][pos.y] then
							self[pos.x][pos.y] = {};
						end
						if not self[pos.x][pos.y][pos.z] then
							self[pos.x][pos.y][pos.z] = {};
						end
						local this = self[pos.x][pos.y][pos.z];
						table.insert(this, {
                            direction = direction or {0,1,2,3,4,5,6,7};
							german = german or "";
							english = english or "";
							hours = hours or {0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23};
							months = months or {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16};
                            chance = chance or 100;
							} );
				end
}

-- Tutorial by Rincewind and Estralis
AmbientList:add( position(28,101,100 ),{5,6,7},"[Tutorial] Dies ist der Weg nach Runewick, dem Reich der Weisheit und Magie.","[Tutorial] This is the way to Runewick, realm of wisdom and magic.",nil,nil,100); --Tutorial
AmbientList:add( position(36,108,100 ),{3,4,5},"[Tutorial] Dies ist der Weg nach Galmair, dem Reich des aufstrebenden Wohlstands.","[Tutorial] This is the way to Galmair, realm of prosperity and wealth.",nil,nil,100); --Tutorial
AmbientList:add( position(45,97,100 ),{1,2,3},"[Tutorial] Dies ist der Weg nach Cadomyr, dem Reich von Ruhm und Ehre.","[Tutorial] This is the way to Cadomyr, realm of honour and glory.",nil,nil,100); --Tutorial

--SW map by Estralis et al.
AmbientList:add( position(93,587,0),nil,"In der Ferne hörst du das Bellen eines Hundes.","In the distance, you can hear a barking dog.",nil,nil,1); --General Cadomyr
AmbientList:add( position(105,569,0),nil,"Ein scharfer Wind bläßt durch die Straßen Cadomyrs.","A strong wind blows in the streets of Cadomyr.",nil,nil,1); --General Cadomyr
AmbientList:add( position(121,551,0),nil,"Überall um dich herum spürst du den Stolz und die Ehre Cadomyrs.","All around, you can feel the pride and honour of Cadomyr.",nil,nil,1); --General Cadomyr
AmbientList:add( position(130,587,0),nil,"In der Ferne hörst du Gelächter.","In the distance, you can hear laughter.",nil,nil,1); --General Cadomyr
AmbientList:add( position(130,606,0),nil,"Ein Hund bellt irgendwo im Norden. Oder ist es ein schnarchender Ork?","A dog barks to the north, or was that an angry orc?",nil,nil,1); --General Cadomyr
AmbientList:add( position(121,565,0),nil,"Die Wüstenblume Cadomyr erscheint heute in besonderer Blüte zu stehen.","The desert flower, Cadomyr, seems to blossom in a special way today.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,1); --General Cadomyr, daylight
AmbientList:add( position(251,528,0),nil,"Deine Füße hinterlassen flache Eindrücke im weichen Sand.","Your feet make shallow imprints in the shifting sand.",nil,nil,10); --General desert
AmbientList:add( position(259,570,0),nil,"Der Wind bläßt dir Sandkörner ins Gesicht.","The wind blows sand grains at your face.",nil,nil,10); --General desert
AmbientList:add( position(263,598,0),nil,"Die Sandlandschaft ist hier flach und eintönig, die Orientierung fällt dir schwer.","The sandy ground is flat with no obvious landmarks. Judging distances becomes quite difficult.",nil,nil,10); --General desert
AmbientList:add( position(264,631,0),nil,"Ein starker Wind bläst über die Dünen.","A strong wind blows in the dunes.",nil,nil,10); --General desert
AmbientList:add( position(298,677,0),nil,"Eine plötzliche Windböe blößt dir Sand ins Gesicht. Die Tränen schießen dir in die Augen und du reibst sie ausgiebig.","A sudden gust of wind blows sand into your face. Tears flood your eyes and you rub them profusely. ",nil,nil,10); --General desert
AmbientList:add( position(331,537,0),nil,"Der Sand knirscht unter deinen Füßen.","The sand crunches under your feet.",nil,nil,10); --General desert
AmbientList:add( position(336,563,0),nil,"Vor dir erstrecken sich die Dünen, so weit das Auge reicht.","The dunes ahead of you seem to stretch endlessly.",nil,nil,10); --General desert
AmbientList:add( position(348,710,0),nil,"Warmer Wind bläst durch die Wüste und Geheul ist in der Ferne zu hören.","A warm wind blows across the desert, and howls can be heard in the distance.",nil,nil,10); --General desert
AmbientList:add( position(349,576,0),nil,"Du wirst das Gefühl nicht los, dass dich jemand beobachtet.","You struggle to ignore the strange feeling that you are being watched.",nil,nil,10); --General desert
AmbientList:add( position(365,619,0),nil,"Ein scharfer Wind wirbelt den Sand um dich herum auf als du dich dem Herz der Wüste Katanbi näherst.","The fierce wind bellows and blows the sand wildly around you; the Katanbi desert proves quite treacherous.",nil,nil,10); --General desert
AmbientList:add( position(400,709,0),nil,"Nach dem anstrengenden Marsch durch feinen Sand mutet es regelrecht erfrischend an, wieder festen Boden unter den Füßen zu haben. ","Walking through the sand proves to be quite the workout for your legs and feet as you dredge along.",nil,nil,10); --General desert
AmbientList:add( position(402,707,0),nil,"Beim Umherstreifen in der Wüste rinnt dir immer wieder etwas Sand ins Schuhwerk und scheuert zwischen deinen Zehen. ","Whilst roaming the desert, sand trickles through your footwear over and over again, rubbing between your toes. ",nil,nil,10); --General desert
AmbientList:add( position(109,709,0),nil,"Vom sandigen Boden her steigt eine Hitze auf, die deine Augen austrocknet.","The heat of the sand is rising up to meet your dry eyes.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General desert, daylight
AmbientList:add( position(171,686,0),{0,1,7},"Weit im Norden erheben sich die Einsamen Berge, majestätisch umkreisen mächtige Adler die Bergspitzen.","Far to the north, the Lonely Mountains rise. Proud eagles fly around the mountain tops majestically.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General desert, daylight
AmbientList:add( position(206,737,0),nil,"Sand schießt dir entgegen und prasselt in dein Gesicht, es wird schwierig, etwas zwischen den Dünen zu erkennen.","While the wind should bring comfort in the beating sun the presence of sand in each gust only brings agitation.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General desert, daylight
AmbientList:add( position(244,720,0),nil,"Die Sonne blendet dich auf dem Marsch durch die Wüste. Du setzt deinen Weg fort, doch schützt du deine Augen mit der Hand vor dem grellen Schein.","The bright sun dazzles you as you walk through the desert. As you continue along it becomes necessary to shield your eyes from its glare.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General desert, daylight
AmbientList:add( position(285,711,0),nil,"In der Ferne erblickst du eine Wolke von Sand und Staub, die auf dich zugeweht wird.","In the distance you see the sand and dust being blown in your direction. ",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General desert, daylight
AmbientList:add( position(330,752,0),nil,"Du bemerkst eine verlockende Oase in der Ferne. Als du dir aber die Augen reibst, verschwindet das Trugbild.","You notice an oasis in the distance agonisingly close, but as you rub your eyes the mirage vanishes.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General desert, daylight
AmbientList:add( position(345,715,0),nil,"Hoch über dir zieht ein Geier seine Kreise, ein fürwahr unheilvolles Omen.","Above, a vulture soars through the skies. A troubling sign, indeed. ",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General desert, daylight
AmbientList:add( position(400,695,0),nil,"Ein Geier zieht seine Kreise über der Wüste.","A vulture flies in circles over the desert.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General desert, daylight
AmbientList:add( position(412,762,0),nil,"Eine kleine Echse läuft geschwind eine Sandverwehung herab.","A small lizard runs swiftly down a sand drift.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General desert, daylight
AmbientList:add( position(437,797,0),{5,6,7},"Die karge Wüste Katanbi erstreckt sich vor dir. Eine Sandhose bildet sich in der Ferne.","You find yourself between dunes on an open plane when you spot a swirling column of sand ominously looming in the distance.",{8,9,10,11,12,13,14,15,16,17,18,19,20},Nil,10); --General desert, daylight
AmbientList:add( position(213,740,0),nil,"Die Sonne strahlt gnadenlos auf dich herab. Durst beginnt dich zu matern.","The high sun beats down on you harshly. You begin to feel thirsty very quickly.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(239,639,0),nil,"Der heiße Wüstenwind treibt sein munteres Spiel mit einer Windhose aus Sand.","The hot desert wind plays its game with a small vortex of sand forming nearby.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(240,522,0),nil,"Die Hitze der Wüste wird unerträglich. Du fragst dich, wie du hier ohne Sonnenstich wieder herauskommst.","The cruel desert shows you no mercy and you just hope you have enough supplies to make it across.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(246,711,0),nil,"Die Sonne steht hoch am Himmel, deine Augenbrauen glitzern vom Schweiß.","The sun is high in the air, your brow glistens with sweat as you feel its heat.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(266,718,0),nil,"Dein Kopf beginnt sich zu drehen, vermutlich von der Sonne die konstant auf dich hinabscheint.","You start to feel lightheaded with the sun constantly beaming down on you.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(282,646,0),nil,"Die Sonne brennt gnadenlos auf die Wüste nieder.","The sun scorches the desert without mercy.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(300,592,0),nil,"Die Luft ist hier heiß und trocken.","The air wouldn't be so terrible to breathe if you weren't so thirsty and the gusts of wind didn't blow sand into your mouth. ",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(321,529,0),nil,"Die Luft flimmert vor Hitze, gelegentliche Windböen versprechen keine Erleichterung sondern vielmehr Irritation, blasen sie doch Sand in deine Augen und deinen Mund.","The air is quivering with hot vapour. The wind does little to quench the burning heat and with each gust you're pelted with sand.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(324,763,0),nil,"Mit einem Blick in die Ferne bekommst du das Gefühl, dass die Wüste niemals enden wird.","The desert outstretches your sight and just as you reach the top of a dune it seems there is another.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(355,614,0),nil,"Die segenden Strahlen der Sonne fahren Speeren gleich auf jedes Wesen in der Wüste nieder.","Torrid sunbeams dart like spears at every being in the desert.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(352,712,0),nil,"Die unerträgliche Hitze macht jeden Schritt zu einer Tortur.","The unrelenting heat tortures you with every step you take.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(371,569,0),nil,"Die schier endlosen Sandmassen verschwimmen in der Ferne zu einer wabernden Masse. Erbarmungslos brennt die Sonne von oben hernieder.","Vast lands of sand are stretching off into the distance gradually blurring into a wafting mass. From above, the sun burns incessantly.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(427,743,0),nil,"Du spürst die unerträgliche Hitze der Sonnenstrahlen dieses Tages in der Wüste Katanbi auf deiner Haut.","You feel a heavy, almost unbearable heat from the sun's rays this day.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(391,774,0),nil,"Eine angenehm kühle Brise bläßt dir ins Gesicht, dennoch wirkt die Wüste unwirtlich und feindlich.","A calm breeze blows in your face, without sand this time, but the desert still reaches out before you in the most inhospitable way.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{13,14,15,16},10); --General desert, daylight, winter
AmbientList:add( position(73,770,0),{5,6,7},"Am Strand siehst du einen wundervollen Sonnenuntergang, der das Wasser und die fernen Wolken in ein anmutiges Licht taucht.","From the beach you can see the beautiful sunset, covering the distant waters and clouds with an orange glow.",{17,18,19,20},nil,10); --General desert, late daylight
AmbientList:add( position(214,606,0),nil,"Eine Sternschnuppe erhellt kurzzeitig den Nachthimmel, bevor sie am Horizont verschwindet.","A shooting star lights up the sky before it vanishes at the horizon.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(236,666,0),nil,"Du kannst genau die Geräusche der Wüstentiere vernehmen, die die Gelegenheit zur Nahrungssuche unter dem Sternenhimmel wahrnehmen, nun, da die Hitze nicht so unerträglich ist wie tagsüber.","You can hear the wildlife of the desert as the animals take the chance to find food under the infinite stars scattered across the night sky.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(282,678,0),nil,"Die Sandmassen unter dem Nachhimmel sind zur Ruhe gekommen. Nur ihre starke Abwärme zeugt noch von der Hitze des vergangenen Tages.","The desert beneath the night sky has come to rest. The warming radiation the sand emits is the only testimony to the preceding day's heat.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(289,601,0),nil,"In der Wüste ist es kalt und still, wäre nicht das fahle Licht der Monde, könnte man sich schnell verlaufen.","The desert is dark and quiet. Were it not for the faint light of the moons overhead you could easily get lost here.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(297,574,0),nil,"Eine Wolke umhüllt den kleinen Mond Illarions, bekannt als der jüngere Bruder.","A cloud engulfs the small moon of Illarion, and if you are not familiar with this area you may find it difficult to navigate.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(325,517,0),nil,"Hoch am Firmament setzen die Monde ihre immerwährende Jagd fort.","High in the firmament, the moons continue their everlasting chase.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(337,655,0),nil,"Kühler Wind bläst über die Wüste und Geheul ist in der Ferne zu hören. Plötzlich hallt ein markerschütternder Schrei durch das Tal, ein kalter Schauer läuft dir über den Rücken.","A chilly wind blows across the desert and howls can be heard in the distance. Suddenly, a scream echoes across the valley floor sending chills up your spine.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(349,547,0),nil,"Es ist eigentlich bitterkalt, aber der Sand glüht noch immer vor Hitze. ","It's freezing, but the sand still carries some heat.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(358,626,0),nil,"Im fahlen Licht der Monde erscheint die Wüste als ein noch unwirtlicher Ort als sonst.","In the pale light of the moons the desert appears to be an even more inhospitable place.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(380,645,0),nil,"In der Nacht ist es in der Wüste alles andere als heiß.","There is nothing warm about this place at night.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(405,746,0),nil,"Die Nacht in der Wüste ist ungleich kühler als der Tag, die Tiere des Wüstenbodens erwachen zu nächtlichen Spaziergängen.","The night in the desert is much colder than the day. Creatures emerge in search of their nightly harvest.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(422,790,0),nil,"Die Kakteen werfen im fahlen Licht der Monde obskure Schatten.","The pale moons make the cacti cast obscure shadows.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General desert, night
AmbientList:add( position(112,668,-4),nil,"Ein fahler Verwesungsgeruch zieht dir in die Nase.","You can smell the mustiness of the air down here.",nil,nil,10); --Specific Cadomyr
AmbientList:add( position(113,586,0),{0,1,7},"Dir schlägt der Geruch von Wein und Bier entgegen. Doch scheinen die Bewohner Cadomyrs sogar noch im Suff ihre Ehre zu behalten.","You smell wine and beer, however, the citizens of Cadomyr look proud and noble - even if they're drunk.",nil,nil,10); --Specific Cadomyr
AmbientList:add( position(115,607,0),nil,"Das Plätschern des knappen Gut Wasser übt eine ungemein beruhigende Wirkung aus.","The splashing of water in this desolate place makes you feel relaxed and comfortable.",nil,nil,10); --Specific Cadomyr
AmbientList:add( position(116,649,-4),nil,"Im Augenwinkel erspähst du einen dunklen Schatten in den Tiefen der Gruft, doch verschwindet er schneller, als du deinen Kopf drehen kannst.","You catch a glimpse of a silhouette in the distant darkness of the tomb, but before you can get a good look it vanishes suddenly.",nil,nil,10); --Specific Cadomyr
AmbientList:add( position(127,667,-4),nil,"Während du durch die Gruft gehst, meinst du, Geflüster zu hören, aber es ist niemand zu sehen.","As you walk through the tomb, you hear whispering tongues, but you see nobody around.",nil,nil,10); --Specific Cadomyr
AmbientList:add( position(133,589,0),nil,"Obwohl sie bereits abgewischt wurden, kann man noch einige Worte an der Mauer im Osten ausmachen: 'Hastings auf den Thron!'","Albeit wiped off, one can make out that words were written on the wall to the east: 'Hastings for the throne!'",nil,nil,10); --Specific Cadomyr
AmbientList:add( position(134,671,-4),nil,"Dieser Ort macht auf dich einen majestätischer Eindruck, die vergangene Macht des beinahe schon vergessenen Altkönigs ist allgegenwärtig. Jedoch kannst du nicht verleugnen, dass hier noch etwas anderes sein Unwesen treibt…","The feel of majesty and ancient power is at work here, and you can't help but feeling that someone unseen is leaning over your shoulder. ",nil,nil,10); --Specific Cadomyr
AmbientList:add( position(146,664,-4),nil,"Der modrige Geruch der Verwesung erfüllt die Gruft.","A musty smell of decay fills the tomb.",nil,nil,10); --Specific Cadomyr
AmbientList:add( position(155,638,-4),nil,"In der Gruft riecht es abgestanden und modrig. Die Wände sind mit fein gearbeiteten Inschriften versehen. Es ist kalt und feucht hier unten.","The cold clammy crypt reeks with mould and decay. Beneath the layers of dust and sand you can see impressive inscriptions adorning the hallowed halls.",nil,nil,10); --Specific Cadomyr
AmbientList:add( position(121,609,0),nil,"Auf dem Markplatz von Cadomyr herrscht geschäftiges Treiben.","The marketplace of Cadomyr resounds with business and ado.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --Specific Cadomyr, daylight
AmbientList:add( position(120,602,0),nil,"Auf dem Marktplatz nimmst du die verschiedensten Düfte wahr. Einige Kaufleute unterhalten sich, andere sortieren ihre Waren.","At the marketplace you find much bustle and an array of exotic fragrances. You see some merchants conversing and arguing, customers haggling, and other traders preoccupied with sorting their goods.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --Specific Cadomyr, daylight
AmbientList:add( position(121,532,0),nil,"Der Palast der Edwards erscheint heute in besonderem Glanz.","The Edwards' palace radiates a special brilliance today.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --Specific Cadomyr, daylight
AmbientList:add( position(121,546,0),{0,1,7},"Beim Betreten des Palastes hörst du das Keifen der Königin von den Mauern widerhallen: 'Wo bleibt Hassan!'","Upon entering the palace, you hear the queen nagging: 'Where is Hassan?!'",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --Specific Cadomyr, daylight
AmbientList:add( position(119,604,0),nil,"Es ist nicht mehr viel los auf dem Marktplatz von Cadomyr. Die meisten Händler bauen gerade ihre Stände ab und reden nochmal über den Tag.","Not much is going on at the market place of Cadomyr. Most of the merchants are packing their bags and summing up their day.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --Specific Cadomyr, night
AmbientList:add( position(134,543,0),nil,"Die Nacht hat sich über den Palast gelegt, hier und da hört man das Schnarchen der Wachen.","Night has fallen on the palace, and only the cool night breeze and some loud snoring can be heard.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --Specific Cadomyr, night
AmbientList:add( position(29,543,0),nil,"Unter das Meeresrauschen mischen sich auch bärbeißige Männerstimmen - es wird viel gespottet und geflucht. Bei genauerem Hinsehen kannst du einige bullige Silhouetten ausmachen. Sei auf der Hut! ","A number of abrasive male voices pervade along with the sea breeze - there's a lot of foul language and mockery going on. Upon closer examination, you're able to spot several burly silhouettes. Be on your guard! ",nil,nil,100); --Specific location
AmbientList:add( position(130,564,0),{1,2,3},"Als du den Tempel betrittst, durchfährt dich ein gesegnetes Gefühl.","As you enter the temple, a blessed feeling rises in you.",nil,nil,100); --Specific location
AmbientList:add( position(127,636,-4),{0,1,7},"An der Wand im Norden kann man lesen: 'Hastings gehört Cadomyr!'","At the wall in the north one can read: 'Hastings owns… Cadomyr.'",nil,nil,100); --Specific location
AmbientList:add( position(136,696,0),nil,"Du hörst das Klacken von Metall auf Stein, die Luft hier ist staubig und trocken. Die Enge würde einfache Gemüter wahnsinnig machen.","You hear the clinking of metal on stone. The dusty air and tight space would drive those weak of mind to madness. ",nil,nil,100); --Specific location
AmbientList:add( position(157,665,-4),nil,"Die Überreste prunkvoller Grabbeigaben liegen zerwühlt auf dem Boden herum.","The remnants of pompous burial objects are scattered over the ground.",nil,nil,100); --Specific location
AmbientList:add( position(226,513,0),{0,1,7},"In der Ferne sichtest du ein schäbig anmutendes Lager, in dem sich eine Rotte aus zwielichtigen Gestalten tummelt. Für rastende Kaufleute sehen sie definitv zu ungepflegt und rauhbeinig aus. Sei auf der Hut! ","You spot a shabby looking camp in the distance, populated by a mob of ragtag individuals. As you watch them they look far too gruff and unkempt to be simple merchants. Be on your guard!",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,100); --Specific location
AmbientList:add( position(250,512,0),{0,1,7},"Irgendwie fühlst du dich beobachtet von jemanden, den du besser nicht treffen willst. Umkehren ist eine gute Idee, mit mehr Gold wirst du sicher nicht zurückkehren…","You feel as if someone is watching you. The feeling is unnerving and instantly puts you on alert.",nil,nil,100); --Specific location
AmbientList:add( position(359,689,0),nil,"Wie ein Farbklecks auf einer kahlen Wand ragt dieser grüne Streifen aus der Einöde heraus. Eine kleine Zahl von schlanken Palmen, Blumen und Büschen rankt sich um eine Wassergrube, welche von einem Bächlein gespeist wird. ","You see a strip of green rising out of the desert like a blur of color on a blank wall. Upon closer inspection you make out a few slim palm trees, flowers and shrubs entwine around a small pool of water, and a small streamlet seems to be the source of such sweet beauty. ",nil,nil,100); --Specific location
AmbientList:add( position(443,744,0),{1,2,3},"Als du die Höhle betrittst, ist es dir als läufst du gegen eine kühle unsichtbare Wand aus Luft die deinen Körper in eiskaltes Wasser zu tauchen scheint. Beisender Rauch und der Gestank verdorbenen Fleisches durchdringen die Luft.","As you enter the cave you are met with an invisible wall of cold air. It feels like your body is submerged in ice cold water after being burnt by fire. The smell of smoke and decaying flesh is overpowering.",nil,nil,100); --Specific location
AmbientList:add( position(454,795,0),{5,6,7},"Die Straße nach Cadomyr führt durch die unwirtliche Wüste, die von manchen 'Wüste der Verzweiflung' genannt wird.","The road to Cadomyr crosses the inhospitable desert, known to some as the 'Desert of Desperation'.",nil,nil,100); --Specific location
AmbientList:add( position(477,795,0),{5,6,7},"Dies scheint eine Grenze zu sein. Wenige Schritte weiter und du betrittst das stolze Königreich Cadomyr.","This looks like a border, a few steps further and you'll enter the proud kingdom of Cadomyr.",nil,nil,100); --Specific location
AmbientList:add( position(115,641,0),{0,1,7},"Der Anblick Cadomyrs ist beeindruckend, eine Zitadelle der Menschheit, die der Wüste trotzt.","Beholding Cadomyr leaves you in awe, a citadel of mankind that resists the desert.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,100); --Specific location, daylight 
AmbientList:add( position(121,663,-4),nil,"Ein kalter Hauch umschleicht deinen Nacken und ein plötzliches Unbehagen lässt dein Herz tiefer sinken. Ein leiser Strom aus ätherischen Stimmen zieht durch das Gewölbe - oder enspringen sie nur deiner Einbildung?","A cold breeze passes over the back of your neck and a sudden uneasy sensation clings to your heart. A muted stream of ethereous voices travels through the vault - or are they but a mere product of your imagination?",nil,nil,10); --Specific location
AmbientList:add( position(168,596,0),nil,"Die Wände dieser Höhle wurden von Spitzhacken behauen und massives Gebälk hält die Gesteinsmassen über dir vom Einbruch ab. Die Spuren in den bereits ausgebeuteten Adern verraten dir, dass hier Erz gefördert wird.","The walls in this cave were the making of pickaxes and massive joists keep the masses of stone from tumbling down on you. Traces in already exploited seams indicate that ore is being mined here.",nil,nil,10); --Specific location
AmbientList:add( position(132,564,0),{1,2,3},"Am Eingang fällt dir eine Steintafel mit Widmung ins Auge: 'Geweiht dem Schutzherrn all derer, die Seele, Leib und Klinge dem Kampf für eine gerechtere Welt verschrieben haben: Malachín, Gebieter über Jagd und die Kunst des Krieges.'","A stone tablet by the entrance catches your eye. It contains a dedication: 'Consecrated to the patron of all those who committed their minds, bodies and blades to the struggle for a righteous world: Malachín, master of hunting and the art of war.'",nil,nil,10); --Specific Cadomyr
AmbientList:add( position(36,655,0),nil,"Die frische Luft erquickt dich, klares Wasser umspült deine Füße.","The sparkling air makes you feel fresh, and water laps at your feet.",nil,nil,10); --General desert
AmbientList:add( position(98,783,0),nil,"Die Wellen brechen weit draußen auf dem Meer, der Wind bläßt dir Gischt ins Gesicht.","The waves break far out to sea and the wind blows spray into your face.",nil,nil,10); --General desert
AmbientList:add( position(327,541,0),nil,"Die Sonne strahlt auf dich herab und kleine Insekten umschwirren deinen Kopf. Die Wüste scheint sich von hier in alle Richtungen unendlich weit zu erstrecken.","The sun beats down and small insects crowd your eyes. The desert seems to go on forever.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General desert, daylight, not winter
AmbientList:add( position(334,524,0),nil,"Eine dünne Sandschicht bedeckt den Fels hier. Kleinere Spalten im Fels sind bereits komplett mit Sand aufgefüllt.","A thin layer of sand covers the rocks and has found its way into cracks in the ground.",nil,nil,10); --General desert
AmbientList:add( position(382,671,0),nil,"Die Spuren von Tieren sind im Sand um die Oase auszumachen. Die Vegetation ist hier üppig. ","Animal footprints can be seen leading to and from the stagnant water. The vegetation is rich and green.",nil,nil,10); --General desert
AmbientList:add( position(167,609,0),nil,"Die Steine scheinen erzhaltig zu sein, sie sind von den Spuren von Spitzhacken übersäht.","The rocks are filled with ore and bear traces of pickaxes.",nil,nil,10); --Specific location
AmbientList:add( position(100,576,0),{1,2,3},"Es ist ziemlich warm im Raum, man sollte hier mal lüften. Hinter der Theke steht ein gähnender Mann, auf einem der Stühle schnarcht ein anderer Mann vor sich hin.","It is quite warm in the room, someone should open the windows. Behind the shop counter stands a man yawning and on one of the chairs you see another man, snoring.",{0,1,2,3,4,5,6,7,21,22,23,24},{1,2,3,4,5,6,7,8,9,10,11,12},10); --Specific Cadomyr, night, not winter

--Some stuff by Rincewind
AmbientList:add( position(384,198,-6),nil,"Höhlenmalerei: Ein stattlicher Ork mit nacktem Oberkörper, trägt eine enorme Axt und schlägt auf ein derbe Trommel.","Cave art: A portly orc with a bare chest shoulders a giant axe and bangs a rustic drum.",nil,nil,65); --Galmair Underground (Orc chambers)
AmbientList:add( position(385,194,-6),nil,"Höhlenmalerei: Eine sinnliche Orkin in spährlichen, ledernen Gewändern. Ihr süßes Näschen kess in den Himmel streckend.","Cave art: A voluptuous orcess in sparse leather clothing points her cute nose into the skies.",nil,nil,65); --Galmair Underground (Orc chambers)
AmbientList:add( position(348,234,-6),nil,"Höhlenmalerei: Ein beängstigend ausehender Ork mit geballter Faust. Duztende hässliche Narben und eine Sammlung aufgeknüpfter Ohren zieren seine Erscheinung.","Cave art: A brawny, frightening orc with a raised, balled fist is covered in dozens of ugly scars and wears a chain decorated with a collection of cut ears.",nil,nil,65); --Galmair Underground (Orc chambers)
AmbientList:add( position(390,188,-6),nil,"Höhlenmalerei: Ein weißhariger, greiser Ork mit massiver, wuchtiger Rüstung. Er schwingt einen verheerenden Hammer mit beiden Armen.","Cave art: A white haired, long standing orc, wearing a massive suit of armour swings a truculent hammer with both arms.",nil,nil,65); --Galmair Underground (Orc chambers)
AmbientList:add( position(363,207,-6),nil,"Höhlenmalerei: Ein ehrenvoll posierender Ork. Lange dicke Haare gehen ihm bis zur Schulter und ein tief schwarzer Harnisch lassen ihn bedrohlich und stolz zugelich erscheinen.","Cave art: An honourably poised orc with long, thick hair down to his shoulders, wears a deep black cuirass which makes him appear menacing and proud.",nil,nil,65); --Galmair Underground (Orc chambers)
AmbientList:add( position(386,178,-6),nil,"Höhlenmalerei: Ein gammelig ausehender Goblin, umringt von Flammen. Teuflisch grinsend zeigt er seine gammeligen, spitzen Zähne.","Cave art: A scruffy goblin is surrounded by flames, devilishly grinning to show sharp rotten teeth.",nil,nil,65); --Galmair Underground (Orc chambers)
AmbientList:add( position(380,208,-6),nil,"Höhlenmalerei: Ein rasender Ork, der eine gigantische Feuer-Kriegsaxt gegen eine Gruppe übertrieben bärtiger Zwerge schwingt. Zu seinen Füßen liegen unzählige Gefallene.","Cave art: A furious orc, wielding a giant fire war axe against a group of excessively bearded dwarves,stands on the top of a mound of corpses.",nil,nil,65); --Galmair Underground (Orc chambers)
AmbientList:add( position(380,326,-6),{3,4,5},"Der Geruch von kräftigem Zwergenbier steigt dir in die Nase und der Mann an der Theke wirft dir einen mürrischen Blick zu.","The smell of strong dwarven beer wafts up your nose and the man behind the counter looks over to you with a grumpy gaze.",nil,nil,100); --Galmair Underground (Tavern)
AmbientList:add( position(379,326,-6),{3,4,5},"Der Geruch von kräftigem Zwergenbier steigt dir in die Nase und der Mann an der Theke wirft dir einen mürrischen Blick zu.","The smell of strong dwarven beer wafts up your nose and the man behind the counter looks over to you with a grumpy gaze.",nil,nil,100); --Galmair Underground (Tavern)
AmbientList:add( position(366,214,-6),nil,"Höhlenmalerei: Ein hässlicher und ganz und gar fetter Ork. Er schultert ein Fleischerbeil.","Cave art: A fat ugly orc wearing a bloody pinafore has a meat cleaver slung over his shoulder.",nil,nil,65); --Galmair Underground (Orc chambers)
AmbientList:add( position(384,175,-6),nil,"Eine grobe Gravur, in Stein gemeißelt.","A rude engraving is chiselled into the stone.",nil,nil,65); --Galmair Underground (Orc chambers)
AmbientList:add( position(352,217,-6),nil,"Höhlenmalerei: Ein schlaksiger, alter Ork. Er wirkt ungesund dürr und unzählige Narben ziehen Furchen durch seine Haut, wie bei einer Rosine. Eine Aura innerer Kraft scheint ihn zu umgeben.","Cave art: A gangly old orc looks unhealthily skinny and countless scars form furrows through his skin, resembling that of a raisin; an aura of inner strength surrounds him.",nil,nil,65); --Galmair Underground (Orc chambers)
AmbientList:add( position(389,176,-6),nil,"Höhlenmalerei: Eine krummbeinige Orkin, einen schweren Bogen spannend. Ihre Augen schimmern voll Habgier, sie wirkt niederträchtig und verschlagen.","A bandy-legged orcess draws back a heavy bow; her devious eyes seem to be filled with greed and cunning.",nil,nil,65); --Galmair Underground (Orc chambers)

--Other map parts by Estralis et al.
AmbientList:add( position(530,248,0),nil,"Auf deinem Weg durch das Unterholz fühlst du dich beobachtet.","As you make your way through the undergrowth you can't help but feel watched.",nil,nil,10); --General forest
AmbientList:add( position(579,732,0),nil,"Ein uralter, knorriger Baumstumpf trotzt hier allen Änderungen, die den Wald befallen haben.","An old, gnarled tree trunk stands before you. The forest might have grown around this ancient bark.",nil,nil,10); --General forest
AmbientList:add( position(667,167,0),nil,"Ein sanfter Windhauch umstreicht die Bäume, braun-goldene Blätter fallen zur Erde hinab.","There is a slight breeze coming through the trees which causes the dead leaves to fall to the ground.",nil,{9,10,11,12},10); --General forest
AmbientList:add( position(695,186,0),nil,"Der Wald ist hier sehr dicht. Ihn zu durchqueren hat mit Lustwandeln nichts zu tun, spitze Zweige zerkratzen jede ungeschützte Stelle des Körpers.","The forest here is thick. To walk through it is a struggle and branches cause several scratches on uncovered parts of your body.",nil,nil,10); --General forest
AmbientList:add( position(733,115,0),nil,"Ein Windstoß lässt die trockenen Blätter in den Baumkronen rascheln.","A breeze coming through the trees causes the colorful leaves to rustle above you.",nil,{9,10,11,12},10); --General forest
AmbientList:add( position(767,542,0),nil,"Ein unheimliches Knacken erschallt. Bereits das schlimmste fürchtend stellst du fest, dass es sich lediglich um einen gebrochenen Ast handelt.","A familiar creak sounds in the forest. As you ready yourself for an undead attack you realise it is just the trees swaying in the wind.",nil,nil,10); --General forest
AmbientList:add( position(776,420,0),nil,"Die Stille des Waldes wird auf einmal durch das Aufbrausen des Windes jäh zerrissen.","The quiet of the forest is suddenly broken by a small wind that whistles louder.",nil,nil,10); --General forest
AmbientList:add( position(782,492,0),nil,"Einige Baumwurzeln erheben sich hier moosbewachsen aus der Erde.","Several tree roots protude from the earth; moss and insects cover them.",nil,nil,10); --General forest
AmbientList:add( position(784,522,0),nil,"Eine unnatürliche Spannung liegt in der Luft, etwas scheint dich zu beobachten.","There is an unnatural chill in the air, and it feels as though someone is watching you.",nil,nil,10); --General forest
AmbientList:add( position(785,195,0),nil,"Du erspähst etwas aufgewühlte Erde, ein gespaltener Zweig steckt im Mutterboden. In der Nähe zeigt der Stamm eines Baumes fürchterliche Kratzspuren.","You spy a patch of disturbed earth with a snapped twig on top of it. Nearby, scratch marks have gouged the trunk of a tree.",nil,nil,10); --General forest
AmbientList:add( position(790,488,0),nil,"Du hältst kurz inne und lauscht für eine Weile den Geräuschen, die wie das Geflüster der Bäume klingen.","You lean forward and stop a moment, trying to hear the whispers that are passing through the trees.",nil,nil,10); --General forest
AmbientList:add( position(802,69,0),nil,"Das laute Knacken eines Astes, der unter deinen Füßen zerbricht, zerreist die Stille des Waldes.","The loud snap of a branch broken underfoot shatters the silence.",nil,nil,10); --General forest
AmbientList:add( position(834,161,0),nil,"Das Unterholz ist hier dicht und verworren. Dornen bohren sich in dein Fleisch.","The undergrowth surrounding you is tangled and crowded. The thorns tear at your flesh.",nil,nil,10); --General forest
AmbientList:add( position(854,200,0),nil,"Ein Blatt tanzt auf einer leichten Brise, es fällt dir schwer, dieses Wunder Usharas nicht zu bewundern. Langsam läßt es sich zu deinen Füßen auf dem Waldboden nieder, eine wohlverdiente Rast.","As a leaf dances in the gentle breeze, you find it difficult not to admire the beauty of Ushara. It settles at your feet, its performance warranting a well-deserved rest.",nil,nil,10); --General forest
AmbientList:add( position(857,128,0),nil,"Etwas raschelt leise im Unterholz, ganz nah, wie es scheint. Wer oder was schleicht sich da an?","A light rustle reaches your ears, its origin sounds only a short distance away. Could something be watching you?",nil,nil,10); --General forest
AmbientList:add( position(860,857,0),nil,"Der Klang von Musik kann ganz leise im Wald vernommen werden, tief bewegt lauscht du dem Klang.","There is the sound of music in the woods, something deep within you is stirred.",nil,nil,10); --General forest
AmbientList:add( position(870,258,0),nil,"Um dich herum hörst du von Zeit zu Zeit das Knacken von Ästen und das Röhren von Hirschen.","Often you hear branches breaking around you and the call of a stag.",nil,nil,10); --General forest
AmbientList:add( position(774,144,0),nil,"Das würzige Aroma aus verwesenden Pflanzenteilen und Waldkräutern umgarnt dich. Spärlich dringen die Sonnenstrahlen durch die dichten Baumkronen und formen ein Mosaik auf dem Waldboden.","The spicy odour of herbs and decaying plants surrounds you. Scant sunrays passing through the lush treetops are forming mosaic patterns over the soil.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General forest daylight, not winter
AmbientList:add( position(736,59,0),nil,"Auf einmal zischt etwas durch das Unterholz, vielleicht war es ein Wiesel, vielleicht ein Hase, vielleicht aber auch eine Fee… Was immer es war, es ist bereits verschwunden.","Suddenly, something quick moves in the nearby undergrowth... perhaps a weasel, perhaps a bunny, perhaps a fairy... whatever it was, it is gone moments later.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General forest, daylight
AmbientList:add( position(770,79,0),nil,"Während du deine Streifzüge durch den Wald fortsetzt bemerkst du ein Eichhörnchen, welches aufgeschreckt einen Baum hinaufflüchtet.","As you make your way along the forest path, a single scared squirrel flees up the next tree.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General forest, daylight
AmbientList:add( position(775,195,0),nil,"Nicht weit von dir huscht ein Eichhörnchen einen Baum hinauf.","A squirrel scampers up a tree not too far from you.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General forest, daylight
AmbientList:add( position(791,465,0),nil,"Bei jedem Atemzug riechst du den frischen Geruch von Holz, Blättern und auch Pilzen.","You take a deep breath, noticing the strong, fresh smell of wood, leaves and fungus.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General forest, daylight
AmbientList:add( position(794,200,0),nil,"Die Baumkronen verdecken hier die Sicht auf den Himmel.","The sky is obscured by the forest's canopy.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General forest, daylight
AmbientList:add( position(834,147,0),nil,"Eine einzelne Krähe erhebt ihre Stimme und im nächsten Augenblick erhebt sich ein ganzer Schwarm lauthals gen Himmel. Die Stille erobert jedoch schnell den Wald zurück.","A single watchful crow speaks up, and a moment later, a whole flock of these birds shoot up into the sky. Then, there is silence.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General forest, daylight
AmbientList:add( position(853,796,0),nil,"Das grüne Dach der Baumkronen filtert das Licht der Sonne. Der Schatten der Bäume wirkt erfrischend und einladend.","The green roof made by the trees around filters the light, producing a cool, but comfortable and refreshing shade.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General forest, daylight
AmbientList:add( position(861,867,0),nil,"Das Sonnenlicht erhellt Lichtungen im Wald und die Tiere des Waldes bevölkern alles, was zwischen dir und dem Himmel ist.","From above, the sunlight is shining onto the forest floor in some areas and animals are moving about in the upper canopy of the trees.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General forest, daylight
AmbientList:add( position(902,695,0),nil,"Du bemerkst im Augenwinkel, wie etwas zwischen den Bäumen umher huscht. Oder war das nur ein Schatten?","You spot a sudden flash of movement amongst the trees... or perhaps the light plays tricks on you?",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General forest, daylight
AmbientList:add( position(542,761,0),nil,"Das Blätterkleid der Laubbäume lacht in vielen frohen Farben. Jedoch lichtet es sich mit jedem Windstoß etwas mehr - der Winter scheint nicht mehr fern.","The broad-leaved trees shine in many a blithesome colour. With every breeze, however, more are lost and winter no longer seems far away.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{9,10,11,12},10); --General forest, daylight, fall
AmbientList:add( position(830,110,0),nil,"Die Sonne scheint durch den Blätterwald, goldene und silberne Spiegelungen tanzen auf dem Waldboden. Die Bäume hier sind alt und  mächtig.","The sun glints off the leaves, gold and copper reflections scattering on the ground. The trees here are proud and magnificent.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General forest, daylight, not winter
AmbientList:add( position(834,549,0),nil,"Unter deinen Füßen befindet sich schlüpfriges Moos, Wurzeln warten nur auf einen falschen Schritt, um dich zum Stolpern zu bringen.","Below your feet are slippery mosses and roots waiting to cause someone to stumble.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General forest, daylight, not winter
AmbientList:add( position(519,454,0),nil,"Ein großes, gefiedertes Etwas durchstößt die Dunkelheit über deinem Kopf. Hast du es aufgeschreckt? Interessiert es sich überhaupt für dich oder wird es wohlmöglich angreifen…?","Something big and feathered crosses the path above your head, perhaps scared by your wandering, perhaps ignoring you, perhaps preparing to eat you.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General forest, night
AmbientList:add( position(533,238,0),nil,"Der Ruf einer Eule durchdringt die Stille, ein anderer Vogel erhebt sich aufgeschreckt aus einem Nest.","The hoot of an owl punctuates the silence; a bird flies from its nest, disturbed.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General forest, night
AmbientList:add( position(560,471,0),nil,"War dieses furchtbare Geräusch das Heulen eines Wolfes? Hoffentlich nicht.","Was that dreadful sound in the distance the howl of a wolf?",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General forest, night
AmbientList:add( position(709,192,0),nil,"Der Waldboden ist von knorrigem Wurzelwerk durchwoben, was das Vorankommen bei Nacht erschwert. Der unheimliche Gesang eines Waldkautzes ertönt irgendwo in der Ferne. ","Gnarled roots interweave through the forest soil, hampering travel at night. The eerie song of a tawny owl is heard somewhere in the distance.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General forest, night
AmbientList:add( position(753,449,0),{5,6,7},"Das Licht der Monde begrüßt dich, als du aus der Umarmung des Waldes hervortrittst. Ein dünner Nebel überzieht das einladende Land, welches sich vor dir erstreckt.","The nights moons dawn on you, as you escape the woodlands embrace. A faint mist ensembles in the distance, and you feel the open countryside welcome you again.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General forest, night
AmbientList:add( position(763,407,0),nil,"Der Wald liegt menschenleer und grabesstill dar. Aus den Tierbauten luken ängstlich kleine Augenpaare hervor, sicherlich nicht aus Angst vor den Bäumen.","All is silent in the woods as anxious creatures sit quietly in their hidey holes. It is eerie... even the trees look menacing and hostile.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General forest, night
AmbientList:add( position(782,95,0),nil,"Die Schatten der ehrwürdigen Baumriesen verdecken den Blick auf den Nachthimmel. Du spürst regelrecht, wie die aufmerksamen Blicke der Waldtiere auf dir haften.","The shadows of the mighty trees darken the sky. You feel the watchful gazes of many small animals resting on you.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General forest, night
AmbientList:add( position(790,489,0),nil,"Links von dir hörst du den Ruf einer Eule und bald darauf ist von rechts her die Antwort eines anderen Jägers der Nacht zu hören.","From the left, you hear the screech of an owl. From the right, further away, another answers the call.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General forest, night
AmbientList:add( position(817,194,0),nil,"Tiefe Dunkelheit umhüllt den Wald. Du setzt deinen Weg fort, wohl wissend, dass eine Nacht im Wald ein unliebsames Ende nehmen kann.","The woods are very dark at night. Watchful not to leave the path, you carefully make your way knowing that if you should ever get lost in a forest as dark as this one at night it would likely take a long time to find your way home, if you're not eaten by some predator beforehand.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General forest, night
AmbientList:add( position(818,227,0),nil,"Der Wald ist zwar dunkel in der Nacht, aber alles andere als ruhig. Kein einziger Funken Sternenlicht dringt bis zum Waldboden vor.","The woods are not silent at night, but they are dark. You see no single star shining through the dense branches above you.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General forest, night
AmbientList:add( position(875,867,0),nil,"Das Licht der Monde funkelt auf den Blättern. Das silberne Licht erhellt die wundervollen Eldaneichen.","The moonlight sparkles on the leaves above. Silver light is reflected from the beautiful eldan oaks.",{0,1,2,3,4,5,6,7,21,22,23,24},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General forest, night, not winter
AmbientList:add( position(875,86,0),nil,"Hier scheinen dir selbst die Bäume feindlich gesinnt zu sein. Die wenigen Blätter sehen spitz und scharf aus, die Schatten sehen aus, als wenn sie jederzeit lebendig werden könnten, um dich anzufallen.","As you walk along, you notice the trees here seem very hostile. The sparsely growing leaves appear sharp and pointy, and the shadows thrown on the accursed ground seem to spring alive with an eerie sense of lurking doom.",nil,{1,2,3,4,5,6,7,8,9,10,11,12},10); --General forest, not winter
AmbientList:add( position(400,286,0),nil,"In der Ferne hörst du das Lachen und Schreien von Kindern.","The distant laughter and cries of children can be heard.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,1); --General Galmair daylight
AmbientList:add( position(499,156,0),nil,"Der Boden ist hier flach und sieht niedergetrampelt aus. Einige Knochen liegen verstreut am Boden.","The ground here is flat and looks well trampled. There are some bones littered about the place.",nil,nil,10); --General meadow
AmbientList:add( position(709,470,0),nil,"Der Tau hat in dieser Nacht ganze Arbeit geleistet und bedeckt das Gras mit funkelnden Sternen, die in der Sonne glänzen.","There has been a heavy dew fall overnight and the grass gleams in the morning sun.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General meadow, daylight
AmbientList:add( position(730,408,0),nil,"Der See hier liegt still und ruhig dar. Nebelschwaden ziehen über die Wasseroberfläche und Gestrüpp bedeckt das Seeufer.","The lake before you is calm and quiet with mist rolling across and weeds floating on its surface.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General meadow, daylight
AmbientList:add( position(879,550,0),nil,"Die Farbe der Gräser scheint sich langsam davonzustehlen. Kahle Stellen bilden sich auf der Wiese, und das aufgeweichte Erdreich haften daumendick an den Sohlen. ","The colour of the grass appears to fade away. Bare spots are shaping on the grassland, the sodden soil sticking thickly to your soles.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{9,10,11,12},10); --General meadow, daylight, fall
AmbientList:add( position(433,137,0),nil,"Das Gras wiegt sich im Wind einer sanften Brise, der schmeichelnde Geruch von Wildblumen steigt dir in die Nase.","A gentle breeze makes the grass wave and carries the pleasant smell of flowers to your nose.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General meadow, daylight, not winter
AmbientList:add( position(511,788,0),nil,"Das Gras wiegt sich sanft im Wind. Alles ist ruhig, ja, entspannt. Du könntest fast vergessen, was du hier eigentlich wolltest.","The wild grass sways gently in the wind. All is calm, even relaxing, and as you listen you forget for a moment what you were doing.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General meadow, daylight, not winter
AmbientList:add( position(539,743,0),nil,"Das Gras zeigt ein üppiges Grün. Viele Kräuter und Blumen stehen nun in voller Blüte und locken zahllose Bienen an.","The luscious green grass is swarmed by innumerable bees visiting the many herbs and flowers that now are in full bloom.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General meadow, daylight, not winter
AmbientList:add( position(736,425,0),nil,"Ein leichter Wind weht und trägt den wundervollen Geruch der Wildblumen der Ebene zu dir.","The breeze is calm, and you can smell the different scents of the colourful flowers that fill the meadow.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General meadow, daylight, not winter
AmbientList:add( position(868,591,0),{1,2,3},"Vor dir liegt eine idyllische Auenlandschaft. Einige Tiere weiden sich an saftigem, grünen Gras und Bienen umsummen die Blumen.","An idyllic meadow lies before you. Lush, green grass is grazed on and insects flit around the flowers.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General meadow, daylight, not winter
AmbientList:add( position(884,514,0),nil,"Das Zirpen der Grillen begleitet deine Marsch durch die Ebene.","The crickets chirp as you make your way through the grassland.",nil,{1,2,3,4,5,6,7,8,9,10,11,12},10); --General meadow, daylight, not winter
AmbientList:add( position(455,134,0),nil,"Ein langgezogenes Heulen hallt in der Nacht wider, die Tiere um dich herum suchen das Weite.","A long, piercing howl echoes across the night. The wildlife around you scatters.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General meadow, night
AmbientList:add( position(860,324,0),nil,"Alles ist still, doch auf einmal durchbricht ein lautes Stöhnen die Stille…","Everyting is quiet, but suddenly a loud groan breaks the silence.…",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General meadow, night
AmbientList:add( position(894,600,0),nil,"Leise wiegen die Gräser in der nächtlichen Brise. Ein hauchdünner Schleier aus kühler Luft hat sich über das Grün ausgebreitet.","The blades of grass are quietly swinging in the nightly breeze. A flimsy veil of cool air has spreaded over the green.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General meadow, night
AmbientList:add( position(562,437,0),nil,"Trotz der Finsternis ist es noch angenehm warm. Unzählige Grillen zirpen im hohen Gras auf dem Plateau. ","Despite the darkness it is pleasantly warm and countless crickets chirp in the tall grasses of the plateu.",{0,1,2,3,4,5,6,7,21,22,23,24},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General meadow, night, not winter
AmbientList:add( position(613,384,0),nil,"Pflanzen umstreichen deine Beine. Das kitzelt!","Plants brush against your ankles as you walk. They tickle.",nil,{1,2,3,4,5,6,7,8,9,10,11,12},10); --General meadow, not winter
AmbientList:add( position(289,379,1),nil,"Du jappst nach Luft als du den Berg hinaufsteigst.","You struggle for breath as you ascend into the mountains.",nil,nil,10); --General mountain
AmbientList:add( position(351,349,1),nil,"Spitze Steine bohren sich durch deine Fußsohlen. Gutes Schuhwerk ist bei Bergtouren unerlässlich.","You feel the jagged rocks through your boots. You wish you had brought sturdier footwear.",nil,nil,10); --General mountain
AmbientList:add( position(362,387,1),nil,"Zwischen den Felsen bemerkst du das Nest eines Adlers. Küken schlagen sofort Alarm, es wäre unklug, auf die Mutter zu warten…","You notice an eagle nest amongst the rocks. Two chicks screech in fright. You would be foolish to enrage the mother by staying.",nil,nil,10); --General mountain
AmbientList:add( position(366,342,1),nil,"Du trittst einige Steine los, sie fallen viele hundert Fuß bevor sie auf dem Boden aufschlagen.","The rock beneath your foot crumbles. You watch as it falls far down the mountain side before coming to rest.",nil,nil,10); --General mountain
AmbientList:add( position(387,342,0),nil,"Hohe Berggipfel erheben sich über dir, der Weg ist hier felsig und steil.","The mountain peaks loom over you as the terrain becomes rockier and steeper.",nil,nil,10); --General mountain
AmbientList:add( position(425,353,0),nil,"Nur wenig Leben trotzt dem felsigen Untergrund. Drahtige Pflanzen klammern sich abenteuerlich an einen Felsvorsprung, der Wind zerrt an ihnen um sie in die Tiefe zu stürzen.","There is little life on this rocky outcrop. A resilient flower clings to the earth at a precarious angle, the wind tugging at it.",nil,nil,10); --General mountain
AmbientList:add( position(463,262,0),nil,"Die Bergluft ist rein und klar, man hat das Gefühl, dass sie den Klang eines Rufes über viele Meilen forttragen wird.","The mountain air is fresh and cold and seems capable of carrying sounds from a great distance away.",nil,nil,10); --General mountain
AmbientList:add( position(641,395,0),nil,"Die Wege in den Bergen sind schmal und voll von Geröll. Pass auf, wo du hintrittst!","You notice the paths are narrow and covered with loose rock as you approach the mountain. Better watch your step!",nil,nil,10); --General mountain
AmbientList:add( position(665,416,1),nil,"Die Luft ist hier oben in den Bergen kalt und dünn.","You can feel the air getting colder and thinner up high in the mountains.",nil,nil,10); --General mountain
AmbientList:add( position(266,380,1),nil,"Viel Geröll und wenige Pflanzen bedecken dieses karge Plateau. Scharfkantig und rau erheben sich die Felswände über dir.","Lots of rubble and little vegetation covers this barren plateau. Sharp edges and rough rock faces soar above you.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General mountain, daylight
AmbientList:add( position(268,368,1),nil,"Die Berge werfen lange Schatten und auch kannst du kaum die wolkenverhangenen Gipfel erkennen.","A long shadow is cast by the mountains. You can barely make out the top amidst the cloud.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General mountain, daylight
AmbientList:add( position(327,338,1),nil,"Wenn du dich umschaust wird dir erst bewusst, wie hoch du schon geklettert bist. Ein traumhafter Ausblick belohnt dich für deine Mühen.","You turn to see what you have climbed so far. A picturesque vista greets your eyes.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --General mountain, daylight
AmbientList:add( position(348,364,1),nil,"Angenehm warme Bergluft lädt dich ein, kräftig durch zu atmen. In der Ferne lässt sich manchmal das Brüllen eines Berglöwen vernehmen.","The pleasing mountain air invites you to take a deep breath. Sometimes you hear the growl of a mountain lion on the prowl.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General mountain, daylight, not winter
AmbientList:add( position(280,383,1),nil,"Dichter Schnee hält den Gebirgspass bedeckt. Es ist sehr anstrengend, unter diesen Bedingungen den Aufstieg zu schaffen und das Gleichgewicht zu halten.","Thick snow has covered the mountain pass. Mastering the ascent whilst maintaining balance becomes most exhausting under these conditions.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{13,14,15,16},10); --General mountain, daylight, winter
AmbientList:add( position(339,385,1),nil,"Eine nächtliche Bergwanderung kann beschwerlich und gefahrvoll sein. Wer seine Füße nicht sehen kann, verliert hier oben sehr schnell den Boden unter den Füßen.","A nightly hike in the mountains might be troublesome and hazardous. Those who can't see their own feet are likely to lose their footing before long.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General mountain, night
AmbientList:add( position(345,397,1),nil,"Der Boden ist hier recht gefährlich. Jeder Schritt will in der Dunkelheit wohl überlegt sein, zu schnell könntest du dir was brechen.","The ground is treacherous here. Tread carefully, you could easily turn an ankle in the dark.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General mountain, night
AmbientList:add( position(301,341,1),nil,"Die eisige Luft, verwandelt deinen Atem in eine nebelige Schwade.","The crisp cold air turns your breath into a misty plume.",nil,{13,14,15,16},10); --General mountain, winter
AmbientList:add( position(760,558,0),nil,"Hier im Marschland wird jeder Schritt zur Qual. Deine Schuhe sinken ein ums andere mal tief ein.","Walking becomes difficult through the marshy land. With each footstep you sink into the ground.",nil,nil,10); --General swamp
AmbientList:add( position(765,562,0),nil,"Das Summen zahlloser Insektenflügel und das Quaken der Frösche schallt aus allen Richtungen auf dich ein.","The buzzing of countless insect wings and the croaking of the frogs can be heard from every direction.",nil,nil,10); --General swamp
AmbientList:add( position(777,578,0),nil,"Bei jedem Schritt bleibt mehr und mehr widerlicher Schlamm an deinen Schuhen hängen.","With every step you take you can feel a thick, unpleasant mud stick to your boots.",nil,nil,10); --General swamp
AmbientList:add( position(784,560,0),nil,"Kleine Fliegen schwirren hier umher, wahrscheinlich gefällt ihnen die Mischung aus Matsch und Wasser.","Small bugs are buzzing all over the place here, probably they are attracted by the mud and water.",nil,nil,10); --General swamp
AmbientList:add( position(792,547,0),nil,"Der matschige Sumpf brummt nur so vor Leben. Ranken von Pflanzen ziehen sich über den Boden und Mücken stürzen sich auf dich herab in der Hoffnung auf Blut.","The muggy swamp teems with activity. An array of plant life litters the landscape and insects are drawn to your scent.",nil,nil,10); --General swamp
AmbientList:add( position(799,581,0),nil,"Ein bizarres Reptil mit glitschiger, schwarzer Haut flüchtet sich ins Wasser als du dich annäherst. Dieser Ort wimmelt nur so von seltsamem Getier. ","Some weird, slippery, black-skinned critter escapes into the water as you approach. This place crawls with all kinds of strange creatures.",nil,nil,10); --General swamp
AmbientList:add( position(812,566,0),nil,"Eine gallertartige Flüssigkeit im Matsch wirft grünliche Blasen. Ein abgestandener Geruch erfüllt die Luft und der Mißklang von Krötenrufen und Insektenschwärmen schmerzt im Ohr. ","Green, jelly-like fluid bubbles through the mud. A dull stench pervades the air, and the cacophony of swarming bugs and frogs calling rings shrilly in the air.",nil,nil,10); --General swamp
AmbientList:add( position(816,569,0),nil,"Es liegen Nebelschwaden über dem Sumpf. Insekten zirpen und summen auf den Kadaver eines Tieres zu.","There is mist over the murk. Insects chitter and buzz over a dead animal, which gives off an awful stench.",nil,nil,10); --General swamp
AmbientList:add( position(823,573,0),nil,"Die Luft ist drückend hier im Sumpf. Viele Insekten summen umher auf der Suche nach jemanden, den sie stechen können.","All around is the sticky air of the swamp. Many insects are buzzing around, looking for someone to annoy.",nil,nil,10); --General swamp
AmbientList:add( position(837,581,0),nil,"Fäulnisgestank hängt schwer in der Luft und wird umso stärker, je weiter du in den matschigen Sumpf vorstößt.","The scent of putrefaction hangs heavily in the air and seems to grow stronger for every step in the heavy mud.",nil,nil,10); --General swamp
AmbientList:add( position(766,582,0),nil,"Es ist einfach nur unangenehm wie die feuchte Luft deine Kleidung an deinem Körper kleben lässt.","You grow uncomfortable as the humid air makes your clothes stick to your skin.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General swamp, daylight, not winter
AmbientList:add( position(812,553,0),nil,"Der Geruch von Fäulnis lastet über dieser Sumpflandschaft. Zähflüssiger Morast sorgt für ein beschwerliches Vorankommen - außer für die unzähligen Mücken. ","The smell of rotting foulness weighs heavy over the swampland. Viscous morass hampers any advance - except for the the countless gnats.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --General swamp, daylight, not winter
AmbientList:add( position(782,557,0),nil,"Schlammige, kalte Pfützen breiten sich auf der Ebene aus. Laute von Kröten und anderem Getier schallen dir entgegen. ","Oozy, frigid puddles stretch all across the land. Voices of toads and other beasts resonate around you.",nil,{9,10,11,12},10); --General swamp, fall
AmbientList:add( position(809,560,0),nil,"Du starrst in die Tiefen der Dunkelheit, schaurige Schatten streifen in der ferne ziellos umher.","You peer through the darkness, straining your eyes in an attempt to make sense of the eerie shadows in the distance.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General swamp, night
AmbientList:add( position(812,575,0),nil,"Dichte Nebelschwaden halten die Sümpfe bei Nacht überdeckt; Nur das Schilfrohr ragt stellenweise heraus. Es herrscht Totenstille. ","Dense hazes cover the swampland at night. Only reeds stick up here and there. Dead silence prevails.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General swamp, night
AmbientList:add( position(829,579,0),nil,"Das Licht der Monde weist dir den Weg durch Matsch und Schlamm.","The moonlight guides you as you tread carefully through the boggy ground.",{0,1,2,3,4,5,6,7,21,22,23,24},nil,10); --General swamp, night
AmbientList:add( position(915,657,0),nil,"Krötenrufe sind im Sumpf zu hören, das Summen von Insekten raubt einem den Nerv.","Occasional croaks can be heard in the swamp to accompany the buzzing of insects which is constant.",nil,{1,2,3,4,5,6,7,8,9,10,11,12},10); --General swamp, not winter
AmbientList:add( position(307,238,1),{0,1,7},"Du betrittst den Altarraum und sofort spürst du etwas wie göttliche Inspiration und göttliche Stille.","You walk into the sanctuary and instantly you feel inspiration and divine silence.",nil,nil,10); --Specific Galmair
AmbientList:add( position(308,238,1),{0,1,7},"Du betrittst den Altarraum und sofort spürst du etwas wie göttliche Inspiration und göttliche Stille.","You walk into the sanctuary and instantly you feel inspiration and divine silence.",nil,nil,10); --Specific Galmair
AmbientList:add( position(309,238,1),{0,1,7},"Du betrittst den Altarraum und sofort spürst du etwas wie göttliche Inspiration und göttliche Stille.","You walk into the sanctuary and instantly you feel inspiration and divine silence.",nil,nil,10); --Specific Galmair
AmbientList:add( position(310,238,1),{0,1,7},"Du betrittst den Altarraum und sofort spürst du etwas wie göttliche Inspiration und göttliche Stille.","You walk into the sanctuary and instantly you feel inspiration and divine silence.",nil,nil,10); --Specific Galmair
AmbientList:add( position(329,266,-6),nil,"Ratten quieken und pesen vor dir davon. Dieser Ort ist ungewöhnlich still.","Rats squeak and scatter from your footsteps. The way ahead is eerily quiet.",nil,nil,10); --Specific Galmair
AmbientList:add( position(337,220,0),nil,"Im Raum steht ein reich gekleideter Mann, hinter dem einige Truhen randgefüllt mit Gold zu erkennen sind. Er sieht dich misstrauisch an.","The man in this room is clad in fine clothes, behind him you see many chests filled to the brim with gold. He eyes you suspiciously.",nil,nil,10); --Specific Galmair
AmbientList:add( position(378,262,0),{1,2,3},"Dir schlägt eine Hitze entgegen, die ihren Ursprung wohl bei den Heizöfen hat. Die Ambosse sehen sehr abgenutzt aus und die Esse ist bedeckt von Ruß. Es ist sehr stickig und der Geruch von verbrannter Kohle liegt in der Luft.","Some hot air streams straight into your face, probably coming from the hot ovens. The anvils look well used and the forge is covered with a layer of ash. It is very stuffy and the smell of burnt coal is in the air.",nil,{1,2,3,4,5,6,7,8,9,10,11,12},10); --Specific Galmair
AmbientList:add( position(379,262,0),{1,2,3},"Nach der Kälte draußen schlägt dir hier eine angenehme Wärme entgegen, die ihren Ursprung wohl bei den Heizöfen hat. Die Ambosse sehen sehr abgenutzt aus und die Esse ist bedeckt von Ruß. Es ist sehr stickig und der Geruch von verbrannter Kohle liegt in der Luft.","After the coldness outside you appreciate the warm air coming from the three hot ovens. The anvils look well used and the forge is covered with a layer of ash. It is very stuffy and the smell of burnt coal is in the air.",nil,{13,14,15,16},10); --Specific Galmair
AmbientList:add( position(387,246,0),{0,1,7},"Du betrittst den Raum und merkst sofort, dass es zieht. Ein Mann auf einem der Stühle blickt sich ungeduldig um.","You enter the room and immediately notice that there is draught. A man sat on one of the chairs looks around impatiently.",nil,nil,10); --Specific Galmair
AmbientList:add( position(391,321,-6),{3,4,5},"Du betrittst die Taverne und sogleich umhüllt dich wohlige Wärme und der Geruch von starkem Bier strömt in deine Nase.","Upon walking into the tavern the warmth instantly envelopes you and the strong smell of beer fills your nostrils.",nil,nil,10); --Specific Galmair
AmbientList:add( position(409,262,0),{1,2,3},"Du siehst einen unangezündeten Kamin in der Ecke, ein wenig Ruß bedeckt den Boden davor.","You see an unlit fireplace in the corner, a little soot has drifted onto the floor.",nil,nil,10); --Specific Galmair
AmbientList:add( position(410,250,0),nil,"Das Steinpflaster in Galmair ist gut ausgebaut und wird offenbar viel beansprucht. Zahllose Händler und Handwerker, oft mit Lasttieren, ziehen hier täglich vorbei, um ihren Geschäften in der Stadt nachzugehen. ","The pavement of Galmair looks solidly constructed and is obviously widely used. Numerous merchants and craftsmen, often with pack animals, pass through here every day to pursue their business in town.",nil,nil,10); --Specific Galmair
AmbientList:add( position(765,749,0),nil,"Das Sonnenlicht spiegelt sich in der makellosen Seeoberfläche.","The sunlight reflects off of the lake fitfully. The surface is pristine.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --Specific Galmair daylight
AmbientList:add( position(770,758,0),nil,"Der See ist spiegelglatt und sein Wasser kristallklar. Viele Fische ziehen ihre Bahnen in ihrem Reich zwischen dem Grund des Sees und der tödlichen Luft.","The small lake is almost still and appears crystal clear. You see many fish swimming around on the bottom.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --Specific Galmair daylight
AmbientList:add( position(397,143,0),{3,4,5},"Als du ins Freie trittst, knacken die unzähligen vereisten Stellen am Boden vor der Höhle unter deinen Füßen. Die eisige Luft scheint dir die Brust zu verschnüren und das Atmen fällt dir schwer. Bald bemerkst du, dass deine Haare allmählich vereisen.","A thin carpet of icy fog covers the frozen ground. The soft cracking of ice is heard coming from above. The cold air fills your lungs, with every breath you take making it harder to breath for a few moments as you get used to the bitingly cold air.",nil,{13,14,15,16},100); --Specific location
AmbientList:add( position(430,534,0),nil,"Deine Stimme hallt von den massiven Mauern wider, das Echo klingt nur noch wenig nach der Stimme eines Lebenden…","Your voice bounces off the massive walls and echoes eerily.",nil,nil,100); --Specific location
AmbientList:add( position(432,584,0),nil,"An den Wänden hängen abgebrannte Fackeln und auf dem Boden siehst du getrocknete Blutspritzer.","Several burnt out torches hang on the wall and the ground is splattered with dried blood.",nil,nil,100); --Specific location
AmbientList:add( position(535,659,0),nil,"Ein Grabstein; hier hat wohl jemand ins Gras gebissen.","A tombstone, another one bit the dust here.",nil,nil,100); --Specific location
AmbientList:add( position(558,383,0),{0,5,6,7},"Als du die uralten Höhlen betrittst hörst du fließendes Wasser in der Ferne und spürst das Wirken der Magie in jedem Winkel.","As you enter the ancient caves you hear running water in the distance and feel the rush of magical power coursing through the area.",nil,nil,100); --Specific location
AmbientList:add( position(559,245,0),{1,2,3},"Du hörst merkwürdige Geräusche aus den Tiefen der Höhle.","You hear strange noises coming from deep down within the dark dungeon.",nil,nil,100); --Specific location
AmbientList:add( position(649,403,0),nil,"Ein andauerndes Tropfgeräusch hallt leise in den Gängen wieder. Einige Tropfen pladdern auch auf deine Schultern.","There is a steady trickling echoing softly down the rocky corridors. A few drips spatter on your shoulder.",nil,nil,100); --Specific location
AmbientList:add( position(671,402,-3),{0,1,7},"Die Luft wird umso stickiger, je weiter du in die Tiefen der Höhle vordringst. Du hörst nichts als den Hall deiner eigenen Schritte und deine Atemgeräusche.","The cold air becomes still the further you go, the only sound you hear is your own footsteps and breathing.",nil,nil,100); --Specific location
AmbientList:add( position(690,363,-3),nil,"Die Tunnel sind hier so gerade, dass du sehr daran zweifelst, dass Ushara sie erschaffen hat. Diese Höhlen müssen das Werk von Menschen sein.","The tunnels here are so straight, you seriously doubt that Ushara made them. Men made these caves, that's for certain.",nil,nil,100); --Specific location
AmbientList:add( position(696,313,0),{1,2,3},"Sofort als du durch die Tür trittst, nimmst du die verschiedensten Düfte wahr. Einige Tavernengäste unterhalten sich, andere schlürfen an gigantischen Bierkrügen.","As you pass through the door you immediately notice different fragrances. Some guests are having a conversation, some take sips from large tankards.",nil,nil,100); --Specific location
AmbientList:add( position(698,313,0),{1,2,3},"Im Raum ist es etwas wärmer als draußen, du frierst aber trotzdem etwas. An der Theke steht ein fluchender Zwerg, der die Theke gewissentlich auf Hochglanz poliert.","The room is a little bit warmer than outside, but you still feel cold. At the bar stands a cursing dwarf who polishes the table.",nil,{13,14,15,16},100); --Specific location
AmbientList:add( position(698,409,-3),{1,2,3},"Du hörst schlurfende Schritte in der Ferne… was könnte das sein?","You hear shuffling feet and strange moaning in the distance... who could that be?",nil,nil,100); --Specific location
AmbientList:add( position(698,448,-3),{5,6,7},"Die Luft ist in dieser Höhle ungewöhnlich feucht.","The air feels wet as you step through the cave opening.",nil,nil,100); --Specific location
AmbientList:add( position(709,451,-3),nil,"Deine Haut kribbelt an diesem Ort. Ein Schauer läuft dir den Rücken runter und du hörst, wie Wasser im monotonen Takt von der Decke tröpfelt.","You feel your skin prickle in this place. A little shiver makes its way down your spine and you hear the steady trickle of water.",nil,nil,100); --Specific location
AmbientList:add( position(711,421,-3),{5,6,7},"Die Luft ist hier abgestanden und drückend. Ornamente an den Wänden schauen dich mit leerem Blick an und Wandteppiche flattern wie im Wind, obwohl hier kein Luftzug zu spüren ist.","The air is thick, and the room itself somewhat brooding. Ornaments watch you with glossy eyes, and tapestries flicker in the absence of wind.",nil,nil,100); --Specific location
AmbientList:add( position(723,452,-3),{1,2,3},"Dunkelheit ummantelt dich als du immer tiefer in die Gebeine der Erde hinabsteigst. Man sagt, dass hier unten Schrecken lauern, die ihre Beute niemals wieder in die Helligkeit entkommen lassen. ","You're encased by blackness as you descend deeper and deeper into the earth. Supposedly there are horrors lurking down here that never allow their prey to escape to the brightness ever again.",nil,nil,100); --Specific location
AmbientList:add( position(725,408,-3),{0,1,7},"Die Wand im Norden zeigt eine fein gearbeiteter Inschrift, die sich über mehrere Meter ersteckt: 'Glaubensgrundsätze der Salavesh: Glaube nicht den Glauben anderer. Denn dein Glaube ist gerecht.'","The wall to the north shows a finly worked inscription, extending over some length: 'Principles of faith of the Salavesh: Do not believe in the faith of others.'",nil,nil,100); --Specific location
AmbientList:add( position(726,408,-3),{0,1,7},"'Sei nicht gierig, strebe nach Vollkommenheit und teile dein Wissen mit deinen Brüdern.'","'Do not be greedy, aspire to perfection and share you knowledge with your brothers.'",nil,nil,100); --Specific location
AmbientList:add( position(727,480,-3),{0,1,7},"'Sieh zurück und lerne. Sieh nach vorne und lehre. Sieh nach oben und bete. Sie nach unten und predige.'","'Look back and learn. Look forward and teach. Look up and pray. Look down and preach.'",nil,nil,100); --Specific location
AmbientList:add( position(729,480,-3),{0,1,7},"'Bekämpfe, was dich bekämpft. Vernichte, das dich vernichtet. Liebe, was dich liebt.'","'Fight what fights you. Destroy what destroys you. Love what loves you.'",nil,nil,100); --Specific location
AmbientList:add( position(730,408,-3),{0,1,7},"'Bringe Ruhe denen, die danach dürsten, sei es auch nicht in deinem Sinne.'","'Bring rest to those who long for it, even though it does not appeal to you.'",nil,nil,100); --Specific location
AmbientList:add( position(731,408,-3),{0,1,7},"Der letzte Teil einer langen Inschrift: 'Akzeptiere nichts als diese Grundsätze und handele nicht nach den Regeln Fremder. Denn sie sind fehlgeleitet in ihrem Wahn.'","The last part of a long inscription: 'Accept nothing else but these principles and do not act upon the rules of strangers, for they are errant in their delusion.'",nil,nil,100); --Specific location
AmbientList:add( position(741,374,-3),{0,1,7},"Ein markerschütterndes Geheul aus den Tiefen der Höhle läßt deine Haare zu Berge stehen. Entweder, du flüchtest jetzt oder du wirst den untoten Seelen ins Gesicht sehen müssen.","An eerie howl comes from somewhere deep inside the earth and you feel the hair on the back of your neck stand on end. You may have an urge to run away, or do you long to encounter the rising of undead souls?",nil,nil,100); --Specific location
AmbientList:add( position(746,798,0),{5,6,7},"Hier drin riecht es nach den verschiedensten Sachen. Waren aus aller Herren Länder sind hier verstaut.","You smell the most obscure things in here. Goods from distant realms are stacked up.",nil,nil,100); --Specific location
AmbientList:add( position(759,385,-3),{3,4,5},"Um dich herum rumpelts, es riecht hier nach längst vergessenen Zeitaltern.","You sense a deep rumble beneath your feet and the smell is ancient and musty.",nil,nil,100); --Specific location
AmbientList:add( position(788,778,0),nil,"Du fragst dich, warum das Eibenthal diesen Namen trägt. Nicht allzu viele Eiben wachsen hier. Aber der Name scheint sehr treffend die Atmosphäre hier einzufangen.","You wonder why Yewdale goes by this name when so few yews can be seen. Nevertheless, the name fits the appealing ambience.",nil,nil,100); --Specific location
AmbientList:add( position(839,658,1),nil,"Ein starker Schwefelgeruch hängt in der Luft. Deine Füße fühlen sich äußerst heiß an und die Luft brennt beim atmen in den Lungen.","The strong smell of sulphur is overpowering here. Your feet are hot and the air burns your lungs as you breathe.",nil,nil,100); --Specific location
AmbientList:add( position(893,664,0),{1,2,3},"Vor dir erstreckt sich der Morgentausumpf. Eigentlich ein netter Fleck Erde, wären da nicht die unzähligen Mücken.","Ahead, you spot the Dewy Swamps. Actually a nice patch of land were it not for all the mosquitoes.",nil,nil,100); --Specific location
AmbientList:add( position(895,371,0),{3,4,5},"Als du dich den aufgeschütteten Erdhaufen der Gräber näherst scheint dich etwas unaufhaltsam näher zu ziehen. Die rastlosen Seelen rufen nach dir…","As you step closer, something seems to draw you towards the soft earth mounds where the departed souls lie in rest.",nil,nil,100); --Specific location
AmbientList:add( position(836,677,0),{0,1,7},"Die Wärme in der Höhle vertreibt gemächlich die Kälte aus deinen Gliedern und lässt den Schnee auf deinen Schultern schmelzen.","The warm air inside the cave slowly thaws the snow and cold from your body.",nil,{13,14,15,16},100); --Specific location, winter
AmbientList:add( position(134,548,0),{3,4,5},"Der Geruch von Pergament dringt dir in die Nase. Die meisten Bücher in den Regalen sind verstaubt. In der Ecke liegen einige zusammengeknüllte Blätter.","The smell of parchment comes into your nose. Most of the books in the cupboard are dusty. In one corner there are scattered papers.",nil,nil,10); --Specific Runewick
AmbientList:add( position(897,783,3),{5,6,7},"Du trittst auf den Balkon und hörst den Wind leise durch die Ecken pfeifen.","You step onto the balcony and hear the rushing of the wind whistling quietly in the corners.",nil,nil,10); --Specific Runewick
AmbientList:add( position(897,784,3),{5,6,7},"Du trittst auf den Balkon und hörst den Wind leise durch die Ecken pfeifen.","You step onto the balcony and hear the rushing of the wind whistling quietly in the corners.",nil,nil,10); --Specific Runewick
AmbientList:add( position(904,831,0),nil,"Der Duft von frisch Gekochtem liegt in der Luft.","The air is filled with the aroma of fresh cooked meals.",nil,nil,10); --Specific Runewick
AmbientList:add( position(905,829,0),{3,4,5},"Ein appetitlicher Geruch steigt dir vom Ofen her in die Nase. Durch ein offenes Fenster verbreitet sich der Duft auch in der Umgebung.","The pleasant smell of something on the stove gets your nostrils flaring, and an open window lets the aroma waft outside.",nil,nil,10); --Specific Runewick
AmbientList:add( position(947,827,0),{3,4,5},"Du betrittst die Bibliothek und sofort umhüllt dich die Stille. Vereinzelt hörst du raschelnde Pergamente.","You walk into the library and instantly silence surrounds you. Sporadically you hear the crinkling of parchments.",nil,nil,10); --Specific Runewick
AmbientList:add( position(947,828,0),{3,4,5},"Du betrittst die Bibliothek und sofort umhüllt dich die Stille. Vereinzelt hörst du raschelnde Pergamente.","You walk into the library and instantly silence surrounds you. Sporadically you hear the crinkling of parchments.",nil,nil,10); --Specific Runewick
AmbientList:add( position(949,759,3),{5,6,7},"Beim Betreten des Raumes fallen dir die gedeckten Tische auf. Sie laden zum Verweilen ein.","As you walk into the room, the set table catches your eyes. The chairs invite you to take a rest.",nil,nil,10); --Specific Runewick
AmbientList:add( position(949,760,3),{5,6,7},"Beim Betreten des Raumes fallen dir die gedeckten Tische auf. Sie laden zum Verweilen ein.","As you walk into the room, the set table catches your eyes. The chairs invite you to take a rest.",nil,nil,10); --Specific Runewick
AmbientList:add( position(744,810,0),nil,"Der muffige Geruch der See steigt dir in die Nase, Seeleute laufen hier durcheinander und nicken dir kurz zu oder schauen grimmig drein.","The musty smell of sea water fills your nostrils and sailors walk back and forth, either nodding to you, or giving you a grumpy look.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --Specific Runewick daylight
AmbientList:add( position(814,822,0),{1,2,3},"Ein bläulicher Nebel steigt um Runewick herum auf. Was kann das nur wieder sein?","You can see a strangely lit blue mist in the direction of Runewick. What is that?",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --Specific Runewick daylight
AmbientList:add( position(893,843,3),{0,1,7},"Die Vögel zwitschern draußen, im Raum herrscht ein erfrischendes Klima.","The birds are twittering outside and you feel a bracing climate inside.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --Specific Runewick, daylight, not winter
AmbientList:add( position(894,843,3),{0,1,7},"Die Vögel zwitschern draußen, im Raum herrscht ein erfrischendes Klima.","The birds are twittering outside and you feel a bracing climate inside.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{1,2,3,4,5,6,7,8,9,10,11,12},10); --Specific Runewick, daylight, not winter
AmbientList:add( position(907,834,0),nil,"Der Schnee glitzert durch die Fenster und bringt den Raum zum Leuchten. Es riecht nach Wintergebäck.","The glittering snow outside lights up the whole room. You can smell winter pastry.",{8,9,10,11,12,13,14,15,16,17,18,19,20},{13,14,15,16},10); --Specific Runewick, daylight, winter
AmbientList:add( position(683,314,0),nil,"Die Straße hier sieht verlassen aus. Mitunter sind Rufe aus der Taverne zu vernehmen.","The street is quiet. Occasional shouts can be heard from the tavern.",{8,9,10,11,12,13,14,15,16,17,18,19,20},nil,10); --Specific Tavern, daylight

function MoveToField(Char)
	local this = getAmbient(Char);
	if this then
		base.common.InformNLS(Char,this.german,this.english);
	end
end

function getAmbient(Char)
	local pos = Char.pos;
	local dir = Char:getFaceTo();
	if AmbientList[pos.x] and AmbientList[pos.x][pos.y] and AmbientList[pos.x][pos.y][pos.z] then
		local this = AmbientList[pos.x][pos.y][pos.z];
		local list = {};
		for _,ambient in pairs(this) do
			local timeOk, monthOk, dirOk = false, false, false;
			for _,that in pairs(ambient.hours) do
				if that==world:getTime("hour") then
					timeOk = true;
					break;
				end
			end
			for _,that in pairs(ambient.months) do
				if that==world:getTime("month") then
					monthOk = true;
					break;
				end
			end
			for _,that in pairs(ambient.direction) do
				if that==dir then
					dirOk = true;
					break;
				end
			end
			if timeOk and monthOk and dirOk and math.random(0,99)<ambient.chance then --chance!
				table.insert(list,ambient);
			end
		end
		if table.getn(list)>0 then
			return list[math.random(1,table.getn(list))];
		end
	end
	return nil;
end
