-- INSERT INTO npc VALUES (nextval('npc_seq'),2,124,581,0,4,false,'Berni Grunweld','npc_berni_grunweld.lua',0);

require("npc.base.autonpcfunctions")
module("npc.berni_grunweld")

function useNPC(user,counter,param)
    thisNPC:increaseSkill(1,"common language",100);
    thisNPC:talkLanguage(CCharacter.say, CPlayer.german, "Finger weg!");
    thisNPC:talkLanguage(CCharacter.say, CPlayer.english, "Don't you touch me!");
end

function initializeNpc()
    if TraderFirst then
        return true;
    end

    npc.base.autonpcfunctions.InitTalkLists();

    -- ********* START DYNAMIC PART ********

    npc.base.autonpcfunctions.SetRadius(0);
    QuestID = 80;
    -- Queststatus Overview 
    -- 0: No Quest taken 
    -- 1: Quest 1 taken - gather 10 raw materials of two different kinds and 1 needed tools for +5 skill while skill<=20 
    -- 2: Quest 1 solved 
    -- 3: Quest 2 taken - gather 15 raw materials, 2 differnt tools and 5 semi finished products for +5 skill while 20<=40 
    -- 4: Quest 2 solved 
    -- 5: Quest 3 taken - gather 4 needed tools, 10 semi finished products of 2 kinds and 5 easy finished products for +5 skill while 40<=60 
    -- 6: Quest 3 solved 
    -- 7: Quest 4 taken - gather 15 semi finished products, 10 easy finished products of 2 kinds and 5 advanced finished products for skill+5 while 60<=80 
    -- 8: Quest 4 solved 
    -- Cycletext
    npc.base.autonpcfunctions.AddCycleText("#me blickt nachdenklich auf den Kochtopf vor sich","#me looks thoughtful to the kettle infront of him");
    npc.base.autonpcfunctions.AddCycleText("#me schwingt leise kichernd einen Kochlöffel durch die Luft.","#me swings his cooking spoon through the air and chuckles softly.");
    npc.base.autonpcfunctions.AddCycleText("#me versucht vergeblich einen kleinen Fleck auf seiner Hose mit einem Tuch weg zu wischen.","#me tries witout any luck to get rid of a small stain on his trousers.");
    npc.base.autonpcfunctions.AddCycleText("#me summt leise etwas vor sich hin.","#me hums quietly.");
    npc.base.autonpcfunctions.AddCycleText("#me wirft verschiedenes Gemüse in den Topf vor sich und mischt diese zusammen.","#me tosses different vegetables into the pot infront of him and mixes them together.");
    npc.base.autonpcfunctions.AddCycleText("#me schaut sich suchend um.","#me looks around as if looking for something.");
    -- Help 
    npc.base.autonpcfunctions.AddTraderTrigger("Help","[Game Help] This NPC is the cook Berni Grunweld. Keyphrases: Hello, quest, seed, adventure, hatchet, cooking spoon");
    npc.base.autonpcfunctions.AddTraderTrigger("Hilfe","[Spielhilfe] Dieser NPC ist der Koch Berni Grunweld. Schlüsselwörter: Hallo, Quest, Aufgaben, Samen, Beil, Kochlöffel ");
    -- General speech 
    npc.base.autonpcfunctions.AddTraderTrigger("greetings","Hiho, take a seat next me if you are hungry");
    npc.base.autonpcfunctions.AddAdditionalTrigger("hello");
    npc.base.autonpcfunctions.AddAdditionalTrigger("good evening");
    npc.base.autonpcfunctions.AddAdditionalTrigger("good day");
    npc.base.autonpcfunctions.AddAdditionalTrigger("good morning");
    npc.base.autonpcfunctions.AddAdditionalText("Huhu, sit next me I have something great to eat for you");
    npc.base.autonpcfunctions.AddTraderTrigger("grüße","Hiho du, setzt dich doch zu mir falls du Hunger hast");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Tach");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Guten Abend");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Guten Morgen");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Guten Tag");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Huhu");
    npc.base.autonpcfunctions.AddAdditionalText("Huhu, schnapp dir ein Plätzchen neben mir, ich hab was ganz tolles zu essen.");
    npc.base.autonpcfunctions.AddTraderTrigger("Hiho","Hiho, take a seat next me if you are hungry");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Hallo");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Hey");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Greebas");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Greebs");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddAdditionalText("Huhu, sit next me I have something great to eat for you");
    npc.base.autonpcfunctions.AddTraderTrigger("Hiho","Hiho du, setzt dich doch zu mir falls du Hunger hast");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Hallo");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Hey");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Greebas");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Greebs");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddAdditionalText("Huhu, schnapp dir ein Plätzchen neben mir, ich hab was ganz tolles zu essen.");
    npc.base.autonpcfunctions.AddTraderTrigger("who are you","I'm Berni Grunweld the great cook and who are you?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("whats your name");
    npc.base.autonpcfunctions.AddAdditionalTrigger("your name");
    npc.base.autonpcfunctions.AddAdditionalText("I'm Berni, yes Berni is alright");
    npc.base.autonpcfunctions.AddTraderTrigger("wer bist du","Ich bin der Berni Grunweld der großartige Koch und wer bist denn du?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("wer seid ihr");
    npc.base.autonpcfunctions.AddAdditionalTrigger("wie heißt du");
    npc.base.autonpcfunctions.AddAdditionalTrigger("dein name");
    npc.base.autonpcfunctions.AddAdditionalText("Ich bin der Berni, ja Berni reicht vollkommen.");
    npc.base.autonpcfunctions.AddTraderTrigger("Farewell","Bye, i hope you will visit me again");
    npc.base.autonpcfunctions.AddAdditionalTrigger("good bye");
    npc.base.autonpcfunctions.AddAdditionalTrigger("bye");
    npc.base.autonpcfunctions.AddAdditionalTrigger("see you");
    npc.base.autonpcfunctions.AddAdditionalText("Good day to you, if you are hungry, just come to me again.");
    npc.base.autonpcfunctions.AddTraderTrigger("Auf bald","Tschüßi und besuch mich mal wieder.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Tschüß");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Wiedersehen");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Machs gut");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Bis dann");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Bis später");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Schönen Tag noch");
    npc.base.autonpcfunctions.AddAdditionalText("Mach es gut du und komme schnell wieder wenn du Hunger hast.");
    npc.base.autonpcfunctions.AddTraderTrigger("how are you","I'm prett good, thank you, and how are you if I may ask?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("how feel");
    npc.base.autonpcfunctions.AddAdditionalTrigger("how do you do");
    npc.base.autonpcfunctions.AddAdditionalText("I feel very well, yes very, very well, how about you?");
    npc.base.autonpcfunctions.AddTraderTrigger("wie gehts","Mir geht es ganz prima, danke. Wie geht es denn dir?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("wie fühlst");
    npc.base.autonpcfunctions.AddAdditionalText("Ich fühle mich toll, ganz toll und du, geht es dir auch so gut?");
    -- Catching typical NPC phrases 
    npc.base.autonpcfunctions.AddTraderTrigger("what sell","I'm cook, not a trader");
    npc.base.autonpcfunctions.AddAdditionalTrigger("what buy");
    npc.base.autonpcfunctions.AddAdditionalTrigger("list wares");
    npc.base.autonpcfunctions.AddAdditionalTrigger("price of");
    npc.base.autonpcfunctions.AddAdditionalText("I prefer exchanging my wares, I don't like selling them");
    npc.base.autonpcfunctions.AddAdditionalText("I have nothing here, I could sell you");
    npc.base.autonpcfunctions.AddAdditionalText("I don't have any prices, because I don't sell anything.");
    npc.base.autonpcfunctions.AddTraderTrigger("was verkauf","Ich bin kein Händler, nur Koch.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("was kauf");
    npc.base.autonpcfunctions.AddAdditionalTrigger("warenliste");
    npc.base.autonpcfunctions.AddAdditionalTrigger("preis von");
    npc.base.autonpcfunctions.AddAdditionalText("Ich tausche lieber als zu verkaufen");
    npc.base.autonpcfunctions.AddAdditionalText("Ich hab leider nichts da zum verkaufen");
    npc.base.autonpcfunctions.AddAdditionalText("Eine Preisliste habe ich nicht da, weil ich eigentlich nichts verkaufe");
    -- Small talk
    npc.base.autonpcfunctions.AddTraderTrigger("Beruf","Von Beruf bin ich Koch, ja genau.");
    npc.base.autonpcfunctions.AddAdditionalText("Ich bin Koch, einer der besten sogar!");
    npc.base.autonpcfunctions.AddTraderTrigger("profession","I'm a cook, that's right.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("job");
    npc.base.autonpcfunctions.AddAdditionalText("I'm a cook, even the best!");
    npc.base.autonpcfunctions.AddTraderTrigger("gobaith","Gobaith? That's where all those refugees come from all of a sudden, right?");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("gobiath","Gobaith? Da kommen diese ganzen Flüchtlinge plötzlich her, richtig?");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    -- leaders, town and politics
    npc.base.autonpcfunctions.AddTraderTrigger("cadomyr","That's this desert town right? They probably have a hard time to find fresh ingredients there to cook. Maybe I should travel there and serve them some of my cabbage soup.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("cadomyr","Das ist diese Wüstenstadt, richtig? Die haben es sicher schwer, frische Zutaten zum kochen zu finden. Vielleicht sollte ich mal dort hinreisen und ihnen etwas von meiner Kohlsuppe servieren.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("runewick","Runewick is a mighty fine town, isn't it? Lots of fresh veggies and fruits for the perfect dish. The farmers here are the best!");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("runewick","Runewick ist eine ganz prima Stadt oder? Viel frisches Obst und Gemüse für das perfecte Gericht. Die Bauern hier sind die besten!");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("galmair","Galmair... I don't know much about this place, but I heard that you only are treated fair when you have enough money.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("galmair","Galmair... Ich weiß nicht viel über diesen Ort, aber ich habe gehört, dass man nur fair behandelt wird, wenn man genug Geld hat.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("queen","It is said that queen Rosaline of Cadomyr is really pretty but also very strict. I think I saw her once, when she visited the archmage and maybe she even had the chance to taste one of my cakes that day!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("rosaline edwards");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("königin","Es wird gesagt, das Königin Rosaline von Cadomyr sehr hübsch sein soll, aber auch sehr streng. Ich glaube ich habe sie mal gesehen, als sie den Erzmagier besuchte und vielleicht hatte sie an dem Tag auch die Chance einen meiner Kuchen zu probieren!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("rosaline edwards");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("archmage","Archmage Morgan is a really kind and generous leader and I trust him completely. He is good to us, even to the farmers and the once who do not have any profession at all.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Elvaine Morgan");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("erzmagier","Erzmagier Morgan is ein großherziger und gütiger Anfürhrer und ich vertraue ihm. Er ist gut zu uns, sogar zu den Bauern und jenen die keine Arbeit haben.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Elvaine Morgan");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Valerio Guilianni","Valerion Gui..Guilia...Guilianni? Who's that? The name doesn't sound really friendly.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Valerio Guilianni","Valerion Gui..Guilia...Guilianni? Wer ist denn das? Der Name hört sich nicht sehr freundlich an.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    -- Tool hints 
    npc.base.autonpcfunctions.AddTraderTrigger("seed","You will have to plant the seeds into the earth, so that they can grow. If you need more just ask Fred for some.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("seedling");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("Samen","Die Samen musst du in die Erde einpflanzen, damit sie auch wachsen. Wenn du mehr braucht, frag einfach Fred nach ein paar.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("cooking spoon","A carpenter can make you a cooking spoon, you sure find one on the market place or in the workshop.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("Kochlöffel","Einen Kochlöffel kann dir auch ein Schreiner herstellen, den findest du sicher auf dem Marktplatz oder in der Werkstatt.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    -- 1st quest
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Yes, I have something to do for you. Bring me 10 onions and 10 cabbage, than I might let you taste from my soup and it would be nice if you bring me a cooking spoon as well. Here are some seeds and a sickle.");
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",20);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("item",534,30,399,0);
    npc.base.autonpcfunctions.AddConsequence("item",291,30,399,0);
    npc.base.autonpcfunctions.AddConsequence("item",126,1,399,0);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Jup, ich hätte was für dich zu tun, bring mir 10 Zwiebeln sowie 10 Kohlköpfe, dann lass ich dich auch von meiner Suppe kosten und ein neuer Kochlöffel wäre auch nett. Ach und hier ist eine Sichel, die wirst du brauche und ein paar Samen.");
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",20);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("item",534,30,399,0);
    npc.base.autonpcfunctions.AddConsequence("item",291,30,399,0);
    npc.base.autonpcfunctions.AddConsequence("item",126,1,399,0);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("task","Yes, I have something to do for you. Bring me 10 onions and 10 cabbage, than I might let you taste from my soup and it would be nice if you bring me a cooking spoon as well. Here are some seeds and a sickle.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",20);
    npc.base.autonpcfunctions.AddConsequence("item",534,30,399,0);
    npc.base.autonpcfunctions.AddConsequence("item",291,30,399,0);
    npc.base.autonpcfunctions.AddConsequence("item",126,1,399,0);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Jup, ich hätte was für dich zu tun, bring mir 10 Zwiebeln sowie 10 Kohlköpfe, dann lass ich dich auch von meiner Suppe kosten und ein neuer Kochlöffel wäre auch nett. Ach und hier ist eine Sichel, die wirst du brauche und ein paar Samen.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",20);
    npc.base.autonpcfunctions.AddConsequence("item",534,30,399,0);
    npc.base.autonpcfunctions.AddConsequence("item",291,30,399,0);
    npc.base.autonpcfunctions.AddConsequence("item",126,1,399,0);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("quest","If you don't bring me those 10 onions and 10 cabbage, I won't be able to make soup. And without a cooking spoon I cannot cook.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Wenn du mir nicht die 10 Zwiebeln und die 10 Kohlköpfe bringst, kann ich leider auch keine Suppe machen. Und ohne den neuen Kochlöffel kann ich nicht kochen.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("task","If you don't bring me those 10 onions and 10 cabbage, I won't be able to make soup. And without a cooking spoon I cannot cook.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Wenn du mir nicht die 10 Zwiebeln und die 10 Kohlköpfe bringst, kann ich leider auch keine Suppe machen. Und ohne den neuen Kochlöffel kann ich nicht kochen.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Ah, du bist zurück und du hast sogar alles da, was ich von dir wollte, sehr schön. Jetzt aber Augen auf!");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddCondition("item",290,"all",">",9);
    npc.base.autonpcfunctions.AddCondition("item",201,"all",">",9);
    npc.base.autonpcfunctions.AddCondition("item",227,"all",">",0);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",290,10);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",201,10);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",227,1);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","baking","+",5);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest erfüllt] Du hast das Gefühl als hättest du heute viel gelernt.");
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Ah, you're back and you even have everything with you, that I requested. Very good. Now watch closely!");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddCondition("item",290,"all",">",9);
    npc.base.autonpcfunctions.AddCondition("item",201,"all",">",9);
    npc.base.autonpcfunctions.AddCondition("item",227,"all",">",0);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",290,10);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",201,10);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",227,1);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","baking","+",5);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest finished] You have the feeling that you've learnt a lot today.");
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Das ist nicht alles was ich haben wollte, ich wollte 10 Kohlköpfe, 10 Zwiebeln und einen Kochlöffel!");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddCondition("item",290,"all","<",10);
    npc.base.autonpcfunctions.AddCondition("item",201,"all","<",10);
    npc.base.autonpcfunctions.AddCondition("item",227,"all","<",1);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger(".+","That's not everything I wanted. I wanted 10 cabbage, 10 onions and a cooking spoon.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddCondition("item",290,"all","<",10);
    npc.base.autonpcfunctions.AddCondition("item",201,"all","<",10);
    npc.base.autonpcfunctions.AddCondition("item",227,"all","<",1);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    -- 2nd quest
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Oioioi, you again! Now bring me 15 tomatoes, a hatchet for a new fire and a bucket. And don't forget to bring me 5 bowls of onionsoup as well, I want to see if yours is as good as mine by now!");
    npc.base.autonpcfunctions.AddCondition("skill","baking",">",20);
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",40);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Uiuiui, da bist du ja wieder! Jetzt bring mir aber schnell 15 Tomaten, ein Beil für ein neues Feuer und einen Eimer. Und vergiss nicht mir auch noch 5 Schüsseln Zwiebelsuppe zu bringen, ich will sehen ob du die endlich genau so gut machen kannst wie ich! ");
    npc.base.autonpcfunctions.AddCondition("skill","baking",">",20);
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",40);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npc.base.autonpcfunctions.AddTraderTrigger("task","Oioioi, you again! Now bring me 15 tomatoes, a hatchet for a new fire and a bucket. And don't forget to bring me 5 bowls of onionsoup as well, I want to see if yours is as good as mine by now!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("skill","baking",">",20);
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",40);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Uiuiui, da bist du ja wieder! Jetzt bring mir aber schnell 15 Tomaten, ein Beil für ein neues Feuer und einen Eimer. Und vergiss nicht mir auch noch 5 Schüsseln Zwiebelsuppe zu bringen, ich will sehen ob du die endlich genau so gut machen kannst wie ich!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("skill","baking",">",20);
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",40);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npc.base.autonpcfunctions.AddTraderTrigger("quest","You have to practice a little more, than I will gladly help you with more advances recipes.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",20);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Du musst noch ein bisschen mehr üben, dann helf ich dir auch gerne weiter bei schwierigeren Rezepten.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",20);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("task","You have to practice a little more, than I will gladly help you with more advances recipes.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",20);
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Du musst noch ein bisschen mehr üben, dann helf ich dir auch gerne weiter bei schwierigeren Rezepten.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",20);
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Bring me the 15 tomatoes, the hatchet and the bucket, as well as 5 bowls of selfmade onionsoup and I will cook us a tasty stew!");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Bring mir die 15 Tomaten, das Beil und den Eimer, sowie deine 5 Schüsseln selbstgemacher Zwiebelsuppe und ich koch uns einen leckeren Eintopf!");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("task","Bring me the 15 tomatoes, the hatchet and the bucket, as well as 5 bowls of selfmade onionsoup and I will cook us a tasty stew!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Bring mir die 15 Tomaten, das Beil und den Eimer, sowie deine 5 Schüsseln selbstgemacher Zwiebelsuppe und ich koch uns einen leckeren Eintopf!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Endlich bist du wieder da, jetzt aber schnell her mit den Sachen. Schau zu, vielleicht lernst du ja noch dies und das von mir!");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("item",200,"all",">",14);
    npc.base.autonpcfunctions.AddCondition("item",2923,"all",">",4);
    npc.base.autonpcfunctions.AddCondition("item",74,"all",">",1);
    npc.base.autonpcfunctions.AddCondition("item",51,"all",">",1);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",200,15);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",2923,5);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",74,1);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",51,1);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","baking","+",5);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest erfüllt] Du hast das Gefühl als hättest du heute viel gelernt.");
    npc.base.autonpcfunctions.AddTraderTrigger(".+","You're finally back, now quickly hand me those things. Watch me now, maybe you learn a thing or two from me!");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("item",200,"all",">",14);
    npc.base.autonpcfunctions.AddCondition("item",2923,"all",">",4);
    npc.base.autonpcfunctions.AddCondition("item",74,"all",">",1);
    npc.base.autonpcfunctions.AddCondition("item",51,"all",">",1);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",200,15);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",2923,5);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",74,1);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",51,1);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","baking","+",5);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest finished] You have the feeling that you've learnt a lot today.");
    npc.base.autonpcfunctions.AddTraderTrigger(".+","So wird das nichts, du musst mir schon die Sachen bringen die ich von dir wollte, ich zähle sie nochmal auf also schreibs auf. 15 Tomaten, ein Beil, einen Eimer und 5 Schüsseln Zwiebelsuppe!");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("item",200,"all","<",15);
    npc.base.autonpcfunctions.AddCondition("item",2923,"all","<",5);
    npc.base.autonpcfunctions.AddCondition("item",74,"all","=",0);
    npc.base.autonpcfunctions.AddCondition("item",51,"all","=",0);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger(".+","That's not working, you will have to bring me those things I asked you for, I will tell it as well, better note it down. 15 tomatoes, a hatchet, a bucket and 5 bowls of onionsoup!");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("item",200,"all","<",15);
    npc.base.autonpcfunctions.AddCondition("item",2923,"all","<",5);
    npc.base.autonpcfunctions.AddCondition("item",74,"all","=",0);
    npc.base.autonpcfunctions.AddCondition("item",51,"all","=",0);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    -- 3rd quest
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Ah, you're back so soon. I just wanted to make a cake, please bring me the following things: four peels, a small pouch with 10 hops in it, 10 muffins and the most important thing, five honeycombs.");
    npc.base.autonpcfunctions.AddCondition("skill","baking",">",40);
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",60);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npc.base.autonpcfunctions.AddTraderTrigger("quest","So, so, schnell bist du zurück. Ich wollte gerade einen Kuchen backen, bring' mir bitte folgende Sachen: vier Ofenschieber, ein kleinen Beutel mit 10 Hopfen darin, 10 Muffins und das wichtigste nicht zu vergessen, fünf Honigwaben.");
    npc.base.autonpcfunctions.AddCondition("skill","baking",">",40);
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",60);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npc.base.autonpcfunctions.AddTraderTrigger("task","Ah, you're back so soon. I just wanted to make a cake, please bring me the following things: four peels, a small pouch with 10 hops in it, 10 muffins and the most important thing, five honeycombs.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("skill","baking",">",40);
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",60);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","So, so, schnell bist du zurück. Ich wollte gerade einen Kuchen backen, bring' mir bitte folgende Sachen: vier Ofenschieber, ein kleinen Beutel mit 10 Hopfen darin, 10 Muffins und das wichtigste nicht zu vergessen, fünf Honigwaben.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("skill","baking",">",40);
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",60);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Don't disturbe me now, I'm just working on a new recipe. Come back later.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",4);
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",40);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Störe mich jetzt nicht, ich bastel grad an einem neuen Rezept. Komm später wieder.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",4);
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",40);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("task","Don't disturbe me now, I'm just working on a new recipe. Come back later.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",40);
    npc.base.autonpcfunctions.AddCondition("qpg","=",4);
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Störe mich jetzt nicht, ich bastel grad an einem neuen Rezept. Komm später wieder.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",40);
    npc.base.autonpcfunctions.AddCondition("qpg","=",4);
    npc.base.autonpcfunctions.AddTraderTrigger("quest","4 peels, 10 hops, 10 muffings and 5 honeycombs, I think you will have that in no time.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","4 Ofenschieber, 10 Hopfen, 10 Muffins und 5 Honigwaben waren es, ich denke mal das hast du im nu zusammen.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("task","4 peels, 10 hops, 10 muffings and 5 honeycombs, I think you will have that in no time.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","4 Ofenschieber, 10 Hopfen, 10 Muffins und 5 Honigwaben waren es, ich denke mal das hast du im nu zusammen.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Da bist du ja wieder und du hast sogar alles dabei, großartig! Nun kannst du mir auch zugucken wie ich den Kuchen backe, das hilft dir sicher weiter!");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddCondition("item",121,"all",">",3);
    npc.base.autonpcfunctions.AddCondition("item",154,"all",">",9);
    npc.base.autonpcfunctions.AddCondition("item",454,"all",">",9);
    npc.base.autonpcfunctions.AddCondition("item",2529,"all",">",4);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",121,4);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",154,10);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",454,10);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",2529,5);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","baking","+",5);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest erfüllt] Du hast das Gefühl als hättest du heute viel gelernt.");
    npc.base.autonpcfunctions.AddTraderTrigger(".+","You're back and you have everything with you, fantastic! Now you can help me with this cake, I'm sure that'll help you!");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddCondition("item",121,"all",">",3);
    npc.base.autonpcfunctions.AddCondition("item",154,"all",">",9);
    npc.base.autonpcfunctions.AddCondition("item",454,"all",">",9);
    npc.base.autonpcfunctions.AddCondition("item",2529,"all",">",4);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",121,4);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",154,10);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",454,10);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",2529,5);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","baking","+",5);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest finished] You have the feeling that you've learnt a lot today.");
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Du hast ja nicht alles was ich wollte wie mir scheint, hol' mir die Sachen doch bitte, dann back ich einen super leckeren Kuchen!");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddCondition("item",121,"all","<",4);
    npc.base.autonpcfunctions.AddCondition("item",154,"all","<",10);
    npc.base.autonpcfunctions.AddCondition("item",454,"all","<",10);
    npc.base.autonpcfunctions.AddCondition("item",2529,"all","<",5);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger(".+","You don't have everything I asked you for. Get me all those things than I will bake a super tasty cake!");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddCondition("item",121,"all","<",4);
    npc.base.autonpcfunctions.AddCondition("item",154,"all","<",10);
    npc.base.autonpcfunctions.AddCondition("item",454,"all","<",10);
    npc.base.autonpcfunctions.AddCondition("item",2529,"all","<",5);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    -- 4th quest 
    npc.base.autonpcfunctions.AddTraderTrigger("quest","I have one recipe for you left but I want to try some of you selfmade dished. I would like to try 15 sausage dishes, one box with 10 cookies, as well as 10 meat dishes and 5 strawberry cakes.");
    npc.base.autonpcfunctions.AddCondition("skill","baking",">",60);
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",80);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Ein Rezept habe ich noch für dich, dafür will ich aber von dir einige selbstgemachte Gerichte testen. 15 Teller Würstchen mit Beilage, eine Dose mit 10 Keksen darin, sowie 10 Teller Steak mit Beilage und zu guter letzt 5 Erdbeertorten will ich von dir kosten.");
    npc.base.autonpcfunctions.AddCondition("skill","baking",">","60s");
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",80);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npc.base.autonpcfunctions.AddTraderTrigger("task","I have one recipe for you left but I want to try some of you selfmade dished. I would like to try 15 sausage dishes, one box with 10 cookies, as well as 10 meat dishes and 5 strawberry cakes.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("skill","baking",">",60);
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",80);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Ein Rezept habe ich noch für dich, dafür will ich aber von dir einige selbstgemachte Gerichte testen. 15 Teller Würstchen mit Beilage, eine Dose mit 10 Keksen darin, sowie 10 Teller Steak mit Beilage und zu guter letzt 5 Erdbeertorten will ich von dir kosten.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("skill","baking",">",60);
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",80);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Practice your cooking skill a little more, because with practice you get better and if you later ask nicely, I might have another recipe for you.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",6);
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",60);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Übe dich noch etwas im Kochen, denn nur durch Übung wird man besser und wenn du später nett fragst, habe ich vielleicht sogar noch ein Rezept für dich.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",6);
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",60);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("task","Practice your cooking skill a little more, because with practice you get better and if you later ask nicely, I might have another recipe for you.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",60);
    npc.base.autonpcfunctions.AddCondition("qpg","=",6);
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Übe dich noch etwas im Kochen, denn nur durch Übung wird man besser und wenn du später nett fragst, habe ich vielleicht sogar noch ein Rezept für dich.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("skill","baking","=<",60);
    npc.base.autonpcfunctions.AddCondition("qpg","=",6);
    npc.base.autonpcfunctions.AddTraderTrigger("quest","You should bring me 15 sausage dishes, a box with 10 cookies, 10 steaks and of course the 5 strawberry cakes.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",7);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Du solltest mir 15 Teller Würstchen mit Beilage, eine Dose mit 10 Keksen, 10 Teller Steak mit Beilage bringen und natürlich die 5 Erdbeertorten nicht zu vergessen.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",7);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("task","You should bring me 15 sausage dishes, a box with 10 cookies, 10 steaks and of course the 5 strawberry cakes.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("qpg","=",7);
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Du solltest mir 15 Teller Würstchen mit Beilage, eine Dose mit 10 Keksen, 10 Teller Steak mit Beilage bringen und natürlich die 5 Erdbeertorten nicht zu vergessen.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("qpg","=",7);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Jam, jam, deine Gerichte schmecken klasse. Aber ein kleiner Tipp noch, ab und an misch ich ein kleines Stück von einem Sibanacblatt in mein Essen, dadurch bekommt es den herlichen Duft.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",7);
    npc.base.autonpcfunctions.AddCondition("item",2922,"all",">",14);
    npc.base.autonpcfunctions.AddCondition("item",453,"all",">",9);
    npc.base.autonpcfunctions.AddCondition("item",557,"all",">",9);
    npc.base.autonpcfunctions.AddCondition("item",354,"all",">",4);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",2922,15);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",453,10);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",557,10);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",354,5);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","baking","+",5);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",8);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest erfüllt] Du hast das Gefühl als hättest du heute viel gelernt.");
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Mhh..your dishes are tasty. But one small, last tipp, if you mix a small piece of a Sibanac leaf under your dishes it gets this nice smell.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",7);
    npc.base.autonpcfunctions.AddCondition("item",2922,"all",">",14);
    npc.base.autonpcfunctions.AddCondition("item",453,"all",">",9);
    npc.base.autonpcfunctions.AddCondition("item",557,"all",">",9);
    npc.base.autonpcfunctions.AddCondition("item",354,"all",">",4);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",2922,15);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",453,10);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",557,10);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",354,5);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","baking","+",5);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",8);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest finished] You have the feeling that you've learnt a lot today.");
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Wenn du keinen Wert auf meine Forderung legst, mir ein paar von deinen Gerichten zu bringen, helfe ich dir auch nicht!");
    npc.base.autonpcfunctions.AddCondition("qpg","=",7);
    npc.base.autonpcfunctions.AddCondition("item",2922,"all","<",15);
    npc.base.autonpcfunctions.AddCondition("item",453,"all","<",10);
    npc.base.autonpcfunctions.AddCondition("item",557,"all","<",10);
    npc.base.autonpcfunctions.AddCondition("item",354,"all","<",5);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger(".+","If you don't emphasize my demands, to bring me some of you dishes, I cannoth help you!");
    npc.base.autonpcfunctions.AddCondition("qpg","=",7);
    npc.base.autonpcfunctions.AddCondition("item",2922,"all","<",15);
    npc.base.autonpcfunctions.AddCondition("item",453,"all","<",10);
    npc.base.autonpcfunctions.AddCondition("item",557,"all","<",10);
    npc.base.autonpcfunctions.AddCondition("item",354,"all","<",5);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    -- Final dialogue: No more quests, just nice hints 
    npc.base.autonpcfunctions.AddTraderTrigger("quest","You're good enough now, there is nothing more I could teach you. If you keep on practicing you might become a master cook!");
    npc.base.autonpcfunctions.AddCondition("qpg","=",8);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Du bist nun gut genug, es gibt nichts dass ich dir noch beibringen könnte. Strengst du dich noch ein wenig mehr an, wirst du noch ein Meister im kochen!");
    npc.base.autonpcfunctions.AddCondition("qpg","=",8);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("task","You're good enough now, there is nothing more I could teach you. If you keep on practicing you might become a master cook!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("qpg","=",8);
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Du bist nun gut genug, es gibt nichts dass ich dir noch beibringen könnte. Strengst du dich noch ein wenig mehr an, wirst du noch ein Meister im kochen!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("qpg","=",8);
    -- Last catch: Think about keyphrases the player might say and that are not caught until here 
    npc.base.autonpcfunctions.AddTraderTrigger("Yes","Great, hurry up.");
    npc.base.autonpcfunctions.AddAdditionalText("Fantastic, now run!");
    npc.base.autonpcfunctions.AddAdditionalText("Great, but pleace hurry up");
    npc.base.autonpcfunctions.AddTraderTrigger("Ja","Super, mach schnell.");
    npc.base.autonpcfunctions.AddAdditionalText("Wunderbar, dann los!");
    npc.base.autonpcfunctions.AddAdditionalText("Toll, aber beeil dich bitte");
    npc.base.autonpcfunctions.AddTraderTrigger("No","Maybe you will change your mind?");
    npc.base.autonpcfunctions.AddAdditionalText("Why not? Aren't you nice?");
    npc.base.autonpcfunctions.AddAdditionalText("Please, do it for me.");
    npc.base.autonpcfunctions.AddTraderTrigger("Nein","Vielleicht änderst du deine Meinung noch einmal?");
    npc.base.autonpcfunctions.AddAdditionalText("Wieso denn nicht, bist du nicht nett?");
    npc.base.autonpcfunctions.AddAdditionalText("Ach bitte, mach es für mich");
    -- ********* END DYNAMIC PART ********
    TradSpeakLang={0,1};
    TradStdLang=0;

    npc.base.autonpcfunctions.increaseLangSkill(TradSpeakLang);
    thisNPC.activeLanguage=TradStdLang;

end

function nextCycle()  -- ~10 times per second
    initializeNpc();
    npc.base.autonpcfunctions.SpeakerCycle();
end

function receiveText(texttype, message, originator)
    if npc.base.autonpcfunctions.BasicNPCChecks(originator,2) then
        if npc.base.autonpcfunctions.LangOK(originator,TradSpeakLang) then
            npc.base.autonpcfunctions.TellSmallTalk(message,originator);
        else
            npc.base.autonpcfunctions.Confused(
               "#me sieht dich leicht verwirrt an",
               "#me looks at you a little confused"
            );
        end
    end
end
