-- INSERT INTO npc VALUES (nextval('npc_seq'),1,-135,-400,0,4,false,'Daerbur Wimbert','npc_daerbur_wimbert.lua',0);

require("npc.base.autonpcfunctions")
module("npc.daerbur_wimbert", package.seeall)

function useNPC(user,counter,param)
    thisNPC:increaseSkill(1,"common language",100);
    thisNPC:talkLanguage(CCharacter.say, CPlayer.german, "Finger weg!");
    thisNPC:talkLanguage(CCharacter.say, CPlayer.english, "Don't you touch me!");
end

function initializeNpc()
    if TraderFirst then
        return true;
    end

    npc.base.autonpcfunctions.InitTalkLists();

    -- ********* START DYNAMIC PART ********

    QuestID = 68;
    -- NPC by Estralis Seborian
    -- Queststatus Overview
    -- 0: No Quest taken
    -- 1: Quest 1 taken - gather 10 raw materials for 50cp
    -- 2: Quest 1 solved
    -- 3: Quest 2 taken - gather 20 raw materials for 100cp
    -- 4: Quest 2 solved
    -- 5: Quest 3 taken - gather 5 rare raw materials for 100cp
    -- 6: Quest 3 solved
    -- 7: Quest 4 taken - gather 10 distant raw materials for 200cp
    -- 8: Quest 4 solved
    -- Debugging
    npc.base.autonpcfunctions.AddTraderTrigger("set 0","Quest status set to 0");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("set 1","Quest status set to 1");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("set 2","Quest status set to 2");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("set 3","Quest status set to 3");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npc.base.autonpcfunctions.AddTraderTrigger("set 4","Quest status set to 4");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npc.base.autonpcfunctions.AddTraderTrigger("set 5","Quest status set to 5");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npc.base.autonpcfunctions.AddTraderTrigger("set 6","Quest status set to 6");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npc.base.autonpcfunctions.AddTraderTrigger("set 7","Quest status set to 7");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npc.base.autonpcfunctions.AddTraderTrigger("set 8","Quest status set to 8");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",8);
    -- Help 
    npc.base.autonpcfunctions.AddTraderTrigger("Help","");
    npc.base.autonpcfunctions.AddConsequence("inform","[Game Help] This NPC is the miner Daerbur Wimbert. Keyphrases: Hello, quest, pick-axe, miner.");
    npc.base.autonpcfunctions.AddTraderTrigger("Hilfe","");
    npc.base.autonpcfunctions.AddConsequence("inform","[Spielhilfe] Dieser NPC ist der Bergarbeiter Daerbur Wimbert. Schlüsselwörter: Hallo, Quest, Spitzhacke, Bergarbeiter.");
    -- General speech
    npc.base.autonpcfunctions.AddTraderTrigger("Hello","Huh?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Greetings");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Be greeted");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Hail");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Good day");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Good morning");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Good evening");
    npc.base.autonpcfunctions.AddAdditionalText("Hah?");
    npc.base.autonpcfunctions.AddAdditionalText("Heh?");
    npc.base.autonpcfunctions.AddAdditionalText("Hih?");
    npc.base.autonpcfunctions.AddAdditionalText("Hoh?");
    npc.base.autonpcfunctions.AddTraderTrigger("Grüße","Huh?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Gruß");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Seid gegrüßt");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Guten Tag");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Guten Abend");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Mahlzeit");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Tach");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Moin");
    npc.base.autonpcfunctions.AddAdditionalText("Hah?");
    npc.base.autonpcfunctions.AddAdditionalText("Heh?");
    npc.base.autonpcfunctions.AddAdditionalText("Hih?");
    npc.base.autonpcfunctions.AddAdditionalText("Hoh?");
    npc.base.autonpcfunctions.AddAdditionalText("Häh?");
    npc.base.autonpcfunctions.AddAdditionalText("Höh?");
    npc.base.autonpcfunctions.AddAdditionalText("Hüh?");
    npc.base.autonpcfunctions.AddTraderTrigger("Hiho","Huh?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Hallo");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Hey");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Greebas");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Greebs");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddAdditionalText("Hah?");
    npc.base.autonpcfunctions.AddAdditionalText("Heh?");
    npc.base.autonpcfunctions.AddAdditionalText("Hih?");
    npc.base.autonpcfunctions.AddAdditionalText("Hoh?");
    npc.base.autonpcfunctions.AddTraderTrigger("Hiho","Huh?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Hallo");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Hey");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Greebas");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Greebs");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddAdditionalText("Hah?");
    npc.base.autonpcfunctions.AddAdditionalText("Heh?");
    npc.base.autonpcfunctions.AddAdditionalText("Hih?");
    npc.base.autonpcfunctions.AddAdditionalText("Hoh?");
    npc.base.autonpcfunctions.AddAdditionalText("Häh?");
    npc.base.autonpcfunctions.AddAdditionalText("Höh?");
    npc.base.autonpcfunctions.AddAdditionalText("Hüh?");
    npc.base.autonpcfunctions.AddTraderTrigger("Farewell","So, you are leaving. That is interesting, that means, you go somewhere else. Exciting!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Good bye");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Bye");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Fare thy well");
    npc.base.autonpcfunctions.AddAdditionalText("Why did you come if you wanted to leave anyway? You like change to your life, I assume.");
    npc.base.autonpcfunctions.AddAdditionalText("Bye");
    npc.base.autonpcfunctions.AddTraderTrigger("Tschüß","So, du gehst also. Das ist interessant, denn das bedeutet, dass du woanders hingehst. Wie spanned!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Tschüss");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Wiedersehen");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Gehabt euch wohl");
    npc.base.autonpcfunctions.AddAdditionalText("Wieso bist du überhaupt gekommen, wenn du eh wieder gehen wolltest? Du magst Veränderungen in deinem Leben, richtig?");
    npc.base.autonpcfunctions.AddAdditionalText("Tschüß!");
    npc.base.autonpcfunctions.AddTraderTrigger("Ciao","So, you are leaving. That is interesting, that means, you go somewhere else. Exciting!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Adieu");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Au revoir");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddAdditionalText("Why did you come if you wanted to leave anyway? You like change to your life, I assume.");
    npc.base.autonpcfunctions.AddAdditionalText("Bye.");
    npc.base.autonpcfunctions.AddTraderTrigger("Ciao","So, du gehst also. Das ist interessant, denn das bedeutet, dass du woanders hingehst. Wie spanned!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Adieu");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Au revoir");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddAdditionalText("Wieso bist du überhaupt gekommen, wenn du eh wieder gehen wolltest? Du magst Veränderungen in deinem Leben, richtig?");
    npc.base.autonpcfunctions.AddAdditionalText("Tschüß!");
    npc.base.autonpcfunctions.AddTraderTrigger("How are you","Good and bad at once I feel. Sometimes, I feel a bit more bad than good, sometimes vice versa.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("How feel");
    npc.base.autonpcfunctions.AddAdditionalTrigger("How do you do");
    npc.base.autonpcfunctions.AddAdditionalText("I feel just like you, maybe a bit more sad or lucky, who knows.");
    npc.base.autonpcfunctions.AddAdditionalText("Wie fühlst du dich denn so? Ach, warum haben Leute kein Gefühlssinn, dann würde das dusselige Fragen entfallen.");
    npc.base.autonpcfunctions.AddTraderTrigger("Wie geht","Gut und schlecht gleichzeitig, so fühl ich mich. Manchmal ein bisschen mehr schlecht als gut, manchmal genau anders herum.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Wie fühlst");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Wie ist es ergangen");
    npc.base.autonpcfunctions.AddAdditionalText("Ich fühl mich genauso wie du, vielleicht ein wenig schlechter oder besser, wer weiß das schon.");
    npc.base.autonpcfunctions.AddAdditionalText("How do you feel? Alas, why don't we all have a sense for feelings, then, all these stupid questions would be unnecessary.");
    npc.base.autonpcfunctions.AddTraderTrigger("your name","Daerbur Wimbert.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("who are you");
    npc.base.autonpcfunctions.AddAdditionalTrigger("who art thou");
    npc.base.autonpcfunctions.AddAdditionalText("Daerbur.");
    npc.base.autonpcfunctions.AddAdditionalText("Daerbur Wimbert, son of Dimbur Wimbert and Klemka Jebmil, brother of Turgen Wimbert and Nadla Wimbert. That's me.");
    npc.base.autonpcfunctions.AddTraderTrigger("dein name","Daerbur Wimbert.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("wer bist du");
    npc.base.autonpcfunctions.AddAdditionalTrigger("wer seid ihr");
    npc.base.autonpcfunctions.AddAdditionalTrigger("wie heißt");
    npc.base.autonpcfunctions.AddAdditionalText("Daerbur.");
    npc.base.autonpcfunctions.AddAdditionalText("Daerbur Wimbert, Sohn von Dimbur Wimbert und Klemka Jebmil, Bruder von Turgen Wimbert und Nadla Wimbert. Das bin ich.");
    -- Catching typical NPC phrases 
    npc.base.autonpcfunctions.AddTraderTrigger("what sell","I sell nothing to you, you sell nothing to me. Everyone keeps his property, fine.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("what buy");
    npc.base.autonpcfunctions.AddAdditionalTrigger("list wares");
    npc.base.autonpcfunctions.AddAdditionalTrigger("price of");
    npc.base.autonpcfunctions.AddAdditionalText("You have enough, I have enough, so why trade?");
    npc.base.autonpcfunctions.AddAdditionalText("Bartering is so stupid, don't we all want to betray each other?");
    npc.base.autonpcfunctions.AddTraderTrigger("was verkauf","Ich verkaufe dir nichts, du verkaufst mir nichts. Jeder behält, was er hat, gut, nicht?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("was kauf");
    npc.base.autonpcfunctions.AddAdditionalTrigger("warenliste");
    npc.base.autonpcfunctions.AddAdditionalTrigger("preis von");
    npc.base.autonpcfunctions.AddAdditionalText("Du hast genug, ich hab genug, also warum handeln?");
    npc.base.autonpcfunctions.AddAdditionalText("Feilschen ist ziemlich dusselig, will doch jeder nur den anderen hehupsen.");
    npc.base.autonpcfunctions.AddTraderTrigger("tell something","Once upon a time, in land far far away... I forgot the rest. But this line thrills me!");
    npc.base.autonpcfunctions.AddAdditionalText("And they all died happily ever after... I'm not a good story teller.");
    npc.base.autonpcfunctions.AddAdditionalText("What shall I tell you, fairytales? Better ask a fairy!");
    npc.base.autonpcfunctions.AddTraderTrigger("erzähl was","Es war einmal in einem fernen Land, hinter den sieben Bergen... Den Rest hab ich vergessen, aber diese Zeile ist der Hammer.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("erzähl etwas");
    npc.base.autonpcfunctions.AddAdditionalText("Und wenn sie nicht noch leben, sind sie wohl gestorben... Ich bin nicht gut darin, Geschichten zu erzählen.");
    npc.base.autonpcfunctions.AddAdditionalText("Was soll ich dir erzählen, Märchen? Frage lieber eine Fee danach.");
    -- Small talk: The talk here should focus on possible questions. Feel free to add more!
    npc.base.autonpcfunctions.AddTraderTrigger("miner","I dig for gems, metals, and holes.");
    npc.base.autonpcfunctions.AddAdditionalText("Once, I dug a hole and some stinky, black fluid squirted out. Bah!");
    npc.base.autonpcfunctions.AddAdditionalText("If you find any gems, well, do not pick them up or nobody else can find them anymore.");
    npc.base.autonpcfunctions.AddTraderTrigger("Bergarbeiter","Ich grabe nach Edelsteinen, Metallen und Löchern.");
    npc.base.autonpcfunctions.AddAdditionalText("Einmal hab ich ein Loch gegraben und da spritze so eine schwarze, stinkende Flüssigkeit raus. Bah!");
    npc.base.autonpcfunctions.AddAdditionalText("Wenn du Edelsteine findest, lass sie doch liegen, sonst kann sie kein anderer mehr finden.");
    npc.base.autonpcfunctions.AddTraderTrigger("dark hole","It is not dark down here, you just need a torch.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddAdditionalText("A nice mine, isn't it? All mine in this mine, hehe.");
    npc.base.autonpcfunctions.AddTraderTrigger("Dunkelloch","Es ist doch nicht dunkel hier unten, du brauchst nur eine Fackel.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddAdditionalText("Eine schöne Mine, nicht wahr? Alles meins hier unten!");
    npc.base.autonpcfunctions.AddTraderTrigger("mine","It is not dark down here, you just need a torch.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddAdditionalText("A nice mine, isn't it? All mine in this mine, hehe.");
    npc.base.autonpcfunctions.AddTraderTrigger("Mine","Es ist doch nicht dunkel hier unten, du brauchst nur eine Fackel.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddAdditionalText("Eine schöne Mine, nicht wahr? Alles meins hier unten!");
    -- Factions
    npc.base.autonpcfunctions.AddTraderTrigger("Runewick","In Runewick, da sind sie dick!");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Runewick","Runewick, that makes me sick!");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Galmair","Ja, Galmair, das ist hier!");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Galmair","Yes, Galmair, that is here!");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Cadomyr","Cadomyr, das verbitt' ich mir!");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Cadomyr","Cadomyr, won't come here!");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    -- Tool hints
    npc.base.autonpcfunctions.AddTraderTrigger("pick","You look like somebody who can swing a pick. Everybody does, at least I think so. Perhaps you can do a task for me.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("hacke","Du siehst aus wie jemand, der eine Spitzhacke schwingen kann. Naja, jeder sieht so aus, denk ich. Vielleicht kannst du einen Auftrag für mich ausführen.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("pick","Need a pick, it has a nick. In Galmair, you get a new one.");
    npc.base.autonpcfunctions.AddTraderTrigger("hacke","Brauchst 'ne Hacke, war die letzte kacke. In Galmair kriegst du eine neue.");
    -- 1st quest: Take a tool and gather 10 raw materials for 50cp.
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Somehow, all rocks have decided to lay down on the gems. Can you collect ten stone blocks with this pick so I can reach the gems underneath?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("item",2763,1,399,0);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npc.base.autonpcfunctions.AddConsequence("inform","[New quest] Dark Hole Mine I");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Aus irgendeinem Grund haben die Felsen beschlossen, sich auf die Edelsteine zu legen. Kannst du zehn Steinblöcke mit dieser Spitzhacke sammeln, damit ich an die Edelsteine darunter komme?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("item",2763,1,399,0);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npc.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Dunkellochmine I");
    npc.base.autonpcfunctions.AddTraderTrigger("task","Somehow, all rocks have decided to lay down on the gems. Can you collect ten stone blocks with this pick so I can reach the gems underneath?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddConsequence("item",2763,1,399,0);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npc.base.autonpcfunctions.AddConsequence("inform","[New quest] Dark Hole Mine I");
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Aus irgendeinem Grund haben die Felsen beschlossen, sich auf die Edelsteine zu legen. Kannst du zehn Steinblöcke mit dieser Spitzhacke sammeln, damit ich an die Edelsteine darunter komme?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddConsequence("item",2763,1,399,0);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npc.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Dunkellochmine I");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Away with those rocks! Bring me ten stone blocks and I'll reward you.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Weg mit den Steinen! Bring mir zehn Blöcke und ich belohne dich.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("task","Away with those rocks! Bring me ten stone blocks and I'll reward you.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Weg mit den Steinen! Bring mir zehn Blöcke und ich belohne dich.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Perfekt. Warum wachsen den Steinen eigentlich keine Beine, dann könnten wir uns das Geschleppe sparen. Hier ist deine Belohnung.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddCondition("item",733,"all",">",9);
    npc.base.autonpcfunctions.AddCondition("town","=","galmair");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",733,10);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 50 Kupferstücke und deine Bergbaufertigkeit steigt. Dein Ansehen bei Don Valerio Guilianni steigt.");
    npc.base.autonpcfunctions.AddConsequence("rankpoints","galmair","+",5);
    npc.base.autonpcfunctions.AddConsequence("money","+",50);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Perfect. Why have rocks no legs so we could stop carrying them? Here is your reward.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddCondition("item",733,"all",">",9);
    npc.base.autonpcfunctions.AddCondition("town","=","galmair");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",733,10);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 50 copper coins and your mining skill increases. You advance in Don Valerio Guilianni's favour.");
    npc.base.autonpcfunctions.AddConsequence("rankpoints","galmair","+",5);
    npc.base.autonpcfunctions.AddConsequence("money","+",50);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Perfekt. Warum wachsen den Steinen eigentlich keine Beine, dann könnten wir uns das Geschleppe sparen. Hier ist deine Belohnung.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddCondition("item",733,"all",">",9);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",733,10);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 50 Kupferstücke und deine Bergbaufertigkeit steigt.");
    npc.base.autonpcfunctions.AddConsequence("money","+",50);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Perfect. Why have rocks no legs so we could stop carrying them? Here is your reward.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddCondition("item",733,"all",">",9);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",733,10);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 50 copper coins and your mining skill increases.");
    npc.base.autonpcfunctions.AddConsequence("money","+",50);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Weg mit den Steinen! Bring mir zehn Blöcke und ich belohne dich.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddCondition("item",733,"all","<",10);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Away with those rocks! Bring me ten stone blocks and I'll reward you.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddCondition("item",733,"all","<",10);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    -- 2nd quest: Gather 20 different raw materials for 100cp.
    npc.base.autonpcfunctions.AddTraderTrigger("quest","There is so much coal on top of the gems. Can you dig away twenty lumps of coal and bring them to me?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npc.base.autonpcfunctions.AddConsequence("inform","[New quest] Dark Hole Mine II");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Es liegt eindeutig zu viel Kohle über den Edelsteinen. Schippst du bitte zwanzig Klumpen weg und bringst sie mir?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npc.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Dunkellochmine II");
    npc.base.autonpcfunctions.AddTraderTrigger("task","There is so much coal on top of the gems. Can you dig away twenty lumps of coal and bring them to me?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npc.base.autonpcfunctions.AddConsequence("inform","[New quest] Dark Hole Mine II");
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Es liegt eindeutig zu viel Kohle über den Edelsteinen. Schippst du bitte zwanzig Klumpen weg und bringst sie mir?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npc.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Dunkellochmine II");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","There is so much coal on top of the gems. Can you dig away twenty lumps of coal and bring them to me?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Es liegt eindeutig zu viel Kohle über den Edelsteinen. Schippst du bitte zwanzig Klumpen weg und bringst sie mir?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("task","There is so much coal on top of the gems. Can you dig away twenty lumps of coal and bring them to me?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Es liegt eindeutig zu viel Kohle über den Edelsteinen. Schippst du bitte zwanzig Klumpen weg und bringst sie mir?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Wie wundervoll! Weg ist die Kohle, nun geht's ans Eingemachte. Hier, dein Lohn, gib es nicht alles auf einmal aus.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("item",21,"all",">",19);
    npc.base.autonpcfunctions.AddCondition("town","=","galmair");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",21,20);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 100 Kupferstücke und deine Bergbaufertigkeit steigt. Dein Ansehen bei Don Valerio Guilianni steigt.");
    npc.base.autonpcfunctions.AddConsequence("rankpoints","galmair","+",10);
    npc.base.autonpcfunctions.AddConsequence("money","+",100);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","How marvelous! Away is the coal, now we can get things done. Here, your reward, don't spend it all at once.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("item",21,"all",">",19);
    npc.base.autonpcfunctions.AddCondition("town","=","galmair");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",21,20);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 100 copper coins and your mining skill increases. You advance in Don Valerio Guilianni's favour.");
    npc.base.autonpcfunctions.AddConsequence("rankpoints","galmair","+",10);
    npc.base.autonpcfunctions.AddConsequence("money","+",100);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Wie wundervoll! Weg ist die Kohle, nun geht's ans Eingemachte. Hier, dein Lohn, gib es nicht alles auf einmal aus.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("item",21,"all",">",19);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",21,20);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 100 Kupferstücke und deine Bergbaufertigkeit steigt.");
    npc.base.autonpcfunctions.AddConsequence("money","+",100);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","How marvelous! Away is the coal, now we can get things done. Here, your reward, don't spend it all at once.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("item",21,"all",">",19);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",21,20);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 100 copper coins and your mining skill increases.");
    npc.base.autonpcfunctions.AddConsequence("money","+",100);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Grabe weiter, es liegt immernoch so viel Kohle über den Edelsteinen.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("item",21,"all","<",20);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Dig some more, there is still so much coal atop the gems.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("item",21,"all","<",20);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    -- 3rd quest: Gather 5 rare raw materials for 100cp.
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Hey-ho! Now we can dig for gems. Gather five raw blackstones for me and I will reward you generously.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",4);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npc.base.autonpcfunctions.AddConsequence("inform","[New quest] Dark Hole Mine III");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Hey-ho! Jetzt können wir nach Edelsteinen graben. Bring mir fünf ungeschliffene Schwarzsteine und ich belohne dich großzügig.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",4);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npc.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Dunkellochmine III");
    npc.base.autonpcfunctions.AddTraderTrigger("task","Heydiho! Now we can dig for gems. Gather five raw blackstones for me and I will reward you generously.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("qpg","=",4);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npc.base.autonpcfunctions.AddConsequence("inform","[New quest] Dark Hole Mine III");
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Heydiho! Jetzt können wir nach Edelsteinen graben. Bring mir fünf ungeschliffene Schwarzsteine und ich belohne dich großzügig");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("qpg","=",4);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npc.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Dunkellochmine III");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Bring me five raw blackstones and you get money. I'm so excited!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Bring mir fünf ungeschliffene Schwarzsteine und du bekommst Geld. Ich bin so aufgeregt!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("task","Bring me five raw blackstones and you get money. I'm so excited!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Bring mir fünf ungeschliffene Schwarzsteine und du bekommst Geld. Ich bin so aufgeregt!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Danke für die Edelsteine. Du fragst dich, was ich mit ihnen mache? Ich verstecke sie in einer anderen Höhle!");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddCondition("item",252,"all",">",4);
    npc.base.autonpcfunctions.AddCondition("town","=","galmair");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",252,5);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 100 Kupferstücke und deine Bergbaufertigkeit steigt. Dein Ansehen bei Don Valerio Guilianni steigt.");
    npc.base.autonpcfunctions.AddConsequence("rankpoints","galmair","+",15);
    npc.base.autonpcfunctions.AddConsequence("money","+",100);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Thank you for the gems. You wonder what I want to do with them? I hide them in another cave!");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddCondition("item",252,"all",">",4);
    npc.base.autonpcfunctions.AddCondition("town","=","galmair");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",252,5);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 100 copper coins and your mining skill increases. You advance in Don Valerio Guilianni's favour.");
    npc.base.autonpcfunctions.AddConsequence("rankpoints","galmair","+",15);
    npc.base.autonpcfunctions.AddConsequence("money","+",100);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Danke für die Edelsteine. Du fragst dich, was ich mit ihnen mache? Ich verstecke sie in einer anderen Höhle!");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddCondition("item",252,"all",">",4);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",252,5);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 100 Kupferstücke und deine Bergbaufertigkeit steigt.");
    npc.base.autonpcfunctions.AddConsequence("money","+",100);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Thank you for the gems. You wonder what I want to do with them? I hide them in another cave!");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddCondition("item",252,"all",">",4);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",252,5);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 100 copper coins and your mining skill increases.");
    npc.base.autonpcfunctions.AddConsequence("money","+",100);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Mehr Edelsteine, bitte. Ich brauche wenigstens fünf ungeschliffene Schwarzsteine, ja?");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddCondition("item",252,"all","<",5);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Some more gems, please. I need five raw blackstones, not less, yes?");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddCondition("item",252,"all","<",5);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    -- 4th quest: Gather 10 raw materials from a totally different location for 200cp. Link to other quest. Hint how to get there.
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Watch out! The ceiling is instable, run and bring me ten logs of conifer wood to support the ceiling. You get the best wood from Elstree forest.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",6);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npc.base.autonpcfunctions.AddConsequence("inform","[New quest] Dark Hole Mine IV");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Vorsicht! Die Höhlendecke ist einsturzgefährdet, lauf und bring mir zehn Nadelholzstämme um die Decke abzustützen. Das beste Holz bekommst du im Elsbaumwald.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",6);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npc.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Dunkellochmine IV");
    npc.base.autonpcfunctions.AddTraderTrigger("task","Watch out! The ceiling is instable, run and bring me ten logs of conifer wood to support the ceiling. You get the best wood from Elstree forest.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("qpg","=",6);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npc.base.autonpcfunctions.AddConsequence("inform","[New quest] Dark Hole Mine IV");
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Vorsicht! Die Höhlendecke ist einsturzgefährdet, lauf und bring mir zehn Nadelholzstämme um die Decke abzustützen. Das beste Holz bekommst du im Elsbaumwald.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("qpg","=",6);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",7);
    npc.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Dunkellochmine IV");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Beware of the forester Valandil if you venture to Elstree forest to bring me logs of conifer wood.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",7);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Nimm dich vor dem Förster Valandil in acht, wenn du in den Elsbaumwald gehst, um mir Nadelholzstämme zu holen.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",7);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("task","Beware of the forester Valandil if you venture to Elstree forest to bring me logs of conifer wood.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("qpg","=",7);
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Nimm dich vor dem Förster Valandil in acht, wenn du in den Elsbaumwald gehst, um mir Nadelholzstämme zu holen.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("qpg","=",7);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Oh, gut, Holz! Fällt mir hier unten nicht nur nicht der Himmel, sondern auch nicht die Decke auf den Kopf.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",7);
    npc.base.autonpcfunctions.AddCondition("item",3,"all",">",9);
    npc.base.autonpcfunctions.AddCondition("town","=","galmair");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",3,10);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 200 Kupferstücke und deine Bergbaufertigkeit steigt. Dein Ansehen bei Don Valerio Guilianni steigt.");
    npc.base.autonpcfunctions.AddConsequence("rankpoints","galmair","+",20);
    npc.base.autonpcfunctions.AddConsequence("money","+",200);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",8);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Oh, fine, wood. Not only won't the sky fall on my head down here, but also the ceiling won't.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",7);
    npc.base.autonpcfunctions.AddCondition("item",3,"all",">",9);
    npc.base.autonpcfunctions.AddCondition("town","=","galmair");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",3,10);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 200 copper coins and your mining skill increases. You advance in Don Valerio Guilianni's favour.");
    npc.base.autonpcfunctions.AddConsequence("rankpoints","galmair","+",20);
    npc.base.autonpcfunctions.AddConsequence("money","+",200);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",8);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Oh, gut, Holz! Fällt mir hier unten nicht nur nicht der Himmel, sondern auch nicht die Decke auf den Kopf.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",7);
    npc.base.autonpcfunctions.AddCondition("item",3,"all",">",9);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",3,10);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst 200 Kupferstücke und deine Bergbaufertigkeit steigt.");
    npc.base.autonpcfunctions.AddConsequence("money","+",200);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",8);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Oh, fine, wood. Not only won't the sky fall on my head down here, but also the ceiling won't.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",7);
    npc.base.autonpcfunctions.AddCondition("item",3,"all",">",9);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",3,10);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded 200 copper coins and your mining skill increases.");
    npc.base.autonpcfunctions.AddConsequence("money","+",200);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","mining","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",8);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Du kommst ohne Nadelholz wieder? Hat Valandil dich beim Holzfällen erwischt?");
    npc.base.autonpcfunctions.AddCondition("qpg","=",7);
    npc.base.autonpcfunctions.AddCondition("item",3,"all","<",10);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger(".+","You come back without conifer wood? Did Valandil catch you, chopping trees?");
    npc.base.autonpcfunctions.AddCondition("qpg","=",7);
    npc.base.autonpcfunctions.AddCondition("item",3,"all","<",10);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    -- Final dialogue: No more quests, just nice hints
    npc.base.autonpcfunctions.AddTraderTrigger("quest","I thank you for all you did, you made the world a better place. Or you changed nothing, but got money.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",8);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Ich danke dir, für alles, was du getan hast. Du hast die Welt zu einem besseren Ort gemacht. Oder du hast nichts bewirkt, aber ordentlich abkassiert.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",8);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("task","I thank you for all you did, you made the world a better place. Or you changed nothing, but got money.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("qpg","=",8);
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Ich danke dir, für alles, was du getan hast. Du hast die Welt zu einem besseren Ort gemacht. Oder du hast nichts bewirkt, aber ordentlich abkassiert.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("qpg","=",8);
    -- Last catch: Think about keyphrases the player might say and that are not caught until here
    npc.base.autonpcfunctions.AddTraderTrigger("Yes","What was first, yes or no? I mean, did people first think about how to agree or how to disagree?");
    npc.base.autonpcfunctions.AddAdditionalText("Indeed.");
    npc.base.autonpcfunctions.AddAdditionalText("Yes?");
    npc.base.autonpcfunctions.AddTraderTrigger("Ja","Was war wohl zuerst da, ja oder nein? Ich meine, haben sich die Leute zuerst überlegt, zuzustimmen oder abzulehnen?");
    npc.base.autonpcfunctions.AddAdditionalText("Jawohl.");
    npc.base.autonpcfunctions.AddAdditionalText("Ja?");
    npc.base.autonpcfunctions.AddTraderTrigger("No","I say yes, you say no, I say goodbye, you say hello!");
    npc.base.autonpcfunctions.AddAdditionalText("No?");
    npc.base.autonpcfunctions.AddAdditionalText("Why?");
    npc.base.autonpcfunctions.AddTraderTrigger("Nein","Ich sage ja, du sagst nein, ich sage tschüß, du sagst hallo!");
    npc.base.autonpcfunctions.AddAdditionalText("Nein?");
    npc.base.autonpcfunctions.AddAdditionalText("Wieso?");
    npc.base.autonpcfunctions.AddTraderTrigger("nuts","I am what I am. And what are you, something else?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("nutty");
    npc.base.autonpcfunctions.AddAdditionalTrigger("strange");
    npc.base.autonpcfunctions.AddAdditionalTrigger("wierd");
    npc.base.autonpcfunctions.AddAdditionalTrigger("loony");
    npc.base.autonpcfunctions.AddAdditionalText("That's all a matter of perspective.");
    npc.base.autonpcfunctions.AddAdditionalText("Points of view!");
    npc.base.autonpcfunctions.AddTraderTrigger("komisch","Ich bin, was ich bin. Und was bist du, was anderes?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("bescheuert");
    npc.base.autonpcfunctions.AddAdditionalTrigger("dusselig");
    npc.base.autonpcfunctions.AddAdditionalText("Das ist alles Ansichtssache.");
    npc.base.autonpcfunctions.AddAdditionalText("Meinungen.");
    npc.base.autonpcfunctions.AddTraderTrigger("ROFL","#me laughes out loud.");
    -- Cycletext: Please add at least(!) five cycletext messages. The more, the better. You can use emotes (#me is green), too. 
    npc.base.autonpcfunctions.AddCycleText("Ich frag mich, was wir sagen würden, wenn der Boden dauernd auf uns rumtrampeln würde. Er ist ziemlich ruhig...","I wonder what we would say if the ground would stomp on us. It is quite silent...");
    npc.base.autonpcfunctions.AddCycleText("Ist Dunkelheit das Fehlen von Licht oder Licht das Fehlen von Dunkeltheit?","Is darkness the lack of light or light the lack of darkness?");
    npc.base.autonpcfunctions.AddCycleText("#me hält einen funkelnden Edelstein vor seine zugekniffenen Augen und nickt langsam.","#me holds a gem in front of his eyes and nods slowly.");
    npc.base.autonpcfunctions.AddCycleText("Vorsicht vor den Steinen.","Beware of rocks.");
    npc.base.autonpcfunctions.AddCycleText("Wer braucht schon den Himmel, wenn man eine gut abgestützte Höhlendecke hat.","Who needs the sky when you have a well supported ceiling.");
    npc.base.autonpcfunctions.AddCycleText("Hela, heba, helloa.","Hela, heba, helloa.");
    -- ********* END DYNAMIC PART ********
    TradSpeakLang={0,1};
    TradStdLang=0;

    npc.base.autonpcfunctions.increaseLangSkill(TradSpeakLang);
    thisNPC.activeLanguage=TradStdLang;

end

function nextCycle()  -- ~10 times per second
    initializeNpc();
    npc.base.autonpcfunctions.SpeakerCycle();
end

function receiveText(texttype, message, originator)
    if npc.base.autonpcfunctions.BasicNPCChecks(originator,2) then
        if npc.base.autonpcfunctions.LangOK(originator,TradSpeakLang) then
            npc.base.autonpcfunctions.TellSmallTalk(message,originator);
        else
            npc.base.autonpcfunctions.Confused(
               "#me sieht dich leicht verwirrt an",
               "#me looks at you a little confused"
            );
        end
    end
end