-- INSERT INTO npc VALUES (nextval('npc_seq'),2,-100,-420,0,4,false,'Lilith Needlehand','npc_lilith_needlehand.lua',1);

require("npc.base.autonpcfunctions")
module("npc.lilith_needlehand")

function useNPC(user,counter,param)
    thisNPC:increaseSkill(1,"common language",100);
    thisNPC:talkLanguage(CCharacter.say, CPlayer.german, "Finger weg!");
    thisNPC:talkLanguage(CCharacter.say, CPlayer.english, "Don't you touch me!");
end

function initializeNpc()
    if TraderFirst then
        return true;
    end

    npc.base.autonpcfunctions.InitTalkLists();

    -- ********* START DYNAMIC PART ********

    QuestID = 73;
    -- Author: Vern Kron (PO Artimer Fault), heavily revised by Estralis Seborian
    -- Help
    npc.base.autonpcfunctions.AddTraderTrigger("Help","");
    npc.base.autonpcfunctions.AddConsequence("inform","[Game Help] This NPC is the tailor Lilith and may need help in a task. Keyphrases: Hello, Quest, Needle, Tailor.");
    npc.base.autonpcfunctions.AddTraderTrigger("Hilfe","");
    npc.base.autonpcfunctions.AddConsequence("inform","[Spielhilfe] Dieser NPC ist die Schneiderin Lilith. Sie könnte Hilfe bei einer Aufgabe gebrauchen. Schlüsselwörter: Hallo, Quest, Nadel, Schneider.");
    -- General speech
    npc.base.autonpcfunctions.AddTraderTrigger("Hello","Hiho! You must have come to help me!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Greetings");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Be greeted");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Hail");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Good day");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Good morning");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Good evening");
    npc.base.autonpcfunctions.AddAdditionalText("Oh my, hello there! You are here to assist me, I assume.");
    npc.base.autonpcfunctions.AddAdditionalText("#me gives a charming smile.");
    npc.base.autonpcfunctions.AddTraderTrigger("Grüße","Hiho! Du bist sicher hier, um mir zu helfen!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Gruß");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Seid gegrüßt");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Guten Tag");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Guten Abend");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Mahlzeit");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Tach");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Moin");
    npc.base.autonpcfunctions.AddAdditionalText("Oh, hallo!");
    npc.base.autonpcfunctions.AddAdditionalText("#me lächelt freundlich.");
    npc.base.autonpcfunctions.AddTraderTrigger("Hiho","Hiho! You must have come to help me!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Hallo");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Hey");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Greebas");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Greebs");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddAdditionalText("Oh my, hello there! You are here to assist me, I assume.");
    npc.base.autonpcfunctions.AddAdditionalText("#me gives a charming smile.");
    npc.base.autonpcfunctions.AddTraderTrigger("Hiho","Hiho! Du bist sicher hier, um mir zu helfen!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Hallo");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Hey");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Greebas");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Greebs");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddAdditionalText("Oh, hallo! Du kannst mir bestimmt helfen.");
    npc.base.autonpcfunctions.AddAdditionalText("#me lächelt freundlich.");
    npc.base.autonpcfunctions.AddTraderTrigger("Farewell","#me waves excitedly.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Good bye");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Bye");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Fare thy well");
    npc.base.autonpcfunctions.AddAdditionalText("Good Bye!");
    npc.base.autonpcfunctions.AddAdditionalText("Come back soon and maybe we can have some cake!");
    npc.base.autonpcfunctions.AddAdditionalText("#me turns back to the sheep, saying over her shoulder 'Farewell' as she pets one.");
    npc.base.autonpcfunctions.AddTraderTrigger("Tschüß","#me winkt freudig zum Abschied.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Tschüss");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Wiedersehen");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Gehabt euch wohl");
    npc.base.autonpcfunctions.AddAdditionalText("Auf wiedersehen!");
    npc.base.autonpcfunctions.AddAdditionalText("Komm bald zurück und dann essen wir Kuchen!");
    npc.base.autonpcfunctions.AddAdditionalText("#me wendet sich wieder den Schafen zu.");
    npc.base.autonpcfunctions.AddTraderTrigger("Ciao","#me waves excitedly.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Adieu");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Au revoir");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddAdditionalText("Good Bye!");
    npc.base.autonpcfunctions.AddAdditionalText("Come back soon and maybe we can have some cake!");
    npc.base.autonpcfunctions.AddAdditionalText("#me turns back to the sheep, saying over her shoulder 'Farewell' as she pets one.");
    npc.base.autonpcfunctions.AddTraderTrigger("Ciao","#me winkt freudig zum Abschied.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Adieu");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Au revoir");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddAdditionalText("Auf wiedersehen!");
    npc.base.autonpcfunctions.AddAdditionalText("Komm bald zurück und dann essen wir Kuchen!");
    npc.base.autonpcfunctions.AddAdditionalText("#me wendet sich wieder den Schafen zu.");
    npc.base.autonpcfunctions.AddTraderTrigger("How are you","I'm in a hurry! The archmage ordered a robe and I didn't finish it yet.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("How feel");
    npc.base.autonpcfunctions.AddAdditionalTrigger("How do you do");
    npc.base.autonpcfunctions.AddTraderTrigger("Wie geht","Ich bin in Eile. Der Erzmagier hat eine Robe bestellt und ich habe sie noch nicht fertig.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Wie fühlst");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Wie ist es ergangen");
    npc.base.autonpcfunctions.AddTraderTrigger("your name","My name is Lilith Needlehand, and I am a tailor, and it is a pleasure to meet you!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("who are you");
    npc.base.autonpcfunctions.AddAdditionalTrigger("who art thou");
    npc.base.autonpcfunctions.AddTraderTrigger("dein name","Mein Name ist Lilith Needlehand und ich bin eine Schneiderin. Es ist schön, deine Bekanntschaft zu machen.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("wer bist du");
    npc.base.autonpcfunctions.AddAdditionalTrigger("wer seid ihr");
    npc.base.autonpcfunctions.AddAdditionalTrigger("wie heißt");
    -- Catching typical NPC phrases
    npc.base.autonpcfunctions.AddTraderTrigger("what sell","I am not currently selling or buying anything. I need to finish an order first.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("what buy");
    npc.base.autonpcfunctions.AddAdditionalTrigger("list wares");
    npc.base.autonpcfunctions.AddAdditionalTrigger("price of");
    npc.base.autonpcfunctions.AddTraderTrigger("was verkauf","Ich kaufe oder verkaufe derzeit nichts. Ich muss erstmal eine Bestellung fertig bekommen.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("was kauf");
    npc.base.autonpcfunctions.AddAdditionalTrigger("warenliste");
    npc.base.autonpcfunctions.AddAdditionalTrigger("preis von");
    npc.base.autonpcfunctions.AddTraderTrigger("tell something","Hrm? I don't know what you are talking about. Do you expect me to gossip like an old halfling woman?!");
    npc.base.autonpcfunctions.AddTraderTrigger("erzähl was","Hrm? Worüber sprichst du? Soll ich dir dummes Zeug erzählen wie ein Waschweib?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("erzähl etwas");
    -- Small talk: The talk here should focus on possible questions. Feel free to add more!
    npc.base.autonpcfunctions.AddTraderTrigger("Tailor","As a tailor, I use wool, thread, and dye to create clothes. Some people only wear armor, but for a fancy evening nothing beats a fancy robe or dress.");
    npc.base.autonpcfunctions.AddTraderTrigger("Schneider","Als Schneiderin mache ich Kleidung aus Wolle, Garn und Färbemittel. Einige Leute tragen den ganzen Tag ihre Rüstung, aber für einen schönen Abend gibt es nichts feineres als ein tolles Kleid.");
    npc.base.autonpcfunctions.AddTraderTrigger("order","Oh dear, the archmage ordered a new robe. I totally forgot working on it! Maybe you can help me with this task.");
    npc.base.autonpcfunctions.AddTraderTrigger("Bestellung","Ohje, der Erzmagier hat eine neue Robe bestellt. Ich hab vollkommen vergessen, daran zu arbeiten. Vielleicht kannst du mir mit dieser Aufgabe helfen.");
    npc.base.autonpcfunctions.AddTraderTrigger("robe","Oh dear, the archmage ordered a new robe. I totally forgot working on it! Maybe you can help me with this task.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Robe","Ohje, der Erzmagier hat eine neue Robe bestellt. Ich hab vollkommen vergessen, daran zu arbeiten. Vielleicht kannst du mir mit dieser Aufgabe helfen.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    -- Tool hints
    npc.base.autonpcfunctions.AddTraderTrigger("needle","I use my needle to make clothes.");
    npc.base.autonpcfunctions.AddTraderTrigger("Nadel","Mit meiner Nadel nähe ich Kleidung.");
    npc.base.autonpcfunctions.AddTraderTrigger("scissors","To get scissors, I strongly suggest you talk to a smith, or you may purchase them from the nearby shop, I believe!");
    npc.base.autonpcfunctions.AddTraderTrigger("Schere","Wenn du eine Schere brauchst, geh doch zu einem Schmied oder frag im Laden.");
    -- Faction stuff
    npc.base.autonpcfunctions.AddTraderTrigger("Elvaine","Archmage Morgan, yes, I think he ordered a new robe. I should work on it!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Morgan");
    npc.base.autonpcfunctions.AddAdditionalTrigger("archmage");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Erzmagier");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Elvaine","Erzmagier Morgan, ja, der hat eine neue Robe bei mir bestellt. Ich sollte besser mal an ihr arbeiten.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Morgan");
    npc.base.autonpcfunctions.AddAdditionalTrigger("archmage");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Erzmagier");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Runewick","This is Runewick! I personally enjoy it here.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Runewick","Dies hier ist Runewick. Mir gefällt es hier.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Valerio","Ui, they have no law in Galmair, but everyone knows the Don is the boss.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Guilianni");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Don");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Valerio","Ui, es gibt kein Gesetz in Galmair, aber jeder weiß, dass der Don der Boss ist.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Guilianni");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Don");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Galmair","Galmair is funny. I used to live there, but here, it is more pleasant.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Galmair","Galmair ist echt komisch. Ich hab da früher mal gelebt, aber hier ist es schöner.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("rosaline","A woman rules Cadomyr. That is so funny!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("königin");
    npc.base.autonpcfunctions.AddAdditionalTrigger("queen");
    npc.base.autonpcfunctions.AddAdditionalTrigger("edwards");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("rosaline","Eine Frau regiert Cadomyr. Das ist so lustig!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("königin");
    npc.base.autonpcfunctions.AddAdditionalTrigger("queen");
    npc.base.autonpcfunctions.AddAdditionalTrigger("edwards");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Cadomyr","Cadomyr is far away, somewhere in the west I think. They don't like women there, but are ruled by a queen. Strange, eh?");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Cadomyr","Cadomyr ist weit weg, irgendwo im Westen meine ich. Die mögen keine Frauen da, aber trotzdem regiert da eine Königin. Komisch, oder?");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    -- Main land factions
    npc.base.autonpcfunctions.AddTraderTrigger("albar","They are mad, those albarians.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("albar","Die spinnen, die Albarier.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("gynk","My aunt lives near Gynk. I always write her a letter, each month.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("gync");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("gync","Meine Tante lebt bei Gynk. Ich schreibe ihr jeden Monat einen Brief.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("gynk");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("salkama","The Archmage talks a lot about Salkamar, I know nothing about that.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("salkama","Der Erzmagier redet viel über Salkamar, ich weiß da nichts drüber.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    -- Gods; each NPC should at react on one god, being a follower of said god
    npc.base.autonpcfunctions.AddTraderTrigger("Irmorom","Irmorom guides my needle. Sometimes, he's angry and I sting myself.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Irmorom","Irmorom führt meine Nadel. Manchmal ist er böse auf mich und dann picks ich mich.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Cherga","Eeek!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Moshran");
    -- 1st quest: Gather 20 wool
    npc.base.autonpcfunctions.AddTraderTrigger("quest","I could use some help at tailoring a robe for the archmage, yes! Please get me twenty pieces of wool, I am short on that.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npc.base.autonpcfunctions.AddConsequence("inform","[New quest] The Lazy Tailoress I");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Ich könnte etwas Hilfe gebrauchen, um eine Robe für den Erzmagier zu schneidern. Bring mir doch bitte zwanzig Wollballen, ich habe keine mehr.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npc.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Das faule Schneiderlein I");
    npc.base.autonpcfunctions.AddTraderTrigger("task","I could use some help at tailoring a robe for the archmage, yes! Please get me twenty pieces of wool, I am short on that.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npc.base.autonpcfunctions.AddConsequence("inform","[New quest] The Lazy Tailoress I");
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Ich könnte etwas Hilfe gebrauchen, um eine Robe für den Erzmagier zu schneidern. Bring mir doch bitte zwanzig Wollballen, ich habe keine mehr.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("qpg","=",0);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npc.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Das faule Schneiderlein I");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Did you forget? I need twenty bundles of wool! Oh please, I need to finish the robe for the archmage in time.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Hast du es schon vergessen? Ich brauche zwanzig Wollballen. Bitte, ich muss die Robe für den Erzmagier rechtzeitig fertig kriegen.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("task","Did you forget? I need twenty bundles of wool! Oh please, I need to finish the robe for the archmage in time.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Hast du es schon vergessen? Ich brauche zwanzig Wollballen. Bitte, ich muss die Robe für den Erzmagier rechtzeitig fertig kriegen.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Oh, danke! Ich habe keine Belohnung für dich, aber du kannst meine Ersatznadel haben.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddCondition("item",170,"all",">",19);
    npc.base.autonpcfunctions.AddCondition("town","=","runewick");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",170,20);
    npc.base.autonpcfunctions.AddConsequence("item",47,1,999,0);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst eine Nadel und deine Schneidereifähigkeit steigt. Dein Ansehen bei Erzmagier Elvaine Morgan steigt.");
    npc.base.autonpcfunctions.AddConsequence("rankpoints","runewick","+",5);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","tailoring","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Why thank you! I don't have a real reward for you, but you can have my spare needle.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddCondition("item",170,"all",">",19);
    npc.base.autonpcfunctions.AddCondition("town","=","runewick");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",170,20);
    npc.base.autonpcfunctions.AddConsequence("item",47,1,999,0);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded a needle and your tailoring skill increases. You advance in Archmage Elvaine Morgan's favour.");
    npc.base.autonpcfunctions.AddConsequence("rankpoints","runewick","+",5);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","tailoring","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Oh, danke! Ich habe keine Belohnung für dich, aber du kannst meine Ersatznadel haben.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddCondition("item",170,"all",">",19);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",170,20);
    npc.base.autonpcfunctions.AddConsequence("item",47,1,999,0);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst eine Nadel und deine Schneidereifähigkeit steigt.");
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","tailoring","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Why thank you! I don't have a real reward for you, but you can have my spare needle.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddCondition("item",170,"all",">",19);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",170,20);
    npc.base.autonpcfunctions.AddConsequence("item",47,1,999,0);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded a needle and your tailoring skill increases.");
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","tailoring","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Hmm, das ist noch nicht genug Wolle.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddCondition("item",170,"all","<",19);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Hrm.. there is not enough wool here yet.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",1);
    npc.base.autonpcfunctions.AddCondition("item",170,"all","<",19);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    -- 2nd quest: Gather 15 thread
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Oh, you want to help me some more? Well, I certainly need some thread for the robe. Bring me fifteen bobbins of thread, please.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npc.base.autonpcfunctions.AddConsequence("inform","[New quest] The Lazy Tailoress II");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Oh, du willst mir noch mehr helfen? Nun, ich werde sicherlich einiges an Garn für die Robe brauchen. Bring mir doch bitte fünfzehn Spulen.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npc.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Das faule Schneiderlein II");
    npc.base.autonpcfunctions.AddTraderTrigger("task","Oh, you want to help me some more? Well, I certainly need some thread for the robe. Bring me fifteen bobbins of thread, please.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npc.base.autonpcfunctions.AddConsequence("inform","[New quest] The Lazy Tailoress II");
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Oh, du willst mir noch mehr helfen? Nun, ich werde sicherlich einiges an Garn für die Robe brauchen. Bring mir doch bitte fünfzehn Spulen.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("qpg","=",2);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",3);
    npc.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Das faule Schneiderlein II");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Oh, you want to help me some more? Well, I certainly need some thread for the robe. Bring me fifteen bobbins of thread, please.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Oh, du willst mir noch mehr helfen? Nun, ich werde sicherlich einiges an Garn für die Robe brauchen. Bring mir doch bitte fünfzehn Spulen.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("task","Oh, you want to help me some more? Well, I certainly need some thread for the robe. Bring me fifteen bobbins of thread, please.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Oh, du willst mir noch mehr helfen? Nun, ich werde sicherlich einiges an Garn für die Robe brauchen. Bring mir doch bitte fünfzehn Spulen.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Ah, vielen lieben Dank. Ich weiß das zu schätzen und hoffe, du aktzeptierst dieses Kleid als Zeichen meines Anerkennung.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("item",50,"all",">",14);
    npc.base.autonpcfunctions.AddCondition("town","=","runewick");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",50,15);
    npc.base.autonpcfunctions.AddConsequence("item",385,1,999,0);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst ein blaues Kleid und deine Schneidereifähigkeit steigt. Dein Ansehen bei Erzmagier Elvaine Morgan steigt.");
    npc.base.autonpcfunctions.AddConsequence("rankpoints","runewick","+",10);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","tailoring","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Ah, thank you so much! I appreciate this greatly, I hope you accept this dress as compensation.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("item",50,"all",">",14);
    npc.base.autonpcfunctions.AddCondition("town","=","runewick");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",50,15);
    npc.base.autonpcfunctions.AddConsequence("item",385,1,999,0);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded a blue dress and your tailoring skill increases. You advance in Archmage Elvaine Morgan's favour.");
    npc.base.autonpcfunctions.AddConsequence("rankpoints","runewick","+",10);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","tailoring","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Ah, vielen lieben Dank. Ich weiß das zu schätzen und hoffe, du aktzeptierst dieses Kleid als Zeichen meines Anerkennung.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("item",50,"all",">",14);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",50,15);
    npc.base.autonpcfunctions.AddConsequence("item",385,1,999,0);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst ein blaues Kleid und deine Schneidereifähigkeit steigt.");
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","tailoring","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Ah, thank you so much! I appreciate this greatly, I hope you accept this dress as compensation.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("item",50,"all",">",14);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",50,15);
    npc.base.autonpcfunctions.AddConsequence("item",385,1,999,0);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded a blue dress and your tailoring skill increases.");
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","tailoring","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",4);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Garn, Garn, ohje, mir ist das Garn ausgegangen und du hast auch nicht genug!");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("item",50,"all","<",14);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Thread, thread, my dear, I lack thread and you don't have enough!");
    npc.base.autonpcfunctions.AddCondition("qpg","=",3);
    npc.base.autonpcfunctions.AddCondition("item",50,"all","<",14);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    -- 3rd quest: Gather 5 red cloth.
    npc.base.autonpcfunctions.AddTraderTrigger("quest","I'm short on red cloth! But I need some for the robe for Elvaine Morgan. Can you please get me five panels?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",4);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npc.base.autonpcfunctions.AddConsequence("inform","[New quest] The Lazy Tailoress III");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Mir ist der rote Stoff ausgegangen! Den brauch ich aber für die Robe für Elvaine Morgan. Bringst du mir fünf Bahnen, bitte?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",4);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npc.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Das faule Schneiderlein III");
    npc.base.autonpcfunctions.AddTraderTrigger("task","I'm short on red cloth! But I need some for the robe for Elvaine Morgan. Can you please get me five panels?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("qpg","=",4);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npc.base.autonpcfunctions.AddConsequence("inform","[New quest] The Lazy Tailoress III");
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Mir ist der rote Stoff ausgegangen! Den brauch ich aber für die Robe für Elvaine Morgan. Bringst du mir fünf Bahnen, bitte");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("qpg","=",4);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",5);
    npc.base.autonpcfunctions.AddConsequence("inform","[Neues Quest] Das faule Schneiderlein III");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","I'm short on red cloth! But I need some for the robe for Elvaine Morgan. Can you please get me five panels?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Mir ist der rote Stoff ausgegangen! Den brauch ich aber für die Robe für Elvaine Morgan. Bringst du mir fünf Bahnen, bitte.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("task","I'm short on red cloth! But I need some for the robe for Elvaine Morgan. Can you please get me five panels?");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Mir ist der rote Stoff ausgegangen! Den brauch ich aber für die Robe für Elvaine Morgan. Bringst du mir fünf Bahnen, bitte.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Danke, genau, was ich gebraucht habe! Nun kann ich die Robe für den Erzmagier Morgan fertigstellen. Hier, dies war mein letzter Versuch, er hat sie zurückgeschickt, sie war ihm zu eng.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddCondition("item",174,"all",">",4);
    npc.base.autonpcfunctions.AddCondition("town","=","runewick");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",174,5);
    npc.base.autonpcfunctions.AddConsequence("item",558,1,999,0);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst eine Meistermagierrobe und deine Schneidereifähigkeit steigt. Dein Ansehen bei Erzmagier Elvaine Morgan steigt.");
    npc.base.autonpcfunctions.AddConsequence("rankpoints","runewick","+",20);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","tailoring","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Thank you, that is exactly what I needed! Now I can finish the robe for archmage Morgan. Here, take my last attempt, he sent it back, it was too tight for him.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddCondition("item",174,"all",">",4);
    npc.base.autonpcfunctions.AddCondition("town","=","runewick");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",174,5);
    npc.base.autonpcfunctions.AddConsequence("item",558,1,999,0);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded a master mage robe and your tailoring skill increases. You advance in Archmage Elvaine Morgan's favour.");
    npc.base.autonpcfunctions.AddConsequence("rankpoints","runewick","+",20);
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","tailoring","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Danke, genau, was ich gebraucht habe! Nun kann ich die Robe für den Erzmagier Morgan fertigstellen. Hier, dies war mein letzter Versuch, er hat sie zurückgeschickt, sie war ihm zu eng.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddCondition("item",174,"all",">",4);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",174,5);
    npc.base.autonpcfunctions.AddConsequence("item",558,1,999,0);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest gelöst] Du erhältst eine Meistermagierrobe und deine Schneidereifähigkeit steigt.");
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","tailoring","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Thank you, that is exactly what I needed! Now I can finish the robe for archmage Morgan. Here, take my last attempt, he sent it back, it was too tight for him.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddCondition("item",174,"all",">",4);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddConsequence("deleteitem",174,5);
    npc.base.autonpcfunctions.AddConsequence("item",558,1,999,0);
    npc.base.autonpcfunctions.AddConsequence("inform","[Quest solved] You are awarded a master mage robe and your tailoring skill increases.");
    npc.base.autonpcfunctions.AddConsequence("skill","crafting","tailoring","+",1);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",6);
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Uhm... ich brauche mehr roten Stoff. Anderenfalls kann ich die Robe für den Erzmagier Morgan nicht fertigstellen.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddCondition("item",174,"all","<",4);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger(".+","Hrm... I need a little more red cloth. Otherwise, I cannot finish the robe for Archmage Morgan.");
    npc.base.autonpcfunctions.AddCondition("qpg","=",5);
    npc.base.autonpcfunctions.AddCondition("item",174,"all","<",4);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    -- Final dialogue: No more quests, just nice hints
    npc.base.autonpcfunctions.AddTraderTrigger("quest","I don't need anything else, but thank you! You saved my day!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",6);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Ich brauche nichts weiter, aber danke nochmal! Du hast mir ganz schön aus der Patsche geholfen.");
    npc.base.autonpcfunctions.AddAdditionalTrigger("mission");
    npc.base.autonpcfunctions.AddCondition("qpg","=",6);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("task","I don't need anything else, but thank you! You saved my day!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("adventure");
    npc.base.autonpcfunctions.AddCondition("qpg","=",6);
    npc.base.autonpcfunctions.AddTraderTrigger("Auftrag","Ich brauche nichts weiter, aber danke nochmal! Du hast mir ganz schön aus der Patsche geholfen!");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Aufgabe");
    npc.base.autonpcfunctions.AddAdditionalTrigger("Abenteuer");
    npc.base.autonpcfunctions.AddCondition("qpg","=",6);
    -- Cycletext: Please add at least(!) five cycletext messages. The more, the better. You can use emotes (#me is green), too.
    npc.base.autonpcfunctions.AddCycleText("#me summt ein Liedchen.","#me hums a small song.");
    npc.base.autonpcfunctions.AddCycleText("#me schaut zum Himmel und murmelt: 'Fast schon Zeit für ein Stück Kuchen.'","#me looks at the sky, and mumbles: 'Nearly time for pie...'");
    npc.base.autonpcfunctions.AddCycleText("#me streichelt ein Schaf.","#me pats a sheep.");
    npc.base.autonpcfunctions.AddCycleText("Oh, ist schon wieder Essenszeit?","Oh, is it nearly time to eat again?");
    npc.base.autonpcfunctions.AddCycleText("Hallo da drüben!","Hello over there!");
    npc.base.autonpcfunctions.AddCycleText("#me kichert freudig.","#me giggles.");
    npc.base.autonpcfunctions.AddCycleText("Ohje, ich muss fertig werden.","Oh, I have to get things done.");
    -- ********* END DYNAMIC PART ********
    TradSpeakLang={0,1};
    TradStdLang=0;

    npc.base.autonpcfunctions.increaseLangSkill(TradSpeakLang);
    thisNPC.activeLanguage=TradStdLang;

end

function nextCycle()  -- ~10 times per second
    initializeNpc();
    npc.base.autonpcfunctions.SpeakerCycle();
end

function receiveText(texttype, message, originator)
    if npc.base.autonpcfunctions.BasicNPCChecks(originator,2) then
        if npc.base.autonpcfunctions.LangOK(originator,TradSpeakLang) then
            npc.base.autonpcfunctions.TellSmallTalk(message,originator);
        else
            npc.base.autonpcfunctions.Confused(
               "#me sieht dich leicht verwirrt an",
               "#me looks at you a little confused"
            );
        end
    end
end