-- INSERT INTO npc VALUES (nextval('npc_seq'),0,-61,-134,0,2,false,'Marcus','npc_marcus.lua',0);

require("npc.base.autonpcfunctions")
module("npc.marcus", package.seeall)

function useNPC(user,counter,param)
    thisNPC:increaseSkill(1,"common language",100);
    thisNPC:talkLanguage(CCharacter.say, CPlayer.german, "Finger weg!");
    thisNPC:talkLanguage(CCharacter.say, CPlayer.english, "Don't you touch me!");
end

function initializeNpc()
    if TraderFirst then
        return true;
    end
    
    npc.base.autonpcfunctions.InitTalkLists();
    
    
    -- ********* START DYNAMIC PART ********
    QuestID = 557;
    npc.base.autonpcfunctions.AddTraderTrigger("Hafen","Der Hafen ist im Süden von Trollsbane");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddTraderTrigger("Harbo[u]*r","The harbour is in the south of Trollsbane");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddTraderTrigger("job","Im Augenblick habe ich nichts für euch zu tun.");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("job","Currently i have nothing to do for you.");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("auftrag","Im Augenblick habe ich nichts für euch zu tun.");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddTraderTrigger("beruf","Ich bin Händler");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddTraderTrigger("deine aufgabe","Ich bin Händler");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddTraderTrigger("eure aufgabe","Ich bin Händler");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddTraderTrigger("helfen","Ihr habt mir schon genug geholfen");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddTraderTrigger("hilfe","Ihr habt mir schon genug geholfen");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddTraderTrigger("help","Ihr habt mir schon genug geholfen");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddTraderTrigger("was tust du","Ich bin Händler. Also handle ich. Aber im Augenblick kann ich euch nichts anbieten.");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddTraderTrigger("was tut ihr","Ich bin Händler. Also handle ich. Aber im Augenblick kann ich euch nichts anbieten.");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddTraderTrigger("was macht ihr","Ich bin Händler. Also handle ich. Aber im Augenblick kann ich euch nichts anbieten.");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddTraderTrigger("was machst du","Ich bin Händler. Also handle ich. Aber im Augenblick kann ich euch nichts anbieten.");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddTraderTrigger("mission","Im Augenblick habe ich nichts für euch zu tun.");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("mission","Currently i have nothing to do for you.");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("neu","So neu seit ihr nun auch wieder nicht. Immerhin habt ihr mir schon gut geholfen.");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddTraderTrigger("I[ a']+m new","You aren't that new. You helped me alot allready.");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddTraderTrigger("newbie","You aren't that new. You helped me alot allready.");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Im Augenblick habe ich nichts für euch zu tun.");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Currently i have nothing to do for you.");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("t[äae]+tigkeit","Ich bin Händler. Also handle ich. Aber im Augenblick kann ich euch nichts anbieten.");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddTraderTrigger("what do you do","I'm a trader");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",20);
    npc.base.autonpcfunctions.AddTraderTrigger("Lieferung","Ah. Du hast den Schinken. Hat ganz schön lange gedauert. Hier hast du 3 Silberstücke.");
    npc.base.autonpcfunctions.AddConsequence("money","+",300);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",306,10);
    npc.base.autonpcfunctions.AddCondition("item",306,"all",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",20);
    npc.base.autonpcfunctions.AddTraderTrigger("Lieferung","Das ist aber nicht der ganze Schinken. Wo ist der Rest?");
    npc.base.autonpcfunctions.AddCondition("item",306,"all",">=",0);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddTraderTrigger("Lieferung","Na wo ist denn der Schinken?");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddTraderTrigger("Schinken","Ah. Du hast den Schinken. Hat ganz schön lange gedauert. Hier hast du 3 Silberstücke.");
    npc.base.autonpcfunctions.AddConsequence("money","+",300);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",306,10);
    npc.base.autonpcfunctions.AddCondition("item",306,"all",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",20);
    npc.base.autonpcfunctions.AddTraderTrigger("Schinken","Das ist aber nicht der ganze Schinken. Wo ist der Rest?");
    npc.base.autonpcfunctions.AddCondition("item",306,"all",">=",0);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddTraderTrigger("Schinken","Na wo ist denn der Schinken?");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddTraderTrigger("Aufgabe","Ah. Du hast den Schinken. Hat ganz schön lange gedauert. Hier hast du 3 Silberstücke.");
    npc.base.autonpcfunctions.AddConsequence("money","+",300);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",306,10);
    npc.base.autonpcfunctions.AddCondition("item",306,"all",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",20);
    npc.base.autonpcfunctions.AddTraderTrigger("Aufgabe","Das ist aber nicht der ganze Schinken. Wo ist der Rest?");
    npc.base.autonpcfunctions.AddCondition("item",306,"all",">=",0);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddTraderTrigger("Aufgabe","Na wo ist denn der Schinken?");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddTraderTrigger("Job","Ah. Du hast den Schinken. Hat ganz schön lange gedauert. Hier hast du 3 Silberstücke.");
    npc.base.autonpcfunctions.AddConsequence("money","+",300);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",306,10);
    npc.base.autonpcfunctions.AddCondition("item",306,"all",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",20);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Job","Das ist aber nicht der ganze Schinken. Wo ist der Rest?");
    npc.base.autonpcfunctions.AddCondition("item",306,"all",">=",0);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Job","Na wo ist denn der Schinken?");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Ah. Du hast den Schinken. Hat ganz schön lange gedauert. Hier hast du 3 Silberstücke.");
    npc.base.autonpcfunctions.AddConsequence("money","+",300);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",306,10);
    npc.base.autonpcfunctions.AddCondition("item",306,"all",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",20);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Das ist aber nicht der ganze Schinken. Wo ist der Rest?");
    npc.base.autonpcfunctions.AddCondition("item",306,"all",">=",0);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Na wo ist denn der Schinken?");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("delivery","Ah. You got the ham. Took a long time. Here, take that 3 silvercoins.");
    npc.base.autonpcfunctions.AddConsequence("money","+",300);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",306,10);
    npc.base.autonpcfunctions.AddCondition("item",306,"all",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",20);
    npc.base.autonpcfunctions.AddTraderTrigger("delivery","That is not all the ham. Where is the rest?");
    npc.base.autonpcfunctions.AddCondition("item",306,"all",">=",0);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddTraderTrigger("delivery","Now where is my ham?");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddTraderTrigger("ham","Ah. You got the ham. Took a long time. Here, take that 3 silvercoins.");
    npc.base.autonpcfunctions.AddConsequence("money","+",300);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",306,10);
    npc.base.autonpcfunctions.AddCondition("item",306,"all",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",20);
    npc.base.autonpcfunctions.AddTraderTrigger("ham","That is not all the ham. Where is the rest?");
    npc.base.autonpcfunctions.AddCondition("item",306,"all",">=",0);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddTraderTrigger("ham","Now where is my ham?");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddTraderTrigger("job","Ah. You got the ham. Took a long time. Here, take that 3 silvercoins.");
    npc.base.autonpcfunctions.AddConsequence("money","+",300);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",306,10);
    npc.base.autonpcfunctions.AddCondition("item",306,"all",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",20);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("job","That is not all the ham. Where is the rest?");
    npc.base.autonpcfunctions.AddCondition("item",306,"all",">=",0);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("job","Now where is my ham?");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Ah. You got the ham. Took a long time. Here, take that 3 silvercoins.");
    npc.base.autonpcfunctions.AddConsequence("money","+",300);
    npc.base.autonpcfunctions.AddConsequence("deleteitem",306,10);
    npc.base.autonpcfunctions.AddCondition("item",306,"all",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",20);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","That is not all the ham. Where is the rest?");
    npc.base.autonpcfunctions.AddCondition("item",306,"all",">=",0);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Now where is my ham?");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",10);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Dieb","Dieb? Ein Dieb hat meinen Schinken?!");
    npc.base.autonpcfunctions.AddConsequence("state","=",3);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",2);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddTraderTrigger("Räuber","Räuber? Ein Räuber hat meinen Schinken?!");
    npc.base.autonpcfunctions.AddConsequence("state","=",3);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",2);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddTraderTrigger("ja","Dann such den Dieb und hol den Schinken!");
    npc.base.autonpcfunctions.AddCondition("state","=",3);
    npc.base.autonpcfunctions.AddConsequence("state","=",0);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",2);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddTraderTrigger("nein","Wer hat den Schinken dann?");
    npc.base.autonpcfunctions.AddCondition("state","=",3);
    npc.base.autonpcfunctions.AddConsequence("state","=",0);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",2);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddTraderTrigger("gestohlen","Ich brauch diesen Schinken unbedingt! Ihr müsst den Schinken finden.");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",2);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddTraderTrigger("Schinken","Ich habe den Schinken noch nicht bekommen. Und wenn Nicolas ihn nicht hat... wer hat ihn dann?");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",2);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddTraderTrigger("thief","Thief? A thief has my ham?!");
    npc.base.autonpcfunctions.AddConsequence("state","=",3);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",2);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddTraderTrigger("yes","Then search the thief and get the ham!");
    npc.base.autonpcfunctions.AddCondition("state","=",3);
    npc.base.autonpcfunctions.AddConsequence("state","=",0);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",2);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddTraderTrigger("no","So where is the ham then?");
    npc.base.autonpcfunctions.AddCondition("state","=",3);
    npc.base.autonpcfunctions.AddConsequence("state","=",0);
    npc.base.autonpcfunctions.AddCondition("qpg",">=",2);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddTraderTrigger("stolen","I need that ham! You have to find it.");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",2);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddTraderTrigger("ham","I didn't got the ham. And if Nicolas does not have it. Who has it then?");
    npc.base.autonpcfunctions.AddCondition("qpg",">=",2);
    npc.base.autonpcfunctions.AddCondition("qpg","<",20);
    npc.base.autonpcfunctions.AddTraderTrigger("Hafen","Ja. Der Hafen. Geht einfach zum Westtor aus der Stadt hinaus und folgt der Straße nach Süden. Ihr kommt an der Farmers Union vorbei und dann zum Hafen wo meine Lieferung wartet.");
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddTraderTrigger("Harbo[u]*r","Yes. The harbour. Leave Trollsbane thougth the west gate and follow the street south. Then you pass by the Farmers Union and then you come to the harbour where my delivery waits.");
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddTraderTrigger("job","Ich habe euch doch schon gesagt was zu tun ist. Geht zum Hafen und holt die Lieferung Schinken für mich ab.");
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("job","I told you already what you have to do. Go to the harbour and get the delivery of ham for me.");
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("auftrag","Ich habe euch doch schon gesagt was zu tun ist. Geht zum Hafen und holt die Lieferung Schinken für mich ab.");
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddTraderTrigger("beruf","Ich bin Händler. Habt ihr den Auftrag den ich euch gegeben habe schon erledigt?");
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddTraderTrigger("deine aufgabe","Ich bin Händler. Das sollte meine Aufgabe genug beschreiben. Wann erledigt ihr die Aufgabe die ich euch gab?");
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddTraderTrigger("eure aufgabe","Ich bin Händler. Das sollte meine Aufgabe genug beschreiben. Wann erledigt ihr die Aufgabe die ich euch gab?");
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddTraderTrigger("helfen","Wenn ihr zum Hafen gehen würdet und die Lieferung holt wäre mit genug geholfen.");
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddTraderTrigger("hilfe","Wenn ihr zum Hafen gehen würdet und die Lieferung holt wäre mit genug geholfen.");
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddTraderTrigger("help","If you would go to the harbour and get my delivery everything would be good.");
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddTraderTrigger("was tust du","Ich warte auf eine Lieferung. Habt ihr sie schon geholt?");
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddTraderTrigger("was tut ihr","Ich warte auf eine Lieferung. Habt ihr sie schon geholt?");
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddTraderTrigger("was macht ihr","Ich warte auf eine Lieferung. Habt ihr sie schon geholt?");
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddTraderTrigger("was machst du","Ich warte auf eine Lieferung. Habt ihr sie schon geholt?");
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddTraderTrigger("mission","Ich habe euch schon gesagt was ihr tun sollt. Habt ihr die Lieferung vom Hafen schon geholt?");
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("mission","I told you already what to do. Did you got the delivery from the harbour already?");
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("neu","Schön und gut. Ihr habt doch jetzt etwas zu tun. Holt bitte die Lieferung vom Hafen.");
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddTraderTrigger("I[ a']+m new","I see, I see. But you know what you have to do. Go to the harbour and get the delivery.");
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddTraderTrigger("newbie","I see, I see. But you know what you have to do. Go to the harbour and get the delivery.");
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Ich habe euch schon gesagt was ihr tun sollt. Habt ihr die Lieferung vom Hafen schon geholt?");
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","I told you already what to do. Did you got the delivery from the harbour already?");
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("t[äae]+tigkeit","Ich habe euch schon gesagt was ihr tun sollt. Habt ihr die Lieferung vom Hafen schon geholt?");
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddTraderTrigger("what do you do","I wait for a delivery. Did you got it allready?");
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddCondition("qpg",">",0);
    npc.base.autonpcfunctions.AddTraderTrigger("Hafen","Der Hafen ist südlich von Trollsbane. Am Wasser. Wo wir davon reden. Ich hätte etwas für euch zu tun. Interesse?");
    npc.base.autonpcfunctions.AddConsequence("state","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("Harbo[u]*r","The harbour is in the south of Trollsbane. At the sea. While we talk about it. I have a small job for you. Are you interested?");
    npc.base.autonpcfunctions.AddConsequence("state","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("job","Ja. Ich hätte etwas für euch zu tun. Es geht darum eine kleine Lieferung Schinken vom Hafen zu holen. Habt ihr Interesse das zu erledigen. Ich werde euch dafür Entlohnen.");
    npc.base.autonpcfunctions.AddCondition("state","<>",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("job","Yeah. I have something to do for you. You would have to get a small delivery of ham from the harbour. Are you interested? I will pay you.");
    npc.base.autonpcfunctions.AddCondition("state","<>",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("auftrag","Ja. Ich hätte etwas für euch zu tun. Es geht darum eine kleine Lieferung Schinken vom Hafen zu holen. Habt ihr Interesse das zu erledigen. Ich werde euch dafür Entlohnen.");
    npc.base.autonpcfunctions.AddCondition("state","<>",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("aufgabe","Ja. Ich hätte etwas für euch zu tun. Es geht darum eine kleine Lieferung Schinken vom Hafen zu holen. Habt ihr Interesse das zu erledigen. Ich werde euch dafür Entlohnen.");
    npc.base.autonpcfunctions.AddCondition("state","<>",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("beruf","Ich bin Händler. Leider kann ich im Moment nichts anbieten. Ich erwarte eine Lieferung. Vielleicht könnt ihr mir bei einer kleinen Sache helfen?");
    npc.base.autonpcfunctions.AddCondition("state","<>",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("deine aufgabe","Ich bin Händler. Das sollte meine Aufgabe genug beschreiben. Allerdings hätte ich eine kleine Aufgabe für euch. Interesse?");
    npc.base.autonpcfunctions.AddCondition("state","<>",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("eure aufgabe","Ich bin Händler. Das sollte meine Aufgabe genug beschreiben. Allerdings hätte ich eine kleine Aufgabe für euch. Interesse?");
    npc.base.autonpcfunctions.AddCondition("state","<>",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("helfen","Ihr könnt mir in der Tat helfen. Ich benötige eine Lieferung vom Hafen. Wollt ihr mir helfen?");
    npc.base.autonpcfunctions.AddCondition("state","<>",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("hilfe","Ihr könnt mir in der Tat helfen. Ich benötige eine Lieferung vom Hafen. Wollt ihr mir helfen?");
    npc.base.autonpcfunctions.AddCondition("state","<>",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("help","I could need some help indeed. I need a delivery from the harbour. Would you like to help me?");
    npc.base.autonpcfunctions.AddCondition("state","<>",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("mission","Ich hätte in der Tat etwas für euch zu tun. Es geht um eine Lieferung Schinken die ihr vom Hafen abholten müsstet. Wollt ihr mir dabei helfen?");
    npc.base.autonpcfunctions.AddCondition("state","<>",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("mission","I would have some work for you. Its about getting a delivery from the harbor and take it to me. Would you do this for me?");
    npc.base.autonpcfunctions.AddCondition("state","<>",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("neu","Ah. Ihr seit neu hier. Da habt ihr doch bestimmt Interesse mir bei einer kleinen Angelegenheit zu helfen, oder?");
    npc.base.autonpcfunctions.AddCondition("state","<>",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("I[ a']+m new","Ah. You are new around here. Then you are intressted in helping for sure, aren't you?");
    npc.base.autonpcfunctions.AddCondition("state","<>",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("newbie","Ah. You are new around here. Then you are intressted in helping for sure, aren't you?");
    npc.base.autonpcfunctions.AddCondition("state","<>",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("quest","Ich hätte in der Tat etwas für euch zu tun. Es geht um eine Lieferung Schinken die ihr vom Hafen abholten müsstet. Wollt ihr mir dabei helfen?");
    npc.base.autonpcfunctions.AddCondition("state","<>",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("quest","I would have some work for you. Its about getting a delivery from the harbor and take it to me. Would you do this for me?");
    npc.base.autonpcfunctions.AddCondition("state","<>",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("t[äae]+tigkeit","Ich bin Händler. Leider kann ich im Moment nichts anbieten. Ich erwarte eine Lieferung. Vielleicht könnt ihr mir bei einer kleinen Sache helfen?");
    npc.base.autonpcfunctions.AddCondition("state","<>",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("was tust du","Ich warte auf eine Lieferung. Hättet ihr Interesse für mich eine Lieferung Schinken vom Hafen abzuholen?");
    npc.base.autonpcfunctions.AddCondition("state","<>",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("was tut ihr","Ich warte auf eine Lieferung. Hättet ihr Interesse für mich eine Lieferung Schinken vom Hafen abzuholen?");
    npc.base.autonpcfunctions.AddCondition("state","<>",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("was machst du","Ich warte auf eine Lieferung. Hättet ihr Interesse für mich eine Lieferung Schinken vom Hafen abzuholen?");
    npc.base.autonpcfunctions.AddCondition("state","<>",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("was macht ihr","Ich warte auf eine Lieferung. Hättet ihr Interesse für mich eine Lieferung Schinken vom Hafen abzuholen?");
    npc.base.autonpcfunctions.AddCondition("state","<>",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("what do you do","I wait for a delivery. Are you intressted in getting this delivery of ham from the harbour?");
    npc.base.autonpcfunctions.AddCondition("state","<>",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("ja","Ihr nehmt den Auftrag an ohne zu wissen worum es geht? Ihr müsstet eine Lieferung Schinken vom Hafen holen. Immernoch Interesse?");
    npc.base.autonpcfunctions.AddCondition("state","=",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("yes","You are interessted without knowing what the job is about? You would have to get a small delivery of ham from the harbour to me. Still interessted?");
    npc.base.autonpcfunctions.AddCondition("state","=",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("nein","Ihr wisst doch gar nicht worum es geht! Ihr müsst nur eine kleine Lieferung Schinken vom Hafen hier her bringen. Wollt ihr das nicht doch machen?");
    npc.base.autonpcfunctions.AddCondition("state","=",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("no","You don't even know what this job is about. You just have to get a small delivery from the harbour to me. Don't you want to do this?");
    npc.base.autonpcfunctions.AddCondition("state","=",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("job","Es geht darum eine kleine Lieferung Schinken vom Hafen zu holen und zu mir zu bringen. Übernehmt ihr den Auftrag?");
    npc.base.autonpcfunctions.AddCondition("state","=",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("job","The job is about a delivery of ham you have to get at the harbour and carry it to me. Do you take that job?");
    npc.base.autonpcfunctions.AddCondition("state","=",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("auftrag","Es geht darum eine kleine Lieferung Schinken vom Hafen zu holen und zu mir zu bringen. Übernehmt ihr den Auftrag?");
    npc.base.autonpcfunctions.AddCondition("state","=",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("aufgabe","Es geht darum eine kleine Lieferung Schinken vom Hafen zu holen und zu mir zu bringen. Übernehmt ihr den Auftrag?");
    npc.base.autonpcfunctions.AddCondition("state","=",1);
    npc.base.autonpcfunctions.AddConsequence("state","=",2);
    npc.base.autonpcfunctions.AddTraderTrigger("ja","Sehr gut. Geht zu Nicolas am Hafen. Der soll euch die Lieferung geben. Und beeilt euch. Ich brauche das Fleisch.");
    npc.base.autonpcfunctions.AddCondition("state","=",2);
    npc.base.autonpcfunctions.AddConsequence("state","=",0);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("nein","Naja. Schade. Dann eben nicht.");
    npc.base.autonpcfunctions.AddCondition("state","=",2);
    npc.base.autonpcfunctions.AddConsequence("state","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("yes","Very well. Go to Nicolas at the harbour. He shall give you the delivery. And hurry. I need that meat.");
    npc.base.autonpcfunctions.AddCondition("state","=",2);
    npc.base.autonpcfunctions.AddConsequence("state","=",0);
    npc.base.autonpcfunctions.AddConsequence("qpg","=",1);
    npc.base.autonpcfunctions.AddTraderTrigger("no","Sadly.");
    npc.base.autonpcfunctions.AddCondition("state","=",2);
    npc.base.autonpcfunctions.AddConsequence("state","=",0);
    npc.base.autonpcfunctions.AddTraderTrigger("Gobaith","Ja. Gobaith das ist diese Insel hier.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Gobaith","Yeah. Gobaith is this island.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Greenbriar","Greenbriar war mal ein Halblingsdorf. Ist im Südwesten der Insel.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Greenbriar","Greenbriar was the halfling settlement. Its in the south west of the island.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Hellbriar","Hellbriar ist eine Vulkanlandschaft südlich von Greenbriar. Gefährlicher Ort. Geht dort lieber nicht hin.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Hellbriar","Hellbriar is a vulcan in the south of Greenbriar. Dangerous place. Better don't got there.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("I am","Nice to meet you. I'm %NPCNAME.");
    npc.base.autonpcfunctions.AddTraderTrigger("I'm","Nice to meet you. I'm %NPCNAME.");
    npc.base.autonpcfunctions.AddTraderTrigger("Ich bin","Freut mich euch kennen zu lernen. Ich bin %NPCNAME.");
    npc.base.autonpcfunctions.AddTraderTrigger("Mag Academy","The academy of magic... i have no idea where it is. Better ask a mage.");
    npc.base.autonpcfunctions.AddTraderTrigger("academy mag","The academy of magic... i have no idea where it is. Better ask a mage.");
    npc.base.autonpcfunctions.AddTraderTrigger("Magierakademie","Die Akademie der Magie. Ich habe keine Ahnung wo diese ist. Fragt besser einen Magier.");
    npc.base.autonpcfunctions.AddTraderTrigger("Magier Akademie","Die Akademie der Magie. Ich habe keine Ahnung wo diese ist. Fragt besser einen Magier.");
    npc.base.autonpcfunctions.AddTraderTrigger("Akademie Magi","Die Akademie der Magie. Ich habe keine Ahnung wo diese ist. Fragt besser einen Magier.");
    npc.base.autonpcfunctions.AddTraderTrigger("Nordmark","Die Nordmark ist der Sitz der Barbaren auf Gobaith. Die leben irgendwo weit im Nordwesten der Insel.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Nordmark","The Northmark is the home of the barbarians on Gobaith. They life somewhere in the north west of the island.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Northmark","The Northmark is the home of the barbarians on Gobaith. They life somewhere in the north west of the island.");
    npc.base.autonpcfunctions.AddTraderTrigger("Silberbrand","Silberbrand ist die Heimat der Zwerge. Wenn ihr Schmiedewaren braucht, dort bekommt ihr sie sicher. Aber die Preise dort sind... zwergisch.");
    npc.base.autonpcfunctions.AddTraderTrigger("Silverbrand","Silverbrand is the home of the dwarfs. If you need smithed goods you get them there for sure. But the prices are... dwarf-like.");
    npc.base.autonpcfunctions.AddTraderTrigger("Tol Vanima","Tol Vanima ist die Heimat der Elfen. Man erreicht sie über den Hafen.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Tol Vanima","Tol Vanima is the home of the elves. You can reach it from the harbour by a ferry");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Troll[s ]+Bane","Trollsbane ist diese Stadt hier. Die Stadt liegt ziemlich zentral auf der Insel und ist Heimat vieler Händler, Handwerker, Krieger und leider auch Verbrecher.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Troll[s ]+Bane","Trollsbane is the town you are in currently. The town is more or less central on the island and is the home of many traders, craftsmans, warriors and sadly criminal as well.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Varshikar","Varshikar liegt weit im Nordosten von Gobaith. Hinter der Wüste. Ist ein langer Weg dort hin.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Varshikar","Varshikar is far in the northeast of Gobaith. Behind the Desert. Is a long way to this place.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("auf bald","Bis bald.");
    npc.base.autonpcfunctions.AddTraderTrigger("beruf","Ich bin Händler");
    npc.base.autonpcfunctions.AddTraderTrigger("buy","I don't sell anything at the moment.");
    npc.base.autonpcfunctions.AddTraderTrigger("bye","Farewell");
    npc.base.autonpcfunctions.AddTraderTrigger("dein name","Ich bin %NPCNAME.");
    npc.base.autonpcfunctions.AddTraderTrigger("euer name","Ich bin %NPCNAME.");
    npc.base.autonpcfunctions.AddTraderTrigger("deine aufgabe","Ich bin Händler. Das sollte meine Aufgabe genug beschreiben.");
    npc.base.autonpcfunctions.AddTraderTrigger("eure aufgabe","Ich bin Händler. Das sollte meine Aufgabe genug beschreiben.");
    npc.base.autonpcfunctions.AddTraderTrigger("farewell","Be well");
    npc.base.autonpcfunctions.AddTraderTrigger("god","If you want to know something about the gods, better ask a priest.");
    npc.base.autonpcfunctions.AddTraderTrigger("good day","Greetings");
    npc.base.autonpcfunctions.AddTraderTrigger("gr[üue]+[sß]+e","Ich grüße euch.");
    npc.base.autonpcfunctions.AddTraderTrigger("greetings","Good day");
    npc.base.autonpcfunctions.AddTraderTrigger("greets","Good day");
    npc.base.autonpcfunctions.AddTraderTrigger("guten tag","Grüße");
    npc.base.autonpcfunctions.AddTraderTrigger("Ushara","Ushara ist die Göttin der Erde. Gibt nicht viele die sie verehren glaub ich. Nur ein paar Druiden und Elfen.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Br[áàa]gon","Brágon ist der Gott des Feuers. Er hat Illarion vor langer Zeit schon verlassen.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Eldan","Eldan ist der Gott des Geistes. Die meisten seiner Anhänger sind Magier.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Tanora","Tanora ist die Göttin des Wassers. Die Echsenmenschen verehren sie. Bei ihnen ist sie als Zelphia bekannt.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Zelphia","Zelphia ist der Name von Tanora, der bei den Echsenmenschen üblich ist.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Findari","Findari ist die Göttin der Luft. Barden sollen sie verehren hab ich gehört.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Narg[úùu]n","Nargún ist der Gott des Chaos. Die die ihn verehren sind ausschlieslich irgendwelche Spinner.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Elara","Elara ist die Göttin des Wissens und der Weisheit. Viele Gelehrte beten sie an.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Adron","Adron ist der Gott des Weines und der Feste. Wenn man von einem Gott eine volle Taverne erbitten will, dann von Adron.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Oldra","Oldra ist die Göttin der Fruchtbarkeit und des Lebens. Viele Bauern beten sie an.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Cherga","Cherga ist die Göttin der Geister. Sie sorgt dafür das die Seele in die Nächste Welt kommt, wenn man diese hier verlässt.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Malachin","Malachin ist der Gott der Jagd. Die Graue Rose die ihre Burg im Norden von Trollsbane hat, hat sich dem Glauben an ihm verschrieben. Dort erfahrt ihr sicher mehr über Malachin.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Irmorom","Irmorom ist der Gott des Handwerks. Die Zwerge beten ihn an und können euch sicher alles über ihn erzählen, wenn wir ein paar Krüge Bier ausgebt.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Sirani","Sirani ist die Göttin der Liebe und der Freude. Wenn ihr mehr über sie wissen wollt, solltet ihr eine Sirani Priesterin suchen. Sie kann euch sicher sehr genau zeigen was es bedeutet Sirani anzubeten. Sehr genau.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("sex","male");
    npc.base.autonpcfunctions.AddTraderTrigger("Sirani","Sirani ist die Göttin der Liebe und der Freude. Wenn ihr mehr über sie wissen wollt, solltet ihr eine Sirani Priesterin suchen.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddCondition("sex","female");
    npc.base.autonpcfunctions.AddTraderTrigger("Zhambra","Zhambra ist der Gott der Freundschaft und Treue. Zhrambra Anhänger sind meistens die verlässligsten Freunde die man finden kann.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Ronagan","Ronagan ist der Gott der Diebe. Daher kann man sich wohl denken das die meisten Diebe ihn anbeten.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Moshran","Moshran ist der Blut Gott. Der ist böse. Durch und durch. Genau wie seine Anhänger. Mit denen sollte man sich nicht einlassen.");
    npc.base.autonpcfunctions.AddCondition("lang","german");
    npc.base.autonpcfunctions.AddTraderTrigger("Ushara","Ushare is the godness of earth. There are not many who pray to her. Only some druids and elves");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Br[áàa]gon","Brágon is the god of fire. He left Illarion a long time ago.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Eldan","Eldan is the god of spirit. The most of his followers hare mages.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Tanora","Tanora is the godness of water. The lizards pray to her. They call her Zelphia.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Zelphia","Zelphia is the Name of Tanora the lizards use.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Findari","Findari is the godness of air. Her followers are bards.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Narg[úùu]n","Nargún is the god of chaos. Those who follow him are mad. All of them.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Elara","Elara is the godness of knowledge and wissdome.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Adron","Adron is the god of wine and festivals. Owners of Taverns follow him.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Oldra","Oldra is the godness of life. Many halflings follow her.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Cherga","Cherga is the godness of the ghosts. She takes care that your soul travels savely into the next world. After your life ends.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Malachin","Malachin is the god of hunting. The grey rose who is in the castle north of Trollsbane follows him. There you get more Informations about Malachin for sure.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Irmorom","Irmorom is the god of the crafts. The dwarfs follow him and can tell you everything about him if you give them some beers.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Sirani","Sirani is the godness of love and joy. If you want to know more about her you should search a Sirani Priestess. She can show you very exactly what is means to follow Sirani. Very exactly.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("sex","male");
    npc.base.autonpcfunctions.AddTraderTrigger("Sirani","Sirani is the godness of love and joy. If you want to know more about her you should search a Sirani Priestess.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddCondition("sex","female");
    npc.base.autonpcfunctions.AddTraderTrigger("Zhambra","Zhambra is the god of friendship. Followers of Zhambras are the best friends you can find.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Ronagan","Ronagan is the god of the thiefs. So the most thiefs follow him.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("Moshran","Moshran is the blood god. He is evil. As his followers are. Do not trust any of them.");
    npc.base.autonpcfunctions.AddCondition("lang","english");
    npc.base.autonpcfunctions.AddTraderTrigger("hail","Grüße");
    npc.base.autonpcfunctions.AddTraderTrigger("hallo","Grüße euch");
    npc.base.autonpcfunctions.AddTraderTrigger("hello","Greetings");
    npc.base.autonpcfunctions.AddTraderTrigger("how are you","I'm pretty fine");
    npc.base.autonpcfunctions.AddTraderTrigger("kaufen","Ich verkaufe im Augenblick leider nichts");
    npc.base.autonpcfunctions.AddTraderTrigger("mein name","Freut mich euch kennen zu lernen. Ich bin %NPCNAME.");
    npc.base.autonpcfunctions.AddTraderTrigger("my name","A pleasure. My name is %NPCNAME.");
    npc.base.autonpcfunctions.AddTraderTrigger("sell","I do not sell anything at the moment");
    npc.base.autonpcfunctions.AddTraderTrigger("verkaufen","Ich verkaufe im Augenblick nichts.");
    npc.base.autonpcfunctions.AddTraderTrigger("was kaufst","Ich kaufe im Augenblick nichts.");
    npc.base.autonpcfunctions.AddTraderTrigger("was verkaufst","Ich verkaufe im Augenblick nichts.");
    npc.base.autonpcfunctions.AddTraderTrigger("wer seid","Ich bin %NPCNAME.");
    npc.base.autonpcfunctions.AddTraderTrigger("wer","Ich bin %NPCNAME.");
    npc.base.autonpcfunctions.AddTraderTrigger("what buy","I do not buy anything currently.");
    npc.base.autonpcfunctions.AddTraderTrigger("what sell","I do not sell anything currently.");
    npc.base.autonpcfunctions.AddTraderTrigger("where am I","You are in Trollsbane.");
    npc.base.autonpcfunctions.AddTraderTrigger("who","I am %NPCNAME.");
    npc.base.autonpcfunctions.AddTraderTrigger("wie geht es","Ich kann nicht klagen.");
    npc.base.autonpcfunctions.AddTraderTrigger("wie hei[sß]+t du","Ich werde %NPCNAME genannt.");
    npc.base.autonpcfunctions.AddTraderTrigger("wie hei[sß]+t ihr","Ich werde %NPCNAME genannt.");
    npc.base.autonpcfunctions.AddTraderTrigger("wo bin ich","Ihr seid in Trollsbane.");
    npc.base.autonpcfunctions.AddTraderTrigger("you name","I am %NPCNAME.");
    

    
    -- ********* END DYNAMIC PART ********
    TradSpeakLang={0,1};
    TradStdLang=0;
    
    npc.base.autonpcfunctions.increaseLangSkill(TradSpeakLang)
    thisNPC.activeLanguage=TradStdLang;
    
end

function nextCycle()  -- ~10 times per second
    initializeNpc();
    npc.base.autonpcfunctions.SpeakerCycle();
end

function receiveText(texttype, message, originator)
    if npc.base.autonpcfunctions.BasicNPCChecks(originator,2) then
        if npc.base.autonpcfunctions.LangOK(originator,TradSpeakLang) then

				npc.base.autonpcfunctions.TellSmallTalk(message,originator);
        else
            npc.base.autonpcfunctions.Confused(
               "#me sieht dich leicht verwirrt an",
               "#me looks at you a little confused"
            );
        end
    end
end

function lookAtNpc(Char, mode)
    if initLook==nil then
        output={};
        output[0]="Ein beschäftigt wirkender Mensch mit einer Rolle Pergament, das eine Auflistung zu sein scheint. Murmelnd streicht er dies und das durch.";
        output[1]="A busy-looking human holding a scroll of pergament on which you can see a list. Mumbeling he erases some lines.";
        initLook=1;
    end
    lang=Char:getPlayerLanguage();
    Char:sendCharDescription( thisNPC.id , output[lang] );
end